### ISSUE TITLE
AddControllersAsServices() not working correctly in linux docker image deployment?

### ISSUE THREAD

**Issue by alexandery** [autofac/Autofac#1001]
I've got a self-hosted Kestrel based ASP.Net Core 2.2 app with controllers in a separate assembly. When running on Windows, the controller actions respond to requests. However, packaging as a linux based docker image results in the controllers from assemblies other than main application assembly to not be loaded / instantiated. I've explicitly copied one controller to the application assembly and am able to hit that, but none from the external assembly.

I'm using ```.AddControllersAsServices()``` method of ensuring that Autofac manages controllers' lifecycle (following https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services):

```
services.AddMvc(options => options.EnableEndpointRouting = false)
	.SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
	// Required to ensure Autofac manages controllers lifecycle
	.AddControllersAsServices()
	;
```

I'm using ```void ConfigureServices(IServiceCollection services)``` to setup my services and ```void ConfigureContainer(ContainerBuilder builder)``` to register my components with Autofac. I'm not registering controllers explicitly, but it does work in Windows, so I presume that should be OK.

Any insight or advice would be appreciated. Thanks!

- Autofac v 4.9.2

**Comment by tillig** [comment]
AddControllersAsServices is an ASP.NET Core method, not an Autofac method. Might be something to chase down over there.

**Comment by alexandery** [comment]
Ah.. Sorry for misunderstanding then. It didn't even occur to me that it's not part of Autofac's integration.
