### ISSUE TITLE
[4.9.2] Root lifetime being disposed when processing queue messages in background

### ISSUE THREAD

**Issue by Mortana89** [autofac/Autofac#1012]
Very inconsistently we are getting intermittent exception in Application Insights, about Autofac not able to resolve dependencies.
This happens when our microservices are processing messages/events from the Azure Service Bus.
We are registering AutoFac as required in startup.cs:
```
           ContainerBuilder container = new ContainerBuilder();
            container.Populate(services);
            container.RegisterModule(new MediatorModules());
            container.RegisterModule(new InfrastructureModule());
            container.RegisterModule(new ApplicationModule());

            return new AutofacServiceProvider(container.Build());
```

We are setting up a queue message receiver:
```
services.AddSingleton<IEmailedMeterDataQueueListener>(sp =>
            {
                ILifetimeScope iLifetimeScope = sp.GetRequiredService<ILifetimeScope>();
                AzureServiceBusQueue.SetupQueueAsync(EmailedMeterDataQueueListener.QUEUE_NAME, connectionString).GetAwaiter().GetResult();
                return new EmailedMeterDataQueueListener(connectionString, iLifetimeScope);
            });
```

And then, we, when we receive a message from Azure Service Bus, open a new lifetime scope:
```
using (ILifetimeScope scope = _autofac.BeginLifetimeScope())
                {
                    IEnumerable<SubscriptionInfo> subscriptions = _subsManager.GetHandlersForEvent(eventName);
                    foreach (SubscriptionInfo subscription in subscriptions)
                    {
                        object handler = scope.ResolveOptional(subscription.HandlerType);
                        if (handler == null)
                        {
                            continue;
                        }

                        Type eventType = _subsManager.GetEventTypeByName(eventName);
                        object integrationEvent = JsonConvert.DeserializeObject(message, eventType);
                        Type concreteType = typeof(IIntegrationEventHandler<>).MakeGenericType(eventType);
                        await (Task)concreteType.GetMethod("Handle").Invoke(handler, new object[] { integrationEvent });
                    }
                }
```

It's the beginlifetimescope that throws the following error:

> "Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed."

When I check the snapshot debugger instance that AI captured; I can see that actually the root lifetime is disposed;
![image](https://user-images.githubusercontent.com/45714001/62547167-0d8c0a80-b865-11e9-9a8d-ad088baf0cca.png)

Am I taking a wrong approach in trying to initiate a lifetime scope per message, from an existing lifetime scope in this situation?
Would it be better to pass the IContainer and start from there?

**Comment by alsami** [comment]
**FYI: I formatted the code, if you don't mind you could at to the OP.**

```csharp
var container = new ContainerBuilder();
container.Populate(services);
container.RegisterModule(new MediatorModules());
container.RegisterModule(new InfrastructureModule());
container.RegisterModule(new ApplicationModule());

 return new AutofacServiceProvider(container.Build());`
We are setting up a queue message receiver:

services.AddSingleton<IEmailedMeterDataQueueListener>(sp => { 
	ILifetimeScope iLifetimeScope = sp.GetRequiredService<ILifetimeScope>(); 
	AzureServiceBusQueue.SetupQueueAsync(EmailedMeterDataQueueListener.QUEUE_NAME, connectionString).GetAwaiter().GetResult(); 
	return new EmailedMeterDataQueueListener(connectionString, iLifetimeScope); 
});
```
And then, we, when we receive a message from Azure Service Bus, open a new lifetime scope:

```csharp
using (ILifetimeScope scope = _autofac.BeginLifetimeScope())
{
	IEnumerable subscriptions = _subsManager.GetHandlersForEvent(eventName);
	foreach (SubscriptionInfo subscription in subscriptions)
	{
		object handler = scope.ResolveOptional(subscription.HandlerType);

		if (handler == null)
		{
			continue;
		}

		Type eventType = _subsManager.GetEventTypeByName(eventName);
		object integrationEvent = JsonConvert.DeserializeObject(message, eventType);
		Type concreteType = typeof(IIntegrationEventHandler<>).MakeGenericType(eventType);
		await (Task)concreteType.GetMethod("Handle").Invoke(handler, new object[] { integrationEvent });
	}
}
```

- Would you mind providing the code for the modules that you are using as well? 
- Especially the one for the `MediatorModule`?
- Also which line exactly throws the exception?

**Comment by Mortana89** [comment]
Thanks for the quick reply!!
I would love to set up a small repo but it's a very big project, and I can't even reproduce it steadily locally...

It's this line that throws the error:
```
using (ILifetimeScope scope = _autofac.BeginLifetimeScope())
```

The MediatorModule file:
```
public class MediatorModules : Autofac.Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(typeof(IMediator).GetTypeInfo().Assembly).AsImplementedInterfaces();

            // Register all the Command handler classes (they implement IRequestHandler) in assembly holding the Commands
            builder.RegisterAssemblyTypes(typeof(ApproveInvoiceCommandHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));

            builder.RegisterAssemblyTypes(typeof(ContractSignedEventHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IIntegrationEventHandler<>));

            //*** Configuration Query Commandhandlers ***/
            builder.RegisterAssemblyTypes(typeof(GetNextNumberCommandHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));

            //** Application Services **//
            builder.Register<IBillingRelationService>(context =>
            {
                IMediator mediator = context.Resolve<IMediator>();
                return new BillingRelationService(mediator);
            }).InstancePerLifetimeScope();

            builder.Register<ITemplateService>(context =>
            {
                IMediator mediator = context.Resolve<IMediator>();
                ICloudFileService cloudFileService = context.Resolve<ICloudFileService>();
                return new TemplateService(mediator, cloudFileService);
            }).InstancePerLifetimeScope();

            builder.Register<IInvoiceService>(context =>
            {
                IMediator mediator = context.Resolve<IMediator>();
                ICloudFileService cloudFileService = context.Resolve<ICloudFileService>();
                ITemplateService templateService  = context.Resolve<ITemplateService>();
                return new InvoiceService(mediator, cloudFileService, templateService);
            }).InstancePerLifetimeScope();

            builder.Register<IBillingCalculationService>(context =>
            {
                IInvoiceService invoiceService = context.Resolve<IInvoiceService>();
                IMediator mediator = context.Resolve<IMediator>();
                return new BillingCalculationService(mediator);
            }).InstancePerLifetimeScope();

            builder.Register<IBillingRunService>(context =>
            {
                IInvoiceService invoiceService = context.Resolve<IInvoiceService>();
                IMediator mediator = context.Resolve<IMediator>();
                IBillingCalculationService calcService = context.Resolve<IBillingCalculationService>();
                return new BillingRunService(invoiceService, calcService, mediator);
            }).InstancePerLifetimeScope();

            builder.Register<ServiceFactory>(context =>
            {
                IComponentContext componentContext = context.Resolve<IComponentContext>();
                return t => componentContext.Resolve(t);
            });

            builder.RegisterGeneric(typeof(RequestPreProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));
        }
    }
```

Infrastructure file:
```
public class InfrastructureModule : Autofac.Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            // Register all the Query Handler classes (they implement IRequestHandler) in assembly holding the Commands
            builder.RegisterAssemblyTypes(typeof(GetBillingRelationsForCustomerAndContractQueryHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));


            // Register all the Query Handler classes (they implement IRequestHandler) in assembly holding the Commands
            builder.RegisterAssemblyTypes(typeof(GetInvoiceByIdQueryHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));

            // Register all the Query Handler classes (they implement IRequestHandler) in assembly holding the Commands
            builder.RegisterAssemblyTypes(typeof(GetTaxCodeByIdQueryHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));

            // Register all the Query Handler classes (they implement IRequestHandler) in assembly holding the Commands
            builder.RegisterAssemblyTypes(typeof(TenantApprovedEventHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IIntegrationEventHandler<>));
        }
    }
```

Application Module:
```
public class ApplicationModule
        : Autofac.Module
    {
        public ApplicationModule()
        {
        }

        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(typeof(GenerateInvoiceMessageHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IMessageHandler<>));
            builder.RegisterAssemblyTypes(typeof(AttachmentAddedEventHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IIntegrationEventHandler<>));
            builder.RegisterAssemblyTypes(typeof(GetTemplateDataForInvoiceQueryHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>));


            //** Generic **//
            builder.Register<ServiceFactory>(context =>
            {
                IComponentContext componentContext = context.Resolve<IComponentContext>();
                return t => componentContext.Resolve(t);
            });

            builder.RegisterGeneric(typeof(RequestPreProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));
        }
    }
```

**Comment by alsami** [comment]
From looking into the Autofac-Modules I am little bit confused. There are several registrations that can be merged.

All your modules are registering types required for [MediatR](https://github.com/jbogard/MediatR). Sometimes fully and sometimes uncompleted. For `Autofac` in general that shouldn't be a problem as long as the last types registered are fully working.

It might not be the issue here but I'd ask you to start cleaning that up to make sure this is really not a problem. There is a [sample](https://github.com/jbogard/MediatR/blob/8e0c349ff720dcf8d63cbb560d3718fd229076ae/samples/MediatR.Examples.Autofac/Program.cs#L1) on how to register `MediatR` with `Autofac`. Also a [nuget-package](https://www.nuget.org/packages/MediatR.Extensions.Autofac.DependencyInjection/) that encapsulates all the requirements for `MediatR` which might render your modules obsolete.

I also noticed this registration

```csharp
services.AddSingleton<IEmailedMeterDataQueueListener>(sp =>
	{
		ILifetimeScope iLifetimeScope = sp.GetRequiredService<ILifetimeScope>();
		AzureServiceBusQueue.SetupQueueAsync(EmailedMeterDataQueueListener.QUEUE_NAME, connectionString).GetAwaiter().GetResult();
		return new EmailedMeterDataQueueListener(connectionString, iLifetimeScope);
	});
```

**Optionally** I'd suggest you to change it and not manually resolve an instance of `ILifetimeScope`. Since you are using ASP.NET Core my suggestion would be the following.

1: Create a class for the connection-string

```csharp
public class MyConnectionForSomething
{
	public string ConnectString { get; set; }
}
```

2: After loading the connection-string from your config-file register `MyConnectionForSomething` as `IOptions<T>` within the `ConfigureServices` delegate.

```csharp
services.Configure<MyConnectionForSomething>(options => options.ConnectionString = connectionString);
```

Now you can inject `IOption<MyConnectionForSomething>` into `EmailedMeterDataQueueListener`

3: Register `IEmailedMeterDataQueueListener` either with `IServiceCollection` or `Autofac` as a simple-singleton

With `IServiceCollection`:

```csharp
sp.AddSingleton<IEmailedMeterDataQueueListener, EmailedMeterDataQueueListener>
```

With `Autofac`

```csharp
builder.RegisterType<EmailedMeterDataQueueListener>()
	.As<IEmailedMeterDataQueueListener>()
	.SingleInstance();
```

4: Move the initializing of the queue to the `Configure` delegate in your startup-class which is executed once on startup of the service.

```csharp
public void Configure(IApplicationBuilder app)
{
	AzureServiceBusQueue.SetupQueueAsync(EmailedMeterDataQueueListener.QUEUE_NAME, connectionString).GetAwaiter().GetResult();
      // probably more code here
}
```

I don't have any other idea what could be causing this behavior. `ILifetimeScope` is a singleton and should not be disposed unless the application is stopped.

@autofac/contributors anyone has an idea what this could be?

**Comment by Mortana89** [comment]
I agree with your optional improvement around the service bus registration, I will need to clean that up.
The first section however, might be confusing as you can't read that from the example code, but basically, there are three seperate projects, each holding their autofac module with their own DI registrations. These modules are then (as can seen from startup.cs) registered in the actual asp.net core service. I might need to improve this a bit as well, but there are some differences though.
Thanks for the suggestion though, it's my first experience with Autofac and MediatR so am always interested in improvements!

I do have a snapshot debug from AI, but I can't open that up, you need VS Enterprise for that :(
Would it be of any value?

**Comment by alsami** [comment]
> I do have a snapshot debug from AI, but I can't open that up, you need VS Enterprise for that :(
> Would it be of any value?

I sadly also don't have a VS-Enterprise licence. The full-stack trace on the other hand could be of help. Any chance you can provide that?

**Comment by ilabutin** [comment]
> > I do have a snapshot debug from AI, but I can't open that up, you need VS Enterprise for that :(
> > Would it be of any value?
> 
> I sadly also don't have a VS-Enterprise licence. The full-stack trace on the other hand could be of help. Any chance you can provide that?

I do have VS Enterprise (2017 though). I can try to help here.

**Comment by Mortana89** [comment]
@alsami  I don't have a full stacktrace sadly ...
@ilabutin , that would be very nice! Do you have a mailadress I could forward a link to the diagnostics file to?

**Comment by ilabutin** [comment]
Drop it to ilabutin_at_gmail.com

**Comment by alsami** [comment]
> @alsami I don't have a full stacktrace sadly ...

You could add a logger that writes either to a file or application-insights.

**Comment by Mortana89** [comment]
> > @alsami I don't have a full stacktrace sadly ...
> 
> You could add a logger that writes either to a file or application-insights.

I have a Stacktrace here, it happened again;
System.ObjectDisposedException:
   at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope (Autofac, Version=4.9.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
   at ZFH.Common.Eventing.ServiceBus.AzureServiceBus.AzureServiceBusTopic+<ProcessEvent>d__16.MoveNext (ZFH.Common.Eventing.ServiceBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at ZFH.Common.Eventing.ServiceBus.AzureServiceBus.AzureServiceBusTopic+<<RegisterSubscriptionClientSessionHandler>b__14_0>d.MoveNext (ZFH.Common.Eventing.ServiceBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.ServiceBus.SessionReceivePump+<MessagePumpTaskAsync>d__22.MoveNext (Microsoft.Azure.ServiceBus, Version=3.4.0.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)

**Comment by Mortana89** [comment]
Small update, I've changed the BeginLifeTimeScope to use MatchingScopeLifetimeTags.RequestLifetimeScopeTag as the tag, in our service bus processing logic.
Next to that I decreased maximum limit of default 1000 messages in parallel, to 15. I haven't seen the behavior anymore. I'm hoping it was the tag-part. In any case we don't see any of these exceptions popping up anymore!
