### ISSUE TITLE
Autofac with Azure Functions with IWebJobsBuilder for constructor DI

### ISSUE THREAD

**Issue by prabhug143** [autofac/Autofac#1024]
We are trying Dependency Injection with Autofac to our Azure Functions. We have a startup class [assembly: WebJobsStartup(typeof(Startup))] which calls the ConfigureServices. The out-of-the-box dependency injection with .net core works fine, but we are trying Dependency Injection with Autofac and we are unable to inject our service classes into Azure Function constructor.
When we try to Resolve the dependencies using "Resolve" keyword of IContainer from Autofac, I'm able to resolve the service. Any help in this regard would be highly appreciated.

**Comment by alsami** [comment]
Are you running on Azure functions 2.0? Might [this ](http://codingsoul.de/2018/06/12/azure-functions-dependency-injection-autofac-on-functions-nuget-package/)be of help for you?

**Comment by prabhug143** [comment]
Thank you for the reply. I'm not using AutofacOnFunctions, I'm only using Autofac. I have looked at the link provided, but that deals with AutofacOnFunctions

**Comment by alsami** [comment]
> Thank you for the reply. I'm not using AutofacOnFunctions, I'm only using Autofac. I have looked at the link provided, but that deals with AutofacOnFunctions

I'd suggest you to use it.

As of now, there is [no official support](https://github.com/Azure/azure-functions-host/issues/3736#issuecomment-492337649) replacing the container used for Azure-Functions.

You will have to rely on custom implementations.
