### ISSUE TITLE
Blazor integration

### ISSUE THREAD

**Issue by RedDeathGitHub** [autofac/Autofac#1025]
Hey!

Apologies if this is not the right place to ask, but I can't really find any info on docs or, well, anywhere else :).

Could you provide a sample how to use Autofac with client side Blazor?
Maybe add it to the docs integrations part [here](https://autofac.readthedocs.io/en/latest/integration/) ?

All I found is this PR merge [here](https://github.com/aspnet/AspNetCore/pull/4785) so I think it's possible to use Autofac with Blazor now...

As Blazor grows I'm sure this will be a popular question, I ❤ Autofac, hope you guys can help me!

**Comment by johneking** [comment]
Hey! Yep, as per the linked issue, looks like Blazor partially supports the ASP.NET Core 3 way of doing things and may be rounded out in future, but there are a few bits missing for now. Specifically, a few of the features around the Startup class are missing when using `UseBlazorStartup`, most notably `ConfigureContainer`. 

However, that PR enables the Autofac service provider factory via `UseServiceProviderFactory`, which can accept an action for the registrations.

This does seem like it's worth documenting as the underlying asp.net magic which happens can look a little strange, and the Blazor version diverges from some of the current docs slightly. It also may still be a bit of a moving target but I'll see if I can add something to the docs about it.

For now, an example based on the Counter page in the bundled Blazor template might look like this in the client / webassembly project:

```
public interface ICounter
{
	int Count { get; }
	void Increment();
}

public class CounterService : ICounter
{
	public int Count { get; private set; }
	public void Increment()
	{
		Count++;
	}
}

public class CounterModule : Module
{
	protected override void Load(ContainerBuilder builder)
	{
		builder.RegisterType<CounterService>()
			.As<ICounter>()
			.SingleInstance();
	}
}
```

```
public class Program
{
	public static void Main(string[] args)
	{
		CreateHostBuilder(args).Build().Run();
	}

	public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
		BlazorWebAssemblyHost.CreateDefaultBuilder()
			.UseServiceProviderFactory(new AutofacServiceProviderFactory(b => b.RegisterModule<CounterModule>()))
			.UseBlazorStartup<Startup>();
}
```
Then in the Counter page itself:
```
@page "/counter"
@inject ICounter CounterService
<h1>Counter</h1>

<p>Current count: @CounterService.Count</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

	@code {

		void IncrementCount()
		{
			CounterService.Increment();
		}

	}
```

**Comment by RedDeathGitHub** [comment]
Great, everything worked as advertised, even did some assembly scanning :).
Thank you!

**Comment by johneking** [comment]
There's a [merged PR as a short-term fix](https://github.com/autofac/Documentation/pull/82) and a [new issue in the docs repo](https://github.com/autofac/Documentation/issues/83) to tidy it up more generally - should be good to close this.

**Comment by rashadrivera** [comment]
How can we get Autofac to work with Blazor Server?  When using the _AddServerSideBlazor_ extension, all @inject calls fail unless we also register them via IServiceCollection.  There does not seem to be any documentation that describes how to get this working.

**Comment by tillig** [comment]
I'm not a Blazor user so I can't answer this, but I will offer:

- [We have the [contributed] docs on Blazor here](https://autofac.readthedocs.io/en/latest/integration/blazor.html)
- If you aren't using the `AutofacServiceProviderFactory` then chances are you still have the default MS DI container, which explains why you have to register things with the service collection to get it to work.
- Blazor, to my understanding, isn't that different than setting up a generic hosting application (which was the intent of introducing the generic app hosting model in .NET Core). Don't ignore the docs around .NET Core and ASP.NET Core setup, they might give you ideas of things to look at.

We'd welcome any [PR to the documentation](https://github.com/autofac/Documentation/blob/master/docs/integration/blazor.rst) that could make the usage more clear. But, again, I'm not a Blazor user and I don't really have time to "become an expert" there, so we're going to have to rely on the community to fill in those gaps.
