### ISSUE TITLE
Constructor can't do AOP

### ISSUE THREAD

**Issue by Yeshuaihui** [autofac/Autofac#1033]
Hello, I am using AutoFac when the constructor is abnormal, I want it to be like the IInterceptor interface, I can listen to the instantiation process and can use try catch to do some processing, such as sending an email to the developer when an exception occurs. Wait, but I looked at the source code and didn't seem to see a similar place that could allow me to inject. Is it true that I didn't find it or not? If not, can you add this function?

**Comment by alexmg** [comment]
@Yeshuaihui I would try to avoid doing complex work in a constructor that is likely to result in an exception being thrown. Throwing an exception if a required dependency is missing is a reasonable thing to do, but that should not be something you expect to occur. Your effort may be better spent ensuring you have a good logging mechanism in place for unhandled exceptions that were not expected during regular operation.

**Comment by Yeshuaihui** [comment]
Hello, this is the case when we have multiple environments in development, such as the development environment, continuous integration environment, formal environment, etc., because there is read configuration information in the constructor and the configuration information is placed on a distributed computer, no way Very intuitive to see on the machine, then the machine and the integrated environment is configured, and then in other environments forgotten the configuration, so that the configuration is not read, so abnormal, so I want to get an exception when instantiating Information is analyzed, and I don't think reading the configuration in the constructor is a very complicated operation.
