### ISSUE TITLE
RegisterAssemblyModules with custom initialization

### ISSUE THREAD

**Issue by jesuissur** [autofac/Autofac#1034]
Hi there

It would be nice to have something like `builder.RegisterAssemblyModules<IAmModuleWithCustomInit>((IAmModuleWithCustomInit x)=> x.CustomProp = thisCustomValue)`

The use case we have in mind is to register some modules that should add registrations through some ServiceCollection's extensions (ex: AddHttpClient, Configure<Options>, etc.).

To keep everything together, it could also be something like `builder.PopulateWithModules<IAmModuleWithServiceColDep>(serviceCollection)` where `IAmModuleWithServiceColDep` contains a method like this `void Load(IServiceCollection serviceCollection)`

We could then keep our registration decoupled through modules while having access to the app's ServiceCollection while registering our components hierarchy.

Thanks
Phil

**Comment by tillig** [comment]
**Autofac core doesn't interact with `IServiceCollection`** so we likely wouldn't add anything for that here. Possibly in the `Autofac.Extensions.DependencyInjection` repo, but you'd want to [file a separate enhancement request there](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues).

In both cases, it'll be helpful to see an actual repro of what you're trying to do. **A short description isn't enough.**

For example, `builder.RegisterAssemblyModules` currently registers all the modules found in a set of assemblies. This is largely used to decouple Autofac and a core application assembly from plugin assemblies. The plugins don't know about the app except maybe for a shared set of interfaces, and the app doesn't have references to the plugins. If there's a generic `builder.RegisterAssemblyModules<T>`... what exactly does it do? Does it only register that one particular module? What if it's not found? Is it a custom interface of some nature? What about other modules that are encountered that don't implement that class or interface, or which don't have the property you mentioned?

The best possible example you could provide would be to **actually write the extension method you envision**. Even if it's not perfect or exactly how we'd implement it. You could likely do a lot of this with some manual foreach loops or reflection. What _exactly_ is it supposed to do?

**Comment by tillig** [comment]
Since we haven't gotten any feedback on what this is supposed to do, we'll close it for now. If you can show us what exactly it is that you're looking for, we can reopen if it's something we are able to support.
