### ISSUE TITLE
Does Autofac handle disposal of provided instances for IAsyncDisposable ?

### ISSUE THREAD

**Issue by Rzpeg** [autofac/Autofac#1035]
Some new .NET Core 3 / EF Core 3 components use async enumerators and async streams with IAsyncDisposable implemented. Will Autofac automatically  handle DisposeAsync(), as it does with regular Dispose() of IDisposable ?

**Comment by alistairjevans** [comment]
Not yet; we've just started discussions on implementing support for this though, so watch this space.

**Comment by Rzpeg** [comment]
@alistairjevans Alright, thanks for the info 👍

**Comment by alistairjevans** [comment]
Hey, @Rzpeg, PR #1037 was just merged in with IAsyncDisposable support.

The 5.0.0 release of Autofac will contain this change, or there is a MyGet package available if you want to try it out.

The .NET Core DI integration should also be updated relatively shortly so .NET DI scopes backed by Autofac get async-disposed too.
