### ISSUE TITLE
No accessible constructors were found for the type Interface (Why Autofac is looking for constructor in interface)

### ISSUE THREAD

**Issue by Nitin5acc** [autofac/Autofac#1050]
Hello,

I am using AutoFac in .NET core application. Please see the code below I keep getting this exception -

      Autofac.Core.DependencyResolutionException : An exception was thrown while activating Infrastructure.SharedKernel.Infrastructure.ORM.Event.AuditTrailInterceptor -> Infrastructure.SharedKernel.Abstractions.Context.IApplicationContext.
         Autofac.Core.Activators.Reflection.NoConstructorsFoundException : No accessible constructors were found for the type 'Infrastructure.SharedKernel.Abstractions.Context.IApplicationContext'.

My Interface - 

    public interface IApplicationContext: IHostConnectionKeyProvider
    	{
    		/// <summary>
    		/// Gets or sets the Environment
    		/// Gets the Environment
    		/// </summary>
    		string Environment { get; set; }
    
    		/// <summary>
    		/// Gets or sets the UserId
    		/// </summary>
    		string UserId { get; set; }
    }

Class with above interface-

    public class AuditTrailInterceptor : EmptyInterceptor
        {
            private readonly IApplicationContext _applicationContext;
    
    
            public AuditTrailInterceptor(IApplicationContext applicationContext)
            {
                _applicationContext = applicationContext;
            }
    //
    } 

Application Builder code - 

 

    var builder = new ContainerBuilder();
     builder.RegisterType<IApplicationContext>().AsImplementedInterfaces().InstancePerLifetimeScope();
     builder.RegisterType<AuditTrailInterceptor>().As<IInterceptor>().InstancePerLifetimeScope();

I need help in resolving above exception. **Why Autofac is looking for constructor in interface**??

**Comment by tillig** [comment]
Questions like this are great for [StackOverflow](https://stackoverflow.com) - in the future, please ask there and tag `autofac` (all of us already monitor that).

`builder.RegisterType<IApplicationContext>().AsImplementedInterfaces().InstancePerLifetimeScope();`

You registered an interface as a type so it's going to try to "new up" the thing you registered. Register your implementation of `ApplicationContext` rather than registering the interface itself.

**Comment by Nitin5acc** [comment]
Hello,

SO has a limit of 90 mins on New question by IP, Needed the answer at the earliest.
Thank you very much !!!
One more thing-
Can I register this not as a Type but as an interface?
