### ISSUE TITLE
Add PackageIcon in .csproj

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac#1057]
Recent packaging operations are starting to issue a warning that the 'PackageIconUrl'/'iconUrl' element is deprecated and we should switch to 'PackageIcon'/'icon'.

[More info here.](https://aka.ms/deprecateIconUrl)

Based on that doc...

> You should specify both PackageIcon and PackageIconUrl to maintain backward compatibility with clients and sources that do not yet support PackageIcon. Visual Studio will support PackageIcon for packages coming from a folder-based source in a future release.

Seems easy enough. I'm not sure we should use an `images` folder for the icon but maybe it could live in the root of the repo or the `build` folder or something.

**Comment by tillig** [comment]
I gather this is a thing that we'll have to do for all the projects, so... yeah. And switching from license URL to `PackageLicenseExpression`.

**Comment by alistairjevans** [comment]
I'll PR the change for core now; when we make the multiple changes to the integrations for referencing 5.0 we can update the packageicon and packagelicense info.
