### ISSUE TITLE
Autofac RegisterAssemblyTypes from tests

### ISSUE THREAD

**Issue by olgatei** [autofac/Autofac#1060]
_this question is posted on [stackoverflow](https://stackoverflow.com/questions/59330674/autofac-registerassemblytypes-from-tests), posting it here since it is not answered on SO hopping if gets some traction._

In my `Startup` class I have a method for `RegisterAssemblyTypes` through autofac as the following: 

```csharp
public class Startup
{
    public void ConfigureContainer(ContainerBuilder builder)
    {
        builder.RegisterModule(new ApplicationModule());
    }
}

public class ApplicationModule : Autofac.Module
{
    protected override void Load(ContainerBuilder builder)
    {
        builder
            .RegisterAssemblyTypes(
                typeof(EventHandler).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IIntegrationEventHandler<>));
    }
}
```

What is the suggested way of registering assemblies using `Autofac` (e.g., `RegisterAssemblyTypes`) when the `Startup` class is called from integration tests; e.g.,

```csharp
public class IntegrationTestApplicationFactory : WebApplicationFactory<Startup>
{ }
```

I am using Autofac 4.9.4.

**Comment by tillig** [comment]
As noted in the issue template, we already monitor StackOverflow. Please don't double-post.
