### ISSUE TITLE
PropertiesAutowired is dosen't work in ControllerBase

### ISSUE THREAD

**Issue by HandsomeBoy01** [autofac/Autofac#1063]
I added auto injection, but it doesn't work in ControllerBase!
(.Net core 3.1   autofac latest version)

this is my code:

  ```
 var controllerBaseType = typeof(ControllerBase);
            builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
                .Where(t => controllerBaseType.IsAssignableFrom(t) && t != controllerBaseType)
                .PropertiesAutowired();
   builder.RegisterType<ArticleService>().As<IArticle>().PropertiesAutowired().InstancePerLifetimeScope();
```

 ```
 public void ConfigureServices(IServiceCollection services){
  services.AddMvc().AddControllersAsServices();
  }
```
this is my controller

```
   [Route("api/[controller]")]
   [ApiController]
    public class BaseApiController : ControllerBase
    { 
        public IArticle article { get; set; }

        public BaseApiController()
        {
            article.GetArticleWithIdAsync("a");
        }

    }


```
but article  is null  I don't know why
Can you help me with this question

**Comment by HandsomeBoy01** [comment]
@tillig

**Comment by alistairjevans** [comment]
If you're accessing ``article`` in the constructor, it will always be null, because property injection doesn't happen until after the constructor has exited.

**Comment by HandsomeBoy01** [comment]
> If you're accessing `article` in the constructor, it will always be null, because property injection doesn't happen until after the constructor has exited.

ok ,I see, thank for your help
