### ISSUE TITLE
ComponentContext unable to resolve delegate factories

### ISSUE THREAD

**Issue by keerthimaryala18** [autofac/Autofac#1064]
public interface IConsume
    {
        void Consume(object message);
    }
    public delegate IEnumerable<IConsume> SubscriberFactory(Type messageType);
    public delegate IEnumerable<IConsume> SourceOfTruthProjectorFactory(Type messageType);

Registering the delegate binding

    // create bindings for subscriber delegates
            containerBuilder.Register<SubscriberFactory>(context =>            
                messageType => SubscriberFactory(context.Resolve<IComponentContext>(), subscribers, messageType)
            );

            containerBuilder.Register<SourceOfTruthProjectorFactory>(context =>
               messageType => SubscriberFactory(context.Resolve<IComponentContext>(), sourceOfTruthProjectors, messageType)
           );

        private IEnumerable<IConsume> SubscriberFactory(IComponentContext context, IEnumerable<Type> subscribers, Type messageType)
        {
            var _context = context.Resolve<IComponentContext>();
            foreach (var consumerType in subscribers)
            {
                var genericArgs = ReflectionHelpers.GetGenericParamsFromAnyInheritance(consumerType,
                    type => type == messageType || type.IsAssignableFrom(messageType));
                if (genericArgs.Any())
                    yield return (IConsume)context.Resolve(consumerType);
            }
        }

'messageType' resolves at run-time.
This fails to resolve the IComponentContext and hence failing the binding with the following error

`This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.`

I also tried resolving IComponentContext again in the SubscriberFactory method specified above and it failed with the same error.

**Comment by alsami** [comment]
I think it is this line causing the problem

`yield return (IConsume)context.Resolve(consumerType);`

You need to use the inner-context that you've already resolved in function-factory.
`yield return (IConsume)_context.Resolve(consumerType);`

That should do the trick. Would you mind trying that?

**Comment by keerthimaryala18** [comment]
Thanks for the reply. I tried that as well and it resulted in the same error. Not sure if resolving the 'messageType' at run-time is causing the Context to expire

**Comment by alsami** [comment]
> Not sure if resolving the 'messageType' at run-time is causing the Context to expire

I don't think that should be a problem. Would you mind creating a small repo for reproducing this issue?

**Comment by alexmg** [comment]
Closing as insufficient detail provided to reproduce the issue. Please feel free to open with additional information if this is still a problem.
