### ISSUE TITLE
How to resolve dependency (that is registered in nested scope) from parent scope?

### ISSUE THREAD

**Issue by asadalidev** [autofac/Autofac#1065]
I am trying to resolve dependency (registered in nested scope) from parent scope.
I registered 'SomeClass' in nested scope, but later somewhere else in the program I want to resolve it from container.

`void RegisterDependenciesForNestedScope(ContainerBuilder cb) => cb.RegisterType<SomeClass>().SingleInstance();`

            using (var scope = container.BeginLifetimeScope("Asad", RegisterDependenciesForNestedScope))
            {
                container.Resolve<SomeClass>();
            }`

Currently, it throws an exception that Type is not registered (which is obvious). But how I can do this?

**Comment by tillig** [comment]
If you register something only in a child scope it will never be seen by a parent. Scopes are one-way hierarchical.

Please ask further usage questions ("how do I do this?") on StackOverflow.
