### ISSUE TITLE
Autofac 5.0 Upgrade Causing Missing Method Exception In Test Classes

### ISSUE THREAD

**Issue by eseger13** [autofac/Autofac#1074]
After updating to Autofac 5.0, I'm getting the error below in my test library.  I've upgraded another project to Autofac 5.0 (from 4.9.4) and got the same error in project's test library.  I've attempted to downgrade back to 4.9.4, but the error persists.  

System.MissingMethodException : Method not found: 'Void Autofac.RegistrationExtensions.RegisterSource(Autofac.ContainerBuilder, Autofac.Core.IRegistrationSource)'.
  Stack Trace: 
    AutoMock.ctor(MockRepository repository, Action`1 beforeBuild)
    AutoMock.ctor(MockBehavior behavior, Action`1 beforeBuild)
    AutoMock.GetLoose()

SIT Project File
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.9.4" />
    <PackageReference Include="AutofacSerilogIntegration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

Test Project File
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extras.Moq" Version="4.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Moq" Version="4.13.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdobeConnectorLocal\AdobeConnectorLocal.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

</Project>

**When filing an issue, please include:**

- Assembly version information for _all_ project dependencies (packages.config, project.json)
- The stack trace and message of any exception(s) encountered.
- If possible, a reproduction of the issue (ideally in a unit test form).

**Comment by eseger13** [comment]
My project file info was deleted on submission.  

Test Project File
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extras.Moq" Version="4.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Moq" Version="4.13.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdobeConnectorLocal\AdobeConnectorLocal.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

</Project>

**Comment by eseger13** [comment]
Deleted again.  
[SIT_ProjectDependencies.txt](https://github.com/autofac/Autofac/files/4129263/SIT_ProjectDependencies.txt)
[Test_ProjectDependencies.txt](https://github.com/autofac/Autofac/files/4129264/Test_ProjectDependencies.txt)

**Comment by tillig** [comment]
This is an issue with the Autofac.Extras.Moq extension, not Autofac core. [As noted in the Autofac 5 release notes](https://github.com/autofac/Autofac/releases/tag/v5.0.0), we're still working on updating the integration and extension libraries. Updating Autofac.Extras.Moq looks like it's going to be a little more tricky than some of the others.

Please be patient, we're getting there. If you still see it after you get the updated version of Autofac.Extras.Moq [once it's released] then file a new issue. Thanks!

**Comment by eseger13** [comment]
Thanks for the fast reply.
