### ISSUE TITLE
ComponentRegistration Activating is not working as before

### ISSUE THREAD

**Issue by ysmoradi** [autofac/Autofac#1077]
> Is this for Autofac 5? [Read the release notes!](https://github.com/autofac/Autofac/releases/tag/v5.0.0) We are working on updating integration libraries but they're not all done. Please don't file issues about integration library incompatibility until you get the updated version which may not yet be published! If you really need it faster, a PR directly to the integration library will speed it up! (When the integration library is posted, file additional issues in that repo. THIS IS FOR CORE AUTOFAC ONLY.)

I've updated Signalr2 integration with a [PR](https://github.com/autofac/Autofac.SignalR/pull/7), please accept that (:

> Try StackOverflow! If you have a _usage question_ ("How do I...?" "Others have this working but I can't get it...") please try [StackOverflow](https://stackoverflow.com) and tag your question `autofac`. We, along with a great community, monitor those questions.

I wasn't able to find something related to my issue

> **Have you [read the docs?](https://autofac.readthedocs.io/)**

Yes

> **This repo is for core Autofac only.** If you are encountering issues with an integration package (MVC, Web API, etc.) please file it in the appropriate repo. Thanks!

my issue is directly related to autofac

**When filing an issue, please include:**

> - Assembly version information for _all_ project dependencies (packages.config, project.json)
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.9.4" />
  </ItemGroup>

</Project>
```

> - The stack trace and message of any exception(s) encountered.

There is no exception

> - If possible, a reproduction of the issue (ideally in a unit test form).

Just copy paste following codes:

```cs
class Program
    {
        static async Task Main(string[] args)
        {
            ContainerBuilder containerBuilder = new ContainerBuilder();

            containerBuilder.RegisterCallback(x =>
            {
                x.Registered += (sender, args) =>
                {
                    args.ComponentRegistration.Activating += ComponentRegistration_Activating;
                };
            });

            containerBuilder.RegisterGeneric(typeof(InMemoryRepository<>)).As(typeof(IRepository<>)).PropertiesAutowired(PropertyWiringOptions.PreserveSetValues);
            containerBuilder.RegisterType<CustomersController>().PropertiesAutowired(PropertyWiringOptions.PreserveSetValues);

            using var container = containerBuilder.Build();

            await container.Resolve<CustomersController>().AddNewCustomer();
        }

        static void ComponentRegistration_Activating(object sender, ActivatingEventArgs<object> e)
        {
            Console.WriteLine(e.Instance);
        }
    }

    public interface IRepository<TEntity>
        where TEntity : class
    {
        Task Add(TEntity entityToAdd, CancellationToken cancellationToken);
    }

    public class InMemoryRepository<TEntity> : IRepository<TEntity>
        where TEntity : class
    {
        public async Task Add(TEntity entityToAdd, CancellationToken cancellationToken)
        {

        }
    }

    public class Customer
    {

    }

    public class CustomersController
    {
        public Lazy<IRepository<Customer>> CustomersRepository { get; set; }

        public async Task AddNewCustomer()
        {
            await CustomersRepository.Value.Add(default, default);
        }
    }
```
In autofac 4.9.4, ComponentRegistration_Activating is being called in a way that is expected and you can see InMemoryRepository<Customer>, but in autofac 5, you won't see that )-:

**Comment by tillig** [comment]
I'm guessing this is somehow related to the immutable container mechanism and a change in how/when events are fired. Is the callback executing after the components are registered? (I'm not able to debug into this at the moment, but that's where I'd start.) Off the top of my head I don't know what the updated code would be.

**Comment by ysmoradi** [comment]
All other registrations are fine, only generic registrations are in trouble!

**Comment by weelink** [comment]
The `Registered` and `RegistrationSourceAdded` events are only raised from a `IComponentRegistryBuilder`. In this scenario a registration is added later in the process when no `IComponentRegistryBuilder` is available. It seems that is the reason the event isn't being raised.

I've created a [PR to solve this problem](https://github.com/autofac/Autofac/pull/1079), but it introduces a nasty design issue. I don't have a solution to this yet.
