### ISSUE TITLE
Re-add the three-parameter ResolveRequest constructor

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac#1081]
In [d485f39](https://github.com/autofac/Autofac/commit/df15144fee19eff1f0624716239609727134f812#diff-6ce39e829d26a0cf0e6a5452761df8e8) the three-parameter constructor for `ResolveRequest` was removed, which is a breaking change. We need to put it back and issue a 5.1.1 release.

Related: autofac/Autofac.Wcf#21

**Comment by alexmg** [comment]
Mea culpa. I should have seen that one coming.
