### ISSUE TITLE
System.IO.FileLoadException after updating to AutoFac 5.1.0 (Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0)

### ISSUE THREAD

**Issue by tivtag-atwork** [autofac/Autofac#1082]
Hello Team,

when I upgrade our project from AutoFac 4.9.4 to AutoFac 5.1.0 I get the following FileLoadException at runtime: 

```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

We use:
- .NET Framework 4.8
- the new VS19 .csproj format
- MessagePack 2.1.90, which has a dependency on System.Threading.Tasks.Extensions (**>= 4.5.3**).
- System.Threading.Tasks.Extensions.dll is in the Output folder with File version 4.6.27818.1

I can see that AutoFac 5.1.0 references Microsoft.Bcl.AsyncInterfaces (>= 1.1.0), which requires System.Threading.Tasks.Extensions (**>= 4.5.2**).

I have tried various Binding Redirects, without success. But maybe the wrong one?

Thank you for your support!
Paul

**Comment by alsami** [comment]
Hi, thanks for reporting this.

First, could you try adding an explicit reference to `System.Threading.Tasks.Extensions` to version `4.5.3`?

If that doesn't help, would you be so kind to provide a sample project to reproduce the issue?

**Comment by tivtag-atwork** [comment]
Hi alsami, thank you for your idea!

Adding an explicit reference to `System.Threading.Tasks.Extensions` to version 4.5.3 and also including the following binding redirect made it work!

```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
  </dependentAssembly>
</assemblyBinding>
```

Working with these newer .NET Libraries has been troublesome at times.

Thank you!
Cheers, Paul
