### ISSUE TITLE
Ambiguous invocation ResolutionExtensions and ResolutionValueExtensions

### ISSUE THREAD

**Issue by BlackGad** [autofac/Autofac#1086]
**Environment**
Autofac 5.1.2
Visual studio 2017
.NET 4.6.1

**Code**
```CSharp
ILifetimeScope scope;
var instance = scope.ResolveOptional<IInterface>();
```

**Build error**
```
Source.cs(Line, Position): error CS0121: The call is ambiguous between the following methods or properties: 'ResolutionExtensions.ResolveOptional<TService>(IComponentContext)' and 'ResolutionValueExtensions.ResolveOptional<TService>(IComponentContext)'
```

**Comment by alistairjevans** [comment]
Can you provide the definition of ``IInterface``?

**Comment by BlackGad** [comment]
Here [example](https://github.com/BlackGad/AutofacAmbiguousInvocation)
On Visual Studio 2019 with ReSharper you can see this error if project `C# Language Level` option is CSharp70.
Or use generic Visual Studio 2017 build

**Comment by alistairjevans** [comment]
Are you somehow restricted to 7.0? If you change from 7.0 (default) to 7.3 (latest) in VS2017, the problem is fixed.

I think this was an extension method bug in C# 7.

**Comment by BlackGad** [comment]
Seems our CI (TeamCity) do not pass [-langversion](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option) option at all. 

Will try to force higher C# version.

**Comment by alistairjevans** [comment]
You should be able to set it in the project file:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#edit-the-project-file

**Comment by BlackGad** [comment]
@alistairjevans Thank you. Force flag in project solve this. 
Hope this issue will help somebody in future :)

**Comment by treehan77** [comment]
I have same issue exactly with a previously working call with ResolveOptional.  I am using c# 7.3 already though.  I am in VS2017 and AutoFac 4.9.2 worked, updating to 5.2.0 shows this error.  How to fix?

**Comment by tillig** [comment]
Make sure you delete all the .user, bin, and obj in the solution to ensure nothing is cached incorrectly.
