### ISSUE TITLE
RegistrationBuilder.RegisterSingleComponent

### ISSUE THREAD

**Issue by yuzd** [autofac/Autofac#1087]
Is this for Autofac 5? [Read the release notes!]
yes verison5.1.2

i update from 4.9.4

i want if Instance (marked as AutoActivate ) is created then register more. just like spring ioc AutoConfiguration Bean in java!

in 4.9.4 i use RegistrationBuilder.RegisterSingleComponent（） successfull do that!

but update to 5.1.2 

“Autofac.Core.IComponentRegistry” =》 “Autofac.Core.Registration.IComponentRegistryBuilder”	

RegistrationBuilder.RegisterSingleComponent（） err!

how to change my code ?

**Comment by alistairjevans** [comment]
The container registry is now immutable (i.e. you cannot change it after it has been built). This will account for the difference you are seeing.

If you share your 'before' code, we may be able to guide you in the required changes.

**Comment by yuzd** [comment]
That's a big change!  Because there's no way to implement something like spring ICO AutoConfiguration (by method invoke and get the return object to register to IOC as singleton)?

Do you have any other way Or suggest?

**Comment by alistairjevans** [comment]
You're correct about it being a big change, hence the major version increment! 

From what I can tell of your library, you should still be able do what you want, but you will need to detect and create your instances of AutoConfiguration(s) manually inside your Module load method, rather than use the Start callback.  

All the existing functionality is still there, but you can only do it prior to the container being built, either directly via ContainerBuilder, or by using ContainerBuilder.RegisterCallback and then using the provided IComponentRegistryBuilder in that callback.

**Comment by yuzd** [comment]
by using ContainerBuilder.RegisterCallback and then using the provided IComponentRegistryBuilder in that callback
==> Can I get registered object from the container in the callback?

**Comment by alistairjevans** [comment]
The container doesn't exist at that point, so you cannot resolve from it. 

If you're scanning the assembly for these configuration classes, would you be able to use Activator.CreateInstance when you find them and then invoke the appropriate methods directly, without needing to resolve it from the container?

**Comment by yuzd** [comment]
Activator.CreateInstance when you find them and then invoke the appropriate methods directly, without needing to resolve it from the container?
==> i can do that . but i need to remove parameters in method

![image](https://user-images.githubusercontent.com/16083659/74928130-d998c100-5413-11ea-8760-5cdc31020ff1.png)

i think about it.

**Comment by alistairjevans** [comment]
As an alternative, if you must resolve an instance from a container, you could consider creating the initial container without your custom items in, and then creating a new lifetime scope, using the configuration callback there to change the registered components.

At the point of creating a new lifetime scope you can both resolve from the parent container, and reconfigure the component registry for the new lifetime scope.

**Comment by yuzd** [comment]
thanks  i will have a try

**Comment by alistairjevans** [comment]
Ok; I'm going to close this issue for now. We can open it again if you find some bug that's blocking your refactoring.

**Comment by yuzd** [comment]
i found a question: 
```csharp

var builder = new ContainerBuilder();
builder.Populate(services);

 builder.RegisterModule(new AutofacAnnotationModule(typeof(Startup).Assembly);
builder.Register<yy>();
 var container = builder.Build();
container.Resove<yy>();
container.Resove<XX>(); // have probleam
 
```

```
// in my AutofacAnnotationModule i will cretae new Container.

 protected override void Load(ContainerBuilder builder)
        {
          

            builder.RegisterBuildCallback(scope => { 

               
                var child = scope.BeginLifetimeScope(cfg =>
                {
                   cfg.Register<xx>();
                     //do my work
                });

                //how to get child from root scope?
               // child  is my new Container,ho can be to useed from rootScope call
              // child instance can not register to builder
                

            });
}
```
