### ISSUE TITLE
Resolved Factory Delegates Bypass Parameters Passed to `Resolve`

### ISSUE THREAD

**Issue by brucificus** [autofac/Autofac#1097]
This is for Autofac version 5.1.2.

I am attempting to call `ILifetimeScope.Resolve<Func<Owned<TService>>>(…)`, _with_ parameters, but it seems the parameters are being thrown away and not passed to the resolution of `TService`.

Here is a reproduction:

```csharp
[Test]
public void CanResolveOwnedServiceFactoryWithParameterizedResolve()
{
    ContainerBuilder containerBuilder = new ContainerBuilder();
    containerBuilder.RegisterType<Service2>();
    using (var container = containerBuilder.Build())
    {
        var ownedFactory = container.Resolve<Func<Owned<Service2>>>(
        new [] {
            TypedParameter.From(new Service1())
        });
        using (var ownedInstance = ownedFactory()) // throws DependencyResolutionException
        {
            …
        }
    }
}
public class Service1 { }
public class Service2 { public Service2(Service1 dependency) { } }
```

I would expect this resolution to succeed. Instead, it throws a `DependencyResolutionException`.

I am specifically calling `Resolve` in this way because I want to provide a variable number of parameters while keeping the resulting factory delegate niladic.

**Comment by brucificus** [comment]
It looks like [`ResolutionExtensions.TryResolveService(…)`](https://github.com/autofac/Autofac/blob/b913d2f33054d45bc11a9b5894915f01f8b1db9b/src/Autofac/ResolutionExtensions.cs) doesn't pass the `parameters` to `ComponentRegistry.TryGetRegistration(…)`, so they never make it down to `FactoryGenerator` where they could be used to generate the factory.

**Comment by alistairjevans** [comment]
With a factory resolve operation, can you not just pass the parameters to the factory method?

Something like this (haven't tested it though):

```csharp
using (var container = containerBuilder.Build())
{
    var ownedFactory = container.Resolve<Func<Service1, Owned<Service2>>>();
    using (var ownedInstance = ownedFactory(new Service1()))
    {
        …
    }
}
```

**Comment by alistairjevans** [comment]
> keeping the resulting factory delegate niladic.

Oh, I see. I don't see a way for that to work the way you have it, the factory generator doesn't consider provided parameters at resolve time (as you say). All parameters must be provided when the factory delegate is invoked.

I can see a way of doing it using reflection, but it would be pretty nasty.

**Comment by brucificus** [comment]
@alistairjevans Thanks for the eyeballs on this.

After poking at the Autofac code, I don't think this can be accomplished trivially. Most notably it would require breaking changes to `IRegistrationSource` signatures.

As a work-around, I will go the reflection route. Ironically, I suspect it will involve doing the inverse of what `FactoryGenerator` does: creating a `Func` with _no_ parameters that closes over a (dynamically generated) invocation of a `Func` with all the accumulated parameters.

**Comment by alistairjevans** [comment]
Ok, not sure it's something we'll have time to work on ourselves to be honest. I'm going to label this as an enhancement and close it; if you want to contribute a PR for it at some point, we can re-open this and discuss it in more depth.

Thanks
