### ISSUE TITLE
Autofac generic decorator doesn't work in version 5.1.2

### ISSUE THREAD

**Issue by sinanakyazici** [autofac/Autofac#1098]
I have code block like below,

```csharp
using System;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Autofac;
using MediatR;

namespace DecoratorConsoleApp
{
    public class Program
    {
        private static void Main()
        {
            var mediator = Register();
            Task.Run(async () => { await mediator.Send(new CreateCustomerCommand()); }).Wait();
            Console.ReadLine();
        }

    public static IMediator Register()
    {
        var builder = new ContainerBuilder();

        builder.RegisterAssemblyTypes(typeof(IMediator).GetTypeInfo().Assembly).AsImplementedInterfaces();

        builder
            .RegisterAssemblyTypes(typeof(CreateCustomerCommandHandler).GetTypeInfo().Assembly)
            .AsClosedTypesOf(typeof(IRequestHandler<,>))
            .AsImplementedInterfaces();

        builder.Register<ServiceFactory>(ctx =>
        {
            var c = ctx.Resolve<IComponentContext>();
            return t => c.Resolve(t);
        });

        builder.RegisterGenericDecorator(typeof(DiagnosticDecorator<,>), typeof(ICommandHandler<,>));
        var container = builder.Build();

        return container.Resolve<IMediator>();

    }
}

public interface ICommand<out TResponse> : IRequest<TResponse> { }

public interface ICommandHandler<in TRequest, TResponse> : IRequestHandler<TRequest, TResponse> where TRequest : ICommand<TResponse> { }

public class CreateCustomerCommand : ICommand<Guid> { }

public class CreateCustomerCommandHandler : ICommandHandler<CreateCustomerCommand, Guid>
{
    public async Task<Guid> Handle(CreateCustomerCommand request, CancellationToken cancellationToken)
    {
        await Task.CompletedTask;
        Console.WriteLine("test");
        return new Guid();
    }
}

public class DiagnosticDecorator<TRequest, TResponse> : ICommandHandler<TRequest, TResponse> where TRequest : ICommand<TResponse>
{
    private readonly ICommandHandler<TRequest, TResponse> _decorated;

    public DiagnosticDecorator(ICommandHandler<TRequest, TResponse> decorated)
    {
        _decorated = decorated;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken)
    {
        Console.WriteLine("before");
        var response = await _decorated.Handle(request, cancellationToken);
        Console.WriteLine("after");
        return response;
    }
}
}
```

MediatR version is 8.0.1 I'm trying to run it. DiagnosticDecorator doesn't work Autofac.5.1.2. I downgraded Autofac version to 4.9.0. It works. . What is difference between versions ?

**Comment by alistairjevans** [comment]
Hi @sinanakyazici, can you please provide some indication of what doesn't work?

Ideally, a failing unit test that we can run.

Thanks

**Comment by sinanakyazici** [comment]
Hi @alistairjevans , Decorator doesn't work. I don't understand why. It is a console application. Project config like below :

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.9.0" />
    <PackageReference Include="MediatR" Version="8.0.1" />
  </ItemGroup>

</Project>
`

**Comment by alistairjevans** [comment]
Ok, I know what's going on here; you are registering a decorator for ``ICommandHandler<,>``, but MediatR resolves the ``IRequestHandler<,>`` service. If you change the decorator registration, it works as expected.

The reason this is different in Autofac v5 is because we improved the decorator behaviour to make the selection of the decorator dependent on the service that was requested, rather than the object to decorate (which resolved a whole host of issues with multiple decorator registrations).

**Comment by sinanakyazici** [comment]
@alistairjevans I understand but it is not correct for me.  Because decorator intercepts every request when I change the code as you said. Actually I want to separate commands and queries by interfaces. I want a decorator to run for only the implemented interface from ICommandHandler. I edited my code, Can you check it again, please? Thanks.

**Comment by alistairjevans** [comment]
You will still need to register the decorator against the requested service (``IRequest<>``), but you can use conditional decorators to only apply a decorator to classes that implement ICommand. From the docs, just as an example:

```csharp
builder.RegisterGenericDecorator(
  typeof(ErrorHandlerDecorator<>),
  typeof(ICommandHandler<>),
  context => !context.AppliedDecorators.Any());
```

**Comment by sinanakyazici** [comment]
@alistairjevans  I changed my code, but it doesn't still work with 5,1,2. It works with 4.9.0.

**Comment by alistairjevans** [comment]
Note that the example I've given is taken directly from the docs (https://autofaccn.readthedocs.io/en/latest/advanced/adapters-decorators.html). The ``ICommandHandler`` needs to be changed to ``IRequestHandler``, and you will need to implement your own custom predicate for filtering to ``ICommandHandler<>``.

**Comment by saiprabhur** [comment]
@sinanakyazici  the issue was fixed ? i could not see any resolution. 
could you share the results if it fixed .
its not working for me..

**Comment by amedora** [comment]
> Note that the example I've given is taken directly from the docs (https://autofaccn.readthedocs.io/en/latest/advanced/adapters-decorators.html). The `ICommandHandler` needs to be changed to `IRequestHandler`, and you will need to implement your own custom predicate for filtering to `ICommandHandler<>`.

@alistairjevans
could you tell me any ideas about these examples? I'm not sure which one has better performance.
```csharp
// filter by naming
builder.RegisterGenericDecorator(
    typeof(Decorator<,>),
    typeof(IRequestHandler<,>),
    context => context.ImplementationType.FullName.EndsWith("CommandHandler"));
```
```csharp
// filter by interface implementation
builder.RegisterGenericDecorator(
    typeof(Decorator<,>),
    typeof(IRequestHandler<,>),
    context =>
    {
        return context.ImplementationType.GetInterfaces().Any(t =>
            t.IsGenericType &&
            t.GetGenericTypeDefinition() == typeof(ICommandHandler<,>));
    });
```

**Comment by alistairjevans** [comment]
From a purely **performance** perspective, it will be faster to compare the name (as per your first example).  However it's much more brittle, so it may be more accurate to check the actual type as you do in your second example.

If you need to, you can always keep a cache somewhere of `ImplementationType` -> `Is this a command handler?` to speed up the second example.

**Comment by alsami** [comment]
I know there has been a lot going on here since the first post but from my understanding of what you are trying to, MediatR has a built-in functionality for. They work similar compared to the Middleware in ASPNET Core for instance.

https://github.com/jbogard/MediatR/wiki/Behaviors

Also, what's the intention of adding and interface on top of the already existing Mediatr interface? Is the idea that this will make it easier to change the underlying CQRS framework?
