### ISSUE TITLE
Unregister(Type) in ContainerBuilder

### ISSUE THREAD

**Issue by ardalis** [autofac/Autofac#1103]
Is this for Autofac 5? Yep.

**Have you [read the docs?](https://autofac.readthedocs.io/)** Yep.

There is apparently no way to unregister types via ContainerBuilder. This means that if I use something like this in one place in my code:

```
            builder.RegisterAssemblyTypes(webAssembly, coreAssembly, infrastructureAssembly).AsImplementedInterfaces();
```
I can't then remove certain types that I don't want to be used in a certain environment.

My question is

1. Is there a way for me to use the above functionality and then remove the 1 or 2 types I want to remove (as opposed to having to register everything by hand).

or if not then 

2. Can we add functionality to `ContainerBuilder` that would support this?

**Comment by alistairjevans** [comment]
You should be able to filter the scanned types with a predicate, or explicit exclusions:

https://autofaccn.readthedocs.io/en/latest/register/scanning.html#filtering-types

Does that not provide what you need?

**Comment by tillig** [comment]
You're correct, though, you can't unregister something that's registered. This doesn't work like an `IServiceCollection` like Microsoft.Extensions.DependencyInjection, though you could always do your registrations with that and use Autofac.Extensions.DependencyInjection to add to the `ContainerBuilder` later. Better to avoid registering the thing in the first place if possible.

**Comment by ardalis** [comment]
I have two projects in play in my scenario:

- Web (the UI and entrypoint)
- Infrastructure (various implementations of interfaces)

Inside Infrastructure is a method that performs Autofac scanning that wires all my interfaces up with their implementations.

Inside Web is logic that determines whether the application is running in "Development" or "Production" environment.

I'd rather keep environment knowledge confined to Web, ideally just in the Startup.cs file. I'd rather keep Autofac wire-up logic where it is, too.

My current approach for some things that have alternative types is something like this:

```
public void ConfigureContainer(ContainerBuilder builder)
{
    builder.InitializeAutofac(Assembly.GetExecutingAssembly());
    if (_env.EnvironmentName == "Development")
    {
        // last registration wins
        builder.RegisterType<LocalSmtpEmailService>().As<IEmailService>();

        // what I want
        buildler.UnregisterType<SomeTypeOnlyUsedInProduction>();
    }
}
```

This lets me use SendGrid in production and a localhost SMTP emulator like SMTP4Dev locally, for instance.

However, this only works if I have an alternative type. In another scenario I'm facing now I need to simply not have some types registered (event handlers). Which led to this question/request.

I suppose an option I have is to pass the environment into my IntializeAutofac extension method (that lives in Infrastructure) and then use a scanning filter like @alistairjevans suggests within there to omit the ones I don't want wired up in certain environments. Then I have environment logic spread between Web and Infrastructure, but at least I would have the behavior I want.

```

**Comment by tillig** [comment]
You could do it in two different registration blocks. In the first, register everything _but_ the event handlers.

```c#
builder.RegisterAssemblyTypes(asm)
  .Where(t => !typeof(IEventHandler).IsAssignableFrom(t))
  .AsImplementedInterfaces();
```

Then register the event handlers with their exceptions separately.

```c#
var onlyInProduction = new [] { typeof(FooHandler), typeof(BarHandler) };

// Both dev and prod
builder.RegisterAssemblyTypes(asm)
  .Where(t => !onlyInProduction.Contains(t))
  .AsImplementedInterfaces();

// Only prod
if(env.IsProduction) {
  builder.RegisterAssemblyTypes(asm)
    .Where(t => onlyInProduction.Contains(t))
    .AsImplementedInterfaces();
}
```

I'm kinda going off the top of my head here, that probably won't compile, but you get the idea.

**Comment by alistairjevans** [comment]
You could also use Autofac Modules to make this nicer? 

You could define a base abstract module class in infrastructure for your common registration behaviour, and then have child classes of that (also in infrastructure) for your different modes of behaviour, where you put in the filtering @tillig described.

Your ``InitializeAutofac`` method could then take a generic type parameter (constrained as IModule) indicating which implementation to use. Something like:

``InitializeAutofac<LocalMode>(...)``

This way, the front-end indicates what 'mode' to start the infrastructure services in, without leaking explicit environment information into the infrastructure.

Slightly cleaner maybe?

**Comment by tillig** [comment]
I think there are quite a few ways to selectively decide to not register something, and since we won't be updating ContainerBuilder to add the feature to unregister something, I'm going to close this.

**Comment by alsami** [comment]
> Inside Infrastructure is a method that performs Autofac scanning that wires all my interfaces up with their implementations.
> 
> Inside Web is logic that determines whether the application is running in "Development" or "Production" environment.
> 
> I'd rather keep environment knowledge confined to Web, ideally just in the Startup.cs file. I'd rather keep Autofac wire-up logic where it is, too.

Just another hint in addition to what has already been said: You can put your registrations in a dedicated assembly with modules and consume `Microsoft.Extensions.Hosting.Abstractions.IHostEnvironment`. `IWebHostEnvironment` derives from it. So you can pass it a long and the environment detail is not related to being a part of Web or not Web.

Or, as already suggested by @alistairjevans, use a predicate that defines whether a specific registration should happen. Let it have a default value. Then any detail would be completely hidden.

```csharp
public class InfraModule : Module
{
    private readonly Func<bool> _shouldRegisterFunc;

    public InfraModule(Func<bool> shouldRegisterFunc= null)
    {
        _shouldRegisterAccessor = shouldRegisterFunc ?? () => true;
    }

    public override void Load(ContainerBuilder builder)
    {
        if (!_shouldRegisterFunc())
           return;
      
       // registrations
    }
}
```
