### ISSUE TITLE
Possible `MissingMethodException` caused by `System.ValueTuple`

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1118]
As discussed [here](https://github.com/autofac/Autofac/pull/1117#discussion_r422606014) using `System.ValueTuple` requires the package `System.ValueTuple` to be referenced when targeting `net461`

As @alistairjevans stated in the discussion linked above, we are already [using](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Util/TypeExtensions.cs#L42) it and not getting any compiler errors (which should not be the case for `net461`).

Here also an [issue](https://github.com/dotnet/roslyn/issues/22903) on the roslyn repository that states, that this missing include was added with `net471`.

Easiest and safest fix would be to have a conditional package-reference

```csharp
<PackageReference Condition="$(TargetFramework) == 'net461'" Include="System.ValueTuple" Version="4.5.0"  />
```

That does not explain why there is no compiler error though.

**Comment by alistairjevans** [comment]
Are you able to recreate this locally @alsami, and get a `MissingMethodException`?

**Comment by alsami** [comment]
> Are you able to recreate this locally @alsami, and get a `MissingMethodException`?

@alistairjevans will get a sample repo ready later today.

**Comment by alsami** [comment]
So I just looked into it a bit and interestingly there is no way to make it throw an error. I double checked if that problem in general does exist and created a [small repository](https://github.com/alsami/ValueTupleNet461) that already fails to compile without the uncommented package-reference in the csproj file.

I then thought it must be somewhat included through some dependency that we have on `net461` but didn't find it for `Microsoft.Bcl.AsyncInterfaces` or for `System.ComponentModel.Composition`.

**Comment by alistairjevans** [comment]
Perhaps it's the netstandard2.0 reference? 

Or something to do with [this ](https://github.com/dotnet/roslyn/issues/22903#issuecomment-340536235) comment in the issue you linked?

**Comment by alsami** [comment]
> Perhaps it's the netstandard2.0 reference?
> 
> Or something to do with [this ](https://github.com/dotnet/roslyn/issues/22903#issuecomment-340536235) comment in the issue you linked?

I figured it out now.  If you uncomment the reference to `Microsoft.Bcl.AsyncInterfaces` in the `Autofac` project, it fails to compile on `net461` in the sample that uses value-tuples.

Not sure why though, I can't find it as a dependency of the package, not even as peer dependency of that said package. Closing this, sorry for the confusion! :)

**Comment by alistairjevans** [comment]
No probs, good to get to the bottom of stuff like this.
