### ISSUE TITLE
Possibility to get registered decorators

### ISSUE THREAD

**Issue by DominikAmon** [autofac/Autofac#1124]
There is no actual way to access all registired decorators.
I suggest a feature like ComponentRegistry.IsRegistered(serviceType) for decorators as well or an enumeration of decorators such as ComponentRegistry.Decorators

If there is already an option for this, I'd be happy to know. 
So far my question on Stackoverflow remains open as well:
https://stackoverflow.com/q/62002424/1099519

**Comment by alistairjevans** [comment]
I have answered the stackoverflow question, but in future please avoid double-posting, it makes it harder to manage all the issues and support questions we have going on.
