### ISSUE TITLE
Cache methods created via reflection if possible

### ISSUE THREAD

**Issue by twsouthwick** [autofac/Autofac#1146]
While submitting #1142 , it was observed that some of the reflection stuff could be cached. This issue is to track that (feel free to close if there's already something better that I did not find).

The context of that comment was the following line:

```csharp
var registrationCreator = CreateRegistrationMethod.MakeGenericMethod(valueType);
```

This is created on any child scope and could be cached so it does not have to be created on calls like this. In an ASP.NET Core service, this ends up being created for every scoped service that goes down this path I believe.

An option would be to use `Delegate.CreateDelegate` such as the following:

```csharp
public class ImplicitRegistrationSource
{
  private delegate IComponentRegistration RegistrationCreator(Service providedService, Service valueService, IComponentRegistration valueRegistration);

  private static readonly MethodInfo CreateRegistrationMethod = typeof(ImplicitRegistrationSource).GetTypeInfo().GetDeclaredMethod(nameof(CreateRegistration));

  private readonly ConcurrentDictionary<Type, RegistrationCreator> _methodCache;

  private RegistrationCreator GetRegistrationCreator(Type type)
      => _methodCache.GetOrAdd(type, t =>
      {
          var method = CreateRegistrationMethod.MakeGenericMethod(t);

          return (RegistrationCreator)Delegate.CreateDelegate(typeof(RegistrationCreator), this, method);
      });
}
```

Whenever a method is needed for a type, it would be retrieved as follows:

```csharp
var registrationCreator = GetRegistrationCreator(valueType);
```

Since I did not see any other usage of `Delegate.CreateDelegate` in the codebase, I wanted to open it up for discussion before submitting a PR to see if there's a reason to not use it here.

**Comment by twsouthwick** [comment]
Actually, I'm seeing a number of usage of `MethodInfo.CreateDelegate`, so looks like that's probably a fine way to go. I'll look into use of `MakeGenericType()` beyond just the implicit source that could benefit from some delegate caching if that sounds good.

**Comment by alistairjevans** [comment]
We do cache methods like this elsewhere (I believe).

It's worth noting that the `RegistrationsFor` will only be invoked the first time a given service is resolved in the container, plus in each scope that contains additional registrations. 

I'm guessing the ASP.NET core request scope has custom registrations, which is why that gets hit on every request.
