### ISSUE TITLE
fake for interface resolved at runtime

### ISSUE THREAD

**Issue by ejwoerlee** [autofac/Autofac#1151]
Using Autofac.Extras.FakeItEasy:
How do I Return a fake for interfaces that are resolved at runtime.

Say I want to (nunit)test the function below:

```
public class TestClass
{
        private readonly IComponentContext context;
        public TestClass(IComponentContext context, ILogger<TestClass> logger) 
        {
            this.context = context;
        }

        public async Task Test(string one, string two)
        {
            try
            {               
                var 
                IPrintHandler printHandler = context.Resolve<IPrintHandlerBO>(new TypedParameter(typeof(string), ipaddress)));

                string stringmessage = "test123" ;
                await printHandler.ProducePrint(stringmessage);
            }
            catch (Exception e)
            {
                throw; 
            }
        }
}
```

How can I setup a unit test using Autofac.Extras.FakeItEasy, since the interface is resolved at runtime ? This doesn't work, since IComponentContext.Resolve is an extension method..

```
using (var fake = new AutoFake())
            {
                // Arrange - configure the fake   
                // A.CallTo(() => fake.Resolve<Autofac.IComponentContext>.Resolve)(...)).Returns("");
               
                var sut = fake.Resolve<TestClass>();

                // Act
                var actual = sut.Test();

                // Assert - assert on the fake
                //A.CallTo(() => fake.Resolve<IDependency>().GetValue()).MustHaveHappened();
            }
```

Thanks in advance!

**Comment by tillig** [comment]
As noted in the issue template:

> Try StackOverflow! If you have a _usage question_ ("How do I...?" "Others have this working but I can't get it...") please try [StackOverflow](https://stackoverflow.com) and tag your question `autofac`. We, along with a great community, monitor those questions.

and

> **This repo is for core Autofac only.** If you are encountering issues with an integration package (MVC, Web API, etc.) please file it in the appropriate repo. Thanks!
