### ISSUE TITLE
Autobot Tesing (not a real issue) 

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1179]

**Comment by alsami** [comment]
Autobot help

**Comment by alsami** [comment]
Autobot ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark tag:v5. 2.0 v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot help

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autobot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark tag:v5. 2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 develop

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark tag:v5.2.0 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark v6 v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark MultiConstructorBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark MultiConstructorBenchmark develop v6

**Comment by alsami** [comment]
Autobot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop develop

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop develop

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop develop

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop develop

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark abcdfgh v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark abcdfgh v6

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark ChildScopeResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark KeylessNestedSharedInstanceLambdaBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:944d4cb4b6b630f70229daf9de7726d5a3dbe848 v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:944d4cb4b6b630f70229daf9de7726d5a3dbe848 v6

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot help

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6 verbose

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6 verbose

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6 verbose

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop v6 verbose

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark master develop verbose

**Comment by tillig** [comment]
Closing this for now. Might be good to either start a new issue or possibly use issues in the a different repo for additional testing if needed later. (It kinda sucks getting 100 emails about this issue as testing goes on, if you know what I mean.)
