### ISSUE TITLE
A simpler way of handling exceptions?

### ISSUE THREAD

**Issue by StojanovicMilos** [autofac/Autofac#1195]
Hi everyone, first time posting, so please forgive me if I did anything wrong.

## Problem Statement

I cannot find a simple way of automatically handling exceptions in builder.Register. For context, here is a sample code:

```
public class MyModule : Module
{
  protected override void Load(ContainerBuilder builder)
  {
    builder.Register(c => 
      {
        TopicClient topicClient = new TopicClient(configuration.ConnectionString, configuration.EntityPath);
        return new MyObject(topicClient);
      }
  }
}
```

TopicClient is Microsoft.Azure.ServiceBus.TopicClient. Configuration is just our wrapper around web.config/app.config. The problem is when TopicClient constructor doesn't get a valid connection string, it throws an exception. That's how MS implemented it and we can't change that. Now, in dev environment, we set that connectionString and everything works fine. The problem occurred when we deployed to production and didn't set the production connectionString to a valid value. Our bad. We spent hours trying to find the source, and eventually we fixed it. Now, since we do not want to have to spend hours to find this out again, we wanted to implement exception handling which will log what exception is thrown. However, the only way we found it can work is wrapping every single object instantiation in try/catch like this: 

```
public class MyModule : Module
{
  protected override void Load(ContainerBuilder builder)
  {
    builder.Register(c => 
      {
        try
        {
          TopicClient topicClient = new TopicClient(configuration.ConnectionString, configuration.EntityPath);
          return new MyObject(topicClient);
        }
        catch (Exception e)
        {
          //handle exception here
        }
      }
  }
}
```

Since we have a lot of objects depending on configuration, this isn't really a feasible solution. Also, doing it like this would cause a lot of code duplication, since exception handling would be the same for all cases, even if it's a single line of code.

## Desired Solution

It would be amazing if Autofac would support global exception handling in all of it's modules in the project/solution. If an exception is thrown anywhere and it's not handled, there should be a place that's a safety net that catches it so we can handle it.

## Alternatives You've Considered

I've looked trough SO and blogs, and the closes things I've found to what I need (other than what I mentioned above) are these: 
- https://autofaccn.readthedocs.io/en/latest/advanced/debugging.html - of course I started with documentation, but it only explains to understand the exceptions being thrown, not how to handle them in prod environment
- https://stackoverflow.com/questions/18578942/how-can-i-log-all-resolve-requests-to-autofac-container - this suggests using ResolveOperationEnding, but I couldn't find any usage examples, not even in the Whitebox profiler (https://code.google.com/p/whitebox/source/browse/Whitebox.Containers.Autofac/WhiteboxProfilingModule.cs)
- https://www.irisclasson.com/2019/09/07/unit-testing-autofac-registrations/ - this suggests unit testing autofac modules which sounds good, but it won't work as production values are entered after installation on production server, to keep privacy of those settings, so I don't think this will work either.
- https://stackoverflow.com/questions/11485372/how-to-handle-constructor-exception-when-using-autofac-wcfintegration - this suggests that I return another type of object in case initialization of the original one fails, but I don't want that, I want it to throw an exception and fail.

## Additional Context

I think I've given you enough information, but if you have any question, please let me know. Thank you in advance!

**Comment by alistairjevans** [comment]
When this fails, you should get a `DependencyResolutionException` thrown by whatever top-level component is resolving the object graph (ASP.NET Core Request Pipeline perhaps?), with the InnerException captured.  Are you saying that your app is not able to capture that exception very easily?

Regardless, I understand the use-case, and this (extending Autofac at a point we hadn't yet allowed for) is one of those things that has historically been quite difficult. However, I have good news! 

In the upcoming v6 release of Autofac, we have made a lot of big changes, including introducing a Resolve Pipeline, into which you can insert your own custom middleware. If you're familiar with the ASP.NET Core middleware approach, it's the same sort of thing. You'll be able to implement your desired functionality this way; here's how it will look in v6:

```csharp
// Register your component as normal.
builder.Register(c =>
{
    TopicClient topicClient = new TopicClient(configuration.ConnectionString, configuration.EntityPath);
    return new MyObject(topicClient);
});

// Hook onto every registration
builder.ComponentRegistryBuilder.Registered += (sender, args) =>
{
    // The PipelineBuilding event fires just before the pipeline is built, and 
    // middleware can be added inside it.
    args.ComponentRegistration.PipelineBuilding += (sender, pipeline) =>
    {
        // Add middleware to the Activation phase (just before object activation).
        pipeline.Use(PipelinePhase.Activation, (ctxt, next) =>
        {
            try
            {
                // This will call the activator.
                next(ctxt);
            }
            catch (Exception ex)
            {
                // Custom exception handling in here.
                // ctxt.Service gives you the service being resolved
                // ctxt.Registration gives you the registration being activated

                // It's a good idea to re-throw.
                throw;
            }
        });
    };
};
```

v6 is expected to be released sometime in the next couple of months, but if you wanted to try it out sooner you can take a look at our pre-release packages on MyGet, all the changes are mostly stable now.

**Comment by StojanovicMilos** [comment]
Hi @alistairjevans, first of all, thank you for the quick and detailed reply!

Our app contains different types of projects (console, web api in different technologies etc.), so for some of them it is quite tricky to catch this exception and the idea was that we have universal solution which will work for all project types, rather than having to create different logic for each project type.

As for the second part of your answer, that is an amazing feature and we'd like to use it. We can't wait for Autofac v6.

Thanks again and good luck on v6.
