### ISSUE TITLE
Discussions + Question

### ISSUE THREAD

**Issue by TonyValenti** [autofac/Autofac#1199]
1.  Can you please enable GitHub discussions on this repo?
2.  Is there a way to use AutoFac to call non-constructor methods on an object?

For example:
````
public class Foo {

  public void Method(string p0, a p1, b p2, c p3){
    ...
  }

  public void Test(){
   //Something like this:
    AutoFac.Invoke(this, nameof(Method), "Hello World");
  }

}
```

**Comment by tillig** [comment]
I'm not sure if we want to enable discussions at this time. [We already have a Google Group for discussions](https://groups.google.com/g/autofac).

For usage and "How do I..." questions, we're really trying to get them directed to StackOverflow as noted in the issue template. Few people monitor the issues here; many, many more (including all of us) monitor StackOverflow.

Autofac is a DI framework, not a method invocation/reflection framework. It constructs objects, [it can do method injection on an object that Autofac constructed](https://autofaccn.readthedocs.io/en/latest/register/prop-method-injection.html#method-injection), but it isn't something you'd use as a way to invoke arbitrary methods.
