### ISSUE TITLE
Diagnostics: Add 'Succeeded' flag to OperationTraceCompletedArgs

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac#1201]
While putting together a blog post on the v6 release, it occurred to me that we do not have a way for Diagnostic Event handlers to know whether the Trace they are getting is for a successful resolve operation, or a failing one.

I can imagine users might want to save failing resolves to whatever output, to reduce the amount of trace they have to wade through when diagnosing errors in a bigger system.

I think we should add a boolean `OperationSucceeded` flag to `OperationTraceCompletedArgs`, which just indicates whether the operation failed or not. We already have this information available in the Diagnostic Tracer, so should be a trivial addition.

I'll raise a PR for the change, but thought I'd raise the issue first for discussion.

**Comment by tillig** [comment]
Good point. The way the tracers know is by intercepting the diagnostic event but that doesn't surface in the rendered trace content.
