### ISSUE TITLE
 [ConfigurePipeline] in 6.0 is not work same as [ActivatedHandlers] 

### ISSUE THREAD

**Issue by yuzd** [autofac/Autofac#1210]
```c#
registrar.RegistrationData.ActivatedHandlers.Add((s, e) => { DoAutoWired(e.Context, e.Parameters, e.Instance); });
```

```c#
 registrar.ConfigurePipeline(p => p.Use(PipelinePhase.Activation, MiddlewareInsertionMode.StartOfPhase, (ctxt, next) =>
{
       next(ctxt);
       DoAutoWired(ctxt, ctxt.Parameters, ctxt.Instance);
 }));
```
before 6.0  
i can do Circular component dependency detected in my function [DoAutoWired] by myself.
but update to 6.0
i can not do that?

how to excute my pipeline before
Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute

**Comment by alistairjevans** [comment]
If you have access to `registrar`, which I guess is an instance of `IRegistrationBuilder`, can you not use the `registrar.OnActivated` method to add an Activated event handler?  That will work the same way as it did before.

If you don't have acccess to that method for some reason, then the middleware you've specified here just needs a little tweak to behave like the OnActivated event:

```csharp
registrar.ConfigurePipeline(p => p.Use(PipelinePhase.Activation, MiddlewareInsertionMode.StartOfPhase, (ctxt, next) =>
{
    next(ctxt);

    // Make sure we capture the instance at this point, before it is replaced by any decorators.
    var newInstance = ctxt.Instance;

    // RequestCompleting event fires after the request has completed, and it's safe to do
    // circular references.
    ctxt.RequestCompleting += (sender, evArgs) =>
    {
        // Use the captured instance.
        DoAutoWired(ctxt, ctxt.Parameters, newInstance);
    };
 }));
```

**Comment by yuzd** [comment]
thanks
