### ISSUE TITLE
Configuring Multiple Mock Dependencies

### ISSUE THREAD

**Issue by dathway** [autofac/Autofac#1218]
I'm in the process of upgrading our Autofac library to the latest version. After the upgrade, I noticed all of our unit tests which were using some form of var mock = AutoMock.GetLoose(), no longer supported the "Provide" method.

After taking a look at the Getting Started docs (https://autofaccn.readthedocs.io/en/v5.2.0/integration/moq.html#getting-started) I've noticed there is a new way of registering mocks and dependent services. However, some of our tests require more than one Mock injected, and it's not clear to me how to do this. For example:

`[Test]
public void Test()
{
  var mockA = new Mock<IServiceA>();
  mockA.Setup(x => x.RunA());

  var mockB = new Mock<IServiceB>();
  mockB.Setup(x => x.RunB());

  // mockA is automatically registered as providing IServiceA
  using (var mock = AutoMock.GetLoose(cfg => cfg.RegisterMock(mockA)))
  {
    // mockA will be injected into TestComponent as IServiceA
    var component = mock.Create<TestComponent>();

    // ...and the rest of the test
  }
}`

How would I register both mockA and mockB?

Thanks.

**Comment by tillig** [comment]
Please ask usage questions on [StackOverflow](https://stackoverflow.com) and tag it `autofac`. If you do find an issue with the Moq integration, please fine it in that repo. This repo is for core Autofac issues only. Thanks!
