### ISSUE TITLE
Service resolved twice when combining 'RegisterAssemblyTypes' with 'RegisterInstance'

### ISSUE THREAD

**Issue by NKnusperer** [autofac/Autofac#1219]
## Describe the Bug

When combining `RegisterAssemblyTypes` and `RegisterInstance` for the same `IService`, `container.Resolve<IEnumerable<IService>>()` will yield two instances of `IService`, one using the `ReflectionActivator` and another one using `ProvidedInstanceActivator`.

## Steps to Reproduce

```c#
public class ReproTest
{
    [Fact]
    public void Repro()
    {
        var builder = new ContainerBuilder();

        builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
            .AssignableTo<IService>()
            .As<IService>();
        
        builder.RegisterInstance(new Service()).As<IService>();

        var container = builder.Build();
        var results = container.Resolve<IEnumerable<IService>>();
        Assert.Single(results);
    }
    
    public interface IService {}
    public class Service : IService {}
}
```

## Expected Behavior

Is this expected behavior?
The documentation for `Registration Concepts` states:

> If more than one component exposes the same service, Autofac will use the last registered component as the default provider of that service

https://autofaccn.readthedocs.io/en/latest/register/registration.html#default-registrations

So I would expect that `RegisterInstance` would override the `RegisterAssemblyTypes` registration and my newed instance would be resolved.

The use-case is that there are many `IService` implementations but only a few need to be newed so simply overwriting them from the assembly scanning was the goal.

If this is expected behavior what would be the solution to this problem without registering every concrete type manually? 

## Dependency Versions

Autofac: 6.0.0
NET Framework: 4.8

**Comment by tillig** [comment]
Functioning as designed.

You're resolving an `IEnumerable<IService>`. It's going to resolve _all_ the registrations. For example, you could do this:

```c#
builder.RegisterInstance(new Service()).As<IService>();
builder.RegisterInstance(new Service()).As<IService>();
builder.RegisterInstance(new Service()).As<IService>();
var container = builder.Build();

// results will have THREE THINGS IN IT
var results = container.Resolve<IEnumerable<IService>>();
```

What the docs are talking about is if you're resolving a _single thing_. The "default" for the single instance is "last in wins."

```c#
builder.RegisterInstance(new Service1()).As<IService>();
builder.RegisterInstance(new Service2()).As<IService>();
builder.RegisterInstance(new Service3()).As<IService>();
var container = builder.Build();

// results will be Service3 - last in wins!
var results = container.Resolve<IService>();
```

For Autofac, if you don't want the thing resolved, you shouldn't register it. That may mean that you need to do some assembly scanning and filtering up front yourself to determine which things should or shouldn't be registered; or add a `Where` clause to the `RegisterAssemblyTypes` to filter things out.

```c#
builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
        .AssignableTo<IService>()
        .Where(t => t.Name != "ThingIDoNotWant")
        .As<IService>();
```

I mean, obviously you could get really fancy with it and gather lists of things you do and don't want and use LINQ in there to get it all the way you need, but that's the idea.

You can also potentially use `PreserveDefaults` to your advantage.

```c#
builder.RegisterInstance(new Service1()).As<IService>();
builder.RegisterInstance(new Service2()).As<IService>().PreserveDefaults();
builder.RegisterInstance(new Service3()).As<IService>().PreserveDefaults();
var container = builder.Build();

// results will be Service1 - PreserveDefaults means don't override
var results = container.Resolve<IService>();
```

Combining these concepts could get you what you want, but out of the box the way you're trying to do this isn't how Autofac works. Sorry.

**Comment by NKnusperer** [comment]
Thank you for the quick response 🙂
