### ISSUE TITLE
How to dynamically register after startup

### ISSUE THREAD

**Issue by qcjxberin** [autofac/Autofac#1222]
I use Roslyn to dynamically inject a controller, and now an error is not register

![image](https://user-images.githubusercontent.com/5792218/97157613-450d0c80-17b3-11eb-8502-b4be18714bb1.png)

**Comment by tillig** [comment]
If you have found a bug in Autofac, we need enough to reproduce the issue so we can troubleshoot it. If you want to know how to do something, please ask [on StackOverflow](https://stackoverflow.com) and tag it `autofac`. If you're doing custom Roslyn work, that's not Autofac so StackOverflow is your best bet.
