### ISSUE TITLE
Investigation: Possible problems using indexOf with NET 5

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1224]
I came across [this](https://github.com/dotnet/runtime/issues/43736) issue stating that globalization on Windows has been switched from NLS to ICU and was wondering if we might be affected by that. Since we are building on Linux and Linux already used ICU before and we've got quite a good amount of use cases covered, I doubt that we are affected by that but I still think it's worth double checking.

**Comment by alistairjevans** [comment]
I also saw that issue; I think the fact we already have the CA1304 analyzer rule applied means that all our methods which work with strings take a `CultureInfo` block. 

In addition, we don't actually use IndexOf anywhere in the codebase, and generally we strive to avoid using strings in a way that might be culture-impacted.

**Comment by alsami** [comment]
Okay, closing this then.
