### ISSUE TITLE
TypeLoadException for open generics implementing derived interface

### ISSUE THREAD

**Issue by InspiringCode** [autofac/Autofac#1237]
## Description

Given the following constellation:
```
        public interface IBase<T> { }

        public interface ISub<T> : IBase<Task<T>> where T : TestObject { }
```
Given that
1. interface `ISub<T>` inherits from `IBase<Task<T>>`, i.e. the generic parameter is passed to the base interface in a different form (encapsulated in a `Task<T>` object in this example).
2. interface `ISub<T>` specifies a constraint on T: `ISub<T> : IBase<Task<T>> where T : TestObject { }`

When resolving the base interface `IBase<Task<TestObject>>`, a `TypeLoadException` (see below) is thrown.

It seems that the `T` of the `IBase<T>` (which is `Task<TestObject>` in the example) is mistakenly used for a `MakeGenericType` call for `ISub<T>` (whose `T` is `TestObject` and NOT `Task<TestObject>`). I don't know why a `ISub<T>` is even constructed in this example, since I am only resolving a `IBase<T>`.

## Complete example as a failing xUnit test
More advanced scenarios and tests can be found in the attached xUnit project: [AutofacOpenGenericBug.zip](https://github.com/autofac/Autofac/files/5655120/AutofacOpenGenericBug.zip)

```c#
using Autofac;
using System.Threading.Tasks;
using Xunit;

namespace AutofacOpenGenericBug {
    public class MinimalScenario {
        [Fact]
        public void TypeLoadException() {
            ContainerBuilder cb = new ContainerBuilder();
            cb.RegisterGeneric(typeof(Implementation<>)).AsImplementedInterfaces();
            IContainer c = cb.Build();

            var instance = c.Resolve<IBase<Task<TestObject>>>();
            Assert.IsType<Implementation<TestObject>>(instance);
        }

        public interface IBase<T> { }

        public interface ISub<T> : IBase<Task<T>> where T : TestObject { }

        public class Implementation<T> : ISub<T> where T: TestObject { }

        public class TestObject { }
    }
}
```

## Exception with Stack Trace
```text
System.ArgumentException : GenericArguments[0], 'AutofacOpenGenericBug.AdvancedTests+TestMessage`1[System.String]', on 'AutofacOpenGenericBug.AdvancedTests+IHandlesAsync`2[M,V]' violates the constraint of type 'M'.
    ---- System.TypeLoadException : GenericArguments[0], 'AutofacOpenGenericBug.AdvancedTests+TestMessage`1[System.String]', on 'AutofacOpenGenericBug.AdvancedTests+IHandles`2[M,R]' violates the constraint of type parameter 'M'.
  Stack Trace: 
    RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
    RuntimeType.MakeGenericType(Type[] instantiation)
    <>c__DisplayClass2_0.<TryBindOpenGenericTypedService>b__3(IServiceWithType s)
    WhereSelectEnumerableIterator`2.MoveNext()
    WhereSelectEnumerableIterator`2.ToArray()
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    OpenGenericServiceBinder.TryBindOpenGenericTypedService(IServiceWithType serviceWithType, IEnumerable`1 configuredOpenGenericServices, Type openGenericImplementationType, Type& constructedImplementationType, Service[]& constructedServices)
    OpenGenericServiceBinder.TryBindOpenGenericService(Service closedService, IEnumerable`1 configuredOpenGenericServices, Type openGenericImplementationType, Type& constructedImplementationType, Service[]& constructedServices)
    OpenGenericRegistrationSource.RegistrationsFor(Service service, Func`2 registrationAccessor)+MoveNext()
    DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
    DefaultRegisteredServicesTracker.TryGetServiceRegistration(Service service, ServiceRegistration& serviceData)
    ComponentRegistry.TryGetServiceRegistration(Service service, ServiceRegistration& serviceRegistration)
    ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
    ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
    ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
    ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
    ResolutionExtensions.Resolve[TService](IComponentContext context)
```

Autofac version : 6.1.0

## Additional Info
The example above is an extremely simplified scenario of a real world in-process messaging system (being open sourced soon), which is part of our core infrastructure at our company. I have attached a simple project with a few more advanced scenarios (xUnit tests), to test a possible bugfix against. I hope this bug will be fixed, since all the open generic and constraint stuff is quite vital for us.

**Comment by tillig** [comment]
> I hope this bug will be fixed, since all the open generic and constraint stuff is quite vital for us.

The quickest way to get your bug fixed is to submit a PR with the fix. Much as we'd like to just jump on every issue, no one on this project gets paid or does it for a living. If it's urgent, send us a PR.

**Comment by alistairjevans** [comment]
Taken a brief look at this this morning to try and scope it out; a couple of points:

- The reason you get an error related to `ISub<T>` when resolving `IBase<T>` is because the `OpenGenericServiceBinder` will make concrete versions of all interfaces implemented by `Implementation<T>` when we first create a concrete version of `Implementation<T>`.  `AsAllImplementedInterfaces` includes inherited interfaces, hence both `ISub` and `IBase` are considered.
Changing your registration to the following makes this work:

  ```csharp
  cb.RegisterGeneric(typeof(Implementation<>)).As(typeof(IBase<>));
  ```

- I believe for this to work automatically, we would need to, for each service on a generic component, compare the provided concrete type argument against a service's type inheritance hierarchy (including multiple inheritance potentially!!) to 'extract' the type that we should use to generate the concrete service type. I'm fairly sure this will get messy.

- One option that might work without needing any Autofac changes is using our new open generic delegate behaviour in v6 to customise resolving `IBase<T>`, checking for a `Task<T>` and then resolving `ISub<>` instead having extracted the inner argument. The below code resolves everything as expected (I believe).  This sort of advanced generic behaviour is kind of why we created the generic delegate feature in the first place.

  ```csharp
    [Fact]
    public void TypeLoadException()
    {
        ContainerBuilder cb = new ContainerBuilder();
        cb.RegisterGeneric(typeof(Implementation<>)).As(typeof(ISub<>));
        cb.RegisterGeneric((ctxt, genericArgs) =>
        {
            // Look at the first generic argument for a Task<T>.
            if (genericArgs[0].GetGenericTypeDefinition() == typeof(Task<>))
            {
                // Extract the base and use it to resolve ISub<>.
                var actualSubArg = genericArgs[0].GetGenericArguments()[0];
             
               // You may want to cache this outputted type to reduce reflection costs
               // on subsequent resolves.
                var subType = typeof(ISub<>).MakeGenericType(actualSubArg);

                return ctxt.Resolve(subType);
            }

            throw new InvalidOperationException("Resolve of IBase must include Task specifier.");
        }).As(typeof(IBase<>));

        IContainer c = cb.Build();

        var instance = c.Resolve<IBase<Task<TestObject>>>();
        var subInstance = c.Resolve<ISub<TestObject>>();
        Assert.IsType<Implementation<TestObject>>(instance);
        Assert.IsType<Implementation<TestObject>>(instance);
    }

**Comment by alistairjevans** [comment]
@tillig, I'm going to vote for closing this issue. We've provided a clear way to resolve the specific scenario by using our Open Generic delegate feature, and implementing generic support for this scenario in a general way that covers every possible case would be very messy.

**Comment by tillig** [comment]
I'm fine calling this a "won't fix." If a PR comes in for it, we can revisit at that time.
