### ISSUE TITLE
Avoid accidentally getting static and public constructors

### ISSUE THREAD

**Issue by maliming** [autofac/Autofac#1238]
Autofac use `DeclaredOnlyPublicFlag` to get the type constructors, But it may get a static & public constructor. However, `Expression.New` does not support static constructors.

https://github.com/autofac/Autofac/blob/e662b6bace37a569eec1e42335336b3fe015855c/src/Autofac/TypeExtensions.cs#L19-L20
https://github.com/autofac/Autofac/blob/e662b6bace37a569eec1e42335336b3fe015855c/src/Autofac/Core/Activators/Reflection/ConstructorBinder.cs#L148

#### Why does this happen?
If I use `Castle.DynamicProxy` to create a proxy class in `Blazor webassembly app` there will be a public and static constructor in an instance.

I think the problem is not Autofac but Castle. But maybe we can move `BindingFlags.Static` from `DeclaredOnlyPublicFlags` to `DeclaredOnlyFlags`:

```cs
private const BindingFlags DeclaredOnlyPublicFlags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly;
private const BindingFlags DeclaredOnlyFlags = DeclaredOnlyPublicFlags | BindingFlags.Static | BindingFlags.NonPublic;
```

```cs
@page "/index"
@using Castle.DynamicProxy
@using System.Reflection

<h1>Hello Blazor</h1>

@code {
    public class MyClass
    {

    }

    protected override async Task OnInitializedAsync()
    {
        var proxyGenerator = new ProxyGenerator();

        foreach (var constructorInfo in proxyGenerator.CreateClassProxyWithTarget(new MyClass())
            .GetType()
            .GetConstructors(BindingFlags.Public | BindingFlags.Static | BindingFlags.Instance | BindingFlags.DeclaredOnly))
        {
            if (constructorInfo.IsPublic && constructorInfo.IsStatic)
            {
                // Will output!
                Console.WriteLine("constructor is public and static");
            }
        }

        await Task.CompletedTask;
    }
}

```

**Comment by tillig** [comment]
I'm not really sure what the issue _with Autofac_ is that you're trying to convey. Is there something in a failing unit test or _very simple, trimmed-down-to-only-the-repro_ project that you could show us? We aren't Blazor and we aren't Castle, so I'm not sure what the use case is that isn't working. If you can repro it _without_ DynamicProxy then maybe you've got something; if it requires that you throw DynamicProxy in the mix, you might be talking to the wrong folks.

I've got plenty of classes in various projects using Autofac that have both public instance and static constructors and I haven't run into any problems.

**Comment by maliming** [comment]
> If you can repro it without DynamicProxy then maybe you've got something; 

I will do that. :)

**Comment by maliming** [comment]
hi @tillig 

If I remove the `MethodAttributes.Public` of `ctor2` it will work.

```cs
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="6.1.0" />
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
        <PackageReference Include="System.Reflection.Emit.ILGeneration" Version="4.7.0" />
    </ItemGroup>

</Project>
```

```cs
using System;
using System.Reflection;
using System.Reflection.Emit;
using Autofac;

namespace ConsoleApp
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            /*
            public class MyDynamicType
            {
                public  static MyDynamicType()
                {

                }

                public MyDynamicType()
                {

                }
            }
             */
            var ab = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(Guid.NewGuid().ToString()), AssemblyBuilderAccess.Run);
            var mb = ab.DefineDynamicModule("test.dll");
            var tb = mb.DefineType("MyDynamicType", TypeAttributes.Public);

            var ctor1 = tb.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, Type.EmptyTypes);
            var ctorIl = ctor1.GetILGenerator();

            // Default class constructor
            ctorIl.Emit(OpCodes.Ldarg_0);
            ctorIl.Emit(OpCodes.Call, typeof(object).GetConstructor(Type.EmptyTypes));
            ctorIl.Emit(OpCodes.Ret);

            // Static&Public class constructor
            var ctor2 = tb.DefineConstructor(MethodAttributes.Static | MethodAttributes.Public, CallingConventions.Standard, Type.EmptyTypes);
            var ctor2Il = ctor2.GetILGenerator();
            ctor2Il.Emit(OpCodes.Ret);
            
            var myDynamicType = tb.CreateType();

            
            var builder = new ContainerBuilder();
            builder.RegisterType(myDynamicType).As(myDynamicType);

            var container = builder.Build();

            container.Resolve(myDynamicType);

            Console.WriteLine("Hello World!");
        }
    }
}

```


```cs
Unhandled exception. System.ArgumentException: The constructor should not be static (Parameter 'constructor')
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Autofac.Core.Activators.Reflection.ConstructorBinder.GetConstructorInvoker(ConstructorInfo constructorInfo)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Autofac.Core.Activators.Reflection.ConstructorBinder..ctor(ConstructorInfo constructorInfo)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ConfigurePipeline(IComponentRegistryServices componentRegistryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices)
   at Autofac.Core.Registration.ComponentRegistryBuilder.Build()
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at ConsoleApp.Program.Main(String[] args) in Program.cs:line 34
```

**Comment by tillig** [comment]
So, to be clear, in order to reproduce this, you manually have to emit IL and can't use a standard code compilation process?

**Comment by tillig** [comment]
I ask because, at least in C#, [static constructors don't have access modifiers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors) so I'm curious if you're emitting some invalid IL.

**Comment by maliming** [comment]
Maybe `DeclaredOnlyPublicFlags` should not contain `BindingFlags.Static`. 

https://github.com/autofac/Autofac/blob/e662b6bace37a569eec1e42335336b3fe015855c/src/Autofac/TypeExtensions.cs#L19

https://github.com/autofac/Autofac/blob/e662b6bace37a569eec1e42335336b3fe015855c/src/Autofac/TypeExtensions.cs#L171-L179

**Comment by maliming** [comment]
> So, to be clear, in order to reproduce this, you manually have to emit IL and can't use a standard code compilation process?

`Castle DynamicProxy` might do something like this.

**Comment by tillig** [comment]
I'll buy that we probably shouldn't be picking up static constructors. However, we can't just change that one value [because it's used to find methods, too](https://github.com/autofac/Autofac/blob/180de40d30da1950f7461a485b24eea89c994567/src/Autofac/TypeExtensions.cs#L126) and finding static methods _is_ interesting. Probably need to have a different flag set for methods vs. constructors.

Seems like an easy enough fix.
