### ISSUE TITLE
Upgrade to stable coverlet 3.x packages

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1241]
Because of the fix required for the coverage to be collected correctly in #1240, we have added pre-releases of  `coverlet.collector` and `coverlet.msbuild`. They may be updated to the stable version once they are released on nuget.org.

The additional nightly-nuget feed from coverlet may also be removed then from the `NuGet.config`.

**Comment by alsami** [comment]
Closing this since it has been merged in January already :)

**Comment by alistairjevans** [comment]
@alsami, didn't we leave the issue open because we saw a big drop in the coverage numbers after merge?

I seem to recall we discussed it in the PR after it was merged?

**Comment by alsami** [comment]
> @alsami, didn't we leave the issue open because we saw a big drop in the coverage numbers after merge?
> 
> I seem to recall we discussed it in the PR after it was merged?

Just double checked. The PR caused a huge drop but it was fixed with a package update that we already got. Currently we are at 77 percent. Almost around the number we had also during the time before the PR.

**Comment by alistairjevans** [comment]
Ok, great, thanks. 👍
