### ISSUE TITLE
ContainerBuilderExtensions.cs(25, 64): [CS3001] Argument type 'ContainerBuilder' is not CLS-compliant

### ISSUE THREAD

**Issue by kendallb** [autofac/Autofac#1255]
## Describe the Bug

When I attempt to upgrade Rebus.Autofac from 5.x to 6.x, I get this error. Gonna leave the package back leveled for the moment but not sure why this is happening? From what I can tell it means something in the Autofac API for ContainerBuilder is not CLS compliant so it fails to compile. Can we get this fixed?

https://github.com/rebus-org/Rebus.Autofac

## Steps to Reproduce

Clone the repo, upgrade to latest Autofac package and compile. In debug mode you get warnings, it release mode you get build failures.

## Expected Behavior

No errors :)

## Dependency Versions

Autofac: 6.0.0 and later

**Comment by tillig** [comment]
Unfortunately, not being CLS compliant [is one of our documented breaking changes for v6.0.0](https://github.com/autofac/Autofac/releases/tag/v6.0.0):

> Autofac is no longer marked CLS compliant. The Microsoft `DiagnosticSource` and related entities we (and ASP.NET Core, and others) use for diagnostics is not CLS compliant so Autofac can't be, either.

So... sorry, not really going to be able to fix it. :( If you can get the MS folks to mark `DiagnosticSource` as CLS compliant we might be back in the game.

**Comment by alistairjevans** [comment]
As of v6.0, Autofac is no longer CLS compliant, since we are using `DiagnosticSource` for the new resolve tracing functionality.

See https://github.com/autofac/Autofac/issues/1245

**Comment by kendallb** [comment]
Ahh, thanks. I guess the fix might be to also make Rebus.Autofac not CLS compliant. Or leave it at the older level and those who consume it can use the later version knowing it's not CLS compliant.
