### ISSUE TITLE
Provide new configuration and usage samples for .NET 5

### ISSUE THREAD

**Issue by OculiViridi** [autofac/Autofac#1262]
I'm starting a new test project using **.NET 5** and some new technologies and libraries (**Autofac** is one of them).

As my company adopts Autofac as the standard IoC Container, but I've never used it, I wanted to know if the Autofac configuration within a **.NET 5 Web API** project can be different from that of a .NET Core 3.0/3.1 project.

So I'm asking if it is possible and if it could be useful, to add some new examples of code for Autofac configuration and usage on .NET 5.
For now I followed the documentation and used the .NET Core 3.0+ guidelines.

**Comment by tillig** [comment]
The usage between .NET Core 3.x and .NET 5 isn't any different. Just swap the .NET Core dependency versions.

If you have some specific points in the docs you'd like updated or think are unclear, [please file those things in the Documentation repo](https://github.com/autofac/Documentation). If the examples are wrong or unclear, [please file those things in the Examples repo](https://github.com/autofac/Examples).

For basic usage questions, [please use StackOverflow and tag your question with `autofac` along with any other tags.](https://stackoverflow.com/tags/autofac)
