### ISSUE TITLE
MediatR: Decorators for IRequestHandler <TRequest> (without result) are not invoked - Autofac 6.1.0

### ISSUE THREAD

**Issue by ghuarcayam** [autofac/Autofac#1273]
## Describe the Bug

I have checked this issue https://github.com/autofac/Autofac/issues/1098#issuecomment-606455207. In that issue it explains how to configure decorators for IRequestHandler <TRequest, TResult> (With return value), I have tried it and it has worked for me, however, my problem is when I want to configure generic decorators for IRequestHandler <TRequest> (Without return value), the LoggingDecorator <TRequest> and DiagnosticDecorator <TRequest> decorators are never executed

## Steps to Reproduce

```c#
class Program
    {
        static IContainer container;


        static async Task Main(string[] args)
        {

            Setup();


            using (var scope = container.BeginLifetimeScope())
            {
                var mediatr = scope.Resolve<IMediator>();
                await mediatr.Send(new CreatePersonCommand() { x = 1, y = 2 });
            }
        }


        public static void Setup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new MediatRModule(new Assembly[] { (typeof(Program).Assembly) }));
            builder.RegisterGenericDecorator(typeof(DiagnosticDecorator<>), typeof(IRequestHandler<>), context => !context.AppliedDecorators.Any());
            builder.RegisterGenericDecorator(typeof(LoggingDecorator<>), typeof(IRequestHandler<>), context => !context.AppliedDecorators.Any());
            container = builder.Build();
        }
    }


    public class LoggingDecorator<TCommand> : IRequestHandler<TCommand>
       where TCommand : IRequest
    {

        private readonly IRequestHandler<TCommand> commandHandler;

        public LoggingDecorator(IRequestHandler<TCommand> commandHandler)
        {
            this.commandHandler = commandHandler;
        }
        public async Task<Unit> Handle(TCommand request, CancellationToken cancellationToken)
        {
            Console.WriteLine("executing...");
            return await this.commandHandler.Handle(request, cancellationToken);
        }
    }

    public class DiagnosticDecorator<TCommand> : IRequestHandler<TCommand>
        where TCommand : IRequest
    {

        private readonly IRequestHandler<TCommand> commandHandler;

        public DiagnosticDecorator(IRequestHandler<TCommand> commandHandler)
        {
            this.commandHandler = commandHandler;
        }
        public async Task<Unit> Handle(TCommand request, CancellationToken cancellationToken)
        {

            var r = await commandHandler.Handle(request, cancellationToken);

            return r;
        }
    }


    public class CreatePersonCommand : IRequest
    {
        public int x { get; set; }

        public int y { get; set; }
    }

    public class CreatePersonCommandHandler : IRequestHandler<CreatePersonCommand>
    {
        public async Task<Unit> Handle(CreatePersonCommand request, CancellationToken cancellationToken)
        {
            return Unit.Value;
        }
    }
```
Configuration module for MediatR
```c#
internal class MediatRModule : Autofac.Module
    {
        private readonly Assembly[] assemblies;

        public MediatRModule(Assembly[] assemblies)
        {
            this.assemblies = assemblies;
        }

        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(typeof(IMediator).GetTypeInfo().Assembly)
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope();


            var openHandlerTypes = new[]
            {
                typeof(IRequestHandler<,>),
                typeof(IRequestExceptionHandler<,,>),
                typeof(IRequestExceptionAction<,>),
                typeof(INotificationHandler<>),
            };
            
            foreach (var openHandlerType in openHandlerTypes)
            {
                builder.RegisterAssemblyTypes(this.assemblies)
                    .AsClosedTypesOf(openHandlerType)
                    .AsImplementedInterfaces();
            }

            builder.RegisterGeneric(typeof(RequestPostProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));
            builder.RegisterGeneric(typeof(RequestPreProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));

            builder.RegisterGeneric(typeof(RequestExceptionActionProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));
            builder.RegisterGeneric(typeof(RequestExceptionProcessorBehavior<,>)).As(typeof(IPipelineBehavior<,>));

            

            builder.Register<ServiceFactory>(outerContext =>
            {
                var innerContext = outerContext.Resolve<IComponentContext>();

                return serviceType => innerContext.Resolve(serviceType);
            }).InstancePerLifetimeScope();
        }
    }
```

## Exception with Stack Trace

Decorators are never invoked

## Dependency Versions
TargetFramework:  net5.0
Autofac: 6.1.0
MediatR: 9.0.0

**Comment by tillig** [comment]
I don't know about the rest of the owners here, but I'm not a MediatR user and don't really have the time to become one at the moment. It seems like there's a lot here - two different decorators, a command, some other stuff... Any way to trim this down at all? I get that you want two different decorators to work, but if you remove one... does the other start working? If not, the second decorator is _interesting_ but not _relevant_ and can be removed from the repro. What else can be removed? Does `Setup` need to be a separate method or could the repro be smaller and easier to follow if it was inlined?

Truly sorry to be that guy, just... Given the limited time we have, any help you can provide up front to make it as easy as possible to see what's going on will help.

Also: have you tried the [new diagnostics support](https://autofaccn.readthedocs.io/en/latest/advanced/debugging.html#diagnostics)? It'd be interesting to see if things are getting resolved the way you expect and might shed some light into the issue.

**Comment by alistairjevans** [comment]
I'm not certain @ghuarcayam (could be some other MediatR stuff going on I don't know about), but I notice that you register decorators for `IRequestHandler​<>`, but then do assembly scanning for `IRequestHandler​<,>`, which is an entirely different service from Autofac's perspective. 

Do you just need to change the interface you're decorating?

**Comment by alsami** [comment]
Just jumping in here since I am using `MediatR` a lot. You shouldn't write a decorator for stuff like logging the requests.
`MediatR` has a built-in functionality for that by implementing and registering types with the interface `IPipelineBehaviors<TRequest, TResponse>`. You can find samples in [the official repository](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples/GenericPipelineBehavior.cs#L18). Those behaviors can just be registered like a generic, a sample for that can be found [here as well](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.Autofac/Program.cs#L55).

What you are doing now will cause `MediatR` to invoke all handlers matching the signature (Request, Response), the real one and the one that just does logging, since it relies on assembly-scanning to register and resolve handlers as can be seen in the code you have provided:

```csharp
builder.Register<ServiceFactory>(outerContext =>
{
    var innerContext = outerContext.Resolve<IComponentContext>();
    return serviceType => innerContext.Resolve(serviceType);
}).InstancePerLifetimeScope();
```

**Comment by ghuarcayam** [comment]
@tillig @alistairjevans @alsami 

Thanks for your time and help, it has helped me a lot to solve my issue

mainly, when MediatR sends a type to be resolved with Autofac, the Type value is IRequestHandler <Command, Unit>, contained within the serviceType parameter

```c#
builder.Register<ServiceFactory>(outerContext =>
{
    var innerContext = outerContext.Resolve<IComponentContext>();
    return serviceType => innerContext.Resolve(serviceType);
}).InstancePerLifetimeScope();
```
I have finally solved it, modifying these lines of code

```c#
  builder.RegisterGenericDecorator(typeof(DiagnosticDecorator<>), typeof(IRequestHandler<>));
  builder.RegisterGenericDecorator(typeof(LoggingDecorator<>), typeof(IRequestHandler<,>));
```
Thank you

**Comment by LeftTwixWand** [comment]
Hey, I have pretty similar problem. I've segregated IRequest into ICommand and IQuery.
So I have ICommandHandler and IQueryHandler, that implements IRequestHandler.

How can I specify decorators, that relates to ICommandHandler and IQueryHandler?

**Comment by LeftTwixWand** [comment]
Ok, I've solved it

**Comment by LeftTwixWand** [comment]
I've created a sample app to demonstrate Requests processing in the latest Autofac & MediatR versions:
[github.com/LeftTwixWand/ModernCQRS](https://github.com/LeftTwixWand/ModernCQRS)

The sample output:
![CQRS](https://user-images.githubusercontent.com/50652041/151836701-8a6a60c0-acad-4da2-8462-a9589d2f4207.png)
