### ISSUE TITLE
Dependency Injection support for Azure Functions V3 (IFunctionsHostBuilder) 

### ISSUE THREAD

**Issue by ssunkari** [autofac/Autofac#1279]
**Is your feature request related to a problem? Please describe.**
I am struggling to find a way to integrate Autofac with Azure functions V3. There is no mention in the Microsoft docs about any 3rd party DI integration. I would like to use autofac multitenant and Keyed Resolution features in Azure functions, the default DI lacks supports for this.  
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

**Describe the solution you'd like**
Would love to see any development towards building an extension for Azure Functions that work with default DI just like it does today with web apps that implement IHost.

**Describe alternatives you've considered**
I have looked into third-party integrations using attribute bindings but is very immature and lots of custom code

Found below on Azure-functions Official Github repo too
https://github.com/Azure/azure-functions-host/issues/4429

**Comment by tillig** [comment]
Duplicate https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/90
