### ISSUE TITLE
DLL-Dependency conflict with version mismatch of System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by Yeah69** [autofac/Autofac#1293]
## Describe the Bug

In a private multi-project .Net solution that I am working on, I run into a `FileLoadException` when I use `Autofac` in one project and `IdentityModel.OidcClient` in another over nuget. 

## Steps to Reproduce

Unfortunately, I couldn't reproduce it with a dummy solution. I've tried to find out why it works in the simpler dummy solution and not in the solution at hand, but I had no luck so far.

## Expected Behavior

Autofac runs without this exception.

## Exception with Stack Trace

```
System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Autofac.Core.Lifetime.LifetimeScope..ctor(IComponentRegistry componentRegistry, Object tag)
   at Autofac.Core.Lifetime.LifetimeScope..ctor(IComponentRegistry componentRegistry)
   at Autofac.Core.Container..ctor(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at [blackened].DI.AutofacModule.BuildContainer(ISettings propertiesSettings, IProgram program, ILogTimestamps logTimestamps, IDisposeOnAppExit disposeOnAppExit)
   at [blackened].DI.ContainerAdapter..ctor(ISettings propertiesSettings, IProgram program)
   at [blackened].Program.RunAsFirstInstance() in C:\Users\[blackened]\Documents\git\[blackened]\[blackened]\[blackened]\Program.cs:line 46
   at [blackened].Program.Run() in C:\Users\[blackened]\Documents\git\[blackened]\[blackened]\[blackened]\Program.cs:line 37
   at [blackened].Program.Main(String[] args) in C:\Users\[blackened]\Documents\git\[blackened]\[blackened]\[blackened]\Program.cs:line 83

=== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Users/[blackened]/Documents/git/[blackened]/[blackened]/[blackened]/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Autofac, Version=6.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\[blackened]\Documents\git\[blackened]\[blackened]\[blackened]\bin\Debug\[blackened].exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Attempting download of new URL file:///C:/Users/[blackened]/Documents/git/[blackened]/d[blackened]/[blackened]/bin/Debug/System.Diagnostics.DiagnosticSource.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

## Dependency Versions

`Autofac`: `6.1.0`
`IdentityModel.OidcClient`: `4.0.0`

## Additional Info

I've checked out `Autofac` locally, set the nuget dependency of `System.Diagnostics.DiagnosticSource` to version `5.0.1`, compiled and used `Autofac` as .dll directly at the solution at hand. It worked without the exception being thrown.

So if it isn't a problem to upgrade the `System.Diagnostics.DiagnosticSource` dependency. It would fix the issue.

Otherwise, I have further additional info.

`IdentityModel.OidcClient` depends on `Microsoft.Extensions.Logging` >= `5.0`
![image](https://user-images.githubusercontent.com/11756150/140285353-c975db0d-bd59-4269-b6fb-2aa95052ada5.png)

Which on the other hand depends on `System.Diagnostics.DiagnosticSource` >= `5.0`
![image](https://user-images.githubusercontent.com/11756150/140298990-b09f5a6e-9867-49cc-8feb-3c7c002f9482.png)

Contrary, `Autofac` depends on `System.Diagnostics.DiagnosticSource` >= `4.7.1` (its still the same situation with `Autofac` `6.3.0`)
![image](https://user-images.githubusercontent.com/11756150/140299383-a4fff88e-5dd3-471b-94ab-ff97df257aed.png)

If I build the root project of the solution following version of `System.Diagnostics.DiagnosticSource` is picked
![image](https://user-images.githubusercontent.com/11756150/140299671-76da8de0-36cd-43bc-bd4d-9610bfaa9a96.png)

On paper for nuget its a valid choice, because `5.0` == `5.0` and `5.0` >= `4.7.1`. However, technically the runtime seems to require at least the major versions to match exactly.

**Comment by alsami** [comment]
That looks like a problem of the legacy .NET framework. You need to update your bindig redirects as described [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by Yeah69** [comment]
Thank you, @alsami. Your tip helped.
