### ISSUE TITLE
Property injection for all classes

### ISSUE THREAD

**Issue by ransht** [autofac/Autofac#1312]
## Problem Statement

Im migration from Lamar to autofac
in lamar we used this: Policies.SetAllProperties(c => c.OfType<IMessageMapperFactory>())
this injects property to all classes that use this propery

## Desired Solution
My desired solution is a proper and easy way to make it easy.

## Alternatives You've Considered
I tried propertiesAutowired() to each class but its not the ideal way

## Additional Context
Hope we find solution soon so I can finish the migration
thanks.

**Comment by tillig** [comment]
What I _think_ you're asking for is something like what we show in the documentation [for log4net integration](https://autofac.readthedocs.io/en/latest/examples/log4net.html) - you'd adapt that to inject the property types you want.

If that's not what you're asking for, please clarify the question. We aren't Lamar users.

Be aware property injection has a performance cost so by doing this you're adding overhead to every resolve, whether it has the property type or not.

**Comment by tillig** [comment]
Since we haven't gotten any feedback on this issue, I'm going to close it. If there's something else we need to do, we can always reopen.
