### ISSUE TITLE
Autofac.6.3.0.nupkg is not AuthentiCode signed

### ISSUE THREAD

**Issue by Lang-Cheng** [autofac/Autofac#1314]
In our company we can only consume nugets from internal feed. And we cannot publish autofac.6.3.0.nupkg because it is not AuthentiCode signed.
Would it be possible to start AuthentiCode-signing Autofac?

Thanks!

Your package autofac.6.3.0.nupkg failed to publish to the feed.
Request date: 3/14/2022 9:56:02 AM

Package information:
Package:   autofac.6.3.0.nupkg
Class:   External
Source:   https://www.nuget.org/packages/Autofac/6.3.0
Registration:   Mocked registration for passing NugetValidator. Currently registration info is not needed in CG.

Failure log:
ERROR: File not AuthentiCode signed: Autofac.dll
ERROR: File not AuthentiCode signed: Autofac.dll
ERROR: File not AuthentiCode signed: Autofac.dll

**Comment by alistairjevans** [comment]
Authenticode signing puts a significant burden on us as maintainers, both financial and time, for relatively limited benefit considering the general adoption of Authenticode package signing in the .NET OSS package ecosystem, so we are not likely to add Authenticode signing.

If you're running in the hardened environment you describe, my best suggestion would be to download our .nupkg file directly from our releases page, and then sign the package yourself using your own organisation's signing certificate before uploading to your internal repository.
