### ISSUE TITLE
Expose LifeTimeScope.IsDiposed property

### ISSUE THREAD

**Issue by TrabacchinLuigi** [autofac/Autofac#1319]
## Problem Statement

When a scope is disposed the tracked disposable instances aren't disposed instantly, so if for some reason (a timer or an event handler) one of those instances that haven't already been disposed try to use another dependency that have been already disposed or try to resolve something an object disposed exception is thrown

## Desired Solution

Expose LifeTimeScope.IsDiposed property, so such a class could just resolve the parent LifetimeScope and check whether to try to execute or not that.

## Alternatives You've Considered

Since I'm not sure if IsDisposed is set at the end of the Dipsose() method or not, expose An IsDisposing Property too

**Comment by alistairjevans** [comment]
I am a little confused by your problem statement...all tracked instances of a lifetime scope complete disposal before the `Dispose` call to the scope completes.  

Are you dealing with child scopes here? Autofac doesn't dispose of all child scopes when the parent scope is disposed.

**Comment by TrabacchinLuigi** [comment]
Same scope, let's say we have two class a and b, and for some reason class a gets disposed first and takes 5 seconds to dispose, class b have a timer that runs every 1 second and depends on class a.


Now that you said the scope gets disposed after disposing tracked instances exposing the disposed property won't make any difference anyway... 

It's better that we have a third coordinator class having let's say a cancellation token or whatever...
