### ISSUE TITLE
Container built time performance has worsened since 4.8.x

### ISSUE THREAD

**Issue by Alexandr-Gurinovich** [autofac/Autofac#1329]
## Problem Statement

We have a big project and do a lot of registrations in a container. After an update of Autofac from 4.8.1 to 6.2 we notice almost 2x increase of time spent for registrations (around 4000 registrations in our case).  It is quite sensitive as our application can run on slow mobile devices. For example on slow android device the time grew from 3 seconds to 7 seconds.

## Desired Solution

It would be great if we could improve the performance of Container built with lots of registrations. 

Proposed solution:
1. detect changes that impacted Container built time
2. detect the root cause of performance degradation
3. try resolve performance issues

**Comment by tillig** [comment]
Given this has been open for several months with no profiler input or suggestions on improvement, I'm going to close this. Container build time only happens once per application and isn't as important for the [small] team to focus on as application execution time performance - resolution of services. If folks want container build time improvements, please open a **new issue** and include some concrete ideas, like a repro with some profiler data.
