### ISSUE TITLE
Delegate factory wraps exceptions from constructor in DependencyResolutionException

### ISSUE THREAD

**Issue by siimnelis** [autofac/Autofac#1344]
## Problem Statement

Let's say Shareholding from this example https://autofac.readthedocs.io/en/latest/advanced/delegate-factories.html

It's constructor looks something more like this.

  public Shareholding(string symbol, uint holding)
  {
     if(!IsValidSymbol())
       throw new ShareHoldingSymbolsInvalidException();

    Symbol = symbol;
    Holding = holding;
  }

It has business rules validation, for which is valid symbol, the autofac calls the constructor with right parameters provideded for the facotry, but the reason the instance creation fails, is because the data is invalid, not that there is a technical problem resolving the instance.

So going on with the example from previous tutorial.

There is code like this, that creates the shareholding.

var createHolding = scope.Resolve<Shareholding.Factory>();

// 1234 shares of "ABC"
var holding = createHolding("ABC", 1234);

This will break on DependencyResolutionException.
## Desired Solution

What I would desire is that call to:

var holding = createHolding("ABC", 1234);

would be equal to new Shareholding("ABC", 1234) in a sense, the exception the application actually breaks on is the exception thrown inside a constructor.

There are multiple ways to approach this, one way would be, I am not sure we can do this with reflection but if we could distinguish between constructor was actually invoked and then there was an exception thrown inside, or we couldn't find the right parameters with correct types.

If that can't be done I wish I could use the Middleware functionaility something like this.

 public class ReThrowDomainExceptionMiddleware : IResolveMiddleware
        {
            public PipelinePhase Phase => PipelinePhase.ParameterSelection;

            public void Execute(ResolveRequestContext context, Action<ResolveRequestContext> next)
            {
                try
                {
                    next(context);
                }
                catch (DependencyResolutionException ex)
                {
                    if (ex.InnerException?.InnerException is DomainException domainException)
                        throw domainException;
                }
            }
        }

I can try to rethrow it currently it still ends up in ResolveOperation.cs

            catch (Exception exception)
            {
                End(exception);
                if (DiagnosticSource.IsEnabled())
                {
                    DiagnosticSource.OperationFailure(this, exception);
                }

                throw new DependencyResolutionException(ResolveOperationResources.ExceptionDuringResolve, exception);
            }

and finally shows up as DependencyResolutionException

if autofac had a catch like this before the previous ResolveOperation.cs

            catch (ReThrowException exception)
            {
                End(exception);
                if (DiagnosticSource.IsEnabled())
                {
                    DiagnosticSource.OperationFailure(this, exception);
                }

                throw exception.InnerException;
            }

I could throw ReThrowException  from my middleware, that would take an inner exception, that I actually want the object creation to fail on.
## Alternatives You've Considered

I have considered looking for the domain exception like this ex.InnerException?.InnerException is DomainException domainException where I actually need it, but this doesn't feel right, I would like if the delegate facotry in this instance failed with the domain exception by default

**Comment by tillig** [comment]
Just so I'm clear: It doesn't sound like the exception is _suppressed_ - that is, the exception still happens and will cause the execution to stop - it's just _wrapped_ with a `DependencyResolutionException`, right?

**Comment by siimnelis** [comment]
> 

Yes exactly, I have to go looking for it though, I wish there was a way to tell autofac, if you fail because of this instance of an exception, don't wrap it.

**Comment by tillig** [comment]
I think this is going to be "functions as designed" and not something we'll dive in and fix.

Delegate factories are effectively resolve operations, even if it appears they boil down to executing a constructor. [In that `ShareHolding` example](https://autofac.readthedocs.io/en/latest/advanced/delegate-factories.html), you'll see that when the `IQuoteService` gets added to the `Shareholding` class - that gets resolved from the container.

These things are, from an Autofac standpoint, all effectively the same thing:

```c#
// Execute the resolve through a delegate interface.
var factory = container.Resolve<Shareholding.Factory>();
var sh1 = factory("ABC", 2);

// Execute the resolve through a more generic Func<T, U> interface.
var func = container.Resolve<Func<string, uint, Shareholding>>();
var sh2 = func("ABC", 2);

// Execute the resolve using parameters directly provided.
var sh3 = container.Resolve<Shareholding>(
  new TypedParameter(typeof(string), "ABC"),
  new TypedParameter(typeof(uint), 2));
```

In all three cases, it's just resolve with a different "front end interface." These alternative interfaces are provided so you can test your code and so you don't have to spread Autofac code through your own.

Unfortunately, though, the abstraction does break down in that, _because they are all resolve operations_, if something goes wrong in them, the contract with Autofac is that what you'll get _is a `DependencyResolutionException`_.

Trying to bubble something up specifically from a constructor like that would have a lot of challenges. Brainstorming:

- There are places in the Autofac code where we assume the exceptions are normalized like, as you already saw, `ResolveOperation`. All of those places would have to be updated to know about it.
- What do we do if the exception happens as a super-deep dependency? A needs B needs C which calls the delegate factory and gets the exception. When that goes all the way back up to A (which _shouldn't know_ about its complete dependency chain - that's DI), does that domain exception go all the way through or can it get wrapped somewhere in the pipeline?
- Does it matter if it's a straight `Resolve<T>` or if it's a delegate factory? If we treat them the same, we effectively break the contract that `Resolve<T>` will report `DependencyResolutionException`; if we treat them differently, we need to start tracking more data about exact types of resolution, and that can get expensive perf-wise.
- Performance is also a factor - every time we have to check "is this something we do or not?" that's cycles added to every resolve operation. Even if it's opt-in, that means we need to make sure the hot path where folks _haven't_ opted in is still performant and unaffected by this.
- Support - someone's got to own the feature, maintain it, test it, document it, and ensure from implementation day forward that it's there and never breaks - both functionality and performance. How many people want this? Given there are [currently] between one and three people _total_ maintaining Autofac and providing support along with all the integration libraries, is the value of the feature enough to take on the additional support burden?

In the end, I have to make the judgment call that, while this might sound interesting to a few people, it's not really something we'd be interested in taking on.

If you really, really want it, we'd be happy to check out a PR with the feature and see if that code is something we can support. If you find that you _can_ do it through middleware, or through some sort of extension, but maybe we haven't opened up the right extension points, that's definitely something we can talk about opening up - it'd be really sweet if you could write the feature you need as an extension and support it as its own thing.
