### ISSUE TITLE
ContainerBuilder.Properties

### ISSUE THREAD

**Issue by wasabii** [autofac/Autofac#1345]
I have been using ContainerBuilder.Properties to store an object necessary for use between registration calls. However, I ended up with a memory leak after a minor change recently.

This led me down a route of investigation where I've discovered that ContainerBuilder.Properties is the same as ComponentRegistryBuilder.Properties, and which is copied to ComponentRegistry.Properties, as well as exposed through a FallbackDictionary to subsequent nested scope's builder.

I haven't been able to find any documentation regarding the operation of ContainerBuilder.Properties, except that it would be useful as a place to store information during registration.

So it flows down?

ComponentRegistrationBuilder.RegistrationAdded and RegistrationSourceAdded both seem to use the Properties dictionary to store their event handlers. Weird, unexpected. But what it means is these delegate lists end up being visible through the FallbackDictionary to nested scopes, so listeners on the parent scope that receive events, get events for nested scopes as well? And two nested scopes each with events registered may actually receive events intended for each other. And they need to ensure they unsubscribe to the events, else they may themselves contribute to a memory leak?

I just want to clarify the operation of Properties.

**Comment by tillig** [comment]
There's a lot to unpack here and I'm not quite clear on the nature of the issue. The title on the issue doesn't help clarify what you're looking for, either.

- Did you find a bug?
- Are you looking for some all-inclusive list of everywhere that dictionary gets used?
- Something else?

**Comment by wasabii** [comment]
It may be a bug. But that depends on what the intentions were.

Was it intended that if you create two nested lifetime scopes (A and B), and in each, subscribe to Registered on builder.ComponentRegistryBuilder.Registered, that the event handlers for A are invoked when a registration occurs on B, and vica-versa?

Because that looks like what would happen.

**Comment by wasabii** [comment]
I'm not sure whether it's a bug, or just it's operations being unclear to me.

I was using Properties to store information related to building the container. It was unexpected that that information be copied into nested scope's builders.

It looks like the events work fine, since it does a get/set on the Properties[], creating a new delegate, and overriding the value in the parent scope. So nevermind about that.

I worked around my issue by clearing the value out of Properties in a BuildCallback. Just seems unexpected that I'd have to do that.

**Comment by wasabii** [comment]
Actually, just thought of another scenario too.

Let me just clear this up. Let's say I create a ContainerBuilder. I subscribe to builder.ComponentRegistryBuilder.Registered with an event handler A. I build the container. I call BeingLifetimeScope(builder => {}). Within the callback, I subscribe event handler B to Registered. I register something with that nested builder. Is it expected that A is invoked?

**Comment by tillig** [comment]
If you wouldn't mind, so I can be sure I'm understanding what you're asking, can you actually write out the scenario in code? For example, you mention something about an event handler B but it never seems to enter the picture again, so I'm unclear what that might have to do with anything.

Technically, if you're writing it up in minimal repro unit test format, it would also help to explain what you see happening now and what you expect to see.

Unfortunately, the team support levels are pretty low right now and I'm on my phone trying to get a little work-life balance on the US holiday weekend. (I'm answering here so you can maybe guess how that's going.) The more you can do to really boil down the question, clearly express the minimal repro, and do research on your own until you get stuck, the more likely you'll get a faster answer.

I will say... That way it's working now is how it's worked for a few years, so whatever the observed behavior is, I think that's as designed. Admittedly I do not keep every facet of the internal workings of Autofac in my head, given this is a "free time activity" and not my paid day job or anything. It's possible you've found an issue, absolutely, but if you're just curious about the nuances of what's happening right now, the easiest way to figure it out is to set up tests and try things out or look at the tests in our repo to see.

**Comment by wasabii** [comment]
The following fails with a `NotImplementedException`. I find this unexpected. I'm done with the first `ContainerBuilder`. The container has been built. The `ContainerBuilder` has fallen outside of scope. And yet, it's being kept alive by the event, because the event is a `Delegate` inside the `MulticastDelegate` stored `Properties`. And that Properties dictionary is kept alive by the `FallbackDictionary` that is retained on the resulting `IContainer`.

In my case, I was using the `Registered` event to track information related to objects that had been registered. There were two problems with this: a) I was storing my own information in Properties, and expecting it to be removed when the ContainerBuilder was discarded and b) I was subscribing to Registered to track that information, inadvertidly tracking information related to children scopes.

Frankly, whether this is a bug is up to you. But it's very awkward and easy to get wrong.

```
using System;

using Autofac;
using Autofac.Core;

public class Program
{

    public static void Main(string[] args)
    {
        IContainer c;

        {
            var b = new ContainerBuilder();
            b.ComponentRegistryBuilder.Registered += ComponentRegistryBuilder_Registered1;
            c = b.Build();
        }

        GC.Collect();

        c.BeginLifetimeScope(b2 =>
        {
            b2.ComponentRegistryBuilder.Registered += ComponentRegistryBuilder_Registered2;
            b2.RegisterInstance(new object());
        });
    }

    static void ComponentRegistryBuilder_Registered1(object sender, ComponentRegisteredEventArgs e)
    {
        var b = e.ComponentRegistryBuilder;
        throw new NotImplementedException();
    }

    static void ComponentRegistryBuilder_Registered2(object sender, ComponentRegisteredEventArgs e)
    {

    }

}
```

**Comment by wasabii** [comment]
The only way I've found to work around this is to unregister from the events inside of BuildCallbacks. Which is super weird to do:

```


        {
            var b = new ContainerBuilder();
            b.ComponentRegistryBuilder.Registered += ComponentRegistryBuilder_Registered1;
            // do stuff with container, like load modules
            b.ComponentRegistryBuilder.Registered -= ComponentRegistryBuilder_Registered1;
            c = b.Build();
        }
```

**Comment by tillig** [comment]
OK, so the real crux of the question is about whether registration in a child scope should cause registration events in a parent scope to be raised. I vaguely recall that was intentional, though off the top of my head I can't recall the exact reason why. Given I'm on my phone I'm not really able to search adequately through the code to see if we have tests around this expectation or not. Did you see any tests around it?

**Comment by wasabii** [comment]
`ChildScopeBuilderGetsParentProperties` asserts that Properties should flow from parent to children, but doesn't make mention of the event handlers specifically.

**Comment by alistairjevans** [comment]
@wasabii, have you confirmed that _both_ attached handlers fire in the child scope? I imagine the first one is throwing , then not proceeding to the second?

This will likely fit firmly in the "works as designed" category imho, and not something we're likely to break now, since some people are probably relying on this behaviour.

I'd suggest a contribution to docs if you think there's something to clarify?

**Comment by alistairjevans** [comment]
I believe also you could add your own deferred callback to `ComponentRegistryBuilder` as a "last" registration callback, and remove your handler before the container build completes.

**Comment by wasabii** [comment]
ComponentRegistryBuilder_Registered2 is invoked successfully, before invoking ComponentRegistryBuilder_Registered1.

>This will likely fit firmly in the "works as designed" category imho, and not something we're likely to break now, since some people are probably relying on this behaviour.

That's fine. It's just incredibly unexpected behavior to have the entire ContainerBuilder object, and all that entails, kept alive by the GC because you left a dangling event handler. It's not clear that the event's lifetime isn't actually tied to the lifetime of the container builder. I'm also somewhat at a loss as to why the parent ContainerBuilder would want to receive notifications of child scope registrations, perhaps originating from random Threads, after the ContainerBuilder itself has been built, and thus is not usable anyways.

>I believe also you could add your own deferred callback to ComponentRegistryBuilder as a "last" registration callback, and remove your handler before the container build completes.

I'm using BuildCallback to do this. But yeah, totally non-obvious.

I will consider the docs.

**Comment by alistairjevans** [comment]
> It's just incredibly unexpected behavior to have the entire ContainerBuilder object, and all that entails, kept alive by the GC because you left a dangling event handler

Is the _entire_ `ContainerBuilder` not collected? I'd expect the event handlers to be persisted, which are held in `Properties` in a fairly deeply nested object, as you've said, and preserved down to child scopes, but the actual `ContainerBuilder` object should be collectible. Let us know if you see the entire builder object itself kept alive.

It's also a "classic" .net annoyance that dangling event handlers keep objects alive long after you'd expect them to depart.

**Comment by wasabii** [comment]
I misspoke, sorry. The ContainerBuilder itself isn't kept. The ComponentRegistryBuilder however is, since it's the `sender` on any events that might be sent. That's a much smaller surface (no configuration callbacks).

>It's also a "classic" .net annoyance that dangling event handlers keep objects alive long after you'd expect them to depart.

Usually only the other way around though: for instance, in my example, Program is kept alive by the events, and that has to be considered. But in this case, the Builder stuff itself is.

**Comment by wasabii** [comment]
I should note, it's incredibly easy for me to be wrong here, and for ContainerBuilder to infact be kept alive. Because users can very easy use the event handlers to modify the ContainerBuilder: specifically it's properties. And thus the handlers which get passed down through Properties might contain a reference to ContainerBuilder very easily.

**Comment by wasabii** [comment]
Imagine the following:

```

IContainer c;

{
  var b = new ContainerBuilder();
  b.ComponentRegistryBuilder.Registered += (s, a) => b.Properties["registeredCount"] = (int)b.Properties["registeredCount"] + 1;
  c = b.Build();
}

```

**Comment by alistairjevans** [comment]
I see what you're saying, but in that case you should be referencing properties on `s`, not `b`, to avoid the capture. All dotnet code that captures variables into closures naturally can result in some unexpected object lifetimes, there's no way for us to 100% protect people from that.

Also, the `ComponentRegistryBuilder` isn't captured into the event callback's context, because it's the "current" builder passed into each callback as `sender`, not the one it was registered into.

Anyway, that's all by the by, as I said, if you feel there's some clarification needed in the docs about the `Registered` event handler lifetime, happy to look at a PR for it.
