### ISSUE TITLE
Performance issue(Thread Blocked) during DI using Autofac 4.4.0

### ISSUE THREAD

**Issue by dewanymca** [autofac/Autofac#1356]
We have been using Autofac for DI in our application. Recently we changed implementation for one of Azure Cosmos Adapter and replaced it with the new implementation and corresponding changes were done in DependencyINjection file to register new dependency. With this change, we are seeing sluggishness in app, we load tested this in UAT and collect a dotnet-dump which points to call stack of Autofac and shows 300 thread blocked. We are not sure how to look into this.

Adding dotnet-dump snip which shows a blocked thread
<img width="422" alt="image" src="https://user-images.githubusercontent.com/15336470/204797543-df973dc0-cea1-42b7-aa9e-612aea3cb981.png">

**Comment by tillig** [comment]
It's been a couple months pending input here so I'm going to close this. If input comes in and maybe a repro so we can start fixing it, we can reopen.
