### ISSUE TITLE
Please teach AutoFac about Immutable Collections

### ISSUE THREAD

**Issue by TonyValenti** [autofac/Autofac#1372]
## Problem Statement
We have code like this:
```
public class Foo {
  protected ImmutableArray<Bar> Data {get; }

  public Foo(IEnumerable<Bar> Data){ 
    this.Data = Data.ToImmutableArray();
  }
}
```

And we'd like to replace it with code like this:
```
public class Foo {
  public required ImmutableArray<Bar> Data {protected get; init; }
}
```

But Autofac does not know how to construct an ```ImmutableArray``` or ```ImmutableList```.

## Desired Solution
Please teach Autofac how to construct those types as a replacement for IEnumerable.

## Alternatives You've Considered
I could do this:
```
public class Foo {
  public required IEnumerable<Bar> Data {protected get; init; }
}
```
But it does not have the same characteristics as Immutables.

**Comment by alistairjevans** [comment]
Is there a reason you cannot use `IReadOnlyList<Bar>`?

```csharp
public class Foo {
  public required IReadOnlyList<Bar> Data {protected get; init; }
}
```

That works out-of-the-box.

**Comment by TonyValenti** [comment]
@alistairjevans With the immutable structures I get non-destructive mutations which I don't get with the IReadOnlyList.  IReadOnlyList is basically only a pre-enumerated enumerable.

**Comment by alistairjevans** [comment]
Are you modifying lists of injected services after they are injected? You might have to provide a fuller example here, not sure I understand.

**Comment by TonyValenti** [comment]
Hi @alistairjevans -
No, we're not doing any modifications to them. We just prefer using ImmutableArray/ImmutableList over IReadOnlyCollection.

**Comment by tillig** [comment]
Duplicate #1408
