### ISSUE TITLE
DiagnosticSource `Event` and `WriteEvent` parameter mismatch

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac#1382]
## Describe the Bug

**It's unclear if this is something Autofac can fix** but it seems reasonable to look into.

Based on [this StackOverflow question](https://stackoverflow.com/questions/76390692/the-parameters-to-the-event-method-do-not-match-the-parameters-to-the-writeeven), it appears a WPF app targeting .NET 4.7.2 with diagnostics enabled is throwing an exception with this message whenever `Resolve` is called:

`The parameters to the Event method do not match the parameters to the WriteEvent method. This may cause the event to be displayed incorrectly.`

## Steps to Reproduce

**I'm not sure how to replicate the issue** - the original person asking the question can't replicate it outside of this specific app, which may mean there is something hooked to the `DiagnosticSource` that is executing during that `FilterAndTransform` stage causing the mismatch.

I know we've also seen trouble in the past with full .NET Framework not being fully `netstandard` compatible, I wonder if this could be one of those places.

## Exception with Stack Trace

```text
DiagnosticSourceEventSource.Event() at C:\Users\gael\AppData\Roaming\JetBrains\Rider2023.1\resharper-host\SourcesCache\5525318ba2913ce58be271c55cfb2f2dd9c0982e1f8234fb78d859d7b1d997c\DiagnosticSourceEventSource.cs:line 214
DiagnosticSourceEventSource.FilterAndTransform.<>c__DisplayClass2_1.<.ctor>b__2() at C:\Users\gael\AppData\Roaming\JetBrains\Rider2023.1\resharper-host\SourcesCache\5525318ba2913ce58be271c55cfb2f2dd9c0982e1f8234fb78d859d7b1d997c\DiagnosticSourceEventSource.cs:line 617
DiagnosticSourceEventSource.CallbackObserver<KeyValuePair<string, object>>.OnNext()
DiagnosticListener.Write()
DiagnosticSourceExtensions.OperationStart()
ResolveOperation.ExecuteOperation()
ResolveOperation.Execute()
LifetimeScope.ResolveComponent()
Container.ResolveComponent()
ResolutionExtensions.TryResolveService()
ResolutionExtensions.ResolveService()
ResolutionExtensions.Resolve()
```

## Dependency Versions

Autofac: 7.0.1

## Additional Info

Original requestor is @valhentai - unclear if there's more to add here, perhaps some application-specific information about the way diagnostics are set up in the app.

**Comment by tillig** [comment]
I found [the source for `DiagnosticSourceEventSource` that I think corresponds to `System.Diagnostics.DiagnosticSource` v4.7.1 (released 5/12/2020)](https://github.com/dotnet/runtime/blob/ccf6aedb63c37ea8e10e4f5b5d9d23a69bdd9489/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs), which is what we're referencing in Autofac. There is a lot of interesting conditional code in there. There have been a ton of changes since that drop and it may be worth taking an upgrade in Autofac to ensure a better experience, though I'm not sure if it'd fix this.

@valhentai, does your project specifically reference `System.Diagnostics.DiagonosticSource`? Can you tell what version you're using?

**Comment by tillig** [comment]
Per the comment thread in that SO question, there was a listener for HTTP requests running that was somehow also attached to the Autofac diagnostic source, trying to output both event types. Without more info on the setup I can't suggest a concrete fix, but the gist here is that the wrong listener was subscribed to Autofac events.

I'm going to close this as not an Autofac problem. Is someone comes up with a specific bug and repro, open a new issue and include the repro so we can look into it.

**Comment by sakennedy** [comment]
I have also documented the same issue here: https://stackoverflow.com/questions/75993176/asp-net-site-generates-hundreds-duplicate-messages-the-parameters-to-the-event

The problem for my team is that the call to the 'DiagnosticSourceEventSource.FilterAndTransform' originates from an 'EtwCommand' of some unknown origin. I cannot see the call stack passed this method and many of the arguments are not visible from the debugger (though not sure if that would even help). At this time we have no idea why this call is triggered.

This single call however results in a severe drop in performance as every Autofac interaction results in a call to the 'DiagnosticSourceEventSource' which synchronously writes the same message to 'Debug.Log'.

From our point of view Autofac is the only consumer of the 'DiagnosticSourceEventSource'. It would be great if there was an option to opt-out of 'Autofac' using 'DiagnosticSourceEventSource'. 

At the moment we must use the following hack to work around:

`var diagnosticsLib = Assembly.Load("System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51");
var diagnosticSourceEventSourceType = diagnosticsLib.GetType("System.Diagnostics.DiagnosticSourceEventSource");
object diagnosticSourceEventSource = diagnosticSourceEventSourceType.InvokeMember("Logger", BindingFlags.Static | BindingFlags.GetField | BindingFlags.Public, null, null, null);
        
if (diagnosticSourceEventSource is IDisposable disposable)
    disposable.Dispose();`

**Comment by fubar-coder** [comment]
For System.Diagnostics.DiagnosticSource 8.0.0, you have to change the code from:

```c#
var diagnosticsLib = Assembly.Load("System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51");
var diagnosticSourceEventSourceType = diagnosticsLib.GetType("System.Diagnostics.DiagnosticSourceEventSource");
object diagnosticSourceEventSource = diagnosticSourceEventSourceType.InvokeMember("Logger", BindingFlags.Static | BindingFlags.GetField | BindingFlags.Public, null, null, null);

if (diagnosticSourceEventSource is IDisposable disposable) disposable.Dispose();
```

to:


```c#
var diagnosticsLib = Assembly.Load("System.Diagnostics.DiagnosticSource, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51");
var diagnosticSourceEventSourceType = diagnosticsLib.GetType("System.Diagnostics.DiagnosticSourceEventSource");
object diagnosticSourceEventSource = diagnosticSourceEventSourceType.InvokeMember("Log", BindingFlags.Static | BindingFlags.GetField | BindingFlags.Public, null, null, null);

if (diagnosticSourceEventSource is IDisposable disposable) disposable.Dispose();
```

The assembly version changed and the internal field was renamed from `Logger` to `Log`.
