### ISSUE TITLE
Support 8.0

### ISSUE THREAD

**Issue by kfrancis** [autofac/Autofac#1383]
## Problem Statement

As .NET MAUI's generally pretty wonky to work with, we're trying to stay on the bleeding edge to take advantage of the latest fixes but that currently requires net8.0 and the latest supported from autofac is net7.0 leading to exceptions like this:

![6n5u2-1686756558-112918](https://github.com/autofac/Autofac/assets/67574/5077bf1d-a4ae-404e-a362-1ed21f2f6957)

## Desired Solution

Can there be some prelim support for the .net8.0 framework? It's due to be released in November 2023, so it would be nice to get some support there. It does look like there have been some beta releases related to .net core support historically, so this would be along the same lines.

## Alternatives You've Considered

None, we can't force this to work.

## Additional Context

We were looking at [this blog post](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-preview-5/) and see that some of the bugs stopping our production app from being that much closer might have been addressed but on trying we're not able to load the app due to autofac issues. The app works without the error in net7.0, but fails when moving to net8.0.

**Comment by tillig** [comment]
A general `DependencyResolutionException` doesn't actually tell us that adding .NET 8 support will fix anything. For all we know, you wired something up wrong in your app and adding .NET 8 wouldn't fix it. Unfortunately, due to limited time, I can't promise any sort of early builds or beta support here.

**Comment by tillig** [comment]
You can totally use Autofac in .NET 8, just like you can use other libraries that don't _explicitly target_ .NET 8 in .NET 8. Each new .NET version is backwards-compatible, runtime-wise, with the previous. Libraries don't have to target every version of .NET that gets released.

**Comment by tillig** [comment]
Based on #1385 we may have a technical requirement to update to .NET 8 to support some new language features, which is one of the reasons we'd make such an upgrade. I'll close this issue for now since it may happen as a byproduct of needing to support new .NET 8 features.
