### ISSUE TITLE
Required properties not working with WebAPI controllers

### ISSUE THREAD

**Issue by Jeern** [autofac/Autofac#1405]
## Describe the Bug

In a .NET 7 ASP.NET Web Api app I use Autofac like this:

            builder.Host.UseServiceProviderFactory(_ => new AutofacServiceProviderFactory())
                .ConfigureContainer<ContainerBuilder>((c, cb) =>
                {
... registrations done here
                });

## Steps to Reproduce

When I resolve an instance of a service inheriting  ControllerBase using either an IContainer og builder.Services.GetService<>
properties marked required and constructor parameters resolves as expected.

But if just call the service from the browser only constructor parameters are resolved. The required properties are null.

It seems the ASP.NET Web API is not resolving the service instance using one of the two methods I mentioned. 

## Expected Behavior

I expect any properties marked required to be resolved. Instead they are null. Only constructor parameters are resolved.

## Dependency Versions

Autofac: 7.1.0

## Additional Info

The properties marked required are not resolved no matter if they are in a base class or directly on the service class. They are resolved properly in both cases when resolving manually.

The test I have done is where all properties and parameters are of the same type (i.e. the type is registered properly)

**Comment by Jeern** [comment]
Btw. Forgot to mention that I have the same problem with old fashioned PropertiesAutowired which has worked for me in the past. Back then I used a Startup class and a ConfigureContainer override. Now I am using the new recommended .ConfigureContainer<ContainerBuilder> method as mentioned.

**Comment by alistairjevans** [comment]
Have you called `AddControllersAsServices`? 

https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

**Comment by Jeern** [comment]
Amazing. That worked :) Thank you so much !!!  have been pulling my hair for hours...  is AddControllersAsServices a new requirement ? I have not used it before but had success using PropertiesAutowired  in Autofac 6

**Comment by tillig** [comment]
Not new, that's been a thing since ASP.NET Core started. [It's been in our docs for seven years now.](https://github.com/autofac/Documentation/commit/8e39369470bd82e0d022381fd85f3ab473ac8567)

**Comment by Jeern** [comment]
Cool. I wonder how we got PropertiesAutowired  to work without it then, but no matter. Thank you again :)
