### ISSUE TITLE
Autofac does not correctly process `required` members for NetFramework (or any version of .NET < 7.0)

### ISSUE THREAD

**Issue by DoctorVanGogh** [autofac/Autofac#1420]
## Describe the Bug

Properties declared as `required`[^1] are not correctly injected with Autofac when running anything below NET7.

## Steps to Reproduce

Use the attached unit test project (multi-targeting both NetFramework 472 & NET 8.0)

```c#
using Autofac;
using Autofac.Core;

namespace AfRequiredTests {

    public class Foo {
        public required int Bar { get; set; } = -1;
    }

    public class AfRequiredTests {
        public ILifetimeScope Scope { get; }

        public AfRequiredTests() {
            var cb = new ContainerBuilder();

            cb.RegisterType<Foo>()
                .AsSelf();

            this.Scope = cb.Build();

        }

        [Fact]
        public void TestWithMissingRequiredParameter() {
            Assert.Throws<DependencyResolutionException>(
                Scope.Resolve<Foo>
            );
        }

        [Fact]
        public void TestSuppliedRequiredValueIsUsed() {
            const int customValue = 42;

            Assert.Equal(customValue, Scope.Resolve<Foo>(TypedParameter.From(customValue)).Bar);
        }

    }
}
```
[AfRequiredTests.zip](https://github.com/user-attachments/files/16571239/AfRequiredTests.zip)

## Expected Behavior

Correct injection of properties with a `RequiredMemberAttribute` in _all_ (framework) builds of autofac as described in https://autofac.readthedocs.io/en/latest/register/registration.html#required-properties

## Exception with Stack Trace

_Not applicable_

## Dependency Versions

Autofac: 8.0.0
Required: 1.0.0

### Observed bahaviour 
| req. value | NET 8 | NF 4.72 |
|--------|:--------:|:--------:|
| supplied | ✅  | ⛔ <br/> ignored |
| missing | ✅ <br/> (expected exception) |  ⛔ <br/> (no exception) |

### Suggested fix
The bug (feature? 😉 ) is quite obviously buried in https://github.com/autofac/Autofac/blob/ec4907fb6ea61015080b76bcd18cbcf63e43579e/src/Autofac/Core/Activators/Reflection/InjectableProperty.cs#L29C1-L31C7

```cs
internal class InjectableProperty
{
    ...
    public InjectableProperty(PropertyInfo prop)
    {
       ...
#if NET7_0_OR_GREATER
        IsRequired = prop.GetCustomAttribute<RequiredMemberAttribute>() is not null;
#endif
    }
   ...
}   
```
And the current code is _correct_ for NET 7+ (Since there _is_ no predefined _type_ `RequiredMemberAttribute` in previous versions and it just would not build for previous versions).[^2]

But as far as the _compiler_ is concerned, the required feature is not enforced by type ***reference*** but by type ***name***.

So that `#if ...` block should actually have a second branch:
```cs
#if NET7_0_OR_GREATER
        IsRequired = prop.GetCustomAttribute<RequiredMemberAttribute>() is not null;
#else
        IsRequired  = prop.GetCustomAttributesData()
            .Any(
                cad => cad.AttributeType.FullName == "System.Runtime.CompilerServices.RequiredMemberAttribute"
            );
#endif
```

--- 
[^1]: While NetFramework (& NET Core versions below 7) do not _inherently_ support `required` members, they are perfectly able to use this feature using polyfill style code (for example using nuget packages). All the *compiler* requires is a `LangVersion`  offering the feature and an appropriate attribute type declared in the `System.Runtime.CompilerServices` _namespace_ with the _type name_ `RequiredMemberAttribute`. Most prominent nuget package solving this issue: https://www.nuget.org/packages/Required
[^2]: I have no idea which attribute is used if you supply a custom `System.Runtime.CompilerServices.RequiredMemberAttribute` type on a NET7+ build. There _might_ be mismatch issues happening if the custom type is used and AF only checks via (framework) type reference.

**Comment by alistairjevans** [comment]
Hi, thanks for raising the issue; good spot, I didn't realise someone had created a polyfill for the required behaviour.

Are you able to raise a PR with the proposed change?

**Comment by DoctorVanGogh** [comment]
Yeah, I think I'll be able to file a PR.

---

As for polyfills, as far as I know there are nuget packages for _all_ modern language features for the "old" frameworks:
- `Microsoft.Bcl.AsyncInterfaces` for `await using`/`await foreach` (and async enumerables in general)
- `System.Threading.Tasks.Extensions` for `ValueTask`s
- `Nullable` for all the nullable fun (including all the `[NotNullWhen...]` decoration variants).
- `Required` for `required` support
- `IsExternalInit` for `init` property accessors
- `IndexRange` for `[.. var foo, ]` slicing patterns

**Comment by DoctorVanGogh** [comment]
Not to be a pest. but any ETA-(ish) on an 8.0.1 nuget? 

Because that'll determine if I have to ship some things with a `develop` custom Autofac build in the interim 🤔

**Comment by tillig** [comment]
No ETA provided. We have some other PRs pending that we'd like to get into the next release.

**Comment by DoctorVanGogh** [comment]
Custom build it is then. 👍
