### ISSUE TITLE
Add Compability for FromKeyedServices  

### ISSUE THREAD

**Issue by LechAtAtlasCopco** [autofac/Autofac#1422]
## Problem Statement

Service use Microsoft.Extensions.DependencyInjection

    public Service([FromKeyedServices("whatever")] Channel<whatever> whateverChannel)

## Desired Solution

Service should be able use FromKeyedServices  instead of KeyFilter
rewriting to
    public Service([KeyFilter("whatever")] Channel<whatever> whateverChannel) is not an soultion
because Service is not my code

## Additional Context
https://stackoverflow.com/questions/78706913/how-to-make-worker-class-compatible-with-autofac-also-with-microsoft-dependency

**Comment by tillig** [comment]
`FromKeyedServices` is supported only when used in conjunction with the [Autofac.Extensions.DependencyInjection](https://github.com/autofac/Autofac.Extensions.DependencyInjection) package, but it _is there_ [as of 9.0.0](https://github.com/autofac/Autofac.Extensions.DependencyInjection/releases/tag/v9.0.0)

**Comment by LechAtAtlasCopco** [comment]
I use [Autofac.Extensions.DependencyInjection](https://github.com/autofac/Autofac.Extensions.DependencyInjection) in version 9.0.0 but. I get an exception while resolving.

None of the constructors found on type ...

Is there an working test? on Github?

**Comment by tillig** [comment]
All of the tests are based on the Microsoft specification tests for DI containers, like this one [for the keyed services handling](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/test/Autofac.Extensions.DependencyInjection.Test/Specification/BuilderKeyedSpecificationTests.cs).

Everything to do with MS injection compatibility is in that repo. If there's a bug you've found, [please file it over there](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues) - this repo is really for issues with just core Autofac.
