### ISSUE TITLE
Resolution parameters are not passed on to transitive sub-resolutions

### ISSUE THREAD

**Issue by DoctorVanGogh** [autofac/Autofac#1425]
## Describe the Bug

If you have a dependency chain of `Wiz -> Bar -> Foo` and ask for a `Wiz` while supplying a `Foo`, resolution will fail because `Bar`supposedly cannot be constructed since it has no `Foo`. 

## Steps to Reproduce

Run the following unit test:

```c#
using Autofac;

namespace AfTransitiveParameters; 

public class Foo;
public class Bar(Foo foo);
public class Wiz(Bar bar);

public class TransitiveParameters {

    public TransitiveParameters()
    {
        var cb = new ContainerBuilder();

        cb.RegisterType<Bar>()
            .AsSelf()
            .InstancePerDependency();

        cb.RegisterType<Wiz>()
            .AsSelf()
            .InstancePerDependency();

        this.Scope = cb.Build();
    }

    public IContainer Scope { get; }

    [Fact]
    public void TransitiveParameter() {
        Assert.IsType<Wiz>(Scope.Resolve<Wiz>(TypedParameter.From(new Foo())));
    }

    [Fact]
    public void TransitiveFactory() {
        var factory = Scope.Resolve<Func<Foo, Wiz>>();

        Assert.IsType<Wiz>(factory(new Foo()));
    }

    [Fact]
    public void ManuallyBrokenTransitivity() {

        var bar = Scope.Resolve<Bar>(TypedParameter.From(new Foo())); 
        var wiz = Scope.Resolve<Wiz>(TypedParameter.From(bar));

        Assert.IsType<Wiz>(wiz);
    }
}
```
The first two tests will _fail_ because purportedly no `Foo` is available 😞 

## Expected Behavior
Parameters should work transitively. Claiming "None of the constructors  [...] can be invoked with the available [...] parameters. Cannot resolve parameter [X]"  when you have explicitly supplied a parameter for X seems... weird 🤔 

## Exception with Stack Trace

```text
Autofac.Core.DependencyResolutionException : An exception was thrown while activating AfTransitiveParameters.Wiz -> AfTransitiveParameters.Bar.
---- Autofac.Core.DependencyResolutionException : None of the constructors found on type 'AfTransitiveParameters.Bar' can be invoked with the available services and parameters:
Cannot resolve parameter 'AfTransitiveParameters.Foo foo' of constructor 'Void .ctor(AfTransitiveParameters.Foo)'.```
```

## Dependency Versions

Autofac: 8.0.0

## Additional Info
Obviously the transitive chain can be manually broken but that requires knowledge of the object graph composition. Which feels off.
Also you could probably do some manual delegate composition on the registration side, but that would be very specialized and again require knowledge of each component node of the object graph.

**Comment by tillig** [comment]
This is functioning as designed. [We have an FAQ about it.](https://autofac.readthedocs.io/en/latest/faq/injecting-global-parameters.html)
