### ISSUE TITLE
when use  masstransit , IScopedMediator  Inconsistent with expected behavior

### ISSUE THREAD

**Issue by ByZhouhang** [autofac/Autofac#1432]
## Describe the Bug

My project is based on the aspnetcore api, I use the Masstransit library, and I use the ScopedMediator 
https://masstransit.io/documentation/concepts/mediator#scoped-mediator

When autofac is not used, the database context injected into the IScopedMediator consumer is the same as the database context injected in the test method.  

With Autofac, the context in the consumer is not the same as the context in the test

I asked the author of the masstransit library, and here are some of his responses

![image](https://github.com/user-attachments/assets/3999dd53-d397-413f-8294-cc4f83f13c44)

```c#
var builder = WebApplication.CreateBuilder(args);

// use  autofac ,but   when i use  MS DI   it behave expectied
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory())
            .ConfigureContainer<ContainerBuilder>(containerBuilder =>
            {
                containerBuilder.RegisterModule<AutofacModuleSetup>();
            });

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddDbContext<TestDBContext>(
       options => options.UseInMemoryDatabase("MyDatabase"));

builder.Services.AddMediator(cfg =>
{  
    cfg.AddConsumer<AddSubjectTriggerConsumer>();
    cfg.AddConsumer<AddSubjectTriggerConsumer2>();
});

builder.Services.AddMassTransit(cfg =>
{
    cfg.UsingInMemory((context, cfg) =>
    {
        cfg.ConfigureEndpoints(context); // 自动配置所有消费者的端点
    });
});


var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapGet("/api/test/masstransitmeditor", async (IScopedMediator _mediatorScoped, TestDBContext _dbcontext, IMediator _mediator) =>
{

    Console.WriteLine(_dbcontext.GetHashCode());
    await _mediatorScoped.Send(new AddTestTriggerCommand { SubjectId = Guid.Empty });
    await _mediator.Send(new AddTestTriggerCommand2 { SubjectId = Guid.Empty });
    return ResponseOutput.Ok();
});

app.Run();
```
```c#

public class AddSubjectTriggerConsumer(TestDBContext _dbcontext) : IConsumer<AddTestTriggerCommand>
{
    public async Task Consume(ConsumeContext<AddTestTriggerCommand> context)
    {

        Console.WriteLine(_dbcontext.GetHashCode());

        Console.WriteLine();

    }
}

public class AddSubjectTriggerConsumer2(TestDBContext _dbcontext) : IConsumer<AddTestTriggerCommand2>
{
    public async Task Consume(ConsumeContext<AddTestTriggerCommand2> context)
    {

        Console.WriteLine(_dbcontext.GetHashCode());

        Console.WriteLine();
    }
}
```

**Comment by tillig** [comment]
We don't support MassTransit or any of the integration libraries. This is likely a question for the MassTransit folks or for someone on [StackOverflow](https://stackoverflow.com).

If you can create a minimum repro not involving MassTransit and determine a bug in core Autofac, please open a new issue. If you can make a minimum repro and you find the bug is in the Autofac integration with .NET Core, [that's a different repo](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues). Either way, if the issue involves a repro that must use MassTransit, there's nothing we can do here to help you.
