### ISSUE TITLE
RegisterGeneric with multiple open types

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#216]
_From [techniq35](https://code.google.com/u/techniq35/) on May 07, 2010 05:59:45_

I've been unsuccessful at resolving dependencies when an interface has 2 
generic types (my IRepository<T, TId> interface takes in the type of the domain 
object(T) and the type of the key for the domain object (TId))

I have attempted to register my repositories using the following:
    builder.RegisterGeneric(typeof(Repository<,>)).As(typeof(IRepository<,>));
but the dependency is not resolved when specified in a constructor's 
parameters, for example: 

```
public CustomerController(IRepository<Customer, int> repository)
{
    this.repository = repository
}
```

as a workaround, I've had to explicitly create a repository that extends the 
Repository base class with the typing and register these classes instead, for 
example

```
public class CustomerRepository : Repository<Customer, int> { ... }

builder.RegisterAssemblyTypes(Assembly.Load("DataServices"))
    .Where(t => t.Name.EndsWith("Repository"))
    .AsImplementedInterfaces();
```

Is there something I'm doing wrong when registering the component, or is this a 
bug?

_Original issue: http://code.google.com/p/autofac/issues/detail?id=216_

**Comment by woodpk** [comment]
I am using Autofac 4.9.2 and this logic no longer works. 
I have the following logic:
            builder.RegisterGeneric(typeof(GetPersonsByIdQueryHandler<,>))
                                                                   .As(typeof(IQueryHandler<,>));
autofac will not register: GetPersonsByIdQueryHandler<,> and gives this error:
Non-generic type GetPersonsByIdQueryHandler cannot be used with type arguments
Can you offer any assistance?

**Comment by tillig** [comment]
@woodpk Not enough information. If you have something we can reproduce - including the types you mention and a unit test format thing so we can actually see it in action - please file a new issue and include that reproduction so we can troubleshoot.
