### ISSUE TITLE
Module.AttachToComponentRegistration() does not detect new registrations in nested scopes

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#218]
_From [nicholas...@gmail.com](https://code.google.com/u/104985896277148547614/) on May 10, 2010 06:23:53_

See: http://groups.google.com/group/autofac/browse_thread/thread/86592faf0bb5aad9

_Original issue: http://code.google.com/p/autofac/issues/detail?id=218_

**Comment by tillig** [comment]
This didn't make it into Autofac 4 but is not forgotten and not off the table. It's just... pretty non-trivial, so the .NET Core stuff took precedence and pushed it out.

**Comment by tillig** [comment]
This issue appears to be somewhat related to, yet sort of the opposite of, #608.

**Comment by evgeny-burmakov** [comment]
Any news after 8 years?
