### ISSUE TITLE
PreserveExistingDefaults doesn't work in nested lifetime scopes

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#272]
_From [mrdont@mail.ru](https://code.google.com/u/mrdont@mail.ru/) on November 19, 2010 12:06:33_

What steps will reproduce the problem? 1. Register one implementation of a service in root container.
2. Begin new lifetime scope and register another implementation of the service, but preserving existing defaults.
3. Resolve service in the created scope.

What is the expected output? First implementation of the service.
What do you see instead? Another implementation of the service.

Service registered in root container is also default implementation in nested scope, until another implementation is registered. But when I specify PreserveExistingDefaults, I expect that new registration won't override existing registrations of the same service.

The following code would reproduce the problem:

        public interface IService {}
        public class Service1: IService {}
        public class Service2: IService {} 

        [Test]
        public void PreserveExternalOverrides()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<Service1>().As<IService>();
            var context = builder.Build();

            var newContext = context.BeginLifetimeScope(b => b.RegisterType<Service2>().As<IService>().PreserveExistingDefaults());

            Assert.IsInstanceOf<Service1>(context.Resolve<IService>());
            Assert.IsInstanceOf<Service1>(newContext.Resolve<IService>()); // fails

        }

_Original issue: http://code.google.com/p/autofac/issues/detail?id=272_

**Comment by tillig** [comment]
NICE! This had been open for almost six years!

**Comment by alexmg** [comment]
I manually merged across the PR from @ilya-g as the starting point so props to them. :+1:
