### ISSUE TITLE
PropertiesAutowired ignores Resolve parameters when it is testing what props can be wired

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#289]
_From [tom8...@gmail.com](https://code.google.com/u/118237168312257315588/) on February 04, 2011 00:30:34_

Windsor is able to autowire properties using arguments passed to resolve.

This doesn't appear to work in autofac. 2.4.3.700

``` csharp
public class A
{
  public string MyProp { get; set;}
}
...
builder.RegisterType<A>().PropertiesAutowired();
...
container.Resolve(typeof(A), new NamedPropertyParameter("MyProp", "hello"));
```

===> I would expect MyProp to be set to "hello".

_Original issue: http://code.google.com/p/autofac/issues/detail?id=289_

**Comment by tillig** [comment]
I think I figured this one out. I pushed a fix for it in [commit 25a8cf5](https://github.com/autofac/Autofac/commit/25a8cf5162097414cdc750d16a15df1c897dfd48).

@alexmg would you mind giving it a once-over to see if it looks decent? Basically the update will consider any manually provided resolve parameters for property injection regardless of whether you specified `PropertiesAutowired` or not - with the thought that if you're passing these parameters in for properties that you know what you're doing and want them to be used.

**Comment by alexmg** [comment]
:shipit:

**Comment by tillig** [comment]
:+1:

**Comment by tillig** [comment]
This behavior changed as a result of fixing #789. See #789 for details.
