### ISSUE TITLE
Enable container configuration using scripting with IronPython (DLR).

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#325]
_From [Petar.An...@gmail.com](https://code.google.com/u/111257598610766743307/) on May 08, 2011 21:44:29_

According to the discussion on the groups [ https://groups.google.com/d/topic/autofac/JMUEVdPoEHs/discussion ] I've created a server repository clone "petarandrijasevic-scripting" with a new container builder extension and a new module. There are also several unit tests that also demonstrate the basic usage.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=325_

**Comment by tillig** [comment]
Given this was originally filed in 2011 and the DLR has come a long way, I'm going to close it and if someone encounters a challenge with using IronPython (the last version of which was, as of now, released in December 2014) or some other .NET-based script language, feel free to open a new issue.
