### ISSUE TITLE
Generic parameters constrained as generic interfaces fail to resolve.

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#330]
_From [Andy.Kut...@gmail.com](https://code.google.com/u/109219675264242751538/) on June 15, 2011 12:01:15_

What steps will reproduce the problem? Here is the situation with a failing test.

```
    public interface IConstraint<T> { }
    public class Constraint<T> : IConstraint<T> { }

    public interface IGenericConstraint<T1, T2> 
        where T2 : IConstraint<T1> 
    {
    }
    public class GenericConstraint<T1, T2> : IGenericConstraint<T1, T2> 
        where T2 : IConstraint<T1> 
    {
    }

    [Test]
    public void GenericConstraints()
    {
        var builder = new ContainerBuilder();

        builder.RegisterGeneric(typeof(Constraint<>))
            .AsImplementedInterfaces();

        builder.RegisterGeneric(typeof(GenericConstraint<,>))
            .AsImplementedInterfaces();

        var container = builder.Build();

        var target = container.Resolve<IGenericConstraint<int, IConstraint<int>>>();
    } What is the expected output? What do you see instead? This above should resolve just fine.  The problem is in ParameterCompatibleWithTypeConstraint in TypeExtensions.cs

    static bool ParameterCompatibleWithTypeConstraint(Type parameter, Type constraint)
    {
        return 
            constraint.IsAssignableFrom(parameter) ||
            (parameter.IsClass &&
               Traverse.Across(parameter, p => p.BaseType)
                   .Concat(parameter.GetInterfaces())
                   .Any(p => p.GUID == constraint.GUID));
    }
```

If the "parameter.IsClass" condition is removed and Traverse is allowed to execute then all works correctly.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=330_

**Comment by VolodymyrGladchenko** [comment]
Hi Alex, 
     I have same problem as describes here. Constraint where T : class 


 public interface IComponentsContext<T> where T : class
  {
    DbSet<T> Components { get; set; }
  }

 public class ComponentsContext<T> : DbContext, IComponentsContext<T> where T : class
  {
    public ComponentsContext()
    {
    }
    public DbSet<T> Components { get; set; }
  }

and registering :

builder.RegisterGeneric(typeof(IComponentsContext<>)).As(typeof(ComponentsContext<>));


Error message:
The service 'ComponentsContext`1' is not assignable from implementation type 'IComponentsContext`1[T]'.

Autofac 3.5.2 version

Can you please comment this issue ?

Thanks in advance
