### ISSUE TITLE
View injection doesn't work with Razor Layouts

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#349]
_From [pa...@pabich.eu](https://code.google.com/u/101214400026779515842/) on November 25, 2011 09:28:26_
1. Open solution in VS 2010
2. Run the app
3. It will blow up in _Layout.cshtml
4. Remove @Dependency.Now from _Layout.cshtml
5. Run the app again. Now it works and Dependency property in Index.cshtml is injected correctly.

It looks like Layout pages are created in a different way than regular pages and that's why dependencies are not injected.

**Attachment:** [AutofacPagesInjection.zip](http://code.google.com/p/autofac/issues/detail?id=349)

_Original issue: http://code.google.com/p/autofac/issues/detail?id=349_

**Comment by Serjster** [comment]
Wow :-1:  This seems like a terrible resolution to this problem! What if I need things like my `IOptions<AppSettings>` in my layout? Which I do....

**Comment by tillig** [comment]
I assume IOptions<AppSettings> is... an ASP.NET Core / MVC 6 construct? This issue is from 2013 - MVC 4, where you can't inject into Razor.

**Comment by Serjster** [comment]
I did get around this issue with using ViewComponents... http://docs.asp.net/projects/mvc/en/latest/views/view-components.html#intro so nm my last comment DI no longer needed in Layout files with ViewComponents.

**Comment by gregorylyons** [comment]
A (slightly) less unpleasant workaround here is:

```csharp
public abstract class InjectedBaseWebView : WebViewPage
{
	public IAmADependency Dependency { get; set; }

	/// <inheritdoc />
	public override void InitHelpers()
	{
		((AutofacDependencyResolver) DependencyResolver.Current).RequestLifetimeScope.InjectUnsetProperties(this);
		base.InitHelpers();
	}
}

//you have to have a generic version as well.
public abstract class InjectedBaseWebView<T> : WebViewPage<T>
{
	public IAmADependency Dependency { get; set; }

	/// <inheritdoc />
	public override void InitHelpers()
	{
		((AutofacDependencyResolver) DependencyResolver.Current).RequestLifetimeScope.InjectUnsetProperties(this);
		base.InitHelpers();
	}
}
```
and in `~\Views\web.config`, alter the pageBaseType to match the type created above (remember to add the correct namespaces etc)
```xml
<pages pageBaseType="InjectedBaseWebView">
```
and in your layout files, you will be able to access the dependencies much like any other helper, simply `@Dependency` to get access to your injected dependency. Not a perfect solution, but fairly clean and maintainable.
