### ISSUE TITLE
Support configuration reading from XML file that is not app.config

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#386]
_From [estrada.raphael](https://code.google.com/u/estrada.raphael/) on August 21, 2012 23:55:04_

What steps will reproduce the problem? 1. Call ctor of ConfigurationSettingsReader
2. Pass custom xml file (see below) as file paramter
3. Autofac complains that it cannot find the section

I would like to see a SettingsReader that can read custom XML (just a plain vanilla autofac section, no app.config specific schema) to configure autofac. What version of Autofac are you using? On what version of .NET/Silverlight? .NET 4.0, version 2.6.3.862

I suggest providing an XmlSettingsReader that does not look for a specific section, but just reads the entire file into a SectionHandler. Given some restrictive accessors (internal types, private _sectionHandler field on ConfigurationSettingsReader) it's tough for me to do this in my own project/namespace (I need to use vanilla autofac binaries for various reasons). 
I tried to derive from ConfigurationSettingsReader, it seems if I managed to deserialize the SectionHandler (tricky since ConfigurationManager is coupled to app.config...) and assign the _sectionHandler via reflection. My main issues were the deserialization part. It's probably much easier for you guys.

the schema of the file I'd like to load contians only autofac info, nothing with regards to app.config (i.e. no <configuration> root, and no <configSections>)

// autofac.config
<autofac>
  <modules>
  ...
  </modules>
  
</autofac>

If I find some down time I'll see if I can do it myself and submit a patch, but it would be great if you guys could do this.

Thanks for the excellent tool!

_Original issue: http://code.google.com/p/autofac/issues/detail?id=386_

**Comment by kbrow20** [comment]
Is the XMLFileReader class been depreciated? I can't seem to find it any longer.

**Comment by tillig** [comment]
[Read the docs.](https://autofac.readthedocs.io/en/latest/configuration/xml.html)

**Comment by kbrow20** [comment]
Ok so you want this now?

builder.RegisterModule(new ConfigurationModule(new ConfigurationBuilder()
                .AddXmlFile(Path.Combine(BinaryPath, $"{ApplicationName}.config"))
                .Build()));
