### ISSUE TITLE
AutofacDependencyResolver.Current Only Works in Request Lifetime

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#400]
_From [travis.illig](https://code.google.com/u/travis.illig/) on January 08, 2013 07:05:27_

To fix issue 351 AutofacDependencyResolver.Current was fixed to be

DependencyResolver.Current.GetService<AutofacDependencyResolver>()

To get the instance of the resolver into the DependencyResolver, a registration is added on the fly during the creation of the RequestLifetimeScope:

builder.RegisterInstance(this).AsSelf();

However, this creates a circular dependency for components that execute BEFORE the request lifetime is instantiated by a call to DependencyResolver.Current.GetService<T>().

For example, if you have a component that executes AutofacDependencyResolver.Current.RequestLifetimeScope during a request but BEFORE DR.C.GetService is called, an exception will happen because AutofacDependencyResolver.Current is null - the on-the-fly registration hasn't happened because it happens during RequestLifetimeScope.

To illustrate how this might work in a unit test, first create a simple request lifetime scope provider that isn't tied to the actual request:

public class SimpleLifetimeScopeProvider : ILifetimeScopeProvider
{
  private readonly IContainer _container;
  private ILifetimeScope _scope;

  public SimpleLifetimeScopeProvider(IContainer container)
  {
    if (container == null)
    {
      throw new ArgumentNullException("container");
    }
    this._container = container;
  }

  public ILifetimeScope ApplicationContainer
  {
    get { return this._container; }
  }

  public void EndLifetimeScope()
  {
    if (this._scope != null)
    {
      this._scope.Dispose();
      this._scope = null;
    }
  }

  public ILifetimeScope GetLifetimeScope(Action<ContainerBuilder> configurationAction)
  {
    if (this._scope == null)
    {
      this._scope = (configurationAction == null)
             ? this.ApplicationContainer.BeginLifetimeScope("AutofacWebRequest")
             : this.ApplicationContainer.BeginLifetimeScope("AutofacWebRequest", configurationAction);
    }
    return this._scope;
  }
}

Then create a new AutofacDependencyResolver with that lifetime scope provider:

DependencyResolver.SetResolver(
  new AutofacDependencyResolver(container,
    new SimpleLifetimeScopeProvider(container)));

Finally, try getting the request scope:

var scope = AutofacDependencyResolver.Current.RequestLifetimeScope;

Technically this SHOULD instantiate the lifetime scope on the first request, but instead AutofacDependencyResolver.Current comes back null.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=400_

**Comment by Seabizkit** [comment]
can someone point me in the right direction, how do you scope DependencyResolver.Current, inother words you want to set a new scope on the service your requesting .Current.GetService<ABC>, where ABC is the instance you want, but you want to modify its scope and creation differently from when it was registered. cant seem to find info around this.

**Comment by alexmg** [comment]
Hi @Seabizkit. I am not able to fully understanding what is being asked here. Are you able to provide some more information or some example code?
