### ISSUE TITLE
Consider using HTTP request based lifetime scopes in SignalR, much like MVC

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#403]
_From [byte...@bytenik.com](https://code.google.com/u/102070836245977043942/) on February 03, 2013 23:56:21_

https://github.com/bytenik/Autofac.Integration.Mvc.SignalR If you do not like the SignalR dependency on the MVC library, consider abstracting the HTTP components from the MVC library into a core HTTP assembly and referencing it from both.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=403_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.SignalR#3
