### ISSUE TITLE
Change IAutofacActionFilter and similar signatures to Task instead of void.

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#411]
_From [felipe.l...@gmail.com](https://code.google.com/u/110206905596210921470/) on February 28, 2013 13:06:35_

What steps will reproduce the problem?
  1. Create and implementation of IAutofacActionFilter
  2. On the implementation of OnActionExecuting decorate it with async
  3. Create a test case for the OnActionExecuting method.
  4. The test completes because I cannot await a void method. What is the expected output? What do you see instead? If there is either an async version of IAutofacActionFilter or it returns a task testing would be possible. The code is behaving as expected I just can't write tests for it. What version of Autofac are you using? On what version of .NET/Silverlight? Autofac 3.0.0 Please provide any additional information below. I can`t use a common IActionFilter because of a requirement to use an component that is InstancePerApiRequest().

_Original issue: http://code.google.com/p/autofac/issues/detail?id=411_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#6
