### ISSUE TITLE
Enable WebAPI action filters to be applied based on predicate

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#439]
_From [travis.illig](https://code.google.com/u/travis.illig/) on May 29, 2013 04:38:55_

The idea is to enable additional configuration of when a filter applies to a controller by allowing use of a lambda predicate during registration.

builder....AsWebApiActionFilter(
  methodInfo => methodInfo.DeclaringType.Namespace.Contains(".Foo") &&
  methodInfo.GetAttribute<BarAttribute>() != null)

Code/discussion here: https://groups.google.com/forum/?fromgroups#!msg/autofac/S2ia55LBqXo/ZnPNvb3UVyMJ

_Original issue: http://code.google.com/p/autofac/issues/detail?id=439_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#9
