### ISSUE TITLE
Autofac integration with WebApi 5RC1 raises TypeLoadException

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#453]
_From [b...@sobenz.co.nz](https://code.google.com/u/112303485445644741087/) on August 05, 2013 14:00:32_

What steps will reproduce the problem? 1. Integrate the latest version of Autofac & the WebApi extension with the release candidate of the upcoming WebApi5 release.
2. Attempt to register any filter to the HttpSelfHostConfiguration via Autofac What is the expected output? What do you see instead? The problem is that the WebApi team have removed the AllowPartiallyTrustedCallers attribute from their assemblies which results in a TypeLoadException when Autofac tries to interact with the WebApi. What version of Autofac are you using? On what version of .NET/Silverlight? Autofac v3.1.1
Autofac for WebApi v3.1.0 Please provide any additional information below.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=453_

**Comment by ryanhmhco** [comment]
I may have just solved this two week old problem. We have a console app that is used as a WebJob on Azure. Azure puts the assemblies in the App_Data/jobs/triggered/{name} path of the WebApplication. So we have our build path for the console app set to that location. It appears that the console assemblies being in that location is causing this security issue with the Autofac MVC 5 library. I'm going to keep looking into this and see if I can reproduce on a simpler project and then put up in repo.
