### ISSUE TITLE
Add IAuthenticationFilter support for WebAPI

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#461]
_From [travis.illig](https://code.google.com/u/travis.illig/) on October 22, 2013 02:56:06_

ASP.NET WebAPI has added a new filter type - IAuthenticationFilter - to the system. Autofac should add support for this filter type.

Forum discussion here: https://groups.google.com/forum/#!topic/autofac/2ToYFB2RTOA

_Original issue: http://code.google.com/p/autofac/issues/detail?id=461_

**Comment by christopheblin** [comment]
Sorry to revive such an old thread but I think that documentation has not been updated accordingly : http://autofac.readthedocs.org/en/latest/integration/webapi.html?highlight=web%20api#provide-filters-via-dependency-injection only mention IAutofacActionFilter, IAutofacAuthorizationFilter and IAutofacExceptionFilter.

Should I create a new issue ?

**Comment by tillig** [comment]
We accept pull requests... hint hint... :)
