### ISSUE TITLE
Web API filters using actionSelectors not working properly with derived controllers

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#463]
_From [chaoaret...@gmail.com](https://code.google.com/u/105380078348205462773/) on October 25, 2013 01:59:28_

What steps will reproduce the problem? 1. An API controller with action methods
2. A derived API controller which is called based on the routing
3. An action filter registered using AsWebApiAuthorizationFilterFor<T> where T can be the base or derived controller and a lambda pointing to an action method that exists on this base controller What is the expected output? What do you see instead? Expect that the actionfilter will be called when accessing the resource, but it is not called. Please use labels and text to provide additional information. This is an odd case possibly related to some reflection being done by Autofac, this case only occurs if the action method exists in the base controller and is called via the derived controller but goes away if the method is marked as virtual (regardless of if the derived controller implements an override or not).

_Original issue: http://code.google.com/p/autofac/issues/detail?id=463_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#10
