### ISSUE TITLE
Empty Lists are create for types not registered in the container.

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#471]
_From [toddby...@gmail.com](https://code.google.com/u/104480275497024275866/) on November 13, 2013 11:58:15_

What steps will reproduce the problem? 1. Create an empty container
2. Call container.InjectProperties
3. dep1.List shouldn't be resolved as no types of Dep2 have been registered in the container. What is the expected output? What do you see instead? In 3.1.1 the attached code works as expected. In 3.1.3 the list gets set to an empty list What version of Autofac are you using? On what version of .NET/Silverlight? Version 3.1.1  & .net 4.5 Please provide any additional information below.

**Attachment:** [Program.cs](http://code.google.com/p/autofac/issues/detail?id=471)

_Original issue: http://code.google.com/p/autofac/issues/detail?id=471_

**Comment by nietras** [comment]
I seem to have hit this issue when resolving `Resolve<string[]>(key)` which returns empty array when no string or string arrays have been registered with the given key. That seems very unfortunate...
