### ISSUE TITLE
RegisterAdapter does not propagate keys or names from TFrom to TTo; and there is no way to do so

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#482]
_From [john.c...@gmail.com](https://code.google.com/u/110322464555689400022/) on January 09, 2014 10:58:34_

The attached xunit test case reproduces the problem.  I've also documented the problem and a workaround on stackoverflow: http://stackoverflow.com/questions/20985715/in-autofac-how-do-i-propagate-keys-through-adapters/21009633 What is the expected output? What do you see instead? I would expect that RegisterAdapter() propagates keys from TFrom to TTo; as it does propagate Metadata from TFrom to TTo.  It's possible that not doing so is a design decision, but I'm not able to figure out why. What version of Autofac are you using? On what version of .NET/Silverlight? Autofac 3.2.0 on .NET 4.5

_Original issue: http://code.google.com/p/autofac/issues/detail?id=482_

**Comment by johncrim** [comment]
Thank you for the work on this.  Poking my head in here as the creator of the issue/request.
