### ISSUE TITLE
RegisterWebApiModelBinders has no effect in Web API 2

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#484]
_From [tommyj...@gmail.com](https://code.google.com/u/100306272949457674127/) on January 20, 2014 00:15:41_

Registering Web API 2 model binders using the extension method `RegisterWebApiModelBinders` has no effect. It's missing the required metadata needed by `AutofacWebApiModelBinderProvider` to resolve the model binder.

Instead of using RegisterWebApiModelBinders, one can manually register the model binders, using:
`builder.RegisterType<RequestContextModelBinder>().AsModelBinderForTypes(typeof(RequestContext));`

Not sure if it is possible to make `RegisterWebApiModelBinders` work, otherwise it should probably be deprecated for Web API 2.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=484_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#8
