### ISSUE TITLE
Web Api application with Autofac and MEF, getting 404 error for api controllers in an external assembly.

### ISSUE THREAD

**Issue by jumuro** [autofac/Autofac#494]
Hello,

I'm developing a Web Api using Autofac and MEF with .NET Framework 4.5.

In the Web Api project I only have some api controllers, all services used in controllers are in their own assemblies.
They all use MEF ExportAttribute and ImportAttribute to use functionality in other modules.
All interfaces implemented by services are in a dll called Interfaces.dll and all modules reference to this assembly. No more references between modules are being used.

I have a module that implements some api controllers too. Api controllers in this module are being registered with builder.RegisterApicontrollers() and its MEF dependencies registered with builder.RegisterComposablePartCatalog(catalog).
I've debugged this class and confirm that all is being loaded correctly.

The problem is that I'm getting "404-Not Found" error for controllers in external assembly with the following message:

{"Message":"No HTTP resource was found that matches the request URI 'http://localhost:54904/api/Processor/ProcessRequest'.",
"MessageDetail":"No type was found that matches the controller named 'Processor'."}

Moving the external controllers to the main project works fine.

Below is my AutofacConfig class and the controller in the external assembly.

```
public static class AutofacConfig
{
    /// <summary>
    /// Register dependencies, sets up Autofac
    /// </summary>
    /// <param name="config"></param>
    public static void RegisterDependencies(HttpConfiguration config)
    {
        // Create the container builder.
        ContainerBuilder builder = new ContainerBuilder();

        // Register the Web API controllers in current assembly
        builder.RegisterApiControllers(Assembly.GetExecutingAssembly());

        // Register the Web API controllers in external assemblies (extensions)
        Assembly[] assemblies = new DirectoryInfo(ConfigurationManager.AppSettings[Resources.AppSettings.ExtensionsPath])
            .GetFiles("*.dll")
            .Select(r => Assembly.LoadFrom(r.FullName)).ToArray();

        builder.RegisterApiControllers(assemblies);

        // Register the Web API Filter Provider
        // To create an apis filter we need just to inherit from IAutofacActionFilter
        builder.RegisterWebApiFilterProvider(config);

        // Register MEF-exported and imported dependencies
        AggregateCatalog catalog = new AggregateCatalog();
        catalog.Catalogs.Add(new AssemblyCatalog(Assembly.GetExecutingAssembly()));
        catalog.Catalogs.Add(new DirectoryCatalog(ConfigurationManager.AppSettings[Resources.AppSettings.ExtensionsPath], "*.dll"));

        builder.RegisterComposablePartCatalog(catalog);

        // Build the container.
        IContainer container = builder.Build();

        // Create the depenedency resolver.
        AutofacWebApiDependencyResolver resolver = new AutofacWebApiDependencyResolver(container);

        // Configure Web API with the dependency resolver.
        config.DependencyResolver = resolver;
    }
}



[Export(typeof(IHttpController))]
[PartCreationPolicy(CreationPolicy.NonShared)]
public class ProcessorController : ApiController
{
    private readonly IProcessorService _processorService;

    [ImportingConstructor]
    public ProcessorController([Import(typeof(IProcessorService))]IProcessorService processorService)
    {
        _processorService = processorService;
    }

    [HttpPost]
    public PaymentResponse ProcessRequest(Foo fooInstance)
    {
        return _processorService.Process(fooInstance);
    }
}
```

Could you please give me a hand?
Many thanks in advance.

**Comment by GaneshSJ** [comment]
Hi, jumuro. Can you please let us know why this issue was closed? Was the issue resolved? Or was it reported incorrectly? I am also facing same issue.
