### ISSUE TITLE
I cant compile successfully.

### ISSUE THREAD

**Issue by liukuo362573** [autofac/Autofac#513]
I downloaded the source code zip file of Autofac ,my computer install VS 2012,I open Autofac.sln,then I compile project,but I can't compile successfully. Who can tell me why?

I found Reference of Autofac class libaray is empty.

**Comment by stratopost** [comment]
I just downloaded Autofac-developer & Autofac-master source as on today and unable to load / compile into visual studio 2013.
 Error as are as foloows:

![image](https://user-images.githubusercontent.com/17094744/27314731-2b169c00-5593-11e7-9ace-bd1dfacd8256.png)

![image](https://user-images.githubusercontent.com/17094744/27314767-682eb096-5593-11e7-8871-be36ea37a849.png)

![image](https://user-images.githubusercontent.com/17094744/27314792-853a9f56-5593-11e7-98f9-d457d327df2c.png)

**Comment by tillig** [comment]
This issue is three years old. We're on VS 2017 now.
