### ISSUE TITLE
RegisterDecorator does not play nicely when decorating items registered with .As<IFoo>() or with .AsImplementedInterfacs()

### ISSUE THREAD

**Issue by JonathanMaccollum** [autofac/Autofac#529]
Let’s say at container builder “build time” we wanted to use configuration to turn on or off a particular decorator.

Test structures:

```
    public interface IFoo
    {
    }
    public class Foo:IFoo
    {

    }
    public class FooDecorator : IFoo
    {
        private readonly IFoo _instance;

        public FooDecorator(IFoo instance)
        {
            if (instance == null) throw new ArgumentNullException("instance");
            _instance = instance;
        }
    }
```

Prior to using RegisterDecorator<IFoo> to accomplish this the code would look like this:

```
        bool turnDecoratorOn = true; // value from configuration
        var cb = new ContainerBuilder();
        cb.RegisterType<Foo>()
            .As<IFoo>() // this is the default implementation of IFoo to be used of the decoration is not enabled.
            .Named<IFoo>("Foo"); 
        if (turnDecoratorOn)
        {
            cb.RegisterType<FooDecorator>()
                .WithParameter(
                    (pi, ctx) => pi.ParameterType == typeof (IFoo),
                    (pi, ctx) => ctx.ResolveNamed<IFoo>("Foo")) // resolve the IFoo parameter with the one registered with name of 'Foo'
                .As<IFoo>();
        }
        using (var container = cb.Build())
        {
            var foo = container.Resolve<IFoo>();
            Assert.IsInstanceOfType(foo, typeof(FooDecorator));
        }
```

And if the config value had it turned off it would test successfully like this:

```
        bool turnDecoratorOn = false;
        var cb = new ContainerBuilder();
        cb.RegisterType<Foo>()
            .As<IFoo>() // this is the default implementation of IFoo to be used of the decoration is not enabled.
            .Named<IFoo>("Foo"); 
        if (turnDecoratorOn)
        {
            cb.RegisterType<FooDecorator>()
                .WithParameter(
                    (pi, ctx) => pi.ParameterType == typeof(IFoo),
                    (pi, ctx) => ctx.ResolveNamed<IFoo>("Foo"))
                .As<IFoo>();
        }
        using (var container = cb.Build())
        {
            var foo = container.Resolve<IFoo>();
            Assert.IsInstanceOfType(foo, typeof(Foo));
        }
```

The reason for this is because using the .As<IFoo>() or .AsImplementedInterfaces() sets up a ‘default value’ for anything that asks for IFoo unless it is over-written by additional registrations that occur on the containerbuilder afterwards.

However, in attempts to make this work with RegisterDecorator<T> my decorated component was not resolved and instead my default component was always resolved:

```
                 bool turnDecoratorOn = true;
        var cb = new ContainerBuilder();
        cb.RegisterType<Foo>()
            .As<IFoo>() // this is the default implementation of IFoo to be used of the decoration is not enabled.
            .Named<IFoo>("Foo"); 
        if (turnDecoratorOn)
        {
            cb.RegisterDecorator<IFoo>(
                instance => new FooDecorator(instance), "Foo")
                .As<IFoo>();
        }
        using (var container = cb.Build())
        {
            var foo = container.Resolve<IFoo>();
            Assert.IsInstanceOfType(foo, typeof(FooDecorator));
        }
```

Basically RegisterDecorator is not over-writing the default registration for the un-named type ‘IFoo’ even though we are registering our decorator it with the .As<IFoo>() statement.  

If we remove the .As<IFoo> from the default registration it works as expected when turnDecoratorOn is true 

```
                 bool turnDecoratorOn = true;
        var cb = new ContainerBuilder();
        cb.RegisterType<Foo>()
            .As<IFoo>() // this is the default implementation of IFoo to be used of the decoration is not enabled.
            .Named<IFoo>("Foo"); 
        if (turnDecoratorOn)
        {
            cb.RegisterDecorator<IFoo>(
                instance => new FooDecorator(instance), "Foo")
                .As<IFoo>();
        }
        using (var container = cb.Build())
        {
            var foo = container.Resolve<IFoo>();
            Assert.IsInstanceOfType(foo, typeof(FooDecorator));
        }
```

…however now it will not resolve when turnDecoratorOn is false, because IFoo by itself is never registered:

```
        bool turnDecoratorOn = false;
        var cb = new ContainerBuilder();
        cb.RegisterType<Foo>()
            .As<IFoo>() // this is the default implementation of IFoo to be used of the decoration is not enabled.
            .Named<IFoo>("Foo"); 
        if (turnDecoratorOn)
        {
            cb.RegisterDecorator<IFoo>(
                instance => new FooDecorator(instance), "Foo")
                .As<IFoo>();
        }
        using (var container = cb.Build())
        {
            var foo = container.Resolve<IFoo>();
            Assert.IsInstanceOfType(foo, typeof(Foo));
        }
```

**Comment by snboisen** [comment]
Now that #272 has been fixed, this issue should have gone away, right?
I'm currently using Autofac 4.2.1, but I still see this exact problem.

**Comment by tillig** [comment]
@snboisen Good point. We ran into this peripherally in #824. I'll reopen this and we can see what we can do. At a minimum, a failing unit test to be sure we don't regress this as it gets fixed.

**Comment by alexandrnikitin** [comment]
It's sad that the #541 fix (and its test) wasn't merged 😞 It's still actual by the way.
@tillig do you want me to rebase it?

**Comment by tillig** [comment]
@alexandrnikitin No, but it may be a starting point for the fix here. The `ComponentRegistry` class really shouldn't know special cases about specific registration sources like `LightweightAdapterRegistrationSource`. The fix really needs to allow for Liskov's substitution principle to work - all sources treated the same.

**Comment by alexandrnikitin** [comment]
@tillig Yeah, that fix doesn't look nice and follows just one principle to get things done 😄 
I'm sorry I don't follow Autofac development progress for a couple of years already. Some parts were changed as I see. I'll try to dive deeper on the weekend. Meanwhile a test #826

**Comment by tillig** [comment]
We're pushing to enhance decorator syntax and features, which will hopefully resolve this issue. I've created a larger meta-issue for tracking that at #880. In the meantime, I'll close this specific issue and hopefully we can handle everything at once.
