### ISSUE TITLE
Request scope is set twice when using Autofac.Integration.Mvc.Owin

### ISSUE THREAD

**Issue by rosslyn-benfoster** [autofac/Autofac#555]
Due to how MVC registers routes, the request scope is actually set twice the first time the application runs.

During route registration MVC invokes the dependency resolver to get an `IControllerFactory` instance which in turn creates the request scope using `RequestLifetimeHttpModule`. Then the middleware is invoked and a new request scope is set.

It's not a major issue but thought it was worth pointing out as it does mean the first scope will never be disposed.

I came across this whilst trying to implement a scope per request using Owin middleware *only*. Due to MVC invoking the dependency resolver so early on, it was throwing exceptions due to the Owin environment having not yet been initialized.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Mvc#5
