### ISSUE TITLE
Null Reference When Using RegisterWebApiFilterProvider and ODataController

### ISSUE THREAD

**Issue by agilbert201** [autofac/Autofac#561]
Using Autofac.WebApi2.3.3.0

Stack trace:

```
Autofac.Integration.WebApi.AutofacWebApiFilterProvider.GetFilters(HttpConfiguration configuration, HttpActionDescriptor actionDescriptor)\r\n at
System.Web.Http.Controllers.HttpActionDescriptor.b__0(IFilterProvider fp)\r\n at
System.Linq.Enumerable.d__14`2.MoveNext()\r\n at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n at
System.Linq.OrderedEnumerable`1.d__0.MoveNext()\r\n at     System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n
at System.Linq.Enumerable.d__a0`1.MoveNext()\r\n at
System.Web.Http.Controllers.HttpActionDescriptor.d__3.MoveNext()\r\n at
System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n at     System.Linq.Enumerable.d__a0`1.MoveNext()\r\n at
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at
System.Web.Http.Controllers.HttpActionDescriptor.InitializeFilterPipeline()\r\n at
System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at     System.Lazy`1.get_Value()\r\n at
System.Web.Http.Controllers.HttpActionDescriptor.GetFilterPipeline()\r\n at
System.Web.Http.Controllers.HttpActionDescriptor.GetFilterGrouping()\r\n at
System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n at
System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at
System.Web.Http.Dispatcher.HttpControllerDispatcher.d__0.MoveNext()" } } }
```

**Comment by robp-technotects** [comment]
FYI

I was having the same issue with the following package.config

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Autofac" version="3.5.2" targetFramework="net45" />
      <package id="Autofac.WebApi2" version="3.4.0" targetFramework="net45" />
      <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.OData" version="5.6.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
      <package id="Microsoft.OData.Core" version="6.11.0" targetFramework="net45" />
      <package id="Microsoft.OData.Edm" version="6.11.0" targetFramework="net45" />
      <package id="Microsoft.Spatial" version="6.11.0" targetFramework="net45" />
      <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net45" />
    </packages>

I had the autofac and OData httpconfiguration in 2 separate calls of GlobalConfiguration.Configure. The issue is the configuration.DependencyResolver is assigned a default resolver NOT the autofac resolver for oData request, works fine for WebApi. 

To resolve, I placed the Autofac and oData configuration into the same call. I do NOT trace why this happens ¯\_(ツ)_/¯.

**Comment by chinwobble** [comment]
What do you mean by placing them in the same call?

**Comment by robp-technotects** [comment]
use the same config reference 

```
config.MapHttpAttributeRoutes();

ConfigureOData.Execute(config);
ConfigureRoutes.Execute(config);
ConfigureAutofac.Execute(config);
```

I have not looked at this since 7/15, so I'm not sure if the same issue exists or has been resolved
