### ISSUE TITLE
Should UseAutofacMiddleware dispose container on OWIN shutdown?

### ISSUE THREAD

**Issue by chriseldredge** [autofac/Autofac#565]
I currently have this method in my OWIN Startup class:

```c#
protected virtual void RegisterShutdownCallback(IAppBuilder app, IContainer container)
{
    var context = new OwinContext(app.Properties);
    var token = context.Get<CancellationToken>("host.OnAppDisposing");

    if (token != CancellationToken.None)
    {
        token.Register(container.Dispose);
    }
}
```

My question is should UseAutofacMiddleware do this for me?

On the one hand, the `IContainer` instance is supplied externally, so there may be cases where the container should not be disposed simply because the OWIN app is shutting down.

On the other hand, the default behavior means that containers won't be disposed properly when a self-hosted app or IIS app shuts down. This can cause problems for containers that have services that need to clean up before the process exits.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi.Owin#1
