### ISSUE TITLE
Can not resolve the lifetimescope type in Application_EndRequest with Mvc 5 integration

### ISSUE THREAD

**Issue by liuhongbo** [autofac/Autofac#570]
This happen after upgrade to v3.3.3 

It will throw an exception 

```
Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
```

**Comment by vincentparrett** [comment]
I just hit this issue in my Application_Error handler, trying to show custom error pages with the correct response code. The worst part is I'm not trying to use the container directly, and have tried excluding my controller from registration - see [http://stackoverflow.com/questions/36001166/mvc-5-custom-error-pages-when-using-autofac](url) - so I'm between a rock and a hard place now.. I don't want to give up either autofac or custom error pages!

**Comment by vincentparrett** [comment]
BTW @kiwidev OWIN + MVC is not a corner case anymore, if you create a default mvc application in VS2015 it comes with all the owin startup code pre-wired.

**Comment by vincentparrett** [comment]
I just solved this by realising mvc was trying to resolve the modelbinder, but making my controller action methods parameterless stopped it from trying that.. problem solved.

**Comment by DaleyKD** [comment]
3 years later... what is the solution to using Autofac with a global exception handler in an MVC app?
