### ISSUE TITLE
Factory Methods and InstancePerLifetimeScope Question

### ISSUE THREAD

**Issue by michael-x** [autofac/Autofac#585]
I have a question regarding factory methods and InstancePerLifetimeScope (or similarly restricting scopes).

I do understand that:
- I can pass parameters to a constructor through delegate or Func<> factory methods.
- InstancePerLifetimeScope is supposed to return one and only one instance of a type per lifetime scope.

Unfortunately using the two features together is a little counterintuitive (even if it is correct): Invoking the factory method with two different sets of parameters within the same lifetime scope **does not** create an instance each, initialized with the respective parameters (as expected from a factory method). Instead the second invocation returns the first instance (as expected from the InstancePerLifetimeScope).

Is there an easy way to get one instance per lifetime scope **and set of parameters** when resolving instances through a factory method?

As a workaround I can register the type as InstancePerDependency and then write a factory/cache class that is registered as InstancePerLifetimeScope. I know that there may be better solutions to the problem in terms of design, but these would require significant refactoring (e.g. passing the parameters to the methods of the class, not the constructor) and I would loose context.

**Comment by nsgaga** [comment]
Hi, just wanted to add my thoughts on this one - this feature is highly unintuitive to say the least. And it gets even more so if using lambda style registrations.  
e.g. I had a lambda registration for the instance (e.g. MyService with .InstancePerMatching...) - and inside of that I've tried to use the MyService.Factory.  
I was getting all sorts of weird results, the factory wasn't instantiating (like you both agreed above) but still parameters were sort of injected - even though I had no property injection going on (just DI at the .ctor level).  
Once I debugged that, I've started looking and found this post - and consequently I've removed the factory all together, it just couldn't work together.
My understanding was that the Factory itself shouldn't follow the lifetime of the component/instance registration, simply if you're using Factory you kind of want a new instance. But I can see how things could be tricky when designing such thing and that kind of depends on the usage.
Just wanted to add my experience on this one.
