### ISSUE TITLE
Release notes on nuget.org

### ISSUE THREAD

**Issue by pawelpabich** [autofac/Autofac#590]
Hi,

Would it be possible to add release notes to nuget?

Thanks

Pawle

**Comment by tillig** [comment]
For the last few releases we've been doing this by modifying the settings in MyGet prior to pushing to NuGet. Now that we're into .NET Core support, this means either continuing to do that or modifying the `packOptions.releaseNotes` property in `project.json`. It would be nice to have a more automated way to handle it.

**Comment by tillig** [comment]
Looking more at this, I'm thinking we probably need to put a link in the NuGet release notes and actually change our release process to use the GitHub "releases" feature, which is where the notes would be (instead of the wiki, like they are now). I'm not really looking for more manual copy/paste work to make releases harder, and given some folks (e.g., China) may not be able to get to NuGet, centralizing on GitHub releases makes sense.

**Comment by tillig** [comment]
I'm going to use this as the item to track the "Add release notes to project.json/nuspec files to point to the wiki release note pages for each package" item from #594.

The full answer to this is to update the packages to point to the Autofac releases (on the respective repository) and use the releases feature both as a way to publish release notes as well as an alternate download mechanism for folks that can't get to nuget.org.

**Comment by tillig** [comment]
Releases have been published for (and project.json/nuspec is updated on)...

- [x] Autofac
- [x] Autofac.Configuration
- [ ] Autofac.Extensions.DependencyInjection
- [ ] Autofac.Extras.AggregateService
- [ ] Autofac.Extras.AttributeMetadata
- [ ] Autofac.Extras.CommonServiceLocator
- [ ] Autofac.Extras.DomainServices
- [ ] Autofac.Extras.DynamicProxy
- [ ] Autofac.Extras.EnterpriseLibraryConfigurator
- [ ] Autofac.Extras.FakeItEasy
- [ ] Autofac.Extras.Moq
- [ ] Autofac.Extras.MvvmCross
- [ ] Autofac.Extras.NHibernate
- [ ] Autofac.Mef
- [ ] Autofac.Multitenant
- [ ] Autofac.Multitenant.Wcf
- [ ] Autofac.Mvc
- [ ] Autofac.Mvc.Owin
- [ ] Autofac.Owin
- [ ] Autofac.SignalR
- [ ] Autofac.Wcf
- [ ] Autofac.Web
- [ ] Autofac.WebApi
- [ ] Autofac.WebApi.Owin

This doesn't necessarily imply that the current _public/published_ version has that out there, but this should be seen on nuget.org when the next version goes out.

**Comment by tillig** [comment]
I've created releases, including retroactive releases, as best as I can given the move from Google Code to GitHub, splitting things from a single giant repo into multiple repos, etc. Going forward if we keep releases going on individual repo sites, the release notes link that appears in NuGet should point to the right spot and get people the info they need.

I'm unaware of tooling that will automatically generate a clean, reliable set of release notes (our commit messages aren't always clean and we don't do "revisionist history" to squash commits and such) so the notes themselves will, for the foreseeable future, be generated by hand. There's not a great way to automate the changing of the contents of the .nuspec or project.json file to include that information so, at least for now, a link will have to suffice.
