### ISSUE TITLE
From NuGet package to source

### ISSUE THREAD

**Issue by MircoBabin** [autofac/Autofac#599]
I installed in my project the following NuGet packages:

```
http://autofac.org/
  Autofac - v<3.5.2>
  Autofac.Owin - v<3.1.0>
  Autofac.SignalR2 - v<3.1.0>
  Autofac.WebApi2 - v<3.4.0>
  Autofac.WebApi2.Owin - v<3.2.0>
```

How do I find the matching sources ?

I looked into branches, into tags, into releases, but I could not find anything on GitHub which refers to a NuGet Package release. Where can I find the sources for above versions ?

**Comment by MircoBabin** [comment]
# Usage
Actually I'm looking for archiving. When we deploy our product depending on Autofac, we archive the sources, binaries, everything, preferably also third party sources like Autofac. 

Because our product can have a really long lifecycle (years) of bugfixing it's important to store everything that might be needed to fix those bugs. And a bug could surface in the future (say over 3 years) in Autofac (I'm not saying Autofac is bad, just sketching the scenario). Because our product is then 3 years old and Autofac probably continued developing, just integrating the latest Autofac version might not always be the right choice. And we might ending up modifying the "old" version of Autofac ... if we have the sources ...

# Symbolsource
I just looked at  http://www.symbolsource.org. It's not clear to me how to download anything from that site. So I guess it can only be used for debugging purposes.

# Suggestion
As a suggestion for releases: The Autofac team could just when they release something (from the master branch ?) tag that commit. Give it a name representing the nuget package, e.g. "Autofac.WebApi2 3.4.0".

And adjust the build system, to also be able to build just **one** package. This way I could checkout the specific commit and just build the Webapi2 package.

The problem arises because the Webapi2 package depends on Autofac 3.5.2. And Autofac version 3.5.2 would not be in that specific Webapi2 release commit, but in another commit.

Maybe the best way forward is to split the project. Have the Autofac core as a separate repository. And have each extension (Webapi, SignalR, Owin) also in a seperate repository. Each Autofac Nuget package would have it's own repository. You could then release tag each repository.

But splitting up one repository with buildsystem and testunits into multiple repositories is a lot of work. And it influences the way the autofac contributors must develop. Changing a development workflow is not easy.

These are just my thoughts on release tagging. Maybe you have some use for it.

# Autofac Nuget dependency tree
```
  -------------------
  Autofac - v<3.5.2>
  http://autofac.org/
  -------------------

    --- Used by (requirement for package) ---
    Autofac.Owin - v<3.1.0>
    Autofac.SignalR2 - v<3.1.0>
    Autofac.WebApi2 - v<3.4.0>
    Autofac.WebApi2.Owin - v<3.2.0>

    --- Files ---
    Autofac.dll
    Autofac.xml

  -----------------------
  Autofac.Owin - v<3.1.0>
  http://autofac.org/
  -----------------------

    --- Uses (recursive dependencies) ---
    Autofac - v<3.5.2>
    Microsoft.Owin - v<3.0.1>
      Owin - v<1.0>

    --- Uses (unique recursive dependency list) ---
    Autofac - v<3.5.2>
    Microsoft.Owin - v<3.0.1>
    Owin - v<1.0>

    --- Used by (requirement for package) ---
    Autofac.WebApi2.Owin - v<3.2.0>

    --- Files ---
    Autofac.Integration.Owin.dll
    Autofac.Integration.Owin.xml

  ---------------------------
  Autofac.SignalR2 - v<3.1.0>
  http://autofac.org/
  ---------------------------

    --- Uses (recursive dependencies) ---
    Autofac - v<3.5.2>
    Microsoft.AspNet.SignalR.Core - v<2.2.0>
      Newtonsoft.Json - v<6.0.6>
      Owin - v<1.0>
      Microsoft.Owin - v<3.0.1>
        Owin - v<1.0>
      Microsoft.Owin.Security - v<3.0.1>
        Owin - v<1.0>
        Microsoft.Owin - v<3.0.1>
          Owin - v<1.0>

    --- Uses (unique recursive dependency list) ---
    Autofac - v<3.5.2>
    Microsoft.AspNet.SignalR.Core - v<2.2.0>
    Microsoft.Owin - v<3.0.1>
    Microsoft.Owin.Security - v<3.0.1>
    Newtonsoft.Json - v<6.0.6>
    Owin - v<1.0>

    --- Files ---
    Autofac.Integration.SignalR.dll
    Autofac.Integration.SignalR.xml

  --------------------------
  Autofac.WebApi2 - v<3.4.0>
  http://autofac.org/
  --------------------------

    --- Uses (recursive dependencies) ---
    Autofac - v<3.5.2>
    Microsoft.AspNet.WebApi.Core - v<5.2.3>
      Microsoft.AspNet.WebApi.Client - v<5.2.3>
        Newtonsoft.Json - v<6.0.6>

    --- Uses (unique recursive dependency list) ---
    Autofac - v<3.5.2>
    Microsoft.AspNet.WebApi.Client - v<5.2.3>
    Microsoft.AspNet.WebApi.Core - v<5.2.3>
    Newtonsoft.Json - v<6.0.6>

    --- Used by (requirement for package) ---
    Autofac.WebApi2.Owin - v<3.2.0>

    --- Files ---
    Autofac.Integration.WebApi.dll
    Autofac.Integration.WebApi.xml

  -------------------------------
  Autofac.WebApi2.Owin - v<3.2.0>
  http://autofac.org/
  -------------------------------

    --- Uses (recursive dependencies) ---
    Autofac - v<3.5.2>
    Autofac.WebApi2 - v<3.4.0>
      Autofac - v<3.5.2>
      Microsoft.AspNet.WebApi.Core - v<5.2.3>
        Microsoft.AspNet.WebApi.Client - v<5.2.3>
          Newtonsoft.Json - v<6.0.6>
    Autofac.Owin - v<3.1.0>
      Autofac - v<3.5.2>
      Microsoft.Owin - v<3.0.1>
        Owin - v<1.0>

    --- Uses (unique recursive dependency list) ---
    Autofac - v<3.5.2>
    Autofac.Owin - v<3.1.0>
    Autofac.WebApi2 - v<3.4.0>
    Microsoft.AspNet.WebApi.Client - v<5.2.3>
    Microsoft.AspNet.WebApi.Core - v<5.2.3>
    Microsoft.Owin - v<3.0.1>
    Newtonsoft.Json - v<6.0.6>
    Owin - v<1.0>

    --- Files ---
    Autofac.Integration.WebApi.Owin.dll
    Autofac.Integration.WebApi.Owin.xml
```

**Comment by tillig** [comment]
Since November 2014 when this was opened we've split the various packages into their own repos and we are tagging releases. There is no plan to go back and try to retroactively tag old releases, so for old/untagged releases, you're on your own. Going forward, check for tags in the appropriate repo.

We are also looking at supporting [the `dnu sources get` command](https://github.com/aspnet/Announcements/issues/46) which may help in your scenario.

If you have further questions or comments on this, a good place to discuss it is our [discussion forum](https://groups.google.com/forum/#forum/autofac). I'd recommend continuing any discussion over there. Thanks!
