### ISSUE TITLE
Allow ModelBinding resolution to work with subclasses

### ISSUE THREAD

**Issue by mmiller678** [autofac/Autofac#603]
I can't get the Autofac model binding for MVC to work with subclasses - which I think is the intended behavior. The current Autofac model bind provider matches on exact type like the built in MVC one does.  

Ideally it would be nice if the model binder could be registered to say I want to be used with the any subclasses that implement the specified type - i.e.

Ideally I would like to do something like this:

builder.RegisterType<EntityModelBinder>()
           .AsModelBinderForTypesAndSubclasses(typeof(IEntity))
           .PropertiesAutowired();
builder.RegisterModelBinderProvider();

autofacModelBinderProvider.GetBinder(typeof(EntityImplementation)) would return EntityModelBinder

Is there a way to do this in the current implementation?  My current solution is to create my own provider and resolve the binders thru the dependency resolver, but I would prefer to use a purely Autofac solution if possible.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Mvc#4
