### ISSUE TITLE
Register generic type of model binder

### ISSUE THREAD

**Issue by TerraVenil** [autofac/Autofac#612]
I can't get the Autofac model binding for MVC to work with generic model binder and I think it should be enhanced. For example, in MVC I can write

`public class SomeBinder<T> : IModelBinder {}`

`public ActionResult Update([ModelBinder(typeof(SomeBinder<List<SomeClassA>>))]List<SomeClassA> parameters)`
and also register through global model binders as

`ModelBinder.Binders.Add(typeof(List<SomeClassA>), new SomeBinder<List<SomeClassA>());`

now update method look like

`public ActionResult Update(List<SomeClassA> parameters)`

and all works fine. But if I am trying to do the same things through Autofac, remove global initialization and use ModelBinderType attribute 

`[ModelBinderType(typeof(List<SomeClassC>))]`
`[ModelBinderType(typeof(List<SomeClassB>))]`
`[ModelBinderType(typeof(List<SomeClassA>))]`
`public class SomeBinder<T> : IModelBinder {}`

and register it when container is build

`builder.RegisterModelBinders(Assembly.GetExecutingAssembly());
builder.RegisterModelBinderProvider();`

but unfortunately Autofac doesn't intercepting http request to controller and not injecting model binder. I find some workaround using generic model binder through inheritance like that

`[ModelBinderType(typeof(List<SomeClassA>))]`
`public class SomeListClassABinder : SomeModelBinder<List<ClassA>>`

but as from my point of view it's not very elegant solution. Why Autofac can't resolve type T? As we already have that type T inside model binder type attribute `typeof(List<SomeClassA>)`?

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Mvc#3
