### ISSUE TITLE
Autofac + WebApi integration problem. Double instantiation of InstancePerLifetimeScope dependency.

### ISSUE THREAD

**Issue by VKrol** [autofac/Autofac#614]
Hi!

I have found an issue with WebApi integration. Sample project: https://github.com/VKrol/WebApplication19
Try to create a request to the "~/api/values", class Foo has been instantiated twice despite the fact that class Foo has been registered as InstancePerLifetimeScope. Please note that I resolve first instance in the Application_AcquireRequestState and the second has been injected in the ValuesController constructor.
I think that this is a bug.

Thanks.

I use the latest versions of Autofac packages:

Package | Version
------------ | -------------
Autofac | 3.5.2
Autofac.WebApi2 | 3.4.0

**Comment by tillig** [comment]
It appears you opened [a question on StackOverflow here](http://stackoverflow.com/questions/27946092/autofac-webapi-double-instantiation-of-instanceperlifetimescope-dependency) - which is the preferred mechanism for asking questions - so we'll let that be the system of record for this one and respond over there. If a bug is discovered, we can create a new, more specific issue to address.

**Comment by VKrol** [comment]
I have not received the answer on the Stackoverflow. And I think that there is the bug.

**Comment by tillig** [comment]
[Answered on SO.](http://stackoverflow.com/questions/27946092/autofac-webapi-double-instantiation-of-instanceperlifetimescope-dependency/28031761#28031761)
