### ISSUE TITLE
Thread safety issue with ComponentRegistration metadata

### ISSUE THREAD

**Issue by cyrildurand** [autofac/Autofac#615]
Hi, 

while watching at source code I noticed that ComponentRegistration use a Dictionary<,> to persist Metadata. If multiple concurrent threads access the dictionary, a thread safe issue may appear on some really rare case. 

Should not ComponentRegistration use a ConcurrentDictionary instead of Dictionary ?

Cyril DURAND

**Comment by tillig** [comment]
The only time the dictionary is accessed from a write perspective is when the container is built, which is a single-threaded operation. If, hypothetically, the metadata is read from multiple threads, I'm not sure that'd be an issue.

Hypothetically, in the most edge of edge cases, you could write a fairly low-level plugin that somehow pokes in metadata after the fact, but if you're working on things at that level _and_ you're doing it multithreaded... well, I guess I'd like to hope that you know what you're doing then. :)

We do [have some documentation on thread safety and handling concurrency](http://autofac.readthedocs.org/en/latest/advanced/concurrency.html) that might help you if you're curious what is supported as thread safe and what is specifically known to not be thread safe. Maybe that will help you out.

**Comment by cyrildurand** [comment]
Thanks for your reply.

I agree with you that this is not a common case but my application may have the problem.

My application allow the user to choose the implementation that the application should use. Le't say I have an IFoo interface and many implementation of IFoo. The user may change the implementation of IFoo using a a dropdownlist. 
I use meta to do this. My default registration look like this `builder.RegisterType<Foo1>().As<IFoo>().WithMetadata("Current", true);` and the user can change the current implementation by modifying the meta : `container.ComponentRegistry.RegistrationsFor(new TypedService(typeof(IFoo))).Where(...).Metadata["Current"] = true;`

I have been able to reproduce an issue with a small piece of code : 

```CSharp
    interface IFoo
    { }

    class Foo1 : IFoo { }
    class Foo2 : IFoo { }
    class Foo3 : IFoo { }
    class Foo4 : IFoo { }

    class Bar
    {
        public Bar([WithMetadata("Current", true)]IFoo foo)
        {
            this._foo = foo;
        }

        private readonly IFoo _foo;
        public IFoo Foo
        {
            get
            {
                return this._foo;
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ContainerBuilder builder = new ContainerBuilder();
            builder.RegisterType<Foo1>().As<IFoo>().WithMetadata("Current", true);
            builder.RegisterType<Foo2>().As<IFoo>().WithMetadata("Current", false);
            builder.RegisterType<Foo3>().As<IFoo>().WithMetadata("Current", false);
            builder.RegisterType<Foo4>().As<IFoo>().WithMetadata("Current", false);
            builder.RegisterType<Bar>().AsSelf().WithAttributeFilter();
            IContainer container = builder.Build();

            Task uiThread = Task.Run(() =>
            {
                try
                {
                    Int32 i = 0;
                    Type[] types = new Type[] { typeof(Foo1), typeof(Foo2), typeof(Foo3), typeof(Foo4) };
                    IEnumerable<IComponentRegistration> registrations = container.ComponentRegistry.RegistrationsFor(new TypedService(typeof(IFoo)));
                    while (true)
                    {
                        Type type = types[i++ % types.Length];

                        // set the new current to always have at least one current
                        registrations.First(r => r.Activator.LimitType == type).Metadata["Current"] = true;
                        foreach (var registration in registrations.Where(r => r.Activator.LimitType != type))
                        {
                            registration.Metadata["Current"] = false;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            });


            Task runtimeThread = Task.Run(() =>
            {
                try
                {
                    while (true)
                    {
                        Bar bar = container.Resolve<Bar>();
                        if (bar.Foo == null)
                        {
                            Console.WriteLine("bar.Foo is null");
                        }
                        else
                        {
                            Console.WriteLine(bar.Foo.GetType());
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            });

            Task.WaitAll(uiThread, runtimeThread);
        }
    }

```

Sometimes bar.Foo is null but as I made this small application, I'm not sure that it is related to Metadatas not being thread safe.

**Comment by tillig** [comment]
Modifying the component registrations manually after the container is built isn't really a supported use case. It's kind of like... well, sort of like going in through reflection to change a private member variable on a class. Technically rather than using ConcurrentDictionary we should probably use a read-only dictionary so this sort of thing gets explicitly disallowed.

If you want to allow a user to choose an implementation, rather than switching the metadata from a Boolean, have multi-valued metadata (like an implementation ID) and resolve based on a fixed value. That means you need something other than the container metadata to synchronize on - like ASP.NET session (for a web app) or something else appropriate to your app - somewhere user selection information can be stored.

You also may need to switch from using the `[WithMetadata]` attribute on the constructor parameter to using Autofac parameters.

Here's an example of how it could be done using your sample code above:

```csharp
class Program
{
  static void Main()
  {
    var prefs = new UserPreferences();
    var builder = new ContainerBuilder();

    // The user preferences should be retrieved from wherever
    // they're stored when requested. For this example, it's just
    // a single instance.
    builder.Register(ctx => prefs).As<UserPreferences>();

    // Use a parameter rather than the metadata attribute
    // mechanism. More flexible, but less "drop-in-and-go."
    var fooParameter = new ResolvedParameter(
      // The parameter will handle any typed IFoo request.
      (pi, ctx) => pi.ParameterType == typeof(IFoo),

      // Dynamically resolve the value based on the user's prefs.
      (pi, ctx) => {
        // Get the user's selection info.
        var userPref = ctx.Resolve<UserPreferences>().Selection;

        // Find the one that matches the user's preference and only
        // actually resolve/instantiate that one. Default if the
        // user hasn't selected something valid or the system
        // has changed since last selection.
        var found = ctx
            .Resolve<IEnumerable<Meta<Lazy<IFoo>>>>()
            .Where(m => m.Metadata.ContainsKey("Selection") && m.Metadata["Selection"].Equals(userPref))
            .FirstOrDefault();
        if(found == null)
        {
          // User has no pref or an invalid pref.
          return ctx.Resolve<IFoo>();
        }
        else
        {
          // User has a valid preference.
          return found.Value.Value;
        }
      });

    builder.RegisterType<Foo1>().As<IFoo>().WithMetadata("Selection", 1);
    builder.RegisterType<Foo2>().As<IFoo>().WithMetadata("Selection", 2);
    builder.RegisterType<Foo3>().As<IFoo>().WithMetadata("Selection", 3);
    builder.RegisterType<Foo4>().As<IFoo>().WithMetadata("Selection", 4);
    builder.RegisterType<Bar>().AsSelf().WithParameter(fooParameter);
    var container = builder.Build();

    for(var i = 1; i <= 4; i++)
    {
      prefs.Selection = i;
      var bar = container.Resolve<Bar>();
      Console.WriteLine(bar.Foo.GetType().Name);
    }
  }
}

// Simple user preferences storage class.
// Other classes - Bar, Foo1 - Foo4, etc. all the same as the above sample.
class UserPreferences
{
  public int Selection { get; set; }
}
```

Regardless, I'd **strongly** recommend against tweaking the metadata post-registration. If you need to do that, then it'll be up to you to synchronize write access to it inside that `uiThread` you have up there.
