### ISSUE TITLE
Documentation error for OWIN Integration?

### ISSUE THREAD

**Issue by Hardrada** [autofac/Autofac#619]
Context: 
Autofac with WebAPI 2.x, OWIN

Location: Quickstart
Source text: 
 // OPTIONAL: Register the Autofac filter provider.
  builder.RegisterWebApiFilterProvider(config);

The documentation states that this line is optional for web api use, however, there is no statement that I can find that mentions it being _required_ when using OWIN. 

Without this included, the AUTHORIZE filters do not work. Is this an error/oversight in documentation?

**Comment by tillig** [comment]
You don't need to use the Autofac filter provider at all if you don't want to - not in OWIN, not in IIS.

If your authorization filters are Autofac filters, you do need the Autofac filter provider. If they are regular filters ([like the ones seen here](http://www.asp.net/web-api/overview/security/authentication-filters)) then they should just work.
