### ISSUE TITLE
Improve detail provided when throwing a DependencyResolutionException

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#621]
Include the details of the graph that failed to be resolved when throwing a DependencyResolutionException.

**Comment by tillig** [comment]
I added details on the exact registration to the exception thrown when a tagged lifetime scope isn't found. Looking at other locations where the exception is thrown, it appears a decent amount of detail is already included.

I'm going to close this one; if there are specific circumstances that need more detail, let's add new issues with information on those scenarios.
