### ISSUE TITLE
I can register a generic but cant never resolve for it

### ISSUE THREAD

**Issue by MrVermond** [autofac/Autofac#626]
public interface ITestMe<T>
    {
        T GetSome ();
    }

    public class Wicked<T1, T2> : ITestMe<T1> where T2 : class
    {
        public T1 GetSome ()
        {
            throw new System.NotImplementedException();
        }

        public T2 Halo ()
        {
            return null;
        }
    }

    public void main(){

        var builder = new ContainerBuilder();
            builder.RegisterGeneric(typeof(Wicked<,>)).As(typeof(ITestMe<>));
            var container = builder.Build();

            var scope = container.BeginLifetimeScope();

            var throwsException = scope .Resolve<ITestMe<object>>();
    }

**Comment by tillig** [comment]
You're not going to be able to resolve it because `Wicked<T1, T2>` needs two generics to be a concrete type but you're trying to resolve it as an `ITestMe<T1>` which only supplies the one generic type parameter. Basically, that's a `Wicked<T1, ???>` which isn't valid as a closed generic.

If you update the interface to have the proper number of generic parameters, it'll work.

    
    public interface ITestMe<T1, T2>
    {
      T1 GetSome();
    
      T2 Halo();
    }
    
    public class Wicked<T1, T2> : ITestMe<T1, T2> where T2 : class
    {
      public T1 GetSome()
      {
        throw new System.NotImplementedException();
      }
    
      public T2 Halo()
      {
        return null;
      }
    }
    
    void Main()
    {
      var builder = new ContainerBuilder();
      builder.RegisterGeneric(typeof(Wicked<,>)).As(typeof(ITestMe<,>));
      var container = builder.Build();
    
      var scope = container.BeginLifetimeScope();
    
      var obj = scope.Resolve<ITestMe<object, string>>();
      obj.GetSome();
    }

**Comment by MrVermond** [comment]
You are absolutely right. I was also aware of that fact. But i would expect a guidance from the framework that this use case does not make sense, maybe even right at the registration step.
