### ISSUE TITLE
Inheritance Security Rules Violated w/ Autofac & MVC5

### ISSUE THREAD

**Issue by ryanhmhco** [autofac/Autofac#627]
Autofac MVC5 Integration does not work with MVC5. I have searched the internet many times over and people are saying the issue is fixed using the RC1 version, etc.. etc.. It is not fixed at all. I have tried everything. Below is the error I am receiving:

Inheritance security rules violated while overriding member: 'Autofac.Integration.Mvc.AutofacDependencyResolver.GetService(System.Type)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

**Comment by tillig** [comment]
Can you provide us with more information about the environment in which you're working? For example, package versions (full four-digit version, not just "MVC 5") will help.

- Autofac version
- .NET version
- MVC version
- OS
- Visual Studio version

Additional questions:

- Do you have all the latest .NET patches on your machine?
- Did you change anything in your environment before finding this? For example, if it's an existing project, did you just update from one version of MVC to another?
- Do you have any binding redirects in your `web.config` file? What are they?
- Can you post a small reproduction somewhere we can look at?

It sounds like it may overlap with issue #453 from a couple years back. We have a lot of folks working on MVC 5 with Autofac so I'm sure we can help you find a solution.

**Comment by ryanhmhco** [comment]
Here is a copy of the packages I am using:

<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net451" />
  <package id="Autofac" version="3.5.2" targetFramework="net451" />
  <package id="Autofac.Mvc5" version="3.3.3" targetFramework="net451" />
  <package id="Autofac.Mvc5.Owin" version="3.1.0" targetFramework="net451" />
  <package id="Autofac.Owin" version="3.1.0" targetFramework="net451" />
  <package id="EntityFramework" version="6.1.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Identity.Owin" version="2.2.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Mvc" version="5.1.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Razor" version="3.1.0" targetFramework="net451" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebPages" version="3.1.0" targetFramework="net451" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.Facebook" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.Google" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.MicrosoftAccount" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.Twitter" version="3.0.1" targetFramework="net451" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" />
  <package id="Owin" version="1.0" targetFramework="net451" />
  <package id="WebGrease" version="1.6.0" targetFramework="net451" />
</packages>

**Comment by tillig** [comment]
Can you take any further updates? The current version of MVC is 5.2.3. The MVC you're using is well over a year old.

If you are stuck on MVC 5.1.0, you probably should try reverting Autofac.Mvc5 to the package that was available back then - which appears to be Autofac.Mvc5.3.1.0.

I honestly believe your issues will disappear if you do a package update and just take the latest version of all your dependencies.

**Comment by ryanhmhco** [comment]
I just updated the project to the following:

&lt;packages&gt;
  &lt;package id=&quot;Antlr&quot; version=&quot;3.4.1.9004&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Autofac&quot; version=&quot;3.5.2&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Autofac.Mvc5&quot; version=&quot;3.3.3&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Autofac.Mvc5.Owin&quot; version=&quot;3.1.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Autofac.Owin&quot; version=&quot;3.1.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;EntityFramework&quot; version=&quot;6.1.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Identity.Core&quot; version=&quot;2.2.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Identity.EntityFramework&quot; version=&quot;2.2.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Identity.Owin&quot; version=&quot;2.2.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Mvc&quot; version=&quot;5.2.3&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Razor&quot; version=&quot;3.2.3&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.Web.Optimization&quot; version=&quot;1.1.3&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.AspNet.WebPages&quot; version=&quot;3.2.3&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Host.SystemWeb&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.Cookies&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.Facebook&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.Google&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.MicrosoftAccount&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.OAuth&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Owin.Security.Twitter&quot; version=&quot;3.0.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Web.Infrastructure&quot; version=&quot;1.0.0.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Newtonsoft.Json&quot; version=&quot;6.0.8&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Owin&quot; version=&quot;1.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;WebGrease&quot; version=&quot;1.6.0&quot; targetFramework=&quot;net451&quot; /&gt;
&lt;/packages&gt;

The same issue is still present...

**Comment by tillig** [comment]
Please post a repro somewhere that we can check out. It's pretty hard to see what's wrong just from a packages.config file - it amounts to guessing what might be wrong and throwing a bunch of possible solutions at you rather than actually being able to dive in and help.

If you have literally taken all the possible package updates available _and_ you have all of the latest .NET patches on your machine then I don't really have any suggestions for you without being able to see a reproduction. Sorry.

**Comment by ryanhmhco** [comment]
This is what my Application_Start looks like:

        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

This is what my Auth.Start looks like:

        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                CookieName = "Sq.Auth",
                LoginPath = new PathString("/account/sign-up"),
                ExpireTimeSpan = TimeSpan.FromHours(1),
                SlidingExpiration = true,
                CookieSecure = CookieSecureOption.Never
            });
            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

            var builder = new ContainerBuilder();
            builder.Register(c => (new HttpContextWrapper(HttpContext.Current) as HttpContextBase))
                .As<HttpContextBase>()
                .InstancePerRequest();
            builder.Register(c => c.Resolve<HttpContextBase>().Request)
                .As<HttpRequestBase>()
                .InstancePerRequest();
            builder.Register(c => c.Resolve<HttpContextBase>().Response)
                .As<HttpResponseBase>()
                .InstancePerRequest();
            builder.Register(c => c.Resolve<HttpContextBase>().Server)
                .As<HttpServerUtilityBase>()
                .InstancePerRequest();
            builder.Register(c => c.Resolve<HttpContextBase>().Session)
                .As<HttpSessionStateBase>()
                .InstancePerRequest();

            builder.RegisterType<SqObjectContext>().As<IDbContext>().InstancePerRequest();
            builder.RegisterGeneric(typeof(EfRepository<>)).As(typeof(IRepository<>)).InstancePerRequest();

            builder.RegisterType<MemoryCacheManager>().As<ICacheManager>().Named<ICacheManager>("sq_cache_static").SingleInstance();
            builder.RegisterType<PerRequestCacheManager>().As<ICacheManager>().Named<ICacheManager>("sq_cache_per_request").InstancePerRequest();

            builder.RegisterType<DiscountService>().As<IDiscountService>().InstancePerRequest();
            builder.RegisterType<OrderTotalCalculationService>().As<IOrderTotalCalculationService>().InstancePerRequest();
            builder.RegisterType<WebJobLogService>().As<IWebJobLogService>().InstancePerRequest();

            builder.RegisterControllers(typeof(MvcApplication).Assembly);

            var container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));

            app.UseAutofacMiddleware(container);
            app.UseAutofacMvc();
   

            //if (FacebookSettings.FacebookAuthenticationEnabled)
            //{
            //    app.UseFacebookAuthentication(
            //       appId: FacebookSettings.FacebookAppId,
            //       appSecret: FacebookSettings.FacebookAppSecretCached);
            //}
        }

**Comment by tillig** [comment]
As mentioned, please post a full repro - a solution we can check out, fire up, build/run, and see the problem in action. That's the next step here for debugging.

**Comment by ryanhmhco** [comment]
Its not a project I post publicly. Let me create a new one from scratch and see if I can reproduce the issue. If I can, I will push that up to you. In the meantime, if you think of any gotchas, please let me know.

**Comment by ryanhmhco** [comment]
I may have just solved this two week old problem. We have a console app that is used as a WebJob on Azure. Azure puts the assemblies in the App_Data/jobs/triggered/{name} path of the WebApplication. So we have our build path for the console app set to that location. It appears that the console assemblies being in that location is causing this security issue with the Autofac MVC 5 library. I'm going to keep looking into this and see if I can reproduce on a simpler project and then put up in repo.

**Comment by ryanhmhco** [comment]
I can't reproduce the issue. Perhaps maybe that folder had an older version of something in it cause it wasn't properly cleaned by VS. I hope thats all it is. My mental state can't handle this coming back to haunt me. Thanks for your help anyways.

**Comment by mylove2010** [comment]
[Tour du lịch đà lạt 1 ngày](http://dulichdalat.biz/tour-da-lat/tour-du-lich-da-lat-1-ngay.html)
