### ISSUE TITLE
looks like 4.0.0-alpha1 has some bad references

### ISSUE THREAD

**Issue by david-peden-q2** [autofac/Autofac#629]
beta-22625 should be beta-22605

C:\src\web-api-skeleton\src\WebApi [master +0 ~1 -0]> kpm restore
Restoring packages for C:\src\web-api-skeleton\src\WebApi\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.Extensions'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ObjectModel'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections.Concurrent'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ComponentModel'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Diagnostics.Contracts'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Diagnostics.Debug'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Diagnostics.Tools'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Linq'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Linq.Expressions'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection.Extensions'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection.TypeExtensions'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Resources.ResourceManager'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Thread'
Resolving complete, 368ms elapsed
Unable to locate System.Collections >= 4.0.10-beta-22625
Unable to locate System.ComponentModel >= 4.0.0-beta-22625
Unable to locate System.Diagnostics.Contracts >= 4.0.0-beta-22625
Unable to locate System.Diagnostics.Debug >= 4.0.10-beta-22625
Unable to locate System.Diagnostics.Tools >= 4.0.0-beta-22625
Unable to locate System.Globalization >= 4.0.10-beta-22625
Unable to locate System.Linq >= 4.0.0-beta-22625
Unable to locate System.Linq.Expressions >= 4.0.0-beta-22625
Unable to locate System.Reflection >= 4.0.10-beta-22625
Unable to locate System.Reflection.Extensions >= 4.0.0-beta-22625
Unable to locate System.Reflection.TypeExtensions >= 4.0.0-beta-22625
Unable to locate System.Resources.ResourceManager >= 4.0.0-beta-22625
Unable to locate System.Runtime >= 4.0.20-beta-22625
Unable to locate System.Threading.Thread >= 4.0.0-beta-22625
Unable to locate System.Threading.Tasks >= 4.0.10-beta-22625
Restore complete, 403ms elapsed
C:\src\web-api-skeleton\src\WebApi [master +0 ~1 -0]>

**Comment by david-peden-q2** [comment]
I cloned Master and it does not appear to have this problem.

**Comment by davidpeden3** [comment]
To be clear, you can reproduce this issue by creating a brand new project and following the directions in your [blog post about 4.0.0-alpha1](http://alexmg.com/autofac-4-0-alpha-1-for-asp-net-5-0-beta-3/).

The following project.json:

```JSON
{
   "webroot":"wwwroot",
   "version":"1.0.0-*",
   "dependencies":{
      "Microsoft.AspNet.Server.IIS":"1.0.0-beta3",
      "Microsoft.AspNet.Mvc":"6.0.0-beta3",
      "Microsoft.AspNet.StaticFiles":"1.0.0-beta3",
      "Microsoft.AspNet.Server.WebListener":"1.0.0-beta3",
      "Autofac":"4.0.0-alpha1",
      "Autofac.Dnx":"4.0.0-alpha1"
   },
   "frameworks":{
      "aspnet50":{
      },
      "aspnetcore50":{
      }
   },
   "exclude":[
      "wwwroot",
      "node_modules",
      "bower_components"
   ],
   "bundleExclude":[
      "node_modules",
      "bower_components",
      "**.kproj",
      "**.user",
      "**.vspscc"
   ]
}
```

results in

![screen shot 2015-03-24 at 12 09 53 pm](https://cloud.githubusercontent.com/assets/1190710/6807796/afcfd1be-d21e-11e4-8846-23bb106c106b.png)

**Comment by davidpeden3** [comment]
Figured it out. My problem was a result of the default NuGet feed configuration with CTP 6 and a [bug that is fixed in beta4](https://github.com/aspnet/dnx/issues/1388). Here is the working nuget.config found in (%appdata%\NuGet\NuGet.Config) for anyone else that runs into this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageRestore>
		<add key="enabled" value="True" />
		<add key="automatic" value="True" />
	</packageRestore>
	<packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="ASP.NET Nightly Release" value="https://www.myget.org/F/aspnetrelease/api/v2/" />
    <add key="ASP.NET Nightly vNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="api.nuget.org" value="true" />
  </disabledPackageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
</configuration>
```

This issue can be closed.
