### ISSUE TITLE
Consider adding an "Up-For-Grabs" label to issues to help new contributers

### ISSUE THREAD

**Issue by chaitanyagurrapu** [autofac/Autofac#632]
I've found that the "up-for-grabs" or similar label for issues are ideal to help a developer familiarize themselves with the code base and start contributing. I would love to contribute to autofac and something similar would be great.

**Comment by tillig** [comment]
I think this is a reasonable thing to consider, though admittedly we don't run into a lot of things that aren't sort of... detailed and challenging. :)

Since there's nothing directly actionable here beyond acknowledging the intent, I'm going to go ahead and close this out.
