### ISSUE TITLE
AttributeUtil support for reflection only context

### ISSUE THREAD

**Issue by cherrydev** [autofac/Autofac#634]
AttributeUtil methods like .HasAttribute is useful for trying to determine if you want to REALLY load an assembly into the execution context when it's in the reflection only context, but you can't call GetCustomAttributes on a member of an reflection only assembly.
The workaround, at least for HasAttribute (which only determines if the member has the attribute but doesn't need to actually materialize it) is to use CustomAttributeData.GetCustomAttributes().
Obviously this won't work for any usage that requires the instance of the attribute itself.

**Comment by tillig** [comment]
A quick search through our repo and I couldn't find any `AttributeUtil` or `HasAttribute` references. Can you point specifically to the type/method(s) to which you're referring?

**Comment by cherrydev** [comment]
Doh.  That's part of Castle.Core, sorry!
