### ISSUE TITLE
NullReferenceException in ContainerProvider.AmbientRequestLifetime

### ISSUE THREAD

**Issue by michael-x** [autofac/Autofac#637]
We seem to be getting the following exception every once in a while during application pool recycle events:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Autofac.Integration.Web.ContainerProvider.get_AmbientRequestLifetime()
   at Autofac.Integration.Web.ContainerProvider.EndRequestLifetime()
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

The AmbientRequestLifetime getter tries to obtain an ILifetimeScope from the current request context and I'm wondering if there are any situations where there is no current request context yet/anymore.

The application is hosted on an IIS 8.5/WS 2012 R2. Around that time the application starts a second log-file which tells me that there seem to be two worker processes active at the same time. What I don't know is, whether this is because of the error above or whether the error above is caused by whatever caused the second worker process to be spawned while the first hasn't finished yet.

**Comment by tillig** [comment]
I hate to ask this, but could you file this over in [the Autofac.Web repo](https://github.com/autofac/Autofac.Web/issues)? We split things up a while back and this repo only has core stuff in it, though we didn't move issues that had been filed prior to the split. It would be better to track and solve issues new issues in the proper repo. Thanks!

**Comment by michael-x** [comment]
No problem. I thought about posting it there, but there were no previous issues and I saw other posts here tagged for Autofac.Web.
