### ISSUE TITLE
Logging Injector

### ISSUE THREAD

**Issue by piers7** [autofac/Autofac#644]
This isn't really an issue, but I put together a generic version of the logging injection module that's in the docs. Since it's generic, it no longer has any dependencies on log4net (or any logging framework), it's just a way of automatically resolving dependencies via a Type->dependency factory delegate. So my thoughts are that it might be handy in core Autofac library (given it's quite a common pattern).

https://gist.github.com/piers7/81724d51a7ca158d721e

Let me know if you are interested in me pushing a PR

**Comment by tillig** [comment]
Ooooh, I like that, it's pretty slick. It might be good to put it in an Extras package, though, rather than in core, so we can update it/add to it as needed without affecting core Autofac. Do you think that would make sense? Like an Autofac.Extras.Logging or something?

@alexmg, what's your take?

**Comment by alexmg** [comment]
I like it. Yeah, probably not a core feature but could be useful in an Extras package. I'm looking for an alternative to this PR too.

https://github.com/autofac/Autofac/pull/645

**Comment by sheastrickland** [comment]
Thanks @piers7, looks great, and like we were on a similar journey :)
We had similar (referenced PR), except with some added hooks for PropertyInjection in a legacy codebase.

**Comment by piers7** [comment]
@tillig *Personally* I'm not sold on creating additional packages (and hence nugets) without a compelling reason. Projects of any size already drown in a nuget soup, and I'd rather it didn't get worse for the sake of a handful of classes. Avoiding host-specific dependencies (Autofac.MVC etc...) for sure, but (for example) I don't see why Autofac.Config has to be separate, and I'd make the same argument here. Just for one thing, discoverability really suffers.
I totally understand the reluctance to go down paths that may lead to breaking changes in future, and avoid creeping bloat, but I look at my projects today and think: wow, that's a *lot* of assemblies.
Just my 2c.

**Comment by piers7** [comment]
@sheastrickland I did see your PR, but to be honest I didn't really grok what it was doing at the time. I'll take another look.

**Comment by sheastrickland** [comment]
@piers7, yeah I've added a lot more information and a gist to help.

**Comment by piers7** [comment]
@sheastrickland Right. I tried to extend my gist to handle log injection into properties also, and _finally_ understood what your PR is all about, and what you've had to do, and why. And that will be really helpful for use cases like this. I've made some other comments on the PR itself.

**Comment by piers7** [comment]
@tillig @alexmg  so do you still want a PR for this, and if so, where do you want it? If Autofac.Extras.Logging, I'm guessing you'll have to create the repository first...

(I'll be really happy when I don't have to keep cutting-and-pasting this into all my projects :-)

**Comment by tillig** [comment]
We will probably put this into another repo/package, so a PR here won't help... but all of our effort right now is going into Autofac 4.0.0 beta and supporting DNX using the new build and NuGet packaging semantics. Once we have Autofac core figured out, we still have to go through and update all of the dependent packages to verify they haven't broken and then update their compatibility information.

Which is to say - we are interested, though, unfortunately, it probably isn't happening really soon.

**Comment by tillig** [comment]
I think we're going to pass on adding a new package for the logging module. We're somewhat "at capacity" with the number of packages and integrations we're able to maintain.

If folks want this, we'd like to invite/encourage someone in the community to create it and own it. Perhaps it could be combined with the global property injection module mentioned in #382?
