### ISSUE TITLE
Autofac not working after update

### ISSUE THREAD

**Issue by usamasheikh** [autofac/Autofac#646]
Hi,

I've been trying to identify problem from 5 days, i've searched almost all forums on internet but couldn't find any solution. I'm using onion architecture with asp.net mvc, i've updated all pacakges to their latest version and after update of autofac to latest stable version my controller is giving this error: 
"no parameterless constructor defined for this object"

I've also posted this question on stackoverflow http://stackoverflow.com/questions/30818756/autofac-not-working-after-update

Please help me with this, please.

**Comment by tillig** [comment]
We monitor StackOverflow and that's a great place to post usage questions. Please try not to cross post.
