### ISSUE TITLE
RegisterHttpRequestMessage fails with Azure App Service Mobile App

### ISSUE THREAD

**Issue by Louliloul** [autofac/Autofac#649]
Hi !

I'm currently playing with Azure App Services Mobile App. I set up a basic solution in VS 2015 RC with Autofac as DI, and one of my dependencies requires the current HttpRequestMessage. So i used the extensions RegisterHttpRequestMessage in order to be able to inject it as needed. But the call to RegisterHttpRequestMessage produces the following exception:

Exception Details: System.TypeAccessException: Attempt by security transparent method 'Autofac.Integration.WebApi.RegistrationExtensions.RegisterHttpRequestMessage(Autofac.ContainerBuilder, System.Web.Http.HttpConfiguration)' to access security critical type 'System.Web.Http.HttpConfiguration' failed.

Assembly 'Autofac.Integration.WebApi, Version=3.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

As the call to RegisterHttpRequestMessage comes before the call to the concerned module, my controller instanciation fails. The second breakpoint below is never reached.
![image](https://cloud.githubusercontent.com/assets/7660709/8286395/7b47021e-1909-11e5-8219-3ce66e14dbad.png)

And when i try to access the service homepage, it tells that the service is unhealthy.
![image](https://cloud.githubusercontent.com/assets/7660709/8286191/70ada066-1908-11e5-9e2a-1a84be964123.png)

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#3
