### ISSUE TITLE
properties Auto wiring does not work with asp.net 5 

### ISSUE THREAD

**Issue by devmondo** [autofac/Autofac#653]
hi, 
i have a base controller and i dont want to use  constructor injection  so i tried below but it does not resolve the property, and yes i have ```IAsyncDocumentSession``` registered with Autofac and it works using constructor injection
```
builder.Register(c => new BaseController()).OnActivated(e =>
{
    e.Instance.dbSession= e.Context.Resolve<IAsyncDocumentSession>();
});
``` 
or this
```

builder.RegisterType<BaseController>()
       .PropertiesAutowired();
```
thanks in advanced.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Mvc#1
