### ISSUE TITLE
Update Autofac.Dnx to beta5

### ISSUE THREAD

**Issue by davidpeden3** [autofac/Autofac#654]
https://github.com/autofac/Autofac/blob/master/src/Autofac.Dnx/project.json#L12 needs to be updated to beta5.

There was a breaking change to rename *.Interfaces to *.Abstractions (https://github.com/aspnet/Announcements/issues/14) which makes 4.0.0-alpha2 incompatible with beta5 projects.

**Comment by tillig** [comment]
We've been keeping the NuGet package compatible with VS tooling to avoid confusion for folks reliant on that. The MyGet feed has our "develop" branch latest and we're already on beta 6. You might be interested in trying that.

https://www.myget.org/gallery/autofac

When VS has an update to support a later toolset and is nice and stable, we'll push to NuGet.

**Comment by davidpeden3** [comment]
Understood. I saw the dev branch but need to specifically target beta5. I'm just running a local build with the fix I needed for now. Thanks.

**Comment by davidpeden3** [comment]
I posted an unofficial [beta5 build on myget](https://www.myget.org/feed/Packages/autofac-dnx-beta5) with [permission](https://twitter.com/Confusion135/status/618799284226387968).

I changed the version to `4.0.0-alpha2-beta5` to disambiguate it from the authoritative builds.

**Comment by neutmute** [comment]
fyi @davidpeden3's link to his custom autofac dnx beta5 package has a typo, use https://www.myget.org/F/autofac-dnx-beta5/api/v2

**Comment by david-peden-q2** [comment]
Sorry for the confusion and thanks for posting the correct link to the feed. I unintentionally linked directly to the package repo.

**Comment by tillig** [comment]
Since VS shipped with beta 5, @alexmg went through the exercise of downgrading everything, renaming the package to Autofac.Framework,DependencyInjection, and publishing a compatible official release... then re-upgrading everything back to beta 6. [Blog article here.](http://alexmg.com/autofac-packages-for-visual-studio-2015-and-asp-net-5/)

**Comment by david-peden-q2** [comment]
Thanks, @tillig @alexmg. I have taken down my public feed.

+1 on the package rename!
