### ISSUE TITLE
Is there a Autofac.Dnx 4.0-alpha3 for DNX 1.0.0-beta5?

### ISSUE THREAD

**Issue by karldodd** [autofac/Autofac#655]
Dnx beta4 to beta5 is a big move that has a lot of breaking changes. My application, which uses Autofac.Dnx 4.0-alpha2, is migrating to dnx beta5.

Background: My app is in beta5 now but Autofac.Dnx alpha2 is still using Microsoft.Framework.DependencyInjection 1.0.0-beta4. So I get error like "The type 'ServiceDescriptor' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Framework.DependencyInjection.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'." But in dnx beta5, the dependency should be Microsoft.Framework.DependencyInjection.Abstractions instead.

So, back to my question, will a new Autofac.DNX package be released on nuget for beta5? I am a bit worried as I see some changes on dev branch are already heading to beta6 now.

Thanks.

**Comment by shiftkey** [comment]
Have a look at the [MyGet](https://www.myget.org/gallery/autofac) feed for very recent builds (3 days ago)...

**Comment by tillig** [comment]
MyGet is the place you want. We're keeping NuGet compatible with VS tooling for now.

**Comment by davidpeden3** [comment]
@karldodd For a beta5 build, see my thread [here](https://github.com/autofac/Autofac/issues/654).

**Comment by tillig** [comment]
Since VS shipped with beta 5, @alexmg went through the exercise of downgrading everything, renaming the package to Autofac.Framework,DependencyInjection, and publishing a compatible official release... then re-upgrading everything back to beta 6. [Blog article here.](http://alexmg.com/autofac-packages-for-visual-studio-2015-and-asp-net-5/)
