### ISSUE TITLE
Missing NeutralResourcesLanguageAttribute Warning in Win 10 Store App

### ISSUE THREAD

**Issue by JohannesMoersch** [autofac/Autofac#656]
I'm getting the following when building a Windows 10 Universal Application with Autofac v4.0.0-alpha2.

Warning		The assembly "e:\...\packages\Autofac.4.0.0-alpha2\lib\portable-net45+win+wpa81+wp80\Autofac.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

Will this cause any problems when trying to deploy to clients?

Thanks

**Comment by tillig** [comment]
We don't write Windows store apps so the best I could say would be - test it out.

That said, we'll see about getting the attribute on there for you in the next release.

**Comment by tillig** [comment]
The updated build should show up in the MyGet feed shortly and will be in the main NuGet feed when VS tooling catches up to DNX versions.
