### ISSUE TITLE
[Question] Resolve Keyed service with factory

### ISSUE THREAD

**Issue by zabulus** [autofac/Autofac#657]
An example is better than thousand words.
I have two implementations of service
```
interface IService
{
}

class Impl1 : IService
{
}

class Impl2 : IService
{
}
```
I register them with next code.
```
builder.Register(x=>new Impl1()).Keyed<IService>(Enum.Value1);
builder.Register(x=>new Impl2()).Keyed<IService>(Enum.Value2);
```
Can I have factory method in my dependent implementation like this:
```
class DependImpl
{
     Func<object, IService> _factory;

    public DependImpl(Func<object, IService> factory)
    {
        _factory = factory;
    }
    
    public void Work( Enum value)
    {
        IService service = _factory(value);
    }
}
```
How can I accomplish this?

**Comment by tillig** [comment]
Try composing the `Func<T>` and `IIndex<T,U>` like this:

``` c#
class DependImpl
{
     IIndex<object, Func<IService>> _factory;

    public DependImpl(IIndex<object, Func<IService>> factory)
    {
        _factory = factory;
    }

    public void Work(Enum value)
    {
        IService service = _factory[value]();
        Console.WriteLine(service);
    }
}
```

[The relationships we support are shown in the documentation.](http://autofac.readthedocs.org/en/latest/resolve/relationships.html)

If you have more usage questions, [try asking on StackOverflow](http://stackoverflow.com) and tag it with `autofac`. We monitor SO and it also allows more people to see the answer.
