### ISSUE TITLE
Allow tenant dependencies to be explicitly resolved

### ISSUE THREAD

**Issue by Togusa09** [autofac/Autofac#662]
It is not possible to resolve objects for a specific tenant from an injected scope. I believe this would normally be possible when you have access to the MultitenantContainer, but not when you're in MVC and reliant on things being injected to controllers.

```csharp 
public ViewResult HomeController(ITenantContext context)
{
    using(var scope = context.GetTenantScope(1))
    {
        var service = scope.Resolve<IService>();
     }
}

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Multitenant#1
