### ISSUE TITLE
Add support for 'dnu sources' command

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#667]
https://github.com/aspnet/Announcements/issues/46

In order for a package to support dnu sources it must include some new information in the `project.json` file.

```
"repository": { 
    "type": "git", 
    "url": "https://github.com/aspnet/options" 
}
```

https://github.com/aspnet/Options/blob/dev/src/Microsoft.Framework.OptionsModel/project.json#L9-L12

**Comment by tillig** [comment]
We're running into a problem on this where a local build with a cloned repo will properly determine the `repo.json` contents for sources and it works:

``` json
{
  "type": "git",
  "url": "https://github.com/autofac/Autofac",
  "commit": "35cb2095bbcf9e873a5ed5efcc6455c69a6f8ce3",
  "path": "src"
}
```

However, on AppVeyor the code is cloned and then shipped to the build agent, so the working repo info isn't there. You get an incomplete `repo.json`:

``` json
{
  "type": "git",
  "url": "https://github.com/autofac/Autofac",
  "commit": "",
  "path": "src"
}
```

This causes `dnu sources get Autofac` to fail.

**Comment by tillig** [comment]
I opened an issue to track the ability to provide the source info from an environment variable: https://github.com/aspnet/dnx/issues/2418

**Comment by tillig** [comment]
...and dnu sources has been removed.

https://github.com/aspnet/Announcements/issues/66

I'm going to leave the `repo` info in the `project.json` files but close this issue since there's nothing to do. We can reopen/revisit if they bring it back.
