### ISSUE TITLE
Service registration order in ASP.NET 5

### ISSUE THREAD

**Issue by endeffects** [autofac/Autofac#670]
Hallo,

I think there is a problem in the registration life cycle in vnext. At the moment i have to build the container to inject the ServiceProvider, from my point of view the workflow should look like:

        public void ConfigureServices(IServiceCollection services)
        {                       
            services.AddMvc();                                        
            services.AddAutofac(); // Inject Autofac Services (IServiceProvider, IServiceScopeFactory) 
        }
                                                 
        public void Configure(IApplicationBuilder applicationBuilder, IHostingEnvironment hostingEnvironment)
        { 
            applicationBuilder.UseAutofac(); // Build the container and resolve dependencies 
            applicationBuilder.UseMvc();
        }     

This implementation would allow a late binding, also all other service instances are available within the applicationBuilder, i.e. for configuration.

**Comment by tillig** [comment]
Hello - sorry it's taken so long to get here, but a lot in the ASP.NET 5 world has been in flux and just getting the builds to be reasonably stable has been a challenge - optimizing the usage pattern has been a little lower priority.

If you check out the application in the samples folder, [you'll see in the Startup.cs](https://github.com/autofac/Autofac/blob/master/samples/AutofacWebApiSample/Startup.cs) how ASP.NET 5 is intended to be registered - it only appears in ConfigureServices. There's no `UseAutofac` or anything else required.

The reason it only hooks in during `ConfigureServices` is that the DI mechanism in ASP.NET 5 has changed quite a bit. In previous OWIN integrations, there was a need for the DI container to have its own OWIN middleware to manage creation of the request lifetime scope. With the new ASP.NET 5 mechanism, the `IServiceProvider` is baked right into the ASP.NET pipeline.

As such, there's no need for any `application.UseAutofac()` the way there is for `application.UseMvc()`.

In `ConfigureServices` the `AddMvc` registers MVC related services in the container; that also needs to happen for Autofac.

In `Configure` the `UseMvc` call adds MVC middleware things to the pipeline. That's not needed for DI anymore, so there's nothing to do there.

Given that, I don't think there's anything to change in the Autofac registration cycle. As long as you register things into your service container during `ConfigureServices` (which is the official ASP.NET 5 place to do that sort of thing) you should be good to go.
