### ISSUE TITLE
Support Open RIA Services

### ISSUE THREAD

**Issue by icnocop** [autofac/Autofac#674]
Hi.

Thank you for Autofac.

I would like to request support for Open RIA Services.
https://openriaservices.codeplex.com/

It's the successor of WCF RIA Services.

Thank you.

**Comment by tillig** [comment]
If/when we do support such a thing, we'll most likely do so by enhancing the existing RIA services integration in that repository: https://github.com/autofac/Autofac.Extras.DomainServices
