### ISSUE TITLE
Strong name signature could not be verified.

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#676]
This issue was raised on the xUnit repository.

https://github.com/xunit/xunit/issues/540

The problem sounds like it's related to the new signing support project.json and our usage of a specified key file. Given that we run our unit tests in xUnit during the build this is rather strange.

A new beta8 package should be on MyGet soon so a quick test might reveal more.

**Comment by alexmg** [comment]
I tested this with 4.0.0-beta8-124 on the MyGet feed and it seems to be OK. 

https://www.myget.org/F/autofac/api/v2

We can't compile using CoreCLR version of DNX without getting a signing error from the compiler. When compiled under CLR all output assemblies appear to have the correct public key.

Leaving open for now until pushed to NuGet and gets some wider testing.

**Comment by tillig** [comment]
This appears to have been resolved with the 4.0.0-beta7-130 release pushed to NuGet. I followed the repro instructions on https://github.com/xunit/xunit/issues/540 and was able to run tests without the strong name signature issue.
