### ISSUE TITLE
ReplaceInstance in IComponentRegistration.Activating gives wrong instance to OnRelease

### ISSUE THREAD

**Issue by RogerKratz** [autofac/Autofac#677]
If IActivatingEventArgs<T>.ReplaceInstance is called from IComponentRegistration.Activating, wrong instance turns up in OnRelease.

If instead replaceinstance is called from OnActivating, correct instance is passed to OnRelease.

Pull request coming soon.

**Comment by tillig** [comment]
For reference: tests for this issue have been merged from PR #678 into the `test/Autofac.Test/Core/ContainerTests.cs` fixture.

**Comment by tillig** [comment]
Fixed in commit https://github.com/autofac/Autofac/commit/e23a7c0e15b9691c6de5ab1f5f4711c29b05e107
