### ISSUE TITLE
Separate lifetime scope injection and component adding in OWIN

### ISSUE THREAD

**Issue by srogovtsev** [autofac/Autofac#680]
I left a [pull request](https://github.com/autofac/Autofac.Owin/pull/3) in Autofac.Owin, and decided to mention it here for consistency.

# The problem
I have fairly simple OWIN pipeline:
```
app
	.UseAutofacMiddleware(container)
	.UseBasicAuthentication()
	.Use((c, next) =>
	{
		//authorization
		return next();
	})
	.Use<PathRewriter>
	(
		container.Resolve<EventConverter>(),
		container.Resolve<Func<Guid, BlobStream>>()
	)
	.UseSendFileFallback()
	.UseStaticFiles();
```

I think that you can already spot the weak spot: `Use<PathRewriter>(container.Resolve<EventConverter>(), container.Resolve<Func<Guid, BlobStream>>())`

The thing is, I have to use several middleware components that are not based on `OwinMiddleware` or are registered by other means (like `UseBasicAuthentication`), and, as far as I know `UseAutofacMiddleware` injects all found middleware right after it.

# Proposed solution
Extract two parts, `UseAutofacLifetimeScopeInjector` and `UseMiddlewareFromContainer<T>` from `UseAutofacMiddleware` thus allowing more precise control over pipeline composition. The example from above would be rewritten as:

```
app
	.UseAutofacLifetimeScopeInjector(container)
	.UseBasicAuthentication()
	.Use((c, next) =>
	{
		//authorization
		return next();
	})
	.UseMiddlewareFromContainer<PathRewriter>()
	.UseSendFileFallback()
	.UseStaticFiles();
```

**Comment by tillig** [comment]
We track the issues for each integration library in the respective repo, so I'll close this and we can track it on the PR.

**Comment by srogovtsev** [comment]
Thanks, it wasn't obvious from the documentation.
