### ISSUE TITLE
Collections being injected incorrectly

### ISSUE THREAD

**Issue by JonathanBooker** [autofac/Autofac#681]
Web Forms
.NET 4.5.1
AutoFac 3.5.2

In our UserControls we have IList<User>. This property is being injected before Page_Load and then it is populated by our code so the DropDownList is bound to twice.

    public IList<User> Users
    {
        set
        {
             DropDownList.DataSource = value;
             DropDownList.DataBind();
         }
    }

Cannot seem to override action of IList being populated by AutoFac which is not the behaviour we want. It is causing issues with the databinding of the list.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Web#3
