### ISSUE TITLE
Using full power of Autofac in ASP.NET 5 (MVC 6)

### ISSUE THREAD

**Issue by ddotlic** [autofac/Autofac#682]
Hi,

first of all thanks for this library, it has made my life easier many many times ever since I started using it.

I can see that you're keeping the code up-to-date with the current beta of ASP.NET 5 , kudos. We're just starting a new major version of our product and are basing it on beta 7 (will update to future versions as they arrive).

I get everything regarding startup, registration and Autofac integration with the MVC 6 except for one thing - since `IServiceProvider` is very, very simple, we lose all of the other ways Autofac is capable of instantiating objects (once initialization is done there's no more Autofac, we can only "see" `IServiceProvider`).

How do I get ahold of container (`IContainer` from Autofac) if I want to use something like, say, resolution by key (`ResolveKeyed`)? I know that technically I should not call `Resolve` under most if not all circumstances, but I have some existing code I would like to reuse...

Is there a clean way to store `IContainer` somewhere other than to do the ugliest thing that can work and  keep the (Autofac) container as a static member of `Startup` class (shudder)?

Any insight is appreciated!

**Comment by tillig** [comment]
If you can get an `IServiceProvider` then you should be able to do:

```csharp
var scope = serviceProvider.GetService(typeof(ILifetimeScope));
scope.ResolveKeyed<IThing>("mykey");
```

The lifetime scope from which things are resolved is, itself, always registered and available.

Alternatively, you can take a constructor parameter that's an `ILifetimeScope` and that will be injected and you can use it.

```csharp
public class MyThingThatGetsResolved
{
  public MyThingThatGetsResolved(ILifetimeScope scope)
  {
    // the scope will be injected and you can save it or resolve something
  }
}
```

If you actually need _literally the root application container_ (for whatever reason) then you might have to do something crazy like this to register it as a service:

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services)
{
  // add other services, then
  var builder = new ContainerBuilder();

  // add other Autofac registrations, then
  IContainer container = null;
  services.Add(
    new ServiceDescriptor(
      typeof(IContainer),
      provider => container,
      ServiceLifetime.Singleton));

  builder.Populate(services);

  // yay for closures!
  container = builder.Build();
  return container.Resolve<IServiceProvider>();
}
```

Then you can get the `IContainer` from the `IServiceProvider`.

```csharp
var container = serviceProvider.GetService(typeof(IContainer));
```

Don't forget that resolving tons of things out of the root container, particularly disposable things, [may indirectly cause a memory leak](http://autofac.readthedocs.org/en/latest/lifetime/index.html) so going the `ILifetimeScope` route is recommended.

For the future, usage questions like this are pretty good to ask [over on StackOverflow](http://stackoverflow.com) and tag them `autofac`. We monitor that, but we also have a _lot more people_ who can chip in. You can potentially get a faster answer that way, especially if we're swamped (like we are now with the DNX support conversion).

Good luck!

**Comment by ddotlic** [comment]
@tillig Hey, thanks a **ton** for a very detailed answer. I really do appreciate you taking time to thoroughly answer my question (despite the fact that it should have been asked on SO).

I've had mixed success in general with SO but will note that should do so for autofac in the future. Just now, by following your advice, I've run into this answer on SO which aligns perfectly with your first proposal for `ILifetimeScope`: http://stackoverflow.com/questions/4609360/resolve-icontainer

I don't care about `IContainer`, `ILifetimeScope` looks perfect for the few places where I actually do _not_ use constructor injection. In the context of an ASP.NET MVC web "app", it's important that it's scoped (which it is).

Honestly, autofac has worked flawlessly for me so until now I've never had to ask a question at all (the docs are very good and eliminate the need to ask these kind of questions).

Thanks again!
