### ISSUE TITLE
Bug in webapi and InstancePerRequest or Feature?

### ISSUE THREAD

**Issue by msapolikarpov** [autofac/Autofac#684]
Hi, i have asp.net webapi and very simple configuration:
```C#
var container = new ContainerBuilder();
container.RegisterApiControllers(...);

container.RegisterType<PerRequest>().As<IPerRequest>().InstancePerRequest();

_container = container.Build();
GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(_container);
```
Classes and interfaces:

```C#
public class IPerRequest{ }
public class PerRequest : IPerRequest { }
```

If i write in action:
```C#
var c = GlobalConfiguration.Configuration.DependencyResolver.GetService(typeof (IPerRequest)); 
```
throws exception:
"Additional information: No scope with a Tag matching 'AutofacWebRequest' is visible from the scope in which the instance was requested. This generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario.) Under the web integration always request dependencies from the DependencyResolver.Current or ILifetimeScopeProvider.RequestLifetime, never from the container itself."

interesting if I'll write it in the constructor of the controller (dependcy injection in controller) then all is well and the object is created

what am I doing wrong?

**Comment by tillig** [comment]
If you resolve something out of the global dependency resolver directly, it's not happening in the context of a request - it's happening at a global level. Even if you're doing it during a controller execution, the global dependency resolver doesn't have any notion of requests.

[We have a lot of doc about working with request-based lifetime scopes.](http://autofac.readthedocs.org/en/latest/faq/per-request-scope.html)

If you need to resolve something directly on a per-request basis, you'll need the `HttpRequestMessage` so you can use the `GetDependencyScope` method on the message and resolve from that scope.

If you have additional usage questions, please ask them over [on StackOverflow](http://stackoverflow.com) and tag them `autofac`. We do monitor questions there, but there's also a larger community of folks who can get you an answer.

**Comment by msapolikarpov** [comment]
ок, спасибо но это кажется странным, я думаю с этим можно работать также как в  MVC и DependcyResolver.Current

**Comment by msapolikarpov** [comment]
ok, thank you but it seems strange, I think this can work as well as in MVC and DependcyResolver.Current
