### ISSUE TITLE
Syntax error on the site

### ISSUE THREAD

**Issue by knemilentsev** [autofac/Autofac#687]
I'm not sure if this is an appropriate place to report this type of issues.
On the site http://autofac.org/ on the main page you can find a line 
builder.RegisterInstance(new TaskRepository).As<ITaskRepository>();
that should be 
builder.RegisterInstance(new TaskRepository()).As<ITaskRepository>();

**Comment by alexmg** [comment]
Thanks for reporting the issue. I've fixed the typo up on the homepage.

https://github.com/autofac/autofac.github.com
