### ISSUE TITLE
Weird User.Identity in a InstancePerRequest resolution

### ISSUE THREAD

**Issue by toben** [autofac/Autofac#692]
It's weird, when I am in my ApiController, HttpContext.Current.User.Identity is good. IsAuthenticated is true, name is the username, etc...
But, before that, when I am in a resolution of an "InstancePerRequest" injection, HttpContext.Current.User.Identity is weird and all fields are null or empty...
```csharp
            builder.Register(c => new HttpContextWrapper(HttpContext.Current))
                .As<HttpContextBase>()
                .InstancePerRequest();
````
This is the code which inject HttpContext.Current in other injections. How that can be possible ?

**Comment by tillig** [comment]
Can you put together a small reproduction showing the issue and post it somewhere? I've never seen the behavior you describe and we can't troubleshoot it just based on the description.

**Comment by tillig** [comment]
Also, I'm going to move this to the Autofac.WebApi repo since we track issues for individual integrations in the respective repositories.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#11
