### ISSUE TITLE
How config generic interface

### ISSUE THREAD

**Issue by hbulzy** [autofac/Autofac#696]
config like this 
 <component instance-scope="per-dependency"
                   type="SYS.Data.Repository2`1, SYS.Framework"
                   service="SYS.Data.IRepository`1">
      </component>
i got a error 
System.ArgumentException: The type 'SYS.Data.Repository2`1[T]' is not assignable to service 'SYS.Data.IRepository`1'.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Configuration#1
