### ISSUE TITLE
Update build for RC1

### ISSUE THREAD

**Issue by shawnwildermuth** [autofac/Autofac#697]
ASP.NET 5 RC1 is now strongly naming their assemblies. The dev branch needs to be rebuild using the full release (rc1-final) version of the libraries. I've tried to use the dev branch dailies from the MyGet feed, but they were built against RC before they were strongly named. Any chance of kicking off a new build?

**Comment by tillig** [comment]
We're doing what we can as fast as we can given, you know, it's not our "day job" :). I probably won't get to this today; @alexmg may have time.

We have an issue #594 where we're tracking the conversion effort for dnx. I'll close this so we don't track the same stuff in two places.

**Comment by tillig** [comment]
(Of course, if you send us a PR on the dev branch with the required updates, I'll totally take it.)

**Comment by shawnwildermuth** [comment]
The thing is that it doesn't require a PR, it's just a new kickoff of the CI build as works with the RC1 it just didn't build against the RC1-final because they hadn't strongly named them yet.

**Comment by shawnwildermuth** [comment]
Sorry to make it sound urgent, just wanted to alert you to the issue with strong names.

**Comment by tillig** [comment]
Looks like it's going to take more than just a new build. I kicked off a new build of the previously passing code and [now there's a ton of NuGet errors like](https://ci.appveyor.com/project/Autofac/autofac/build/4.0.0.172)

`NU1002: The dependency System.Collections 4.0.11-beta-23516 in project Autofac does not support framework .NETPlatform,Version=v5.0`

I'm guessing we also need to update the runtime in `global.json` to handle some things. Updating for `dnx` changes has never been straightforward. :frowning:

**Comment by opiants** [comment]
Switching sdks from `rc1-16048` to `rc1-final` will fix it. Running `test.cmd` will load the packages from the `%userprofile%\.dnx\runtimes` directory first not from the `\packages` directory and because the libraries in `rc1-16048` are not signed it throws the error.

**Comment by shawnwildermuth** [comment]
I've added PR# 698 though I am not sure about how helpful it is. If it isn't, feel free to dump it since I didn't realize you guys were still working on it.

**Comment by tillig** [comment]
Published Autofac and Autofac.Extensions.DependencyInjection 4.0.0-rc1-177 to NuGet with ASP.NET 5 RC1 compatibility.

**Comment by shawnwildermuth** [comment]
Thanks!
