### ISSUE TITLE
Update Autofac.dnx to 6.0.0-rc1-final

### ISSUE THREAD

**Issue by BreakTheSilence** [autofac/Autofac#700]
Autofac.Dnx need to be updated to 6.0.0-rc1-final

There was a breaking change to rename Microsoft.Framework.* to Microsoft.Extensions. (https://github.com/aspnet/Announcements/issues/77) which makes 4.0.0-alpha2 incompatible with 6.0.0-rc1-final projects.

**Comment by tillig** [comment]
Autofac.Dnx has been renamed to Autofac.Extensions.DependencyInjection and has been released to NuGet with RC1 compatibility.

**Comment by BreakTheSilence** [comment]
Thanks!
