### ISSUE TITLE
Update documentation - use InstancePerLifetimeScope instead of InstancePerRequest for ASP.NET 5

### ISSUE THREAD

**Issue by ShadowDancer** [autofac/Autofac#705]
Hello,
I am using autofac integration for mvc6 rc1. I have problem with AutofacWebRequest, it's not correctly initialized. I have controller dependency with "InstancePerRequest" scope ( it works without that scope). Exception happens in DefaultControllerActivator - everything inside should be wrapped by AutofacWebRequest lifetime scope, shouldn't it?

Exception:
http://pastebin.com/YyJT2mex
Stack trace indicates that exception happened in  Microsoft.AspNet.Mvc.Controllers.DefaultControllerActivator.Create(ActionContext actionContext, Type  controllerType)

My configuration:
Startup.cs
```
    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
            // Add framework services.
            services.AddMvc();

            var builder = new ContainerBuilder();
            builder.RegisterType<DependencyType>().InstancePerRequest();
            builder.Populate(services);

            var container = builder.Build();
            return container.ResolveOptional<IServiceProvider>();
     }
```
HomeController:
```
    public HomeController(DependencyType dependency)
        {
            _dependency = dependency;
        }
```
Config.json (dnx46):
```
    "Autofac": "4.0.0-rc1-*",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc1-*",
```

I am porting mvc5 application to mvc6, and these registrations worked back then.

**Comment by alexmg** [comment]
You will have to use InstancePerLifetimeScope instead of InstancePerRequest when upgrading. The new implementation does not use the special lifetime scope tag as the DI abstraction is intended to be multipurpose and not just for MVC or web apps. Sounds like something we need to add to the doco. Leaving open for the moment as a reminder.

**Comment by tillig** [comment]
[Docs updated.](http://autofac.readthedocs.org/en/latest/integration/aspnetcore.html)
