### ISSUE TITLE
Unable to use Autofac 3.5.2 in .NET Framework 4.6.1 environment.

### ISSUE THREAD

**Issue by regionbbs** [autofac/Autofac#706]
Hi,

I used Autofac 3.5.2 in my solution targeted to .NET Framework 4.6.1.

When I run it, __I got "System.Core 2.0.5 not found" exception__.

I found guideline to resolve this issue, __but my system (Windows 10, Visual Studio 2015, .NET Framework 2.0 and 3.5 installed) can't install patch. (blocked by system)__

How can I resolve this issue?
Thank you.

**Comment by tillig** [comment]
If you aren't able to install the patches that will fix the issue, there's nothing we can do for you from the Autofac side. This is a .NET runtime problem requiring patches to the environment to support portable class libraries, not something specific to Autofac. Sorry.

**Comment by linvi** [comment]
I have the exact same problem here. Have you been able to fix it.

"If you aren't able to install the patches that will fix the issue, there's nothing we can do for you from the Autofac side." is a bit aggressive don't you think? Autofac is well known for having this issue and many other PCL library do not have it.

**Comment by LordSmacker** [comment]
I there!

We're also having this problem on our INT environment. But it's OK on DEV.
tillig, can mention patches to support portable class libraries. Can you please tell me, **which patches**, exactly ( URL for the download would be nice ), are needed for our INT environment to get Autofac 3.5.2 working after .NET 4.6.1 upgrade?

----------

This is the exact error we're having:
[NullReferenceException: Object reference not set to an instance of an object.]
   IsIT.SignonServices.Common.Logger..ctor() in c:\Builds\23\48\src\IsIT.SignonServices.Common\Logger\Logger.cs:43
   lambda_method(Closure , Object[] ) +140
   Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +271

[DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Thinktecture.AuthorizationServer.Interfaces.IAuthorizationServerConfiguration)' on type 'TokenService'. ---> Object reference not set to an instance of an object. (See inner exception for details.)]
   Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +736
   Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +266
   Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +86
   Autofac.Core.Resolving.InstanceLookup.Execute() +62
   Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +170
   Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +124
   Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +266
   Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +86
   Autofac.Core.Resolving.InstanceLookup.Execute() +62
   Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +170
   Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) +109
   Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) +122
   Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) +70
   Autofac.Integration.Mvc.AutofacDependencyResolver.GetService(Type serviceType) +95
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +59

[InvalidOperationException: An error occurred when trying to create a controller of type 'Thinktecture.AuthorizationServer.OAuth2.AuthorizeController'. Make sure that the controller has a parameterless public constructor.]
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +240
   System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +103
   System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) +268
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +95
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +921
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137

Kind regards,

**Comment by tillig** [comment]
@LordSmacker The exception you're seeing is not related. If it was related you'd never have gotten to the point where anything was trying to resolve - you'd see an exception mentioning `System 2.0.5.0`. Your exception appears to be that you're missing a dependency registration. It's a good candidate to ask on StackOverflow - please post it there and include details about how you're setting up the container at app start, and tag the question with "autofac". Thanks!
