### ISSUE TITLE
Named collection in parent scope becomes unavailable in child lifetime scope.

### ISSUE THREAD

**Issue by kennethuil** [autofac/Autofac#711]
The issue shows up when you pass a lambda to BeginLifetimeScope.

            var builder = new ContainerBuilder();
            builder.RegisterCollection<ITestInterface>("test")
                .As <IEnumerable<ITestInterface>>();
            builder.RegisterType<Implementation1>().As<ITestInterface>().MemberOf("test");

            using (var container = builder.Build())
            {
                // Resolve the collection directly from the root container.  This works.
                var x = container.Resolve<IEnumerable<ITestInterface>>();
                Assert.AreEqual(1, x.Count(), "Could not resolve collection from container");

                // Create a child scope, but don't pass it a lambda.
                using (var scope = container.BeginLifetimeScope())
                {
                    // This works.
                    var y = scope.Resolve<IEnumerable<ITestInterface>>();
                    Assert.AreEqual(1, y.Count(), "Could not resolve collection from simple lifetime scope");
                }

                // Create a child scope and pass in a lambda to do extra registrations.
                // Note that we don't have to actually do any extra registrations, just pass in an empty lambda
                // to trigger the issue.
                using (var scope = container.BeginLifetimeScope(b => { }))
                {
                    // and this FAILS
                    var y = scope.Resolve<IEnumerable<ITestInterface>>();
                    Assert.AreEqual(1, y.Count(), "Could not resolve collection from lifetime scope created with builder lambda");
                }
            }

**Comment by tillig** [comment]
Sorry for the delay here.

I'd suggest skipping named collection usage. Collection membership is implied now with registrations, a feature added after the named collection mechanism was introduced. I'm thinking named collections should be marked obsolete at this point.

This test not using named collections behaves as expected:

```csharp
[Fact]
public void CollectionInNestedLifetimeScope()
{
    var cb = new ContainerBuilder();
    cb.RegisterType<Foo1>().As<IFoo>();
    cb.RegisterType<Foo2>().As<IFoo>();
    using (var container = cb.Build())
    {
        var collection = container.Resolve<IEnumerable<IFoo>>();
        Assert.Equal(2, collection.Count());

        using (var scope = container.BeginLifetimeScope())
        {
            collection = container.Resolve<IEnumerable<IFoo>>();
            Assert.Equal(2, collection.Count());
        }

        using (var scope = container.BeginLifetimeScope(b => { }))
        {
            collection = container.Resolve<IEnumerable<IFoo>>();
            Assert.Equal(2, collection.Count());
        }
    }
}
```
