### ISSUE TITLE
EF 7 - register a DbContext with ContainerBuilder 

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac#716]
EF7 provides extension methods for registering its services with `IServiceCollection`

It would be nice if there were extensions for Autofac for doing the same thing with `ContainerBuilder`

I have tried to create such methods but I'm new to Autofac and I hit hurdles.

So here is the `IServiceCollection` API:

```
           IConfiguration configuration = GetConfiguration();
           string connectionString = configuration ["EntityFramework:NavMenuContext:ConnectionString"];
           var efServicesBuilder = new EntityFrameworkServicesBuilder(services);
            efServicesBuilder.AddDbContext<NavMenuContext>(options => options.UseSqlServer(connection));

```

Here was my attempt at writing an extension method for Autofac:

```

public static class ContainerBuilderEntityFramework7Extensions
    {

        public static ContainerBuilder AddDbContext<TContext>(this ContainerBuilder builder,
      Action<DbContextOptionsBuilder, IConfiguration> optionsAction = null) where TContext : DbContext
        {
            if (optionsAction != null)
            {
                builder.Register<DbContextOptions<TContext>>(p => DbContextOptionsFactory<TContext>(optionsBuilder =>
                {
                    IConfiguration config = p.Resolve<IConfiguration>();
                    optionsAction(optionsBuilder, config);
                }));
            }
            else
            {
                builder.Register<DbContextOptions<TContext>>(_ => DbContextOptionsFactory<TContext>(null));
            }

            builder.Register<DbContextOptions>(p => p.Resolve<DbContextOptions<TContext>>()).InstancePerLifetimeScope();
            builder.Register<TContext>(p =>
            {
                IServiceProvider serviceProvider = p.Resolve<IServiceProvider>();
                var instance = DbContextActivator.CreateInstance<TContext>(serviceProvider);
                return instance;
            }).InstancePerRequest();

            return builder;
        }

        private static DbContextOptions<TContext> DbContextOptionsFactory<TContext>(
            Action<DbContextOptionsBuilder> optionsAction)
            where TContext : DbContext
        {
            var options = new DbContextOptions<TContext>(new Dictionary<Type, IDbContextOptionsExtension>());
            if (optionsAction != null)
            {
                var builder = new DbContextOptionsBuilder<TContext>(options);
                optionsAction(builder);
                options = builder.Options;
            }

            return options;
        }   


    }


```

Then you would use it like so:

```

 
    public class AutofacModule : AutofacBusinessLayerModule
    {
        protected override void Load(ContainerBuilder builder)
        {
            base.Load(builder);

            builder.AddDbContext<NavMenuContext>((options, configuration) =>
            {
                string connectionString = configuration["EntityFramework:NavMenuContext:ConnectionString"];
                options.UseSqlServer(connectionString);
            });          
            
        }
      
    }

```

However something muct be wrong with my implementation because my attempt yeilds:

![image](https://cloud.githubusercontent.com/assets/3176632/13015778/d22a9a2a-d1b2-11e5-9cc3-b5ef160b3ff9.png)

I have read the autofac documentation, but regarding this error but I haven't yet been able to work out what the problem is, it's such a complex chain of events and delegates!

**Comment by tillig** [comment]
An interesting idea, but I don't know that we'll be adding any new integrations at this point. We currently  maintain between 15 and 20 integrations, some of which are things we're not really experts in, so it makes things tough to help folks out when problems arise.

If you end up figuring it out, you're welcome to start your own Autofac/EF extension library.

As far as troubleshooting your issue, I'm guessing the problem is when you register `TContext` as `InstancePerRequest` - ASP.NET Core doesn't have a tagged request lifetime scope, so switch that to `InstancePerLifetimeScope` instead.

**Comment by dazinator** [comment]
Ok - thanks @tillig !

**Comment by iby-dev** [comment]
@dazinator did you get this working in the end? Where did you leave this?

**Comment by dazinator** [comment]
Can't remember as it was 3 years ago now! I think I did get it working once I took the advice above..

**Comment by iby-dev** [comment]
@dazinator - did you end up creating a seperate package then for this?
