### ISSUE TITLE
Use package for ASP.NET Core specification tests

### ISSUE THREAD

**Issue by halter73** [autofac/Autofac#720]
[ScopingContainerTestBase](https://github.com/autofac/Autofac/blob/ca9ec02b5469d2fd61f6209f8b3d79f7e337188d/test/Autofac.Extensions.DependencyInjection.Test/Specification/ScopingContainerTestBase.cs) can be replaced by [DependencyInjectionSpecificationTests](https://github.com/aspnet/DependencyInjection/blob/396f168715631674afe5372a56bd09e83363e9ad/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs) for use in [AutofacContainerTests](https://github.com/autofac/Autofac/blob/ca9ec02b5469d2fd61f6209f8b3d79f7e337188d/test/Autofac.Extensions.DependencyInjection.Test/Specification/AutofacContainerTests.cs).

The Microsoft.Extensions.DependencyInjection.Specification.Tests package isn't available on NuGet.org yet, but it is on the [ASP.NET vNext MyGet feed](https://www.myget.org/gallery/aspnetvnext) which appears to already be in Autofac's NuGet.config. Using this package will mean that you don't need to manually update the specification tests anymore and should allow quicker feedback when the ASP.NET team starts making new assumptions about how containers behave. Ex: https://github.com/aspnet/Options/issues/122#issuecomment-190540231

**Comment by tillig** [comment]
[We are already doing that on the `develop` branch where the latest work is ongoing.](https://github.com/autofac/Autofac/blob/develop/test/Autofac.Extensions.DependencyInjection.Test/SpecificationTests.cs#L7) Thanks!

**Comment by halter73** [comment]
Awesome! If only github repository search worked on non-default branches...
