### ISSUE TITLE
Dotfuscator Version 4.8.1000.21906 can't recompile after de-compiling and scrambling because of mscorelib.dll 2.0.5.0

### ISSUE THREAD

**Issue by TCDooM** [autofac/Autofac#723]
Hi,
i added a reference to the Autofac with Nuget, since then i can't obfuscate my code.

> [Build Output] Couldn't load external type because its assembly can't be found: System.Reflection.Assembly,mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes"

the Build computer that runs the Dotfuscator is up-to-date with all windows updates, i can't install the KB2468871 since it's blocked of inapplicable.

my BAD solution was to take the Autofac code and recompile it in .NET 4.5.2, that solved it... but i'm not happy about it.

any help is greatly appreciated.
Thanks.

**Comment by tillig** [comment]
Unfortunately, this is probably a Dotfuscator problem. Looking at [the release notes](https://www.preemptive.com/support/dotfuscator-support/dotfuscator-pro-change-log) it appears version 4.8 came out in July 2010 and Portable Class Libraries came out after that. I'm guessing your version of Dotfuscator doesn't know how to handle PCL. Try a newer version. If you can't, you may need to contact PreEmptive support and ask them for help - there's nothing we can do on this end. Sorry.
