### ISSUE TITLE
builder.Register<T>(context => doesn't invoke 'context' Func

### ISSUE THREAD

**Issue by jarzimichal** [autofac/Autofac#726]
Hi,

After upgrading to AutoFac 4.0.0-rc1-177 the builder.Register method is invoked when building the ContainerBuilder but the context Func is not invoked anymore.

In Startup file I register modules like this:
var builder = new ContainerBuilder();
builder.RegisterModule(new Neo4jModule(appConfiguration));
builder.Populate(services);
var container = builder.Build();
return container.Resolve<IServiceProvider>();

In Module class the context Func body is not invoked anymore, however the builder.Register method is invoked properly (Debugger hits that method)
builder.Register<IGraphClient>(context =>
                {
                    // Not invoked anymore
                })
                .SingleInstance();

This code was working with beta version of AutoFac and stopped working when upgraded to 4.0.0-rc1-177 and changed to use Autofac.Extensions.DependencyInjection rather than Framework...

**Comment by tillig** [comment]
Can you post a failing unit test or a more complete repro of the issue somewhere? We have several unit tests across the repo that validate delegate registrations work, so seeing the whole picture - both the registration and resolution - is needed for troubleshooting. (The lambda won't get hit until resolution time, right?)

**Comment by tillig** [comment]
Without a repro I'm not going to be able to fix this. I'm going to close it for now; if you are able to reproduce the issue in a way we can test it, we can definitely re-open.
