### ISSUE TITLE
AutoActivate and IStartabe for scope

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#731]
Current `AutoActivate` feature can't be used for `InstancePerMatchingLifetimeScope` components.

I want some components to be auto activated when I begin their lifetime scope.

Please add this.

**Comment by tillig** [comment]
`AutoActivate` and `IStartable` go hand-in-hand. I'll update the issue to include that.

In the meantime, can you describe how you think this might work? Thinking about things like how you register components for different lifetime scopes, how you can register new components when you start a new scope, and so on... How would you expect this feature to work in the various contexts in which it might be used?

**Comment by tillig** [comment]
Just realized this overlaps pretty heavily with #567 so I'm going to roll it into that.
