### ISSUE TITLE
DefaultConstructorFinder should throw an exception if type being inspected has no public constructors.

### ISSUE THREAD

**Issue by orhtej2** [autofac/Autofac#733]
Currently when registering a type that has no public constructors (namely, a type that only has a private/protected default constructor) DefaultConstructorFinder will return an empty array of constructor which in turn will throw a generic, unhelpful DependencyResolutionException in default IConstructorSelector implementations.
However, in my opinion, if a postcondinion is implemented on IConstructorFinder that forces it to return a no-empty array it would be easier to identify the problem.

**Comment by dyronald** [comment]
We can have DefaultConstructorFinder::GetDefaultPublicConstructors throw an exception if the constructor array is empty. This would move the exception earlier to when the container is built.

Is this is what is wanted here?

**Comment by orhtej2** [comment]
Yes, as long as name of the type and the reason will be in one exception I think this will help a lot.

**Comment by tillig** [comment]
Fix released in [v4.7.0](https://www.nuget.org/packages/Autofac/4.7.0).
