### ISSUE TITLE
Resolve IEnumerable of previously created instances which implement some interface

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#734]
I want to resolve all already created instances which implement some interface. It looks like I can't use TryResolve for this or am I missing something? Because internally TryResolve just calls context.ResolveComponent(registration, parameters) without passing any "try" flag.

**Comment by tillig** [comment]
IEnumerable is sort of a special case thing.

Can you provide some snippets (ideally in the form of a passing or failing unit test) showing what you're trying to do so we can be sure we're on the same page? What's working? What's not?

**Comment by AqlaSolutions** [comment]
[TestFixture]
    public class AutofacTryResolveEnumerableTest
    {
        interface IC
        {
        }

        class C1 : IC
        {
        }

        class C2 : IC
        {
        }

        class C3 : IC
        {
            public C3()
            {
                throw new Exception("Should not happen");
            }
        }

        [Test]
        public void Execute()
        {
            var cb = new ContainerBuilder();
            cb.RegisterType<C1>().SingleInstance().AsSelf().AsImplementedInterfaces();
            cb.RegisterType<C2>().SingleInstance().AsSelf().AsImplementedInterfaces();
            cb.RegisterType<C3>().SingleInstance().AsSelf().AsImplementedInterfaces();
            var c = cb.Build();
            Assert.That(c.Resolve<C1>(), Is.Not.Null);
            Assert.That(c.Resolve<C2>(), Is.Not.Null);
            IEnumerable<IC> found;
            Assert.That(c.TryResolve<IEnumerable<IC>>(out found), Is.True);
            Assert.That(found.Select(x => x.GetType()).ToArray(), Is.EqualTo(new[] { typeof(C1), typeof(C2) }));
        }
    }

**Comment by AqlaSolutions** [comment]
Uh, I've just understood that I'm using `TryResolve` in a wrong way. Is it possible at all to resolve only previously created instances?

**Comment by tillig** [comment]
No, there's not really a way to say "only resolve stuff that's been resolved once before." I'm not sure what the use case for that would be. If you only want one of a thing to be created, you'd register it as single instance. Otherwise, the whole responsibility of the container is to figure out how to wire things up and manage the lifetimes in scopes - and to take that manual checking out of your hands. Perhaps the problem needs to be solved in a different way?
