### ISSUE TITLE
Autofac cannot figure out proper constructor

### ISSUE THREAD

**Issue by kayhustle** [autofac/Autofac#739]
It seems odd to me that Autofac would throw an exception here, as I would assume the framework should be able to figure out the proper constructor to use in this case.  I'm assuming this is a bug, but if not then this is a feature request as the answer is obvious.

`public class Test
    {
        public Test(double data)
        {
            
        }
        public Test(string data)
        {

        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            ContainerBuilder  builder = new ContainerBuilder();
            
            builder.RegisterType<Test>().WithParameter(new PositionalParameter(0, (double) 5));
            var container = builder.Build();
            var colorBucket = container.Resolve<Test>();

        }
    }

`
I would assume this should only throw if I'm passing in null with two nullable parameter types, an inheritance conflict, or with constructors that have identical signatures followed by optional parameters.

**Comment by alexmg** [comment]
The `PositionalParameter` does not take the type provided at runtime into consideration. If you really want to use the `PositionalParameter`, and the parameter count between two constructors is equal, you need to specify the appropriate constructor to use via the `UsingConstructor` method.

```
.UsingConstructor(typeof(double))
.WithParameter(new PositionalParameter(0, (double)5));
```

Given that you actually know the type of the parameter it would be far easier to use the `TypedParameter` instead.

```
.WithParameter(TypedParameter.From(5d));
```

With this there is no ambiguity and no need to indicate which constructor is required as the type will be used to identify the appropriate constructor.
