### ISSUE TITLE
CopyOnWriteRegistry possibly not correctly disposed

### ISSUE THREAD

**Issue by dozm** [autofac/Autofac#746]
at: Autofac/src/Autofac/Core/Registration/CopyOnWriteRegistry.cs  line:59
 _readRegistry?.Dispose(); 
Whether it should be:
_writeRegistry?.Dispose();

this code will not throw an  exception,Since you did not call  _componentRegistry.Dispose() in LifetimeScope.Dispose()

**Comment by tillig** [comment]
This gets a little complicated, but I think you might be right.

Some research/notes:

The only place we create `CopyOnWriteRegistry` is during `LifetimeScope.BeginLifetimeScope` [like here](https://github.com/autofac/Autofac/blob/4debce0dec215ff788cf9e9a86c0d59e27452eb9/src/Autofac/Core/Lifetime/LifetimeScope.cs#L131). The point of the `CopyOnWriteRegistry` is to isolate new registrations that get made in lifetime scope configuration actions from a parent component registry.

The `CopyOnWriteRegistry` gets the parent component registry as a constructor parameter (the "read registry") and then [creates a "scope restricted registry"](https://github.com/autofac/Autofac/blob/4debce0dec215ff788cf9e9a86c0d59e27452eb9/src/Autofac/Core/Lifetime/LifetimeScope.cs#L197) when writes (new registrations) are made.

While the parent lifetime scope (or container) is responsible for disposing of the root component registry, the creation of these disposable scope restricted registries doesn't actually appear to get handled - the `_writeRegistry?.Dispose()` as noted in the original issue isn't called.

That said, it doesn't look like anything actually ever does dispose of these `CopyOnWriteRegistry` instances. The registry isn't [added to the new lifetime scope's `Disposer`](https://github.com/autofac/Autofac/blob/4debce0dec215ff788cf9e9a86c0d59e27452eb9/src/Autofac/Core/Lifetime/LifetimeScope.cs#L73) so I'm not sure where that happens, if at all. I haven't hooked a debugger up to it to verify.

What it looks to me needs to happen:

- The `CopyOnWriteRegistry` needs to be added to the `Disposer` of the child lifetime scope so new registrations will be actively disposed.
- The `_writeRegistry` should be disposed, not the parent `_readRegistry`.
- A little doc should be added to `LifetimeScope.CreateScopeRestrictedRegistry` to indicate how this all works.

@alexmg Does this sound right to you?

**Comment by alexmg** [comment]
This fix is included in 4.6.1 which has been pushed to NuGet.
