### ISSUE TITLE
Using Autofac4 & Asp.net core, how to get IContainer from IServiceProvider instance?

### ISSUE THREAD

**Issue by iron9light** [autofac/Autofac#754]
Is there anyway to get the container from the IServiceProvider which is the return value of Startup.ConfigureServices.
I need to create a object with some specific parameters, and IServiceProvider don't support this feature.

Thanks,
IL

**Comment by tillig** [comment]
Instead of trying to find the container (it's bad practice to resolve from the container if avoidable - can lead to inadvertent memory leaks for disposable components) resolve an ILifetimeScope from the service provider and use that.

**Comment by pantonis** [comment]
@tillig can you show an example of how can we do that?

**Comment by tillig** [comment]
`IServiceProvider.GetService<ILifetimeScope>()`
