### ISSUE TITLE
IAutofacAuthenticationFilter (HttpContext == null)

### ISSUE THREAD

**Issue by Xorcist77** [autofac/Autofac#756]
Attempting to access HttpContext.Current in a standard IAuthenticationFilter (WebAPI2 / .NET 4.6) will return the appropriate HttpContext object.

However using Autofac 3.5.0.0, and attempting to access HttpContext.Current in an injected IAutofacAuthenticationFilter will result in null.

**Comment by tillig** [comment]
I assume this is for the Web API integration. [Can you file it in that repo?](https://github.com/autofac/Autofac.WebApi/issues) thanks.
