### ISSUE TITLE
No way to get scope for current http request (Autofac 4)?

### ISSUE THREAD

**Issue by mexahuk61** [autofac/Autofac#760]
How can we get ILifetimeScope for current http request when HttpContext exists? E.g. I want to resolve service from static extension method. I don't want to create new instance of scope by BeginLifetimeScope() method.

I spend few hours and didn't found solution..

**Comment by tillig** [comment]
Are you using ASP.NET Core, classic ASP.NET MVC, classic ASP.NET Web API, some combination of the above...? As noted in the issue template, please provide more details about your application and what you're trying to achieve so we can best help you.

**Comment by mexahuk61** [comment]
ohh... sorry! I'm using **asp.net core rc2**.

For better understanding:
I have static class with extension methods, which must resolve `IGenericAttributeService` of my service layer. For example I will use method of my singletone engine:  `EngineContext.Current.Resolve<IGenericAttributeService>();`
http://clip2net.com/s/3zkyJ3C 

my method Resolve<>:
http://clip2net.com/s/3zkz1qq

This service has construsctor with few params. One of this: IDbContext 
http://clip2net.com/s/3zkz4VB

(implimentation of dbcontext registered by ContainerBuilder).
http://clip2net.com/s/3zkyGNR

Whats the problem:
We can use many services from asp.net controller. And all of this services will use new instance of DbContext per each http request, because autofac create new child scope(*) of 'root' scope for each http request and destroy when request is done. And we maintain important rule: one dbcontext per request. **All perfect**. But in my Resolve<> method I need to use this 'child' scope(*), because autofac must resolve this DbContext from existing scope. And destroy this when http request is done.

**Comment by tillig** [comment]
[This was cross-posted to StackOverflow here.](http://stackoverflow.com/questions/37891598/no-way-to-get-scope-for-current-http-request-autofac-4)

**Comment by tillig** [comment]
Answer posted to StackOverflow.

**Comment by asadalidev** [comment]
answer on StackOverflow  solved my problem.

**Comment by asadalidev** [comment]
> Answer posted to StackOverflow.

answer posted on StackOverflow solved my problem. this exactly what I am looking for. 
thank you so much.

[StackOverflow Answer](https://stackoverflow.com/questions/37891598/no-way-to-get-scope-for-current-http-request-autofac-4)
