### ISSUE TITLE
Add overload to InjectProperties to accept IPropertySelector

### ISSUE THREAD

**Issue by twsouthwick** [autofac/Autofac#761]
`IPropertySelector` was recently added (#715) to allow for selective property injection with `IRegistrationBuilder.PropertiesAutowired`. There is another entry point for people to inject properties via the `IComponentContext.InjectProperties` method. I propose to add an overload that accepts IPropertySelector:

```csharp
 public static TService InjectProperties<TService>(this IComponentContext context, TService instance, IPropertySelector propertySelector);
```

**Comment by tillig** [comment]
I think that sounds reasonable.
