### ISSUE TITLE
Autofac.3.5.2 NuGet package doesn't add Autofac.dll reference to the project

### ISSUE THREAD

**Issue by Darth-Jurassic** [autofac/Autofac#766]
Autofac.dll reference is not added to the project when installing Autofac 3.5.2 package.

The reference is added well when installing/downgrading to version 3.5.0, but is removed again when upgrading to version 3.5.2.

**Comment by tillig** [comment]
This is a NuGet problem, not something we can do anything about. When you add/remove packages, it's NuGet that actually does add/remove reference, not the package. I'd recommend upgrading to the latest NuGet if you haven't already. If it continues to be a problem, file a ticket with them at https://github.com/NuGet/Home/issues
