### ISSUE TITLE
Cannot Upgrade from 3.5.2 to Rc3 on UWP project

### ISSUE THREAD

**Issue by MMalikKhan** [autofac/Autofac#767]
Hello, i am trying to upgrade from an older version 3.5.2 to latest RC3 on my UWP project and i am getting below error. Is RC3 compatible with the new version of UWP?

thanks for your help.

System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'ProjectName'.
Package restore failed. Rolling back package changes for 'ProjectName'.

**Comment by tillig** [comment]
Can you post a repro, or at least your project.json file, the version of NuGet you're using, and the URL you're using to the NuGet feed? I have seen other projects with other UWP challenges and it's always been a missing reference in the UWP project (the base project template isn't complete); an old NuGet.exe version; or over-aggressive caching by NuGet.org on the v3 feed.

**Comment by MMalikKhan** [comment]
@tillig below are of the projectJson file from the solution. 

{
  "dependencies": {
    "Autofac": "3.5.2",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

another one
{
  "dependencies": {
    "Autofac": "3.5.2",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Sqlite": "7.0.0-rc1-final",
    "GoogleAnalyticsSDK": "1.3.0",
    "HockeySDK.UWP": "4.0.0",
    "MetroLog": "1.0.1",
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Newtonsoft.Json": "8.0.2",
    "Syncfusion.Pdf.UWP46": "14.1.0.41",
    "Syncfusion.SfPdfViewer.UWP46": "14.1.0.41",
    "Template10": "1.1.2",
    "Win2D.uwp": "1.16.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by tillig** [comment]
Hmm. There is definitely something up with this. Like, I can barely install anything that uses the new `netstandard` stuff into UWP (tried AutoMapper and a few others) indicating there's probably something larger amiss here, like a NuGet problem. I'll keep looking.

**Comment by tillig** [comment]
I fixed this by adding a specific requirement for `"Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0"` to a platform target. Seems when they went RTM with .NET Core there were still some version mismatches and weird stuff causing package downgrades. I dunno. This whole thing's been pretty painful.

Anyway, I pushed 4.0.0-rc3-286 and that should fix you up.

**Comment by MMalikKhan** [comment]
@tillig  thank you very much for your quick fix. I will let you know if i get stuck again.
