### ISSUE TITLE
Wcf integration: Service name in .svc file needs to be fully qualified name

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#77]
_From [noackstefan](https://code.google.com/u/noackstefan/) on August 14, 2008 08:05:37_

i tried to use autofac for an iis-hosted wcf service and found that the
﻿service name in the .svc file needs to be the fully qualified name of the
service type like:

<&#37;@ ServiceHost Service="TestService.Service1,TestService"
Factory="Autofac.Integration.Wcf.AutofacServiceHostFactory" &#37;>

instead of:

-﻿<&#37;@ ServiceHost Service="TestService.Service1"
Factory="Autofac.Integration.Wcf.AutofacServiceHostFactory" &#37;>

because AutofacHostFactory (ll. 65-67) does:

Type serviceType = Type.GetType(constructorString, false);
 if (serviceType != null)
  Container.TryGetDefaultRegistrationFor(
  new TypedService(serviceType), out registration);

which is calling Type.GetType(string, bool) using the constructorString.
The type (and therefore the registration) cannot be found when the assambly
name is not explicitly specified. This leads into something like:

"The service 'TestService.Service1' configured for WCF is not registered
with the Autofac container."

Attached is a patch for the Wcf integration example. Maybe you could fix
the example on http://code.google.com/p/autofac/wiki/WcfIntegration too :)

autofac is great, btw!

**Attachment:** [wcf_examlpe_fully_qualified_assembly_name.patch](http://code.google.com/p/autofac/issues/detail?id=76)

_Original issue: http://code.google.com/p/autofac/issues/detail?id=76_

**Comment by Regent** [comment]
This seems to be broken again.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Wcf#13
