### ISSUE TITLE
AsImplementedInterface() doesn't include itself when registering interfaces

### ISSUE THREAD

**Issue by enkafan** [autofac/Autofac#770]
I'm not sure if this is by design, but when registering MassTransit I ran into this. MassTransit has a factory that returns `IBusControl` that I had wired this up with `AsImplementedInterfaces`. To me surprise I couldn't resolve `IBusControl`. Simple fix for me was to use `AsSelf` too, but I didn't know if this was a bug or expected behavior.

Simple failing test:

```csharp
        IImplementedInterface SelfComponentFactory()
        {
            return new SelfComponent();
        }

        [Test]
        public void AsImplementedInterfaces_CanBeAppliedToInstanceRegistrationsOfInterfaces()
        {
            var builder = new ContainerBuilder();
            builder.Register(c => SelfComponentFactory()).AsImplementedInterfaces();
            var context = builder.Build();

            context.Resolve<IImplementedInterface>();
        }
```

the "fix" if this is indeed a bug is was just including the interface in the list of registrations for situations where an interface is being registered:

```csharp
        static Type[] GetImplementedInterfaces(Type type)
        {           
            var interfaces = type.GetInterfaces().Where(i => i != typeof(IDisposable));
            return type.IsInterface ? interfaces.Append(type).ToArray() : interfaces.ToArray();
        }
```

**Comment by tillig** [comment]
Nice catch - thanks! We'll see about getting this in place for the 4.0 release.

**Comment by enkafan** [comment]
Right on, I'm happy to submit a PR but I wasn't sure which branch to target

**Comment by tillig** [comment]
Resolved by https://github.com/autofac/Autofac/pull/772

Thank you very much for the PR!
