### ISSUE TITLE
builder.Populate(services)  报错

### ISSUE THREAD

**Issue by 188** [autofac/Autofac#777]
无法从“Microsoft.Extensions.DependencyInjection.IServiceCollection”转换为“System.Collections.Generic.IEnumerable<Microsoft.Framework.DependencyInjection.ServiceDescriptor>”	

Thanks

**Comment by 188** [comment]
"Autofac": "4.0.0-rc2-240",
    "Autofac.Framework.DependencyInjection": "4.0.0-beta8-157"

**Comment by tillig** [comment]
Assuming you're on .NET Core RTM, you need to update to the latest Autofac and switch to the Autofac.Extensions.DependencyInjection package - it got renamed after beta 8.

**Comment by 188** [comment]
I am using is .net core 1.0.0 release
