### ISSUE TITLE
Error after update from 4.0.0-rc3-280 to 4.0.0-rc3-309

### ISSUE THREAD

**Issue by Lisaj** [autofac/Autofac#779]
Hi,
i update to version 4.0.0-rc3-309 from 4.0.0-rc3-280. This update install many new nugets. Before update my project is depend on System.Net.Http 4.0.0 from netframework. After update System.Net.Http is referenced from nuget version 4.1.0. System.Net.Http version 4.1.0 is not compatible with my project and caused exception:
`Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.`

**Comment by alexmg** [comment]
This sounds like a known issue listed in the corefx repository.

https://github.com/dotnet/corefx/issues/9884

There is a SO thread about it too.

http://stackoverflow.com/questions/38355544/type-argument-system-net-http-headers-mediatypeheadervalue-violates-the-constr

**Comment by Lisaj** [comment]
Thank you for the helpful information.
