### ISSUE TITLE
install package mvc5 .net 4.5

### ISSUE THREAD

**Issue by forX01** [autofac/Autofac#781]
I try to add autofac.mvc but I got an error when I do (Install-Package Autofac.Mvc5)

It said cant install package because no file or assembly reference to .net4.5 in the package .

[french version]
> L'installation a échoué. Restauration en cours...
> Install-Package : Impossible d’installer le package «Autofac.Mvc5 4.0.0». Vous essayez d’installer ce package dans un projet ciblant «.NETFramework,Version=v4.5», 
> mais le package ne contient aucun fichier de contenu ou référence d’assembly compatible avec cette infrastructure. Pour plus d’informations, contactez le créateur 
> du package.
> Au caractère Ligne:1 : 1
> + Install-Package Autofac.Mvc5
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
>

**Comment by alexmg** [comment]
Please try updating your project to target 4.5.1. The next point release will contain a net45 lib folder in the NuGet package. Currently it only has a net451 folder which is incorrect.

**Comment by forX01** [comment]
working, tank you
