### ISSUE TITLE
Consider IL generation to increase performance of internals

### ISSUE THREAD

**Issue by lobster2012-user** [autofac/Autofac#784]
Hello!

```
class Program
    {
        public interface c
        {

        }

        public class cc : c
        {

        }
        interface a
        {

        }
        public class aa : a
        {
            public c Field
            {
                get { return null; }
                set
                {
                    Console.WriteLine(value);//autofac call property.setValue
                }
            }

            public aa()
            {
                Console.WriteLine("b");//autofac call lambda
            }
        }

        public static void Main(string[] args)
        {

            Autofac.ContainerBuilder builder = new ContainerBuilder();

            builder.RegisterType<aa>()
                .As<a>()
                .PropertiesAutowired();

            builder.RegisterType<cc>().As<c>();

            var container = builder.Build();
            var g = container.Resolve<a>();
            Console.WriteLine(g);
        }
```

Sorry if I wrote in the wrong place .
Do you going to replace the code in the future on realtime code generation (emit il)? 
or am I wrong to use autofac?

**Comment by tillig** [comment]
I'm not sure I understand the question. Are you asking if we're going to switch our current internal implementation? Or are you asking if there's some better way to accomplish a task?

**Comment by lobster2012-user** [comment]
Question about (switching) current internal implementation. 
Sorry for my english.

**Comment by tillig** [comment]
We are totally open to pull requests and help improving performance. However...

- We don't want to rely on additional non-core libraries, so adding something like Castle.Core or Mono.Cecil isn't an option.
- We can't break the interfaces without issuing a major release (which we just did) so non-breaking would be good.
- Having some actual performance numbers to compare before and after would help so we can see the differences.
- Ideally it's fairly maintainable. The internals are already pretty complex, which is fine and somewhat unavoidable. I've worked with expression tree parsing and IL generation quite a bit and it can be pretty challenging to troubleshoot issues in there when they arise. We'd have to balance the additional complexity (if any) against both performance and maintainability.

**Comment by madelson** [comment]
Having seen a lot of the libraries I use take this route, it would be great if any switch from reflection to a baked IL method was done lazily and only once the number of usages of a particular resolution reach a certain level. Expression compilation is relatively slow, hurting cold startup. This would be painful for short-lived containers. For example we use containers:

* In unit tests, to wire up mock test dependencies
* In console apps, for organization and testability
* With on-the-fly registrations created in nested lifetime scopes used to "override" a registration

In each of these scenarios, many registrations are created but each is used only ~once per execution, thus eliminating the benefit of such an optimization.

**Comment by tillig** [comment]
Since there's not a specific action here and updates to perf, etc. are more of an "ongoing effort" than any single specific thing, I'm going to close this and we can apply the ideas here as we move forward.
