### ISSUE TITLE
Poor experience installing package into .NET 4.5 project

### ISSUE THREAD

**Issue by mookid8000** [autofac/Autofac#786]
I will not claim to be an expert on .NET Core, in fact I know almost nothing about it. I was just puzzled when I installed Autofac into a .NET 4.5 project when I saw how much stuff got downloaded:

	PM> install-package autofac -ProjectName AutofacTest

	Attempting to gather dependency information for package 'autofac.4.0.0' with respect to project 'AutofacTest', targeting '.NETFramework,Version=v4.5'
	Gathering dependency information took 13 sec
	Attempting to resolve dependencies for package 'autofac.4.0.0' with DependencyBehavior 'Lowest'
	Resolving dependency information took 0 ms
	Resolving actions to install package 'autofac.4.0.0'
	Resolved actions to install package 'autofac.4.0.0'
	Retrieving package 'Microsoft.NETCore.Platforms 1.0.1' from 'nuget.org'.
	Retrieving package 'NETStandard.Library 1.6.0' from 'nuget.org'.
	(...)
	Adding package 'NETStandard.Library.1.6.0' to folder 'c:\temp\AutofacTest\packages'
	Added package 'NETStandard.Library.1.6.0' to folder 'c:\temp\AutofacTest\packages'
	Added package 'NETStandard.Library.1.6.0' to 'packages.config'
	Successfully installed 'NETStandard.Library 1.6.0' to AutofacTest
	Adding package 'Autofac.4.0.0' to folder 'c:\temp\AutofacTest\packages'
	Added package 'Autofac.4.0.0' to folder 'c:\temp\AutofacTest\packages'
	Added package 'Autofac.4.0.0' to 'packages.config'
	Successfully installed 'Autofac 4.0.0' to AutofacTest
	Executing nuget actions took 19,83 sec
	Time Elapsed: 00:00:33.5003611

	>

importing 32 packages in addition to Autofac into my project (full output with ~170 lines can be seen [here](https://gist.github.com/mookid8000/5aceaa41df2b574976fa5c9e14f31978)).

It turned out to be because Autofac was depending on .NETStandard 1.1 (i.e. NETStandard.Library 1.6.0)

![image](https://cloud.githubusercontent.com/assets/32968/17750478/efb5ac30-64c2-11e6-8c9d-a4a642c7966d.png)

which is, apparently, the .NET 4.5 compatible .NET Standard library.

Funny thing is if I change the platform target for my app to .NET 4.5.1 and `Update-Package Autofac -Reinstall` I get this output:

	PM> Update-Package Autofac -Reinstall

	Attempting to gather dependency information for multiple packages with respect to project 'AutofacTest', targeting '.NETFramework,Version=v4.5.1'
	Gathering dependency information took 7,42 sec
	Attempting to resolve dependencies for multiple packages.
	One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'NETStandard.Library 1.6.0 constraint: System.Threading.Timer (>= 4.0.1)'
	Resolving dependency information took 0 ms
	Resolving actions install multiple packages
	Retrieving package 'Autofac 4.0.0' from 'nuget.org'.
	Removed package 'Autofac 4.0.0' from 'packages.config'
	Successfully uninstalled 'Autofac 4.0.0' from AutofacTest
	Package 'Autofac.4.0.0' already exists in folder 'c:\temp\AutofacTest\packages'
	Added package 'Autofac.4.0.0' to 'packages.config'
	Successfully installed 'Autofac 4.0.0' to AutofacTest
	Executing nuget actions took 512,49 ms
	Time Elapsed: 00:00:07.9658772
	PM> 

importing only one single package (Autofac 😁 ) which seems reasonable.

I am not sure that this is a technical issue, but I would argue the it is at least an issue from a library usability perspective. 

If I understand this correctly, either 

1) .NET 4.5 is supported in a weird new way that is pretty intimidating (and pretty useless?), or

2) .NET 4.5.1 is supported (along with 4.5.2, 4.6, and 4.6.1) in the old way by mistake? According to the table on [this page](https://docs.microsoft.com/da-dk/dotnet/articles/standard/library), .NETStandard 1.2 would correspond to .NET 4.5.1, 1.3 to 4.6, etc.

It may also just be me, who is being more confused than usual. Feel free to enlighten me 😄

**Comment by tynor88** [comment]
I experienced the same issue. I had like 20+ additional nuget packages installed from the .NET library when upgrading to Autofac 4.0 (also a project targeted for 4.5).

**Comment by tillig** [comment]
That's just how netstandard support works. If you look at what most of the "dependencies" end up doing under the covers, for full .NET framework support they just point to the system installed assemblies.

[Note that .NET 4.5 is technically deprecated.](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) Consider updating to .NET 4.5.2 or higher, which is supported by Microsoft, if you can.

That said, in the upcoming release we added a specific .NET 4.5 compilation platform target which fixes the issue and only brings the Autofac assembly along. [You can test it out from our MyGet feed if you like.](https://www.myget.org/gallery/autofac)

Be aware that you'll actually see a lot of this sort of thing in coming times, since not every project will add a full .NET compilation target explicitly - the new "portable class library" _is_ targeting netstandard, which breaks away from the notion of installed dependencies.

**Comment by mookid8000** [comment]
> Note that .NET 4.5 is technically deprecated. 

Wow I didn't even know that! Thanks for telling me 😁 

> That said, in the upcoming release we added a specific .NET 4.5 compilation platform target which fixes the issue and only brings the Autofac assembly along. You can test it out from our MyGet feed if you like.

Any chance you will publish 4.0.1 to NuGet.org too?

**Comment by tillig** [comment]
4.0.1 will eventually get there, yes. Hence "upcoming release." ;)

**Comment by mookid8000** [comment]
Excellent! 😁 Thanks

**Comment by mookid8000** [comment]
@tillig I may be impatient, but I went to [https://www.nuget.org/packages/Autofac/](https://www.nuget.org/packages/Autofac/) and have been pressing ⌘+R for six days now.... any idea when 4.0.1 is going to be on NuGet.org?

**Comment by tillig** [comment]
I appreciate your patience. [We work on a lot more than just core Autofac](http://www.paraesthesia.com/archive/2016/06/29/netcore-rtm-where-is-autofac/) and sometimes our paying jobs and families steal time and priority.

I'll see if I can get to this today.

**Comment by alexmg** [comment]
@tillig I was going to push a package earlier but thought I would wait to see how you went with the property injection fix. I guess that one can come in a follow-up release.

**Comment by tillig** [comment]
I wanted to get the property injection fix in at the same time but some other things took priority.

**Comment by alexmg** [comment]
Just pushed 4.0.1 over to NuGet. Let us know if you have any problems @mookid8000.

**Comment by mookid8000** [comment]
@alexmg @tillig you guys are awesome – I really appreciate it, thanks 👌 

I can go update  [Rebus.Autofac](https://github.com/rebus-org/Rebus/tree/master/Rebus.Autofac) now then 😄
