### ISSUE TITLE
Autofac 4.0 - .Net Framework 4.0 compatibility

### ISSUE THREAD

**Issue by wilhelmmedetz** [autofac/Autofac#792]
Are there any plans to make Autofac 4.0 compatible with .Net Framework 4.0?
Would it be possible?

(Would like to upgrade to Autofac 4.0 for all projects, but some projects still must support .Net Framework 4.0).

Thanks for any advice.

**Comment by tillig** [comment]
Unfortunately we're sticking with .NET 4.5+. No plans to back-rev.
