### ISSUE TITLE
RegisterGeneratedFactory and instance scope

### ISSUE THREAD

**Issue by rioka** [autofac/Autofac#793]
According to the docs, the default instance scope is _instance per dependency_.
Anyway, if I register a factory via `RegisterGeneratedFactory`, without specifying a scope, it seems that its scope is _instance per lifetime_.

Is this correct?
Should the docs be updated?

**Comment by tillig** [comment]
Failing unit test?

**Comment by rioka** [comment]
You can get it [here](https://gist.github.com/rioka/5b3c6daaf0a310216c3041e1c121728e)

**Comment by tillig** [comment]
Ah, I see what you're saying.

The _factory_ doesn't get regenerated every single time because that's kind of expensive. The _things you resolve from the factory_ behave correctly. Like this:

```csharp
[Fact]
public void Factory_ResolvedInstancesFromFactory()
{
  var builder = new ContainerBuilder();
  builder.RegisterType<SampleComponent>().As<ISampleComponent>();
  builder.RegisterGeneratedFactory<SampleComponent.AFactory>();
  var _container = builder.Build();
  var f1 = _container.Resolve<SampleComponent.AFactory>();
  var c1 = f1.Invoke(1);
  var c2 = f1.Invoke(1);

  Assert.NotSame(c1, c2);
}
```

Even though you've passed the same parameter into the factory, you'll notice you get different instances.

You control the lifetime of the components the factory provides by changing the component registrations. Also, be sure to resolve things out of lifetime scopes where possible because [resolving everything directly from the root container can cause inadvertent memory leaks](http://autofac.readthedocs.io/en/latest/resolve/index.html). It's also important if you want different lifetime scopes for things from your generated factory - you can't just resolve the factory one time at the start of the app and expect it to magically figure out what the current lifetime scope is.

Here's a passing test that illustrates the concept:

```csharp
[Fact]
public void Factory_InstancePerLifetimeScope()
{
	var builder = new ContainerBuilder();

	// Note the component is now InstancePerLifetimeScope
	builder.RegisterType<SampleComponent>().As<ISampleComponent>().InstancePerLifetimeScope();
	builder.RegisterGeneratedFactory<SampleComponent.AFactory>();
	var _container = builder.Build();

	ISampleComponent c1;
	ISampleComponent c2;
	using (var scope = _container.BeginLifetimeScope())
	{
		var f1 = scope.Resolve<SampleComponent.AFactory>();
		c1 = f1.Invoke(1);
		c2 = f1.Invoke(2);

		// These are the same because the component is instance per
		// lifetime scope. It's only going to resolve once.
		Assert.Same(c1, c2);
	}

	using (var scope = _container.BeginLifetimeScope())
	{
		var f1 = scope.Resolve<SampleComponent.AFactory>();
		c2 = f1.Invoke(2);

		// Now they're different because they came from different scopes.
		Assert.NotSame(c1, c2);
	}
}
```

**Comment by rioka** [comment]
Actually, it does make sense, except maybe this should be more evident from the docs.

Anyway, what if the factory is registered as singleton? In this case, disposable instances of types registered as  _instance per dependency_, resolved in a child scope, seem to be bound to root scope, ie they are not disposed when the scope they're resolved is disposed.

[Here](https://gist.github.com/rioka/a8d30a6d2287ff8849e5722bf0de03a3) is a test for this case.
Is this behavior the intended one?

**Comment by tillig** [comment]
Yep. If you resolve a disposable from the container it won't get disposed until you dispose the container.

There's a lot of this in the docs. [Take some time to read over the section on disposal.](http://autofac.readthedocs.io/en/latest/lifetime/disposal.html)

Don't register the factory as singleton or it will only resolve from the container. My best recommendation for you is to just not try to prematurely optimize, especially around the factory. Register your components correctly with the right lifetime scope and don't over think the factory part.

If you have further usage questions (How do I...? Is this the right way to...? Others have this working but I can't seem to...?) I'd like to try directing you to StackOverflow and tag your question "autofac". We could probably spend a lot of time going back and forth one on one here but there is a huge community of people there that can also help and the two of us on the project are spread a little thin right now. We also monitor StackOverflow, so you'll see us there, too.

If you have suggestions for improving the docs, we are happy to take issues and PRs on the Documentation repository.

**Comment by rioka** [comment]
Ok thanks.

I've been asked to migrate some projects currently using Castle Windsor to Autofac, so I've been trying to spot different behaviors upfront, to avoid issues later.

It is not about premature optimization, it's about a feature (ie factories) for which docs is a little bit misleading, or say it another way, specific behavior like the ones we've been talking about should be documented (especially for users coming from different libraries).
It was not clear, at least for me, that once you register a factory as a singleton (BTW it seems not so strange if, as you've said, creating a factory is an expensive operation), the instance you get is tied to the container, not to the scope in which it is resolved (and again, this is not the documented behavior). 

Just wanted to be sure the one I got was the intended behavior, and not a bug.

I'll try to integrate the docs with this notes, you you think they can be useful.

Thanks again.
