### ISSUE TITLE
NuGet/Xamarin

### ISSUE THREAD

**Issue by Fryhstyxei** [autofac/Autofac#802]
- Assembly version information for _all_ project dependencies (packages.config, project.json)

Pure new Xamarin/.NET Portable project (there's neither a packages.config nor a project.json). .NETPortable, Version=v4.5, Profile=Profile111

- The stack trace and message of any exception(s) encountered.

Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

- If possible, a reproduction of the issue (ideally in a unit test form).

Try to install autofac 4.1.1 using the NuGet Xamarin Studio/Visual Studio addin.

**Comment by tillig** [comment]
Autofac supports `netstandard1.1` which includes profile 111. If it can't be added, that indicates an older version of NuGet that doesn't understand the new netstandard monikers. Are you able to add any other .NET Core references, like Microsoft.Extensions.DependencyInjection?

**Comment by Fryhstyxei** [comment]
I was able to add Unity via the built-in NuGet Addin, just for test purposes.
I was also able to add autofac to my project by  downloading it manually!

I'm also going to try the following: Install a newer NuGet version and map the framework-link to nuget to the newer version. Stay tuned!

**Comment by tillig** [comment]
Unity doesn't target netstandard and CommonServiceLocator is a PCL, not something that targets a newer netstandard moniker, so that's not a valid test in this case.

Updating NuGet will probably help.

**Comment by tillig** [comment]
Any update on this? If it's resolved, I'd like to close it. If we don't hear back within a week or so, we'll also close the issue.

**Comment by Fryhstyxei** [comment]
Resolved. I'm sorry for my late response. I ended up using NuGet 3 CLI, completely independent from my IDE.
