### ISSUE TITLE
AutoFac Per Request Instance of dependency

### ISSUE THREAD

**Issue by FullyCSharped** [autofac/Autofac#803]
I have an API controller with a constructor parameter which is a EF repository class from [MembershipReboot](https://github.com/brockallen/BrockAllen.MembershipReboot) being injected, but the problem I am facing is that with the registration code I have currently any updates done on the DB are not fetched

var config = new HttpConfiguration();
config.MapHttpAttributeRoutes();

var builder = new ContainerBuilder();

builder.RegisterType<CustomUserRepository()
    .As<IUserAccountRepository<CustomUser>>()
    .WithParameter("ctx", new CustomDatabase(Constants.CONNECTION_STRING));
builder.RegisterApiControllers(Assembly.GetExecutingAssembly());

var container = builder.Build();
var resolver = new AutofacWebApiDependencyResolver(container);

How can i modify this registration so that I get a new instance every time for every request so that any updates done on the DB are also fetched.

I tried few extension methods to specify lifestyle behavior as mentioned in the [link](http://docs.autofac.org/en/latest/faq/per-request-scope.html) but doesn't work

**Comment by tillig** [comment]
Question [cross posted to StackOverflow](http://stackoverflow.com/q/40024013/8116).

For future reference, you can _just_ post usage questions there. We monitor those questions as well and it saves time not handling the same question twice.
