### ISSUE TITLE
where autofac.dll? my vs is 2013  

### ISSUE THREAD

**Issue by leizhizhi** [autofac/Autofac#804]
Google has been banned in China,so i can't use nuget

**Comment by leizhizhi** [comment]
Google has been banned in China,so i can't use nuget

**Comment by tillig** [comment]
NuGet isn't run by Google, but I understand the problem. Unfortunately we don't offer direct downloads. Have you tried the MyGet feed? Is that also blocked?

**Comment by leizhizhi** [comment]
no..I am chinese .english is so poor. i try it . thank you very much.

**Comment by leizhizhi** [comment]
sorry.MyGet is also blocked.

**Comment by tillig** [comment]
I [added a release with the latest Autofac package](https://github.com/autofac/Autofac/releases/tag/v4.1.1). You should be able to download from there.
