### ISSUE TITLE
Autofac with MVC 5 and Identity FW middleware

### ISSUE THREAD

**Issue by kazper** [autofac/Autofac#806]
When you google "autofac mvc 5 identity" you get first result for this nice looking article ["Configuring Autofac to work with the ASP.NET Identity Framework in MVC 5"](https://developingsoftware.com/configuring-autofac-to-work-with-the-aspnet-identity-framework-in-mvc-5/). I followed it and it worked great until I realized that the user identity does not get rejected when security stamp changes. To be more precise, UseCookieAuthentication's OnValidateIdentity in Startup.Auth does not get properly called when 'validateInterval' is elapsed. I am not sure of the reason because I did not have much success debugging the external Identity.Owin library. I imagine that the ApplicationUserManager does not get properly resolved but what boggles me is that no exceptions are thrown.

To verify my claims, you can download the source code from the article [here](https://developingsoftware.com/wp-content/uploads/AutofacIdentityExample.zip) and compare it to the default ASP.NET MVC project. Change the 'validateInterval' in Startup.ConfigureAuth from 30 minutes to ~1 second. If you log in with a user in two different browsers and change password in one then you should be logged out of the other browser's session as changing the password updates the security stamp. Or just log in with a user and change the security stamp manually under the AspNetUsers table.

Help on how to resolve this matter is highly appreciated!

**Comment by tillig** [comment]
This is a great question to ask over on [StackOverflow](http://www.stackoverflow.com). Tag it with `autofac` and other appropriate tags.

We love to help, but... We didn't write that article and, honestly, the problem you're describing sounds like an issue with the identity stuff not working rather than a problem with how the DI is configured. Getting more eyes on the question from the community will help get you an answer faster.

**Comment by kazper** [comment]
Ok, thanks! I post it here if anyone's curious - http://stackoverflow.com/questions/40185064/autofac-with-asp-net-identity-in-mvc-5-does-not-validate-security-stamp-in-owin
