### ISSUE TITLE
Improve cleanup on lifetime scope disposal

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac#807]
Based on notes in [this StackOverflow question](http://stackoverflow.com/questions/40290851/autofac-owin-and-memory-leaks-is-autofac-leaking-with-owin), it seems `LifetimeScope` doesn't clean up after itself as well as it could.

For example, after calling `Disposer.Dispose()` to clean up `IDisposables` in the scope, should we also call [`_sharedInstances.Clear()` to remove references from the shared instances](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Core/Lifetime/LifetimeScope.cs#L49)?

Are there other places we're inadvertently holding references longer than needed?

**Comment by OnurGumus** [comment]
Can we back port this change to 3.5.x as well ? We are waiting .NET Core to be more matured.

**Comment by tillig** [comment]
@OnurGumus The 4.x series of Autofac is not just for .NET Core. If you want the updates, you'll need to upgrade.
