### ISSUE TITLE
how to get the current scope on asp.net core

### ISSUE THREAD

**Issue by xLabel** [autofac/Autofac#808]
on mvc3/4 , we can using Autofac.Integration.Mvc.AutofacDependencyResolver to get current lefttime, like the picture example. But now is on asp.net core , the new platform is using 'Autofac.Extensions.DependencyInjection.AutofacServiceProvider' to set in .
i must get the current scope to resolve the same instance.  (which is registertype is InstancePerLifetimeScope) .

please help !!!
![image](https://cloud.githubusercontent.com/assets/3363613/19960534/6f460b4a-a1e8-11e6-8764-c57d20cab5f9.png)

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Extensions.DependencyInjection#6
