### ISSUE TITLE
Autofac.Configuration. Generic interface configuration problem.

### ISSUE THREAD

**Issue by Defee** [autofac/Autofac#810]
Hi.
Here is the case I want to use Autofac:

1. Use JSON Config to specify dependencies.
2. I have generic Interface.
3. I have generic Interface realization to use as the injected object
To reproduce issue you can download the package I tested on odec.Category.DAL.

Interface
```
public interface ICategoryRepository<in TKey, TContext, TCategory, in TCategoryFilter> :
        IEntityOperations<TKey, TCategory>,
        IActivatableEntity<TKey, TCategory>,
        IContextRepository<TContext>
        where TKey : struct 
        where TCategory : class
    {
        IEnumerable<TCategory> Get(TCategoryFilter filter);
        IEnumerable<TCategory> GetForAutoComplete(string term, int? maxRows = null);

        void ApproveCategory(TCategory category);
    }
```
Realization (Code details are unneccessary)
```
public class CategoryRepository : 
        OrmEntityOperationsRepository<int, Server.Model.Category.Category, DbContext>, 
        ICategoryRepository<int, DbContext, Server.Model.Category.Category, CategoryFilter>
    {...}
```
 I tried for the config:

**_Case 1- fully qualified name of the ICategoryRepository<int, DbContext,_** Server.Model.Category.Category, CategoryFilter>:
"components": [
        {
            "type": "odec.Category.DAL.CategoryRepository, odec.CP.Category.DAL",
            "services": [
                {
                    "type": "odec.Category.DAL.Interop.ICategoryRepository`4[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.EntityFrameworkCore.DbContext, Microsoft.EntityFrameworkCore, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[odec.Server.Model.Category.Category, odec.CP.Server.Model.Category, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[odec.Server.Model.Category.Filters.CategoryFilter, odec.CP.Server.Model.Category, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
                }
            ],
            "injectProperties": true
        }
    ]

**Error: The Type "ICategoryRepository" could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".could not be found**.

**_Case 2 - Simple name of the type._** 
"components": [
        {
            "type": "odec.Category.DAL.CategoryRepository, odec.CP.Category.DAL",
            "services": [
                {
                    "type": "odec.Category.DAL.Interop.ICategoryRepository, odec.CP.Category.DAL.Interop"
                }
            ],
            "injectProperties": true
        }
    ]

**Error: The Type "ICategoryRepository" could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".could not be found**.

**_Case 3 - Name of generic interface_** 
"components": [
        {
            "type": "odec.Category.DAL.CategoryRepository, odec.CP.Category.DAL",
            "services": [
                {
                    "type": "odec.Category.DAL.Interop.ICategoryRepository`4, odec.CP.Category.DAL.Interop"
                }
            ],
            "injectProperties": true
        }
    ]
**Error: Autofac has found the interface for now, but he said:
The type 'odec.Category.DAL.CategoryRepository' is not assignable to service 'odec.Category.DAL.Interop.ICategoryRepository4'.
It seems to be a false, because the CategoryRepository is the realisation of ICategoryRepository<,,,,>**.

Please help. The goal is to do it from the configuration.

**Comment by tillig** [comment]
A better place to ask "How do I...?" questions is StackOverflow and tag it `autofac`. We watch there as well as here (So you don't need to cross post), but there is a larger community available there to help faster.

In the meantime I'll move this to the correct repo.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Configuration#9
