### ISSUE TITLE
Aspnet Core view debugging is broken

### ISSUE THREAD

**Issue by ShadowDancer** [autofac/Autofac#812]
If you use AspNet Core with net46 framework and You have following entries in project.json:
```
{
    "Autofac": "4.0.0",
    "Autofac.Extensions.DependencyInjection": "4.0.0",
}
```

You may face issue where breakpoint in view  is not hit, instead debugger breaks on next instruction that would be executed after all view (wrong instruction is shown). To solve this problem you need to update autofac to version 4.2.0:
```
{
    "Autofac": "4.2.0",
    "Autofac.Extensions.DependencyInjection": "4.0.0",
}
```

**Comment by ShadowDancer** [comment]
I wanted to put it here in case others face similar issue, because google is silent about this.

**Comment by alexmg** [comment]
Thanks for the leaving the note @ShadowDancer. I suspect that someone will end appreciate this. 👍
