### ISSUE TITLE
help,how I can pass a variable parameter value like this below......

### ISSUE THREAD

**Issue by 564064202** [autofac/Autofac#817]
builder.RegisterType<CustomerEntities>().
               As<DbContext>().WithParameter("nameOrConnectionString", **changeAnyTime**).
               InstancePerRequest();

**Comment by tillig** [comment]
As noted in the issue template, [have you tried StackOverflow first?](http://stackoverflow.com) There's a much larger community there able to answer your questions in a more timely fashion. We also monitor StackOverflow, so I'd recommend re-asking the question there (after searching for your answer through the existing questions there) and tag it `autofac`.
