### ISSUE TITLE
Can't install on portable-net452+win81 (System.Collections conflict)

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [autofac/Autofac#818]
Project type: Class Library
**Autofac v4.2.1**

Project targets:
- .NET Framework 4.6
- Windows 10

**project.json** content
```json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net452+win81"
    }
  }
}
```

Installation fails with:
```
...
PM> Install-Package Autofac
Restoring packages for 'ClassLibrary1'.
Restoring packages for C:\ClassLibrary1\project.json...
Install-Package : Version conflict detected for System.Collections. 
 ClassLibrary1 (>= 1.0.0) -> Autofac (>= 4.2.1) -> NETStandard.Library (>= 1.6.0) -> System.Collections (>= 4.0.11) 
 ClassLibrary1 (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (= 4.0.10).
At line:1 char:1
+ Install-Package Autofac
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Autofac 4.2.1 is not compatible with .NETPlatform,Version=v5.0.
At line:1 char:1
+ Install-Package Autofac
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with .NETPlatform,Version=v5.0.
At line:1 char:1
+ Install-Package Autofac
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Ins 
   tallPackageCommand
 
```

Similar issues with:
* Simple Injector https://github.com/simpleinjector/SimpleInjector/issues/360
* MvvmCross https://github.com/MvvmCross/MvvmCross/issues/1391

**Comment by tillig** [comment]
What happens if you update to [`Microsoft.NETCore.Portable.Compatibility` 1.0.1](https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility/1.0.1)?

I ask because I'm not sure there's much we can do from the Autofac side. The problem is in bad version specifications in the .NET Core base libraries used by the `Microsoft.NETCore.Portable.Compatibility` package, not a binding we specifically put in. Autofac is following [the recommended practice of referencing the `NETStandard.Library` package](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries) so it's not something we can change or control from this end.

It seems like a similar answer is being reached in the other issues you filed - something needs to happen in base .NET Core rather than the libraries that are consuming it.

**Comment by UnderHeavyDevelopment** [comment]
Here are some tries:

1. Try number one: Install ``Microsoft.NETCore.Portable.Compatibility`` 1.0.1

Result: **Fail**  
Target: ``PCL portable-net452+win81``
``Microsoft.NETCore`` 5.0.0
``Microsoft.NETCore.Portable.Compatibility`` 1.0.1

``project.json``
```json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net452+win81"
    }
  }
}
```

Fails with:

```
PM> Install-Package Microsoft.NETCore.Portable.Compatibility -v 1.0.1
Install-Package : Microsoft.NETCore.Portable.Compatibility 1.0.1 is not compatible with .NETPlatform,Versi
on=v5.0.
```

---

2. Workaround number two: downgrade target from Windows 10 to Windows 8.1

Result: **Success**
Target: ``PCL Profile44``

```project.json```
```json
{
  "supports": {},
  "dependencies": {
    "Autofac": "4.2.1"
  },
  "frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile44": {}
  }
}
```

---

3. Workaround number three: Install Autofac on .NETStandard target

Result: **Success**
Target: ``.NETStandard 1.1``

``project.json``
```json
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.0",
    "Autofac": "4.2.1"
  },
  "frameworks": {
    "netstandard1.1": {}
  }
}
```

---

However these don't solve the problem 100%.

**Comment by UnderHeavyDevelopment** [comment]
Update: I think, workaround 3. solves my problem. I've checked https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries#how-to-target-the-net-standard and for my needs, ``.NETStandard 1.4`` is ok. I can install Autofac on this target.

Then I can reference such library in UWP app and WPF app targeting .NET 4.6. Solution then compiles and runs. I will update if any news.
