### ISSUE TITLE
I cannot upgrade autofac package to the latest version because it required .net 4.5.1

### ISSUE THREAD

**Issue by aleksandar1971** [autofac/Autofac#820]
I tried updating nuget package to the latest version in my MVC project but it fails because it requires .net 4.5.1. Our company is using VC 2012 and .net 4.5 and I cannot upgrade .net at this point because it has to be update on all infrastructure.
Can you guys add 4.5 folder in nuget package for my upgrade to work?

**Comment by tillig** [comment]
[The latest, Autofac 4.2.1, specifically already targets .NET 4.5.](https://www.nuget.org/packages/Autofac/4.2.1) If it's not being recognized, it's a NuGet problem - like your version of NuGet is too old to recognize some of the newer package formatting. There's not anything we can do about that... But we do already support .NET 4.5.
