### ISSUE TITLE
Support instance`s life-scope based on external events

### ISSUE THREAD

**Issue by HamedFathi** [autofac/Autofac#822]
Consider below code in ASP.NET Core

```

public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry(Configuration);
            services.AddMvc();
            var builder = new ContainerBuilder();

            var loader = new LoadEngine<IContract>(@"DIRECTORY PATH") // works based on FileSystemWatcher and have ConcurrentDictionary as repository so can return latest types.
                .EnableHotPlug()
                .Build();

            var type = loader.GetInstances().FirstOrDefault().GetType(); // First Time
            builder.RegisterType(type).As<IContract>(); // First RegisterType

            loader.OnChange += () => // LoadEngine detect some changes in plugin directory so fire OnChange
            {
                type = loader.GetInstances().FirstOrDefault().GetType(); // Get latest instance from LoadEngine
                builder.RegisterType(type).As<IContract>(); // Register again in Autofac Container
            };

            builder.Populate(services);
            var container = this.ApplicationContainer = builder.Build();
            return new AutofacServiceProvider(this.ApplicationContainer);
        }

```

I wrote a LoadEngine based on FileSystemWatcher when a plugin (.dll) created/deleted/updated in that directory reload types into memory and provide new instance so this library have OnChange event

I want to have instance`s life-scope based on an event when event call Autofac reinstantiation that object.

Now first Resigter type is OK but on event despite of existing a new type Autofac send old type to controllers

**Comment by tillig** [comment]
[Is this your question on StackOverflow?](http://stackoverflow.com/q/41393516/8116)

**Comment by HamedFathi** [comment]
@tillig 

Yes but in stackoverflow I tried use Scopes but in this request I say better autofac works with events for override registration.

See this [Override autofac registration with plugin](http://stackoverflow.com/questions/15754702/override-autofac-registration-with-plugin)

based on answer 

> If you register some interface implementations, **Autofac will use the latest registration.** Other registrations will be overridden. In your case, Autofac will use the plugin registration, if plugin exists and register own IFoo service implementation.

I tried it on event but does not work.

**Comment by tillig** [comment]
As noted on the StackOverflow question, we really need the full code - the stuff you put in this issue - to be in the question so we can see exactly what's going on rather than something "trimmed down."

Please update your SO question and we can finish answering things there. That way not only will the community benefit from the answer, but they'll also have the ability to chime in.

**Comment by HamedFathi** [comment]
@tillig 

Hi

I re-ask the question with more details and a sample code.
If you can and have time please help me

Thanks.
