### ISSUE TITLE
SingleInstance registration not working as expected.

### ISSUE THREAD

**Issue by StephenHurn** [autofac/Autofac#829]
I have created a test application to clarify autofac registration types to my team.  However, it appears that a class registered as SingleInstance creates a unique instance for each scope in my demo app.

I would have expected that each call to resolve the MySingleInstance class would return the same instance, but as can be seen when the app is run, a new instance is created per lifetime scope.

[AutofacDemo.zip](https://github.com/autofac/Autofac/files/762961/AutofacDemo.zip)

**Comment by tillig** [comment]
This sort of "Others have this working but I can't get it..." question is, as noted in the issue template, a great thing for StackOverflow since it allows many others to contribute to the discussion and there are a _lot_ more people who can get eyes on it.

**Comment by tillig** [comment]
The problem is you're not creating lifetime scopes correctly. Don't new up a lifetime scope. Use the `BeginLifetimeScope` method to create a child scope.

```csharp
using(var scope1 = container.BeginLifetimeScope())
{
  using(var scope2 = scope1.BeginLifetimeScope())
  {
   scope2.Resolve<Whatever>();
  }
}
```

[Please see documentation here.](http://autofac.readthedocs.io/en/latest/lifetime/working-with-scopes.html)

**Comment by StephenHurn** [comment]
Thanks for your help.
