### ISSUE TITLE
Support arrays in collection registrations

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#83]
_From [nicholas...@gmail.com](https://code.google.com/u/104985896277148547614/) on September 25, 2008 13:30:54_

Currently only IEnumerable<T>, ICollection<T> and IList<T> are supported.

_Original issue: http://code.google.com/p/autofac/issues/detail?id=82_

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Wcf#9
