### ISSUE TITLE
Autofac.Wcf: using svc-less service, "service" attribute must be fully-qualified type name

### ISSUE THREAD

**Issue by Dennis-Petrov** [autofac/Autofac#830]
Hi.  
When using svc-less [sample](http://autofac.readthedocs.io/en/latest/integration/wcf.html#svc-less-services) from Autofac docs, one must set fully-qualified type name in `service` attribute, e.g.:

                <add factory="Autofac.Integration.Wcf.AutofacServiceHostFactory" relativeAddress="Service1.svc" service="WcfService_CustomInstantiation.Service1, WcfService_CustomInstantiation"/>

If assembly name part will be omitted (as it should be), Autofac can't resolve service:

> [InvalidOperationException: The service 'WcfService_CustomInstantiation.Service1' configured for WCF is not registered with the Autofac container.]
>    Autofac.Integration.Wcf.DefaultServiceImplementationDataProvider.GetServiceImplementationData(String value) +892
>    Autofac.Integration.Wcf.AutofacHostFactory.CreateServiceHost(String constructorString, Uri[] baseAddresses) +133
>    System.ServiceModel.HostingManager.CreateService(String normalizedVirtualPath, EventTraceActivity eventTraceActivity) +1849
>    System.ServiceModel.HostingManager.ActivateService(ServiceActivationInfo serviceActivationInfo, EventTraceActivity eventTraceActivity) +66
>    System.ServiceModel.HostingManager.EnsureServiceAvailable(String normalizedVirtualPath, EventTraceActivity eventTraceActivity) +738
> 

I think, this either should be mentioned in docs, or (better option) is fixed in WCF integration code.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Wcf#10
