### ISSUE TITLE
ASP.NET Web API (4.6) property injection into filters

### ISSUE THREAD

**Issue by brgrz** [autofac/Autofac#831]
I'm having an issue where I'm doing property injection within filters/attributes.

The issue is that filters registered through 

`config.Filters.Add(new MetadataDecoratorAttribute());`

do not get their public properties injected

`public MyEntities DbContext { get; set; }`

while if I apply those filters to the controllers (or, in my case to our base api controller) like this

```
[MetadataDecorator]
public class ApiControllerBase : ApiController
```

then property injection does happen.

I am using the filter registration as instructed

```
// register DI for Web API attributes (action filters)
builder.RegisterWebApiFilterProvider(GlobalConfiguration.Configuration);
```

However the filters in question do not implement Autofac's` IAutofacActionFilter` because that one cannot be used in `config.Filters.Add(`) but they do inherit the `ActionFilterAttribute `class.

For now, we have reverted to attaching the filters to the base ctrl class but I think this is a bug that should be resolved/explained because adding through` config.Filters.Add() `should also work.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.WebApi#23
