### ISSUE TITLE
Cant resolve exception if I dont wait for container to build

### ISSUE THREAD

**Issue by leaderanalytics** [autofac/Autofac#832]
If I just run the unit test it crashes with the exception shown below.
If I place a breakpoint on the line after builder.Build() and press F10 to step through the code it works.
I am not using threads or tasks or async in any of my code proior to where it breaks.
I can reproduce this at will.   Let me know if you need additional code I have it on GitHub.
 
```csharp
[TestMethod]
public void WCF_returns_user()
{

	Mock<INetworkUtilities> mock = new Mock<INetworkUtilities>();
	mock.Setup(x => x.VerifyDBServerConnectivity(It.IsAny<string>())).Returns(false);
	mock.Setup(x => x.VerifyHttpServerAvailability(It.Is<string>(c => c == "http://localhost:61401/"))).Returns(true);
	INetworkUtilities networkUtilitiesMoq = mock.Object;
	builder.RegisterInstance(networkUtilitiesMoq).As<INetworkUtilities>();
	IContainer container = builder.Build();

	IAdaptiveClient<IUsersService> usersClient = container.Resolve<IAdaptiveClient<IUsersService>>();
	int userID = usersClient.CallAsync(x => x.SaveUser(new User { Name = "New User" })).Result;
	User userResult = usersClient.CallAsync(x => x.GetUser(userID)).Result;
	Assert.AreEqual("Application_WCF", usersClient.CurrentEndPoint.Name);
	Assert.IsNotNull(userResult);
	Assert.AreEqual("New User", userResult.Name);
}

```

```
	System.AggregateException occurred
	  HResult=0x80131500
	  Message=One or more errors occurred.
	  Source=<Cannot evaluate the exception source>
	  StackTrace:
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at AdaptiveClientDemo.Tests.IntegrationTests.WCF_returns_user() in C:\Git\AdaptiveClient.AdvancedDemo\AdaptiveClientDemo\test\AdaptiveClientDemo.Tests\IntegrationTests.cs:line 97
```
Inner Exception 1:
FaultException`1: The requested service 'InProcess (LeaderAnalytics.AdaptiveClient.IEndPointValidator)' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

```xml
	<ItemGroup>
		<!--<PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.0" />-->
		<PackageReference Include="AdaptiveClient" Version="0.16.0" />
		<PackageReference Include="Autofac" Version="4.3.0" />
		<PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
		<PackageReference Include="Moq" Version="4.7.1" />
		<!--<PackageReference Include="dotnet-test-nunit" Version="3.4.0-beta-1" />
		<PackageReference Include="NUnit" Version="3.6.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="3.7.0" />-->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="1.1.12" />
		<PackageReference Include="MSTest.TestFramework" Version="1.1.11" />
	  </ItemGroup>
```

**Comment by tillig** [comment]
This is probably better suited for [StackOverflow](http://stackoverflow.com) with an `autofac` tag. There are really only two of us watching issues (the project maintainers) while StackOverflow has a pretty large community of people able to help. We also watch over there, so you'll be getting the best of all worlds.

If you wouldn't mind, please [head over there](http://stackoverflow.com) and ask your question. Tag it with `autofac` as well as `moq` and whatever app type you're using (I'm unfamiliar with `AdaptiveClient` - is it WCF? REST? Add whatever relevant tags to the question.)

In your question, include what you have here as well as...

- Where are you creating the `ContainerBuilder`?
- What is registered in it by default?
- Where are you registering the `IEndpointValidator`?
- Where are you registering the `InProcess`? (It appears that's a service from the stack trace... possible copy/paste issue if it's not?)
- What does the constructor of the `IAdaptiveClient<IUsersService>` look like?

Note that generally people aren't going to be so helpful if you just link to a GitHub repo and tell them to go elsewhere. It'll be good to include the link, but make it easy for the people _answering_ the question to get what they need without a whole lot of research and code spelunking.

**Comment by leaderanalytics** [comment]
thank you tillig, sorry about not including the code - there is a lot of it and it is scattered everywhere.
