### ISSUE TITLE
Integration with NSubstitute?

### ISSUE THREAD

**Issue by grokky1** [autofac/Autofac#833]
Autofac has integration packages for [Moq](http://docs.autofac.org/en/latest/integration/moq.html) and [FakeItEasy](http://docs.autofac.org/en/latest/integration/fakeiteasy.html).

Is there something similar for NSubstitute?

**Comment by tillig** [comment]
If you do a search for "Autofac NSubstitute" you will find a couple of community owned packages that may help. There are no official packages for this and none currently planned.

**Comment by grokky1** [comment]
For anyone else who's interested, there is a [good one here](http://github.com/MRCollective/AutofacContrib.NSubstitute) though it does not yet support .NET Core.
