### ISSUE TITLE
Does Owned<> control disposal only, or does it also control dynamic resolutions?

### ISSUE THREAD

**Issue by grokky1** [autofac/Autofac#834]
I hope this is the right place, because there's no repo for `Autofac.Extensions.DependencyInjection`.

Environment: 
- ASP.NET Core 1.1
- Autofac.Extensions.DependencyInjection 4.0.0

I registered a singleton `Singleton`, which has a constructor injected per-request dependency `IContext`. To avoid a captive dependency bug, I inject it as `Func<IContext>`, and create instances when needed. I expect the delegate factory to give me unique instances every time.

However that's not the case. The instances are always the same object.

I can fix this by changing to `Func<Owned<IContext>>`.

Here is a minimal repro app: the [`project.json`](http://gist.github.com/grokky1/f9de3452cbcfffec04015521dc849f0e) and the [app itself](http://gist.github.com/grokky1/14bc8ce115420a4655c2488d794e4c1d). It runs as an ASP.NET Core console app, without any tweaking necessary.

Is this a bug or by design? I read [the docs](http://autofac.readthedocs.io/en/latest/advanced/owned-instances.html), and I understood that `Owned<>` simply controls disposal. Why does it, in this case, control whether the container resolves the same or a new instance?

**Comment by tillig** [comment]
You get a new context because you registered it instance per lifetime scope and owned items get a tiny lifetime scope. From the docs:

> When `Consumer` is created by the container, the `Owned<DisposableComponent>` that it depends upon will be created inside its own lifetime scope. When `Consumer` is finished using the `DisposableComponent`, disposing the `Owned<DisposableComponent>` reference will end the lifetime scope that contains `DisposableComponent`.

**Comment by grokky1** [comment]
@tillig Thanks Travis! Sorry for the "...a bug or by design..." comment 😆 

As a rule of thumb then, to avoid the "captive dependency" problem which you wrote about (a singleton depending on something non-singleton for e.g.), would it be a good idea to always use `<Func<Owned<Foo>>` in such cases? Or is it a one of those "it depends" situations.

**Comment by tillig** [comment]
It's always "it depends." Usually the best answer is to match lifetime scopes where possible - all singletons, all per request, etc. Or use singletons at the leaf level - repositories and things that have no dependencies - and per dependency or per scope for things that consume those things.

But... It always depends. No "rule of thumb."

**Comment by mderriey** [comment]
Just as a sanity check, since @grokky1 expects new instances of `Context` when invoking the `Func<Context>`, wouldn't it be easier to register it as a transient component with `.InstancePerDependency()` rather than per lifetime scope?

For some context, that discussion comes from this [StackOverflow question](http://stackoverflow.com/q/42744319/562839) and @grokky1 thinks `Owned` is the solution to his problem when I think it's a registration issue in the first place.

Still, good to know that `Owned` *overrides* the lifetime scope and creates one for the life of the component. Very informative, thanks.
