### ISSUE TITLE
UWP VS XAML Designer Issue Specific To Autofac 4.X

### ISSUE THREAD

**Issue by jdomotomlb** [autofac/Autofac#835]
There seems to be a problem using Autofac 4.X in a UWP project and supporting design time creation.  An error is shown in XAML reading, "Could not load file or assembly 'Autofac, Version=4.3.0.0, Culture=neutral, PublicTokenKey=17863af14b0044da' or one of its dependencies.  The system cannot find the file specified." This issue does not exist when using Autofac 3.5.X.

Repro Steps
1. Download and extract Repro.zip
[Repro.zip](https://github.com/autofac/Autofac/files/845621/Repro.zip)
2. Open .sln in VS2015
3. Set platform to x86
4. Build
5. Open MainPage.xaml (see error as shown in the below image)
<img width="1440" alt="issue" src="https://cloud.githubusercontent.com/assets/26442220/23964617/48e6a936-0972-11e7-9531-7b27e929da0a.png">

**Comment by tillig** [comment]
This isn't an Autofac problem, it's a problem with the XAML designer. I just ran into this myself the other day. The reason it happens is the designer creates a shadow copy of your app but, for whatever reason, _doesn't actually copy all of the assemblies into the shadow copy_.

[I blogged details about how to debug into the XAML designer here.](http://www.paraesthesia.com/archive/2017/03/13/how-to-debug-the-xaml-designer/) If you can figure out how to force the XAML designer to copy all the assemblies into the shadow copy area, I'd be happy to update the docs to explain how to get that to work. But... there's nothing we can do from the Autofac side (that I can tell) to _force_ that to happen.

Sorry. :(

**Comment by tillig** [comment]
I think it may have to do with the new package target framework monikers - netstandard and such - that didn't exist prior to UWP and other newer package types. That's why I think it doesn't happen with Autofac 3.5.x - because we didn't actually specify the wider range of compatibility. I don't think the XAML designer knows what to do with it.

**Comment by timg-mlbam** [comment]
I noticed that this still unfortunately happens with VS2017 :(

fyi in case it's useful, I was able to confirm your explanation and manually fix it by copying autofac.dll from my bin folder into the shadowCache folder.

**Comment by tillig** [comment]
It appears [this issue](https://developercommunity.visualstudio.com/content/problem/35539/could-not-load-file-or-assembly-error-when-using-s.html) will be resolved in VS 2017 15.5.
