### ISSUE TITLE
Can I configure interception using xml/json configuration?

### ISSUE THREAD

**Issue by renetitulaer** [autofac/Autofac#836]
Hi,

I'm thinking about migrating from Unity to Autofac.

I need interception, which is supported by autofac:
http://docs.autofac.org/en/latest/advanced/interceptors.html

in combination with xml/json configuration, which is supported by autofac also:
http://docs.autofac.org/en/latest/configuration/xml.html

Is this possible? Can't find anything in the autofac docs or on the internet. With unity this is possible.

**Comment by tillig** [comment]
As noted in the docs:

> Before diving too deeply into JSON/XML configuration, be sure to read [Modules](http://autofac.readthedocs.io/en/latest/configuration/modules.html) - this explains how to handle more complex scenarios than the basic JSON/XML component registration will allow.

The configuration file mechanism isn't intended to be a 100% 1:1 feature replacement for code-based configuration. Modules are the bridge.
