### ISSUE TITLE
Passing constructor parameters from a config file does not work

### ISSUE THREAD

**Issue by arnamq** [autofac/Autofac#837]
Hi,

When I try to pass a constructor parameter from the config file it is ignored by the method IContainer.ResolveNamed.

My config looks like that:
```
     "parameters":{
        "constructorParamName":["stringValue1", "stringValue2"]
     }
```
and the constructor:

`public MyClassConstructor(IList<string> constructorParamName = null) `

Passing properties works fine.

Best regards,
arnam

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.Configuration#12
