### ISSUE TITLE
Attribute filtering not functional when using parameterized instantiation?

### ISSUE THREAD

**Issue by GeorgeTsiokos** [autofac/Autofac#839]
Expected / actual output: `string, abc, 123`
```c#
Console.WriteLine(container.Resolve<Target>());
Console.WriteLine(container.Resolve<Func<Target>>()());
```

Expected output: `first, abc, 123`
```c#
Console.WriteLine(container.Resolve<Target>(new PositionalParameter(0, "first")));
Console.WriteLine(container.Resolve<Func<string, Target>>()("first"));
```
The parameterized factory's output, `Func<string, Target>`, was `first, first, first` using this builder:
```c#
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterInstance("string").As<string>();
containerBuilder.RegisterInstance("abc").Named<string>("letters");
containerBuilder.RegisterInstance("123").Named<string>("numbers");
containerBuilder.RegisterType<Target>().AsSelf().WithAttributeFiltering();
var container = containerBuilder.Build();
```
Second and third constructor parameters use a `KeyFilter`:
```c#
public class Target
{
    public Target(string first, [KeyFilter("letters")] string second, [KeyFilter("numbers")] string third)
    {
        First = first;
        Second = second;
        Third = third;
    }

    public string First { get; }

    public string Second { get; }

    public string Third { get; }

    public override string ToString()
    {
        return $"{First}, {Second}, {Third}";
    }
}
```

**Comment by tillig** [comment]
[Per the docs](http://autofac.readthedocs.io/en/latest/resolve/relationships.html#parameterized-instantiation-func-x-y-b):

> Internally, Autofac treats these as typed parameters. What that means is that **auto-generated function factories cannot have duplicate types in the input parameter list.**

Basically, what you're seeing may be confusing but it's not unexpected.

Attribute filtering really isn't going to work well in combination with parameters you're passing in - either manually or via auto-generated factory. It's really just for resolving without parameters.

Once you try to mix and match you're getting into real edge case territory where we can't win - there's no way to easily automatically infer what the developer's intent is. Was the intent to override an auto resolved parameter or pass a different one in? If we fix it one way, the other half will loudly complain that we guessed wrong.

If you want to do this, I'd recommend registering a custom lambda registration that handles all the crazy factory stuff you might need. (I'm on a phone right now so no samples, sorry.)

**Comment by GeorgeTsiokos** [comment]
I missed that limitation -  The function factories I've used in the past must have been using different types... I completely understand why typed parameters are used instead of positional. My workaround involved creating a separate type to hold the attribute filtered dependencies, allowing me to use a `Func<>` as designed, with typed parameters - I can specify the first constructor parameter while autofac injects the other _WithAttributeFiltering_. Thank you!
