### ISSUE TITLE
RegisterAssemblyTypes should throw helpful exception if no assemblies provided

### ISSUE THREAD

**Issue by jamezor** [autofac/Autofac#843]
Since `RegisterAssemblyTypes` takes a params array of assemblies, it is possible to pass nothing at all. Which happily looks like it has done something, leading to hours of frustration about why your registrations are not being picked up.

Thus I propose that the null check around line 42 in `ScanningRegistrationExtensions.cs` be joined with a length check which would throw an `ArgumentException` explaining how you really should provide at least one assembly to scan.

If the maintainers agree this would be handy then I'll whip up a pull request with unit tests.

**Comment by alexmg** [comment]
I don't think that throwing an exception here is the right option. It is easy to imagine that assembly scanning is often combined with the dynamic discovery of assembly (perhaps a plugin model of sorts). In a scenario such as this finding no assemblies would be reasonable and throwing an exception would cause the application to fail unexpectedly.

You could write your own extension method that performs the check and passes through to the existing `RegisterAssemblyTypes` method. Having faced this issue once though I suspect that this isn't something that will catch you out again. 😃

Thanks for the PR offer but I think we will leave this one with the current behaviour.
