### ISSUE TITLE
Add resolve parameters to constructor selectors

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac#846]
Based on [this StackOverflow question](http://stackoverflow.com/questions/43399385/autofac-unable-to-resolve-between-two-constructors-when-one-is-clearly-more-spec):

If you wanted your constructor selector to behave differently based on parameters provided during the `Resolve()` operation, you couldn't currently do that because all the selector gets is a list of reflected constructor bindings that have been filtered down by which ones can be resolved - not really where those parameters came from or what the available parameter set is.

To allow constructor selectors to be more functional, I propose we enhance `IConstructorSelector` to also take the set of `Parameter` objects being used at the time of resolution.

**Comment by GKBelmonte** [comment]
I think it's worth pointing out that a constructor with 2 Autowiring parameters will win on a Resolve with 1 named parameter.
IMHO opinion "user specified parameter" > "autowiring" > "default"
Thanks a lot!

**Comment by tillig** [comment]
The order of parameter usage is sort of orthogonal to this enhancement request. The point of the enhancement is that if you wanted to change the selector behavior, this opens up that extension point.

**Comment by GKBelmonte** [comment]
True, I guess if I can provide IConstructorSelector to do my "specificity" system, I could do it!

**Comment by GKBelmonte** [comment]
(also tangential, whoever initially created the code in Autofac 1.4.4 used to work in the same scenario. Since there's too much overhead to plugging delegates and there's piles of overloaded constructors I've opted for loading 2 versions of Autofac for now.)

**Comment by tillig** [comment]
Autofac 1.4.4 was... _a long time ago_. The oldest NuGet package out there is [2.2.4 from January 2011](https://www.nuget.org/packages/Autofac/2.2.4.900); [this blog article](https://nblumhardt.com/2009/12/autofac-2-status-update/) from @nblumhardt shows that Autofac 2 was being worked on around the 2009 time... so I'm guessing Autofac 1.4.4 was around... 2008-ish? Sorry things have changed since then so they don't work as expected. Hopefully opening an extension point like this will help.

**Comment by GKBelmonte** [comment]
It's all good, I don't expect it to, i'm just the poor sucker maintaining legacy code until they tell me to go away for a month and re-write the entire thing ;) 
I'm just letting you know that the behaviour was indeed supported at some point

**Comment by tillig** [comment]
Fix released in [v4.7.0](https://www.nuget.org/packages/Autofac/4.7.0).
