### ISSUE TITLE
Feature Request: Enable customizing IIndex<K,V>

### ISSUE THREAD

**Issue by amithegde** [autofac/Autofac#848]
I tried to inherit the interface `IIndex<K,V>` and use it as constructor parameter which did not work. I took a  look at how `IIndex<K,V>` is registered and realized that a class implements it within `Autofac` and there seem to be no way to inherit or implement `IIndex<K,V>` and resolve dependencies using keyed index.

Please allow inheriting/implementing `IIndex<K,V>`.

**Comment by tillig** [comment]
The interface is [already public](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Features/Indexed/IIndex.cs) so you can implement it if you want. Can you provide a code snippet showing what you're trying to do that isn't working?

**Comment by alexmg** [comment]
You won't be able to register your own implementation of `IIndex<K,V>` as an open generic registration because Autofac will replace it with its own during container build.

```
this.RegisterGeneric(typeof(KeyedServiceIndex<,>)).As(typeof(IIndex<,>)).InstancePerLifetimeScope();
```

It would be possible to register a closed generic type manually as this will take precedence over the open generic registration.

```
builder.RegisterType<MyKeyedService<string, string>>().As<IIndex<string, string>>();
```

If you aren't going to use `IIndex<K,V>` it in the manner supported by Autofac then you are probably better off creating your own similar interface.

I am interested to know what were aiming for when implementing this type yourself?

**Comment by amithegde** [comment]
Here is my code:

void Main()
{
	var builder = new ContainerBuilder();
	builder.RegisterType<MyClass1>().Keyed<IMyInterface>(Stragegy.Class1);
	builder.RegisterType<MyClass2>().Keyed<IMyInterface>(Stragegy.Class2);
	
	builder.RegisterType<StrategyProcessor>().As<IStrategyProcessor>();
	
	var container = builder.Build();
	
	var processor = container.Resolve<IStrategyProcessor>();
	processor.Do();
}

public interface IMyIIndex<in TKey, TValue> : IIndex<TKey, TValue>
{ 
	// I would like to use this interface instead of IIndex
}

public interface IMyInterface
{ 
	void DoSomething(int value);
}

public class MyClass1 : IMyInterface
{ 
	public void DoSomething(int value)
	{
		Console.WriteLine($"Value from MyClass1: {value}");
	}
}

public class MyClass2 : IMyInterface
{
	public void DoSomething(int value)
	{
		Console.WriteLine($"Value from MyClass2: {value}");
	}
}

public enum Stragegy
{ 
	Class1,
	Class2
}

public interface IStrategyProcessor
{ 
	void Do();
}

public class StrategyProcessor : IStrategyProcessor
{ 
	IMyInterface class1 = null;
	IMyInterface class2 = null;
	
	public StrategyProcessor(IIndex<Stragegy, IMyInterface> stragegy)
	{
		class1 = stragegy[Stragegy.Class1];
		class2 = stragegy[Stragegy.Class2];
	}

	public void Do()
	{
		class1.DoSomething(123);
		class2.DoSomething(123);
	}
}

I would like to use `IMyIIndex<in TKey, TValue>` or an implementation of it instead of `IIndex<K,V>` in the above class `StrategyProcessor`.

PS: I could not make the whole code to be recognized as code on this editor!

**Comment by tillig** [comment]
I think the best you will be able to do is one of the following things:

- Register a closed generic for a specific `IIndex<K, V>` as noted by @alexmg 
- [Implement a Registration Source](http://autofac.readthedocs.io/en/latest/advanced/registration-sources.html) to handle dynamically resolving/decorating `IIndex<K, V>` with your type.
- Skip using `IIndex<K, V>` at all and create your [own version of `KeyedServiceIndex<K, V>`](https://github.com/autofac/Autofac/blob/41044d7d1a4fa277c628021537d5a12016137c3b/src/Autofac/Features/Indexed/KeyedServiceIndex.cs) that implements your interface and register that in the container in [the same way we register `KeyedServiceIndex<K, V>`.](https://github.com/autofac/Autofac/blob/b5426654f851708aba364fd428c99504f6f049df/src/Autofac/ContainerBuilder.cs#L275)

Regardless, I think there are ways to get your interface in there in the way you want without any modifications to core Autofac.
