### ISSUE TITLE
Support multiple constructors with reflection-based component registration

### ISSUE THREAD

**Issue by GeorgeTsiokos** [autofac/Autofac#850]
Support multiple constructors where the constructor parameters are able to be obtained from the container _and_ __based on the supplied autofac parameters__. The variable nature of the autofac parameters would decide which constructor to select.

For example, given a simple type with two public constructors:

```c#
public class TwoConstructors
{
   readonly object _value;

   public TwoConstructors(IA value) => _value = value;
   public TwoConstructors(IB value) => _value = value;   
   public override string ToString() => _value.ToString();   
}
```
with simple types for the constructor parameters:
```c#
public interface IA { }
public interface IB { }
public class A : IA { public override string ToString() => "A"; }
public class B : IB { public override string ToString() => "B"; }
```
with _reflection-based_ registration:
```c#
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterType<A>().As<IA>();
containerBuilder.RegisterType<B>().As<IB>();
```

It would be great if this _reflection-based_ registration:
```
containerBuilder.RegisterType<TwoConstructors>();
```

would behave like this delegate-based registration:
```c#
containerBuilder.Register((componentContext, parameters) =>
{
   var ia = parameters.OfType<TypedParameter>().Where(typedParameter => typedParameter.Type == typeof(IA)).Select(typedParameter => (IA)typedParameter.Value).FirstOrDefault();
   if (ia != null)
      return new TwoConstructors(ia);

   var ib = parameters.OfType<TypedParameter>().Where(typedParameter => typedParameter.Type == typeof(IB)).Select(typedParameter => (IB)typedParameter.Value).FirstOrDefault();
   if (ib != null)
      return new TwoConstructors(ib);

   throw new DependencyResolutionException("Missing IA or IB parameter");
});
```

Today we receive the following _expected_ exception:

      Unhandled Exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TwoConstructors (ReflectionActivator), Services = [TwoConstructors], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> Cannot choose between multiple constructors with equal length 1 on type 'TwoConstructors'. Select the constructor explicitly, with the UsingConstructor() configuration method, when the component is registered.

- reflection-based component registration does not currently support multiple constructors

Example usage (_works with delegate-based registration_):
```c#
var container = containerBuilder.Build();

Console.WriteLine(container.Resolve<TwoConstructors>(TypedParameter.From(container.Resolve<IA>())));
Console.WriteLine(container.Resolve<TwoConstructors>(TypedParameter.From(container.Resolve<IB>())));
Console.WriteLine(container.Resolve<TwoConstructors>()); // throws expected exception

Console.WriteLine(container.Resolve<Func<IA, TwoConstructors>>()(container.Resolve<IA>()));
Console.WriteLine(container.Resolve<Func<IB, TwoConstructors>>()(container.Resolve<IB>()));
Console.WriteLine(container.Resolve<Func<TwoConstructors>>()); // returns a func that will always throw the expected exception
```

**Comment by piotrzaremba** [comment]
👍.  This is a feature I have wanted for a long time.

**Comment by GeorgeTsiokos** [comment]
__Scenario__:
> Constructors with parameters give you a clear statement of what it means to create a valid object in an obvious place. If there's more than one way to do it, create multiple constructors that show the different combinations.
- https://www.martinfowler.com/articles/injection.htm

__Unity support__:
```c#
var container = new UnityContainer();

container.RegisterType<IA, A>();
container.RegisterType<IB, B>();

container.RegisterType<TwoConstructors>("a", new InjectionConstructor(typeof(IA)));
container.RegisterType<TwoConstructors>("b", new InjectionConstructor(typeof(IB)));

Console.WriteLine(container.Resolve<TwoConstructors>("a", new DependencyOverride(typeof(IA), container.Resolve<IA>())));
Console.WriteLine(container.Resolve<TwoConstructors>("b", new DependencyOverride(typeof(IB), container.Resolve<IB>())));
```
http://stackoverflow.com/a/8853453/5869
http://stackoverflow.com/a/2470137/5869

This feature request is for `RegisterType` to support multiple constructors, which is currently not support. I'm able to resolve the requested type today with delegate-based registration where I construct the type manually (example above).

**Comment by sam-wheat** [comment]
@alexmg  

>> Ideally your class should only have a single constructor that declares all the dependencies the class requires. 

I ran into this issue today and saw the above statement.  This is incorrect on it's face - and if it is the only argument for closing the ticket than further discussion is warranted.  

In my case I'm supplying explicitly supplying the single parameter my object expects yet Autofac fails. There has to be a better way.

**Comment by metu** [comment]
@sam-wheat @alexmg  I ran into the same issue today. Like @GeorgeTsiokos pointed out, it's possible to use delegate-based registration, however when you handing a project over to a relatively junior developer this type of registration can be overwhelming compared to reflection-based registration. @GeorgeTsiokos thanks for pointing out that Unity supports this :D

**Comment by zhangxin511** [comment]
+1. Should be very helpful

**Comment by griffithtp** [comment]
+1
