### ISSUE TITLE
Interception of Registering or Registering Event

### ISSUE THREAD

**Issue by osoykan** [autofac/Autofac#854]
I asked a question in SO. There is a solution that already implemented and also it is answered on SO but, not a good approach IMHO. I was wondering, could be any enhancement or implementation of _interception of Registration_ which means that _interception of IRegistrationBuilder_ such as **Registered** event ?

[SO Question](https://stackoverflow.com/questions/44477061/registering-event-in-autofac)

Thanks in advance.

**Comment by tillig** [comment]
The `IComponentRegistry` supports a [`Registered` event](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Core/IComponentRegistry.cs#L92) to intercept [when a component is added to the registry](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Core/Registration/ComponentRegistry.cs#L190) (and a corresponding `RegistrationSourceAdded` event for registration sources).

Are you imagining some sort of pre-registration event?

**Can you post a block of pseudocode showing how you imagine this might be used if it was offered?** That can help us understand what you think it should look like as well as what you might do with it.

**Comment by osoykan** [comment]
> The IComponentRegistry supports a Registered event to intercept when a component is added to the registry (and a corresponding RegistrationSourceAdded event for registration sources).

Yea. It supports but, this sounds like an immutable event to override a component that when added to the registry. I want to **add/override** some properties to the _registering component_ **at the registering moment.**


> Are you imagining some sort of pre-registration event?


Totally!. Could be pre-registration. 

For example:
```
var builder = new ContainerBuilder();

// convention 1
builder.RegisteringCallback((registrationBuilder, serviceType)=>
{
    if (typeof(IApplicationService).IsAssignableFrom(serviceType))
    {
        //Additional ovveride/addendum incoming registration!
        registrationBuilder
            .EnableInterfaceInterceptors()
            .InterceptedBy(typeof(UnitOfWorkInterceptor));
    }
});

// convention 2
builder.RegisteringCallback((registrationBuilder, serviceType) =>
{
    if (typeof(IShouldBeSelfRegistered).IsAssignableFrom(serviceType))
    {
        //Additional ovveride/addendum incoming registration!
        registrationBuilder
            .AsSelf();
    }
});

builder.RegisterType<UnitOfWorkInterceptor>().AsSelf();
builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
       .AsClosedTypesOf(typeof(IApplicationService))                  
       .AsSelf();

builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
       .AsClosedTypesOf(typeof(IShouldBeSelfRegistered));
```

**Comment by tillig** [comment]
Two years on, there hasn't been any movement on this and it doesn't seem the community has added votes, either. While I think this is a technically interesting feature, I don't know that having a complex eventing system around both _registration_ and _resolution_ is really something we want to take on. I think we'd be interested in a PR if this is something someone wants to look at, but in the meantime, I'm going to close this as "won't fix."
