### ISSUE TITLE
LifetimeScope per module

### ISSUE THREAD

**Issue by Portikus** [autofac/Autofac#858]
**The Situation**
We have some common Interfaces in our Solution like `IWorker` and its implementation `Worker`.
This class need to be configured. 
````csharp  
public class Worker : IWorker
{
    private string selectedTag;

    public string DoWork()
    {
        return this.selectedTag;
    }

    public void Configure(string tag)
    {
        this.selectedTag = tag;
    }
}
````

We are using a plugin like architecture with the help of AutoFacs Modules.
So it is comes from time to time that a module registers and configures a 'Worker':
````csharp  
builder.RegisterType<ViewModel1>();
builder.RegisterType<Worker>()
                   .OnActivating(x => x.Instance.Configure("Worker for ViewModel1"))
                   .AsImplementedInterfaces();
````
A similar code can be found in another module but with another configuration.

**The Problem**

 The problem with this is pretty obvious. One registration of the module is overriding the other one and each time the container resolves an `IWorker` it uses only the last configuration.

**A Solution**

One solution I found in your docs is to use the Keyed function. With this I am able to key every worker with a specific tag. But my problem with this is that I have to use a `KeyFilterAttribute` in the retriving class, which is in my case not desired because we want to minimize the container dependency I only want Autofac specific in my module classes. 

**A possible Solution?**

What I think is a better solution is something like module based lifetime scopes, so that I can configure the container to use a registration for each module.
````csharp  
builder.RegisterType<Worker>()
                   .OnActivating(x => x.Instance.Configure("Worker for ViewModel1"))
                   .AsImplementedInterfaces()
                   .InstancePerLifetimeScope();
````

and if I now register a module I want to tell the container it should create a new scope for this module like:
````csharp  
builder.RegisterModule<Module1>("NewLifetimeScope");
````

What do you think? Is this possible? Or is there another solution I have missed?

**Note that in the end I am using Prism with autofac so I am not able to manually start new LifetimeScopes**
**I attached a small [repo Solution](https://github.com/autofac/Autofac/files/1115365/AutoFacScopePerLifetime.zip) with a unit test to see what I need**

**Comment by tillig** [comment]
These types of "how do I?" questions are usually better suited to StackOverflow. There's only two project owners here and few folks outside that actively monitoring the issues list. SO had a larger audience to help.

If you post there, link it here and close the issue. If you don't, that's fine, but no promises on how quickly you'll get an answer.

**Comment by Portikus** [comment]
https://stackoverflow.com/questions/44848494/lifetimescope-per-module-in-autofac
