### ISSUE TITLE
Prism.Autofac RegisterTypeForNavigation issue

### ISSUE THREAD

**Issue by galmond** [autofac/Autofac#861]
Could one of the autofac developers please take a quick look at the link below?  It contains details of an issue I discovered when using Prism with Autofac.  Brian Lagunas has investigated and provide details of the Unity implementation and has asked if an Autofac developer could implement the fix.

Any help much appreciated, link below:

https://github.com/PrismLibrary/Prism/issues/1120

**Comment by galmond** [comment]
Further investigation suggests this is the reason why a 'AutofacRegionNavigationContentLoader' does not exists...

https://stackoverflow.com/questions/9116835/is-it-possible-to-resolve-an-instance-from-autofac-given-only-a-string-key

Would that be correct?

**Comment by tillig** [comment]
There is already some work going on in Prism to refactor things to remove `ContainerBuilder.Update` usage: https://github.com/PrismLibrary/Prism/issues/969

Neither of the two Autofac maintainers use Prism and we're already trying to be "experts" in the 20-ish integration packages we provide. Much as I respect the Prism project and what it provides, I just don't have the bandwidth to answer Autofac (and integration package) questions, address Autofac (and integration package) issues, _and_ try to take on learning about Prism and the right ways to do things.

This really needs to come from someone in the community that uses Prism, likely someone already working on that `ContainerBuilder.Update` refactor.

Even just trying to quickly glance through that, I'm not sure what registering something for navigation means, how it gets determined to be a navigation target, why there's a fallback that's required, or any of that. That research - the "what's it _really_ supposed to do in the context of a larger Prism system" - is the bulk of the work.

I can say that the StackOverflow answer is accurate: If you need to resolve an object but you _only_ have the key and _not_ a type, you're going to have trouble. That's not how most DI containers work; I'd avoid that if at all possible.

However, something that may help: If you have a base class or interface that your things implement, you can potentially get a similar result:

```csharp
public interface IView { }
public class ViewA : IView { }
public class ViewB : IView { }

public class Program
{
  public static void Main()
  {
    var builder = new ContainerBuilder();
    builder.RegisterType<ViewA>().Named<IView>("MyViewA").AsSelf();
    builder.RegisterType<ViewB>().Named<IView>("MyViewB").AsSelf();
    var container = builder.Build();

    // Get by key:
    container.ResolveNamed<IView>("MyViewA");

    // Get by type:
    container.Resolve<ViewA>();
    container.Resolve(typeof(ViewA));
  }
}
```

Point being, you'd register your things both

- As a named service based on a common interface
- As the actual object itself

Then you could resolve based on either criteria.

**Comment by galmond** [comment]
No problem, thanks for replying. I attempted a fix and although not ideal from the Autofac perspective, i.e. multiple keyed services with potentially the same name, it's in a controlled environment and is working as required. Thanks again.
