### ISSUE TITLE
do not trace instance,do not try to dispose instance,its not your bussiness

### ISSUE THREAD

**Issue by hiwjcn** [autofac/Autofac#863]
when we use root container to create instance,we may cause a memory leak bug.
i do not think its a good decision to trace and auto-dispose instance for users.

if we use a child scope to handler this question, but its not a confortable way to

**Comment by tillig** [comment]
If you don't want Autofac to dispose or track registrations you can register them using `ExternallyOwned` to opt out. [Docs here.](http://autofac.readthedocs.io/en/latest/lifetime/disposal.html)
