### ISSUE TITLE
Entity Framework Core attempts to use wrong options when two contexts are registered

### ISSUE THREAD

**Issue by jaroslawpedrycz** [autofac/Autofac#866]
.Net Core 2 ASP MVC application.
When in Startup.cs register two DbContext with pooling like this:
` services.AddDbContextPool<DbContext1>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("con"));
            });`
            `services.AddDbContextPool<DbContext2>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("con"));
            });`

Exception occur:
ArgumentException: Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions\`1[namesspace.DbContext2]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions\`1[namespace.DbContext1]'

` public DbContext1(DbContextOptions<DbContext1> dbContextOptions) : base(dbContextOptions)
        {
        }`
`public DbContext2(DbContextOptions<DbContext2> dbContextOptions) : base(dbContextOptions)
        {
        }
`

**Comment by tillig** [comment]
Do you happen to have a small repro, preferably in unit test format, where we can try this out? Also, what have you done to dive in and see what's up? Have you gone down through what `AddDbContextPool<T>` does to see what's going on in there? Does this work if you don't have Autofac in the mix and use the default Microsoft container?

**Comment by jaroslawpedrycz** [comment]
I wrote unit tests, and issue NOT exists in Autofac.  You can close ticket.

If you are interested, you can see:
[AutofacDbcontextPoolingTest.zip](https://github.com/autofac/Autofac/files/1293690/AutofacDbcontextPoolingTest.zip)

**Comment by tillig** [comment]
Thanks for taking the time to check into it! Good luck solving it; I'd recommend asking the EF Core folks about it.
