### ISSUE TITLE
How to use autofac in wpf application.

### ISSUE THREAD

**Issue by Tony1952466760** [autofac/Autofac#873]
I want use autofac in my wpf application.
In the mvc application i know use builder.RegisterControllers(assembly);  
but in the wpf i dont know how to config .
thank you .

**Comment by tillig** [comment]
There isn't specific support for WPF. WPF doesn't have "requests" or a composition root, really. Using any DI library ends up being very app specific.

You would do well to search for "WPF dependency injection" (don't think Autofac specific) to get ideas and patterns. StackOverflow is a great resource for stuff like this, too.

**Comment by jmroyb** [comment]
I had same question. No Autofac WPF tutorials available.

I suggest MVVM Light. More tutorials and vsix templates:

https://marketplace.visualstudio.com/items?itemName=LaurentBugnion.MVVMLightforVS2017
