### ISSUE TITLE
View Components (ASP.NET MVC Core) cannot be combined with a request-scope.

### ISSUE THREAD

**Issue by maartenoosterhoff** [autofac/Autofac#875]
1. Open the attached solution in VS2017. It is a dot-net-core-mvc project, which uses Autofac.
2. Run the app.
3. It will blow up while creating an instance of the view-component SampleComponent.
4. Change the registration of the IRepository to scoped singleton.
5. Run the app again. Now it works.

It looks like view-components cannot be combined with a request-scope.

[DiViewComponentTest.zip](https://github.com/autofac/Autofac/files/1372192/DiViewComponentTest.zip)

**Comment by tillig** [comment]
Have you tried this using the default Microsoft container?

**Comment by tillig** [comment]
Looking at your code, I can see the problem. It's the first item listed in our ASP.NET Core docs in the  [Differences From ASP.NET Classic](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#differences-from-asp-net-classic) section:

> **Use InstancePerLifetimeScope instead of InstancePerRequest.** In previous ASP.NET integration you could register a dependency as `InstancePerRequest` which would ensure only one instance of the dependency would be created per HTTP request. This worked because Autofac was in charge of setting up the per-request lifetime scope. With the introduction of `Microsoft.Extensions.DependencyInjection`, the creation of per-request and other child lifetime scopes is now part of the conforming container provided by the framework, so all child lifetime scopes are treated equally - there’s no special “request level scope” anymore. Instead of registering your dependencies `InstancePerRequest`, use `InstancePerLifetimeScope` and you should get the same behavior. Note if you are creating your own lifetime scopes during web requests, you will get a new instance in these child scopes.

[You may want to take a moment to read through the ASP.NET Core integration docs](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html) to ensure you don't run into any other gotchas like this.
