### ISSUE TITLE
Mix registration-time parameters with resolve-time parameters

### ISSUE THREAD

**Issue by huysentruitw** [autofac/Autofac#877]
Would it be possible to support this usage scenario:

    [Fact]
    public void ResolveFactoryWithFixedAndVariableConstructorParameter()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<MixFixedAndVariableConstructorParameter>().WithParameter(new NamedParameter("fixed", "FixedLikeARock"));
        var container = builder.Build();
        var func = container.Resolve<Func<string, MixFixedAndVariableConstructorParameter>>();
        var obj = func("IOftenChangeMyMind");
        Assert.Equal("FixedLikeARock", obj.Fixed);
        Assert.Equal("IOftenChangeMyMind", obj.Variable);
    }

    private class MixFixedAndVariableConstructorParameter
    {
        public string Variable { get; set; }

        public string Fixed { get; set; }

        public MixFixedAndVariableConstructorParameter(string variable, string @fixed)
        {
            this.Variable = variable;
            this.Fixed = @fixed;
        }
    }

I digged into the `FactoryGenerator` class in order to implement this, but it seems like its the wrong place as at that time, we still don't have details about the registration. Not sure how to proceed with this one.

**Comment by huysentruitw** [comment]
Our current work-around is to add a second registration as demonstrated below. However this seems like it should be supported out-of-the-box :)

    builder.Register<Func<string, Owned<MixFixedAndVariableConstructorParameter>>>((ctx, _) => (variable => ctx.Resolve<Owned<MixFixedAndVariableConstructorParameter>>(new NamedParameter("fixed", "FixedLikeARock"), new NamedParameter("variable", variable))));

Also note that we're in need of an `Owned`-instance, but not sure if that makes any difference to my question in original post.

**Comment by tillig** [comment]
The problem you're running into is more to do with the fact the two parameters are _the same type_. [We have some docs on this in the implicit relationship types doc](http://autofac.readthedocs.io/en/latest/resolve/relationships.html#parameterized-instantiation-func-x-y-b):

> Internally, Autofac treats these as typed parameters. What that means is that auto-generated function factories cannot have duplicate types in the input parameter list.

To illustrate that, this test works:

```csharp
[Fact]
public void ResolveFactoryWithDifferentParameterTypes()
{
    var builder = new ContainerBuilder();
    builder.RegisterType<MixFixedAndVariableConstructorDifferentParameters>().WithParameter(new NamedParameter("fixed", "FixedLikeARock"));
    var container = builder.Build();
    var func = container.Resolve<Func<Exception, MixFixedAndVariableConstructorDifferentParameters>>();
    var obj = func(new DivideByZeroException());
    Assert.Equal("FixedLikeARock", obj.Fixed);
    Assert.IsType<DivideByZeroException>(obj.Variable);
}

private class MixFixedAndVariableConstructorDifferentParameters
{
    public MixFixedAndVariableConstructorDifferentParameters(Exception variable, string @fixed)
    {
        this.Variable = variable;
        this.Fixed = @fixed;
    }

    public string Fixed { get; set; }

    public Exception Variable { get; set; }
}
```

Switching one of the parameter types to not be the same as the other allows this to work.

You can emulate what's happening under the covers by manually resolving things with parameters:

```csharp
[Fact]
public void ManualIllustrationOfSameParameterTypes()
{
    var builder = new ContainerBuilder();
    builder.RegisterType<MixFixedAndVariableConstructorStringParameters>().WithParameter(new NamedParameter("fixed", "FixedLikeARock"));
    var container = builder.Build();
    var obj = container.Resolve<MixFixedAndVariableConstructorStringParameters>(new TypedParameter(typeof(string), "IOftenChangeMyMind"));

    // Fails - Fixed becomes "IOftenChangeMyMind"
    Assert.Equal("FixedLikeARock", obj.Fixed);
    Assert.Equal("IOftenChangeMyMind", obj.Variable);
}
```

The reason this happens [is in `ConstructorParameterBinding` here](https://github.com/autofac/Autofac/blob/db0d058b5b58a99c80928e9ad46142271ad0f64e/src/Autofac/Core/Activators/Reflection/ConstructorParameterBinding.cs#L85). That's called from `ReflectionActivator`. Roughly:

- Get the set of parameters that were passed in (the "overrides").
- Concat the set of parameters that were added during registration (the "defaults").
- Foreach constructor parameter
  - Foreach resolution parameter in the complete set
    - If the resolution parameter can supply a value to the constructor parameter, use it.

The problem you're seeing is that both the "override" typed parameter _and_ the "default" named parameter can provide a value to the `fixed` constructor parameter... so the overrides win.

I don't know that there's a good way to fix this on the Autofac side. We don't want to treat different parameter types differently (e.g., the `ConstructorParameterBinding` shouldn't know about the different types of parameters there are; nor should there need to be knowledge across different parameter types about which order of precedence is in place).

Hypothetically there could be some sort of plugin that could be added [way down here in `ReflectionActivator`](https://github.com/autofac/Autofac/blob/fff276e2890e0a5fcbf738560301e594b8cbf6f0/src/Autofac/Core/Activators/Reflection/ReflectionActivator.cs#L120) to allow ordering of the set of parameters used in `ConstructorParameterBinding` but I'm not sure how that'd work off the top of my head. Seems like it'd be a lot of work to get a plugin down there with limited value - like, literally, this one specific edge case and that's about it.

The easiest thing to do if you have the ability is to change the constructor of the class to not take two parameters of the same type. Alternatively, keep your workaround method in place.

**Comment by huysentruitw** [comment]
Thanks for your thorough explanation. I thought that a named parameter always gets precedence on a typed parameter as a named parameter is more specific, but I agree, it's a special edge case and might not be worth (and even be dangerous) to change this functionality.

The workaround method doesn't work, because we need to capture the `IComponentContext` in our `Func`-lambda which throws a runtime exception:

> This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.

Not sure how to properly work-around this.

**Comment by tillig** [comment]
This can probably be cleaned up a bit but I don't have a lot of time to allocate here. Hope it helps.

```csharp
[Fact]
public void Workaround()
{
	var builder = new ContainerBuilder();
	builder.Register((ctx, parms) =>
	{
		// Need the constructor because we need the parameter info for parameter filtering.
		var ctor = typeof(MixFixedAndVariableConstructorParameter).GetConstructor(new Type[] { typeof(string), typeof(string) });

		// We need the parameter info to ensure the resolve parameters can actually
		// supply the value we want.
		var fixedParameterInfo = ctor.GetParameters().First(pi => pi.Name == "fixed");
		var variableParameterInfo = ctor.GetParameters().First(pi => pi.Name == "variable");

		// For the fixed parameter, we only want to allow named overrides, no typed overrides.
		// Fall back to default if none is found.
		Func<object> fixedParameterValueProvider = null;
		parms
			.OfType<NamedParameter>()
			.FirstOrDefault(p => p.Name == "fixed" && p.CanSupplyValue(fixedParameterInfo, ctx, out fixedParameterValueProvider));
		if (fixedParameterValueProvider == null)
		{
			fixedParameterValueProvider = () => "FixedLikeARock";
		}

		// For the variable parameter, we MUST have a parameter passed in. But... we'll let named
		// parameters take precedence.
		Func<object> variableParameterValueProvider = null;
		parms
			.OfType<NamedParameter>()
			.FirstOrDefault(p => p.Name == "variable" && p.CanSupplyValue(variableParameterInfo, ctx, out variableParameterValueProvider));
		if (variableParameterValueProvider == null)
		{
			parms.FirstOrDefault(p => p.CanSupplyValue(variableParameterInfo, ctx, out variableParameterValueProvider));
		}

		if (variableParameterValueProvider == null)
		{
			throw new NotSupportedException("No parameter provided for 'variable'");
		}

		// Use the parameters we found to create the object.
		return new MixFixedAndVariableConstructorParameter((string)variableParameterValueProvider(), (string)fixedParameterValueProvider());
	})
	.As<MixFixedAndVariableConstructorParameter>();

	var container = builder.Build();
	var func = container.Resolve<Func<string, MixFixedAndVariableConstructorParameter>>();
	var obj = func("IOftenChangeMyMind");
	Assert.Equal("FixedLikeARock", obj.Fixed);
	Assert.Equal("IOftenChangeMyMind", obj.Variable);
}
```
