### ISSUE TITLE
Make IDisposable tracking configurable per builder/scope

### ISSUE THREAD

**Issue by eugbaranov** [autofac/Autofac#879]
Sometimes it is much easier to leave GC to deal with `IDisposable` objects than refactoring the entire application to create separate lifetimes per units of work.

Something like this maybe:
```csharp
builder.AutomaticDisposal = false;
```

**Comment by tillig** [comment]
I assume this is so you don't have to register everything as `ExternallyOwned()`?

**Comment by Regent** [comment]
Indeed, effectively having an option to specify whether default option should be `ExternallyOwned` or else.
Maybe an enum allowing to specify whether it should be `ExternallyOwned`, `InstancePerOwned` or `OwnedByLifetimeScope` by default?

**Comment by tillig** [comment]
Just brainstorming since I'm out and only have my phone right now... I wonder if this could be done with a module and `AttachToComponentRegistration`...

**Comment by Regent** [comment]
But wouldn't `registration.Ownership` be read-only at that point?
Also, will it allow to change behavior per scope?

**Comment by tillig** [comment]
As I said, I'm out and in my phone. Feel free to test this out and see what happens. Maybe it works, maybe it doesn't. In was trying to unstick you. If you choose not to try it out, well, that's fine, too.

**Comment by Regent** [comment]
It tried it briefly but couldn't find how to make it work, that's said I'm not a big expert in Autofac, maybe I'm missing something...

**Comment by johneking** [comment]
Looks like this isn't supported with the existing code. There are two distinct features we could add here I think, but I'm just trying to get my head around whether providing support for each set of use-cases is really desirable. Units of work seem somewhat fundamental to using scopes properly and I wonder if the ability to disable ownership across the board via a built-in feature might encourage mis-use (/laziness!)

The simple part would be adding the default ownership on the registration side - that could be done relatively easily by adding an optional parameter to the constructors of `RegistrationData`, `RegistrationBuilder` and `ContainerBuilder`, and conceptually it does seem to make sense that those classes would have that. The `ContainerBuilder` default could then perhaps be passed to the other objects. But then it does bloat out those constructors a bit. Is it worth adding that in just to make the syntax for having a lot of `ExternallyOwned` calls on `IDisposable` types neater? I'm not convinced, but can submit a PR if so.

The other part seems a bit more problematic. I'd be interested to hear more, but is there really a use-case for essentially disabling disposal of `IDisposable`s per lifetime scope? It implies a case where the same registrations are used by multiple scopes with different lifecycles, some unit-of-work-style and others where the GC is left to clean up. If it's all one or the other then it could be controlled on the registration-side. Issues with this setup:

- the information contained in the registrations could end up being misleading, e.g. we have a registration implying automatic disposal but then a scope might not action it. Should the registration alone be the source of truth?
- any extensions where scopes are automatically generated (e.g. asp.net, WCF) would also need extending to account for this alternative usage

**Comment by johneking** [comment]
PR #1014 created for the registration approach above

**Comment by johneking** [comment]
After further investigation + discussion I suggest we close this. The ability to alter the default behaviour at any level is likely undesirable for a few reasons, primarily:

- it provides users with an easy path away from best practice, for example, units of work
- it adds complexity to all registrations because of the additional context of the default. If not fully understood, the same registration used in different places could easily lead to memory leaks.

Given that this looks like it only affects a small set of scenarios involving many objects requiring custom disposal, it's unlikely that the base requirement can't be dealt with better on the application-side via one of several approaches, such as `Owned<T>`.
