### ISSUE TITLE
Upgrading to Autofac 4.6.2 pulls in many extra references

### ISSUE THREAD

**Issue by jamezor** [autofac/Autofac#886]
The Autofac 4.6.2 nuspec contains a bunch of extra references which 4.6.0 did not have, as shown in the below diff. I manually deleted the references which got added to all of my csproj files after the 4.6.0 -> 4.6.2 upgrade and everything still builds just fine so it doesn't appear that these references are needed.

![image](https://user-images.githubusercontent.com/318188/33957163-b126a0ea-e0a5-11e7-9ab4-79ba1e4430d5.png)

**Comment by tillig** [comment]
Autofac doesn't have a .nuspec. Either you're looking at something decompiled from the `.nupkg` or you're looking at an old codeline.

Regardless, this is all generated by the dotnet CLI and Visual Studio build tooling now based on the .csproj contents. Looking at the .csproj [you can see we only reference System and Microsoft.CSharp](https://github.com/autofac/Autofac/blob/ee8994ab451be88bf664dfb0eaa13c72a6d26690/src/Autofac/Autofac.csproj#L50) so it's not something we're adding.

If it's a problem, you may want to file an issue with the [dotnet CLI folks](https://github.com/dotnet/cli) - how the dotnet CLI generates this stuff is _way_ outside our control.

**Comment by jamezor** [comment]
Thanks, it appears to be linked to a dotnet SDK issue: https://github.com/dotnet/sdk/issues/1179

**Comment by migajek** [comment]
I'm not saying it's Autofac fault, but right now the most recent version of Autofac (4.6.2) is kind of broken. The nuget package metadata contains a bunch of unwanted references (like `System.Drawing`), causing projects referencing Autofac 4.6.2 to have these included

```
<dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard1.1">
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="System.ComponentModel" version="4.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Data" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Drawing" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.IO.Compression.FileSystem" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Numerics" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Runtime.Serialization" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Xml.Linq" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
```
