### ISSUE TITLE
Naming Resolving and child dependencies

### ISSUE THREAD

**Issue by 23Alex24** [autofac/Autofac#887]
Hi! Error occurs "None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'ConsoleApplication1.Program+MainClassOlolo' can be invoked with the available services and parameters:
Cannot resolve parameter 'INamed named' of constructor 'Void .ctor(INamed)'."

https://image.ibb.co/gVUNSG/1.png - this is classes (sorry but github incorrect show code)
https://image.ibb.co/cAmK7G/2.png - this is code throws exception

Does the named resolving also resolve child dependencies using a name? Or named resolving applies Name/Key only for resolved type without its child dependencies?

**Comment by 23Alex24** [comment]
help wanted

**Comment by tillig** [comment]
As noted in the issue template, the best first stop for help ("how do I...?" and other questions about usage) is StackOverflow. Have you asked there first? The project owners monitor things there but there's also a larger set of people available to answer your question.

If you have asked there, please include a link to your question here.

**Comment by 23Alex24** [comment]
https://stackoverflow.com/questions/48040577/autofac-naming-resolving-and-child-dependencies

**Comment by tillig** [comment]
Cool, any additional follow up can happen there. If it turns out there's a defect to address, a new issue with the particulars can be filed.

**Comment by alexmg** [comment]
I have posted an answer on SO.
