### ISSUE TITLE
we have been registered a type,but when we call the Resolve method,i get an error,the requested service has not been registered

### ISSUE THREAD

**Issue by hawk199** [autofac/Autofac#890]
autofac 4.2.1

the stack trace:

The requested service 'FW.Core.Repository.IDatabaseFactory' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

   在 Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   在 Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   在 Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   在 Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   在 FW.Core.Engine.AutofacEngine.Resolve[TService](String key) 位置 E:\433\trunk\开发\code\framework\FW.Core.Engine\AutofacEngine.cs:行号 33
   在 jingcai.CacheJob.MatchAndOddsCache..ctor() 位置 E:\433\trunk\开发\code\Job\jingcai.CacheJob\MatchAndOddsCache.cs:行号 39
![image](https://user-images.githubusercontent.com/35512740/35022176-86b0bd7a-fb6f-11e7-8a57-372cd4f5e166.png)

i debug the source code,i foud that getting the service info of the service type  is  by the hashcode of the service type,but the same service type ,the instance of type is different, the hashcode is different.
 in the ComponentRegistry.cs file
    private ServiceRegistrationInfo GetServiceInfo(Service service)
        {
            ServiceRegistrationInfo existing;
            if (_serviceInfo.TryGetValue(service, out existing))
                return existing;

            var info = new ServiceRegistrationInfo(service);
            _serviceInfo.Add(service, info);
            return info;
        }

**Comment by tillig** [comment]
"How do I..." sorts of questions are best suited to StackOverflow. Tag it `autofac` and any other relevant tags. The project owners here monitor SO but so does a much larger audience that can help. If it turns out you've found a bug, out together a _minimal_ repro (think unit test) and explain the specifics around the issue.

**Comment by hawk199** [comment]
this is not a question ,it is a bug

**Comment by tillig** [comment]
Can you please file an issue that has something we can reproduce? That is, can you describe it with a failing test, something we can actually see working incorrectly that doesn't require building and debugging a custom solution? The way this current issue is described, it's all custom code and it's something in your code that isn't working. If we can't reproduce it, we can't fix it.

**Comment by hawk199** [comment]
I an so sorry,there no bug.
