### ISSUE TITLE
MVC6 configured AutoFac container is not able to resolve ILog on Controllers but resolves ILog for services injected into controller...

### ISSUE THREAD

**Issue by hidegh** [autofac/Autofac#892]
I got an MVC6 app. Full .NET framework.
Using Autofac and Log4Net (old fashioned, I do like some parts).

I do have a Log4NetModule based on docs and wiring done based on Quick Start (Without ConfigureContainer) [the other config. is not an option, since due to hangfire.io I need to control the container dispose].

All the log4net references are for the same version.

**When I do have a dependency on ILog within any service, it get's nicely resolved.
When I do have an ILog dependency on a controller itself, it won't get resolved.**

not working:
controller ctor(Ilog logger) - resolving fails

working:
controller ctor(IService service)
service ctor(ILog logger) - ILog is resolved

`
InvalidOperationException: Unable to resolve service for type 'log4net.ILog' while attempting to activate 'Project.Web.DiTestL1'.
Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
lambda_method(Closure , IServiceProvider , Object[] )
Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance<TInstance>(IServiceProvider serviceProvider, Type implementationType)
Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextExceptionFilterAsync>d__24.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ExceptionContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
`

**Comment by tillig** [comment]
Likely you need to [register controllers as services](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services).

If that doesn't work, this is a prime candidate for a StackOverflow question. We monitor there, but also tons of other folks are there, all of whom can help (and possibly in a more timely fashion).

**Comment by hidegh** [comment]
Thanx, the fix helped.

None of the forums mentioned it. It's MVC6 related and (as seen in the AutoFac doc - and as stated on my issue edescription) the rest of the resolvings worked fine.
