### ISSUE TITLE
Add more benchmarks for performance 

### ISSUE THREAD

**Issue by chinwobble** [autofac/Autofac#898]
Currently there are only two benchmarks for performance and one of them is missing a baseline cse.

Autofac.Benchmarks.DeepGraphResolveBenchmark
Autofac.Benchmarks.RootContainerResolveBenchmark

Add additional benchmarks for resolving using different features such as:
- resolving singleinstances 
- resolving generics
- resolving IEnumerable dependencies
- resolving and intercepting with proxies 
- etc

**Comment by tillig** [comment]
While I think adding new benchmarks for performance is a worthwhile thing, I also think this is the sort of issue that can never really be closed - we could add (arbitrarily) five more benchmarks, but the notion of "add more benchmarks" could still be valid.

We would happily accept PRs for more valuable benchmarks, but there's no value in having a persistent issue open for it.
