### ISSUE TITLE
Question about performances

### ISSUE THREAD

**Issue by valeriob** [autofac/Autofac#911]
Hi,
i've been an happy autofac user for ages, but i did not really use any advanced feature so i may be speaking for a minority here. Have you seen those benchmarks ? https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/index.html
Do you think there are some low hanging fruits that can lower autofac overhead ? I see some issues marked as enhancement i guess they are somewhat related.

Thanks

**Comment by tillig** [comment]
Sort of duplicate of #898.

We're doing the best we can with the two project owners supporting and maintaining Autofac and the 20+ integration libraries entirely in our unpaid spare time. We take care of things we know about; if you have something specific you see needs work (and, better, can offer a PR to fix it), we're happy to hear about it.

**Comment by Havunen** [comment]
@tillig @valeriob I created PR to improve perf, it improves runtime 20-30% in simple use cases. https://github.com/autofac/Autofac/pull/914
