### ISSUE TITLE
BeginLifetimeScope(tag, builder) in IStartable.Start causes StackOverflowException

### ISSUE THREAD

**Issue by ConcernedCitizen** [autofac/Autofac#916]
We have a scenario where we're using BeginLifetimeScope within the Start() function of a Startable.  After upgrading to the latest Autofac (v4.8.0), we saw that the BeginLifetimeScope call was causing a StackOverflowException.

It looks like the fix for issue 567 ("AutoActivate / IStartable doesn't work for components configured within a LifetimeScope") had this side effect in our scenario.  The *BeginLifetimeScope(object tag, Action<ContainerBuilder> configurationAction)* function calls StartStartableComponents, which is currently including the Startable that's calling BeginLifetimeScope.  

We worked around it by adding a line to IgnoreStartableComponents within the configurationAction, but the behavior was definitely unexpected.

Replication Code:
[autofac.txt](https://github.com/autofac/Autofac/files/1984646/autofac.txt)

**Comment by tillig** [comment]
I think I have a fix for this and I'll push it shortly. It'll go out as 4.8.1.

I would recommend _not_ doing what you're doing, though. Creating a child lifetime scope during `IStartable.Start()` could get you into other interesting trouble, like if you have an `IStartable` that depends on an `IStartable`, trying to ensure everything gets started in the right order could be sort of tricky. It'd be better to let the startables all finish "starting" before you try creating child lifetime scopes.

I'm personally not a huge fan of startables or container build callbacks. It seems like a convenient way to chain things together at app startup, but it puts a lot of importance on the container that really is application startup logic that you should probably isolate and call entirely separately from creating the container. Something to consider.

**Comment by ConcernedCitizen** [comment]
Thanks Travis, I appreciate it.

Yea, even though all of our Startables are independent, it's kind of an odd use case.  We essentially have a bunch of startables which get run for each "database configuration" (N of them) - those startables resolve something as part of getting their configuration, so the lifetime scope separates those registrations.  I agree with you that it's not the most optimal way to do things, hopefully we'll get time to change how it works at some point.

Thanks again!
