### ISSUE TITLE
“Cannot instantiate implementation type” on ASP.NET Core's application startup

### ISSUE THREAD

**Issue by thiagomajesk** [autofac/Autofac#920]
Hello guys...
Before I start, a little bit of context:

Some time ago, I've opened [this issue](https://github.com/aspnet/DependencyInjection/issues/531) about ASP.NET Core's default container supporting complex cases for generics. While this is not supported I've been managing to use AutoFac for some missing use-cases.

So, I'm having a problem while implementing some generic use-cases using the MediatR library and I'm not sure if the problem is related to AutoFac, my configuration or even ASP.NET Core.

I'm saying this because I'm suspicious that AutoFac is not being registered correctly and the default container is assuming the registration at some point. The reasoning behind that is the stack trace logging the exact same error message I had in the past.

```
Cannot instantiate implementation type
'Project.App.Base.Handlers.CreateEntityCommandHandler`2[TEntity,TCommand]' 
for service type 'MediatR.IRequestHandler`2[TCommand,TEntity]'.
```

I don't think is related to any specific configuration I've done because if I comment my configuration the error still occurs. I'm using the code in this template I'm creating: https://github.com/thiagomajesk/ASP.NET-Core-Bootstrap-Template. 
If you clone the repo and run the application you will see the error, it is thrown just after the application bootstrap.

**PS.:** Just FYI: I've recently ported the project to ASP.NET Core 2.1, so maybe there's something related.

**This is the full stack trace:**

       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate(IEnumerable`1 descriptors)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Project.Web.Program.Main(String[] args) in C:\Users\usr\Source\Repos\_archived\ASP.NET-Core-Bootstrap-Template\Project.Web\Program.cs:line 11

**Comment by tillig** [comment]
As I mentioned on the [now deleted] StackOverflow question, we really need a more minimal repro. On StackOverflow you might have had a whole community of people that could help (which is why the issue template here urges folks to try StackOverflow); here you only get the two Autofac project owners, one of which (me) I know doesn't use MediatR... and if we have to dive into a big repro to debug your code, I'll be honest... given the 20+ integration libraries, the recent release of ASP.NET Core 2.1, and the ongoing issues and maintenance for all the projects here, knowing this is a "spare time" thing we do unpaid... this is going to be a low priority thing to investigate.

Sorry about that, but again, that's why we try to get folks onto StackOverflow.

**Comment by tillig** [comment]
Since this appears to be ASP.NET Core specific, not something with core Autofac, I'm going to move it to the appropriate repo.

**Comment by tillig** [comment]
This issue was moved to autofac/Autofac.AspNetCore#4

**Comment by thiagomajesk** [comment]
@tillig So, It was you earlier! I didn't notice 😄. 

Just to clarify, my motivation to move the SO question here was that it didn't seem to be something related to AutoFac's usage or configuration (like your repo guidelines suggest).

BTW, is not such a big repro, is just a simple web app with minimal ASP.NET Core, AutoFac and MediatR config. But I could try to reduce the code and post it here if that helps although I don't know if that would be sufficient to reproduce the problem, since its very specific (I could try though). 
Like I said before I'm not sure whether this is related to AutoFac or ASP.NET Core DI container. 
However, I'm really suspicious it can be related to the way AutoFac is integrating with the default pipeline.

> and if we have to dive into a big repro to debug your code, I'll be honest... given the 20+ integration libraries, the recent release of ASP.NET Core 2.1, and the ongoing issues and maintenance for all the projects here

To be honest, there's nothing to debug in that repro. If you just clone it and launch the app you will see the problem happening right away. And the error is not anymore clearer than what I've posted here - hence my confusion.

Tell me if there's anything else I can do to speed up this process, I totally understand that this (as many more) OSS projects are sustained in those circumstances and I'm in no position to require anything. I just need some direction.

Since I don't know exactly where the problem is (in which pipeline), how could I isolate that "small repro", do you have any ideas? I don't think that it would be productive to approach this in a "try and fail" manner.

**Comment by tillig** [comment]
Replied in moved issue.
