### ISSUE TITLE
What news about "Action Injection"?

### ISSUE THREAD

**Issue by rc1021** [autofac/Autofac#921]
I found a article. it was published about [Action Injection](https://alexmg.com/posts/introducing-action-injection-with-autofac-aspnet-mvc-integration) on Sunday, May 16, 2010. 

any updates of the issue??

**Comment by tillig** [comment]
[See documentation.](http://autofac.readthedocs.io/en/latest/integration/mvc.html#enable-injection-of-action-parameters)
