### ISSUE TITLE
Ignore Obsolete Assembly Types

### ISSUE THREAD

**Issue by LordPinhead** [autofac/Autofac#922]
Hi,
i have a question about a possible feature of Autofac.
Lets say i have an Assembly with 20 classes, every class has an dummy Interface and a base Interface.

`
public interface IBaseInterface {}
public interface IDummyInterface : IBaseInterface {}

public class ImplementationNew : IDummyInterface {}

[Obsolete]
public class ImplementationOld : IDummyInterface {}
`

Now i scan in my Module Class for every IBaseInterface

`builder.RegisterAssemblyTypes(dataAccess)
.Where(t => t.BaseType.Equals(typeof(IBaseInterface )))
.AsImplementedInterfaces()
.AsSelf();`

Easy as a pie, but it will still register  the old implementation i just have for legacy reasons to remove it for later.

Maybe someone has the some need to Ignore the Obsolete ones without writing an Interceptor.

Edit: Ignore the code for now, IE at work is just a pure pile of Crap with github

**Comment by tillig** [comment]
Just add another where clause.

```csharp
builder
  .RegisterAssemblyTypes(dataAccess)
  .Where(t => t.BaseType.Equals(typeof(IBaseInterface)))
  .Where(t => t.GetCustomAttributes(typeof(ObsoleteAttribute), false).Length == 0)
  .AsImplementedInterfaces()
  .AsSelf();
```

You could put that all in one where clause, too, if you want.
