### ISSUE TITLE
Is it possible to get this working somehow within Unity3d?

### ISSUE THREAD

**Issue by MostHated** [autofac/Autofac#923]
Hey there,
    I am using Unity3d 2018.1.0f3 which is using .net 4.6x and has netstandard 2.0. Does anyone know if its possible to get Autofac working within Unity? Currently, I get an error saying that it unloaded the assemblies due to possible runtime issues.

Thanks,
MH

**Comment by tillig** [comment]
I would recommend asking this question [on StackOverflow](https://stackoverflow.com) and tagging it `autofac` and `unity3d` as noted in the issue template.

**Comment by MostHated** [comment]
I posted it there as well. I wanted to post it here, too just in case there was a possibility of someone looking into it if there was a way to perhaps patch it or come up with a workaround.
