### ISSUE TITLE
When should the dependencies of a Lazy dependency be created?

### ISSUE THREAD

**Issue by peto268** [autofac/Autofac#926]
Hello, in my app I have a lazy dependency which has multiple non lazy dependencies. The graph looks basically like this:

A -> Lazy\<B> -> C -> D

i.e. A uses B (lazily), which uses C, which uses D

I've noticed, that even though the ctor of B wont get called until i use B from A, both C and D ctors get called at the time when i'm resolving A. Is this ok? Neither C nor D is needed at the time A gets created, so this looks like a bug to me.

Thanks

**Comment by tillig** [comment]
Have you reproduced this in a simple unit test form? If so, can you paste that in here?

**Comment by peto268** [comment]
Tried to reproduce it, but in the unit test is not behaving like this. At least i know i have to dig deeper, thanks a lot. Closing this issue.
