### ISSUE TITLE
DependencyResolutionException not deserializable

### ISSUE THREAD

**Issue by wkamir** [autofac/Autofac#932]
The DependencyResolutionException is inherited from System.Exception which implements ISerializable.

It needs to implement the following constructor:

`public DependencyResolutionException(SerializationInfo info, StreamingContext context) :base ( info, context) { }
`

Please see:
https://social.msdn.microsoft.com/Forums/en-US/5b411a37-fafb-475f-9eb0-ee82955bf15a/the-constructor-to-deserialize-an-object-of-type-was-not-found

**Comment by tillig** [comment]
Duplicate #456.

**Comment by gclpixel** [comment]
The fixes doesn't resolve the problem with the required serialization constructor, this ctor exists also in .NET Standard 2.0.
The missing ctor is really annoying.

`public DependencyResolutionException(SerializationInfo info, StreamingContext context) :base ( info, context) { }`

**Comment by alexmg** [comment]
@gclpixel It looks like I missed that constructor when enabling .NET Standard 2.0 support.

**Comment by alexmg** [comment]
The fix will be in `4.9.2` or later.

**Comment by alexmg** [comment]
This fix is included in `4.9.2` on NuGet.
