### ISSUE TITLE
RegisterAssemblyTypes() => Resolve<>() not giving assemblies enough time to load?

### ISSUE THREAD

**Issue by Timovzl** [autofac/Autofac#936]
When we `RegisterAssemblyTypes()` and then `Resolve<>()` a type that has a subdependency, sometimes that subdependency is not recognized, even though it was registered. However, if we 'touch' the assemblies beforehand, the issue disappears! I will explain.

This is the registration and resolution process (names have been obscured):

            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            
            builder.RegisterAssemblyTypes(assemblies)
                .InNamespace("Company.Common")
                .AsImplementedInterfaces()
                .AsSelf()
                .SingleInstance();
            builder.RegisterAssemblyTypes(assemblies)
                .InNamespace("Company.PaymentMethod")
                .AsImplementedInterfaces()
                .AsSelf()
                .SingleInstance();
            
            using (var container = builder.Build())
            {
                // Exception here:
                var totalReportApplicationService = container.Resolve<Reporter.Application.TotalReportApplicationService>();
            }

The relevant types are:
- `Company.PaymentMethod.Reporter.Application.TotalReportApplicationService` (in project A).
- `Company.PaymentMethod.Transactions.Domain.Authorizations.IAuthorizationRepo` (in project B).
- `Company.PaymentMethod.Transactions.Infrastructure.Authorizations.AuthorizationRepo` (in project B).

The following exception occurs:

    Autofac.Core.DependencyResolutionException: 'An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TotalReportApplicationService (ReflectionActivator), Services = [Company.Common.Helpers.DomainModeling.IApplicationService, Company.PaymentMethod.Reporter.Application.TotalReportApplicationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope'

    DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Company.PaymentMethod.Reporter.Application.TotalReportApplicationService' can be invoked with the available services and parameters:
    Cannot resolve parameter 'Company.PaymentMethod.Transactions.Domain.Authorizations.IAuthorizationRepo authorizationRepo' of constructor 'Void .ctor(Company.PaymentMethod.Logging.Domain.ErrorEntry.IErrorEntryIndexer, Company.Common.Helpers.Net.Smtp.ISmtpEmailer, Company.PaymentMethod.Transactions.Domain.Authorizations.IAuthorizationRepo)'.

In short, it tells us that `TotalReportApplicationService` needs an `IAuthorizationRepo`, but that parameter cannot be resolved.

The problem goes away entirely if we do _any one_ of the following:

- Before calling `Resolve<>()`, ask if the problematic dependency is registered: `container.IsRegistered<Company.PaymentMethod.Transactions.Domain.Authorizations.IAuthorizationRepo>(); // true!`
- Before `Build()`, manually register the problematic dependency: `builder.RegisterType<Company.PaymentMethod.Transactions.Infrastructure.Authorizations.AuthorizationRepo>().As<Company.PaymentMethod.Transactions.Domain.Authorizations.IAuthorizationRepo>();`
- Before calling `RegisterAssemblyTypes()`, touch the assemblies manually: `AppDomain.CurrentDomain.GetAssemblies().SelectMany(assembly => assembly.GetTypes()).ToList();`
- Before creating the actual builder, first create another builder and call `builder.RegisterAssemblyTypes(assemblies); builder.Build();`

Hopefully this provides some insight into the cause of the problem. Because any one of the above can alleviate the symptoms, I get the sense that the problem has something to do with assembly loading. It is as if the assembly for Project B, the inner dependency, is not properly loaded by the time `Resolve<>()` is called, unless we use one of the workarounds.

I have tried to make a minimal repro, but I was unable to reproduce the problem outside of the application where I encountered it.

Using:

- .NET Core 2.0
- Autofac 4.8.1
- Autofac.Extensions.DependencyInjection 4.3.0

**Comment by tillig** [comment]
**Autofac itself isn't involved in assembly loading.** You pass the list of assemblies to Autofac, it uses the already loaded instances and does the scanning. It's your .NET runtime that actually does the assembly loading. **This is a synchronous operation**, so it's not that there's a wait or timeout happening. It's either loaded or it's not, and if the .NET runtime needs to load something on the fly, it's up to the runtime to do that.

For safety, we do make sure we [filter out types that can't be loaded](https://github.com/autofac/Autofac/blob/ac840a25dd82b0db3429cd15403411e963bb2102/src/Autofac/Util/AssemblyExtensions.cs). This can sometimes happen in situations where an assembly has been included in the list but not all of the assembly's dependencies are present. We don't want to blow up the whole app for that.

One of the key things there is the `AppDomain.CurrentDomain.GetAssemblies()` - what happens to be currently loaded at any given time depends on what code has been executed and maybe what types have been referenced. For example, [we have some docs about how IIS hosted apps only load assemblies as they're needed after an app recycle](https://autofac.readthedocs.io/en/latest/register/scanning.html). In other app types (like Xamarin) you might see [the linker optimize out types it thinks aren't referenced](https://autofac.readthedocs.io/en/latest/faq/xamarin-issues.html).

The point is, in all these cases, it's the .NET runtime that hasn't loaded the type for whatever reason.

So, why does something like this fix it?

```csharp
container.IsRegistered<IAuthorizationRepo>();
```

By virtue of you _specifically referencing the type_ in the code doing the registration you're forcing the JIT compiler to load that assembly. So by the time the `AppDomain.CurrentDomain.GetAssemblies()` runs, it's _had_ to have loaded that assembly or the code later wouldn't have been able to execute.

As a first step, **I would recommend not using `AppDomain.CurrentDomain.GetAssemblies()` and instead be specific about the list of assemblies you want to scan.** Even if you just do that for testing purposes, see if that fixes the issue. I'd bet it does. If that's the case, then you need to then figure out why your types aren't getting loaded correctly.

You may need to force things to be loaded into the current app by manually iterating through your application folder or tapping into the .NET Core assembly load mechanism. I admit there aren't any great samples of that I can find, though [articles like this exist](https://www.codeproject.com/Articles/1194332/Resolving-Assemblies-in-NET-Core) to explain a bit more and help you get ideas on search terms. There are also [frameworks like this](https://natemcmaster.com/blog/2018/07/25/netcore-plugins/) that help you with plugins in .NET Core and may have some code snippets of interest.

**Comment by Timovzl** [comment]
@tillig That was excellently explained. Thank you for your time and patience.

Where I _do_ want to scan, I have succeeded with a recursive `GetReferencedAssemblies()` (being careful to protect against circular references). Of course, this requires actually loading the assemblies, so some consideration is in order. In my case, I load only what is required, using assembly name prefixes, stopping recursion on mismatches.

**Comment by Timovzl** [comment]
For anyone reading this, there is a better practice that makes this question entirely irrelevant:

In a given solution, each project that has dependencies to register should provide an `Add...()` extension method that adds that projects dependencies to the container.

For example, the database infrastructure project exposes `AddDatabaseInfrastructure()`. The application layer will invoke that extension method as one of the things it registers.

Not only does this avoid the problem described above, since the assemblies are referenced explicitly by virtue of their registration extension methods being invoked, but it provides additional benefits. Each project now takes responsibility for registering its own dependencies (be it manually or through assembly scanning of itself). This creates better boundaries, constraining responsibilities to where they make the most sense. In fact, implementation types can now remain `internal`, since it is the project that defines the type that also registers it in the container.
