### ISSUE TITLE
How to Inject IOptionMonitor when use autofac in asp.net core

### ISSUE THREAD

**Issue by bishopjun11** [autofac/Autofac#937]
How to use Inject IOptionMonitor when use autofac in asp.net core?
Best get the code snippet.

**Comment by tillig** [comment]
As noted in the issue template, please ask usage questions ("how do I...") on [StackOverflow](http://www.stackoverflow.com) and tag them with `autofac` along with other relevant tags.

**Comment by bishopjun11** [comment]
https://stackoverflow.com/questions/52538309/how-do-i-inject-ioptionmonitor-when-use-autofac-in-aps-net-core
