### ISSUE TITLE
KeyFilterAttribute inheritance

### ISSUE THREAD

**Issue by Serg046** [autofac/Autofac#938]
For example I have 2 keyed implementations:

```csharp
interface IProvider {}
class Provider1 : IProvider {}
class Provider2 : IProvider {}

builder.RegisterType<Provider1>().Keyed<IProvider>(1);
builder.RegisterType<Provider2>().Keyed<IProvider>(2);
```

And the service which uses one of them:
```csharp
class SomeService
{
    public SomeService(IProvider p) { }
}
```
Of course, we can apply the attribute right in the `SomeService`:
```csharp
class SomeService
{
    public SomeService([KeyFilter(2)]IProvider p) {}
}
```
But what if we need to decide which version should be used on some upper layer?
Example:
```csharp
class SomeService
{
    public SomeService(IProvider p) {}
}

class ApiController
{
    public ApiController([KeyFilter(2)]SomeService service) {}
}
```
As I understand now the only way we can use is just send the key (2) through all hierarchy until the appropriate service is reached.

**Comment by tillig** [comment]
This has pretty close overlapping ideas with one of our FAQs: [How do I pass a parameter to a component in the middle of a resolve chain?](https://autofac.readthedocs.io/en/latest/faq/injecting-global-parameters.html) It also overlaps a bit with ["How do I pick a service implementation by context?"](https://autofac.readthedocs.io/en/latest/faq/select-by-context.html)

Generally speaking, having to key things all the way down a resolve chain indicates a class/interface design problem. Heavy reliance on keys to differentiate between implementations of a particular service indicates you're not following [the Liskov substitution priniciple](http://en.wikipedia.org/wiki/Liskov_substitution_principle) (the "L" in ["SOLID" design principles](https://deviq.com/solid/)). Trying to pass a key (or parameter) down a resolve chain also breaks inversion of control - your resolve chain, tied together by interface implementations, _shouldn't_ know what the whole chain is down the stack.

All this boils down to: we have no plans to implement key passing/inheritance down the resolve chain. If you need to tie things together with keys like this then you will keep having to manually specify the key in filters as you are doing today.
