### ISSUE TITLE
Hi!, I am wondering if you support .NET Standard 2.0?

### ISSUE THREAD

**Issue by learnersm** [autofac/Autofac#943]

**Comment by alexmg** [comment]
The `4.8.1` package (current release) targets .NET Standard 1.1 and .NET Framework 4.5. It will run any place that .NET Standard 2.0 will.

The upcoming `4.9.0` version (not yet released) has been updated to also include a target for .NET Standard 2.0.

**Comment by learnersm** [comment]
Thanks for the clarity!
