### ISSUE TITLE
RegisterAssemblyModules, Imodule Order

### ISSUE THREAD

**Issue by generik0** [autofac/Autofac#947]
Hi

When using RegisterAssemblyModules i would like to insure teh order of the modules to load.
That way we can insure priority of registration together with preserve existing.

How would autofac feel if i make a PR with::

- Add OrderId to IModule
- Add orderby OrderId in the code below
- In Module class add OrderId = int.MaxValue;

A very simple change that would help greatly in control:-)

![image](https://user-images.githubusercontent.com/2411563/48056426-0dfe5480-e1b2-11e8-98dc-72118f72427e.png)

**Comment by tillig** [comment]
Changing `IModule` would be a breaking API change that would have to wait for a major release. Even then, I'm not totally sure if this is something we'd necessarily go for. There's a lot of importance on registration _order_ for sources, types, etc. so changing that notion to be built into the module would be an API inconsistency.

There are a few ways to work around these things, of course. For example, it'd be easy enough to create a custom attribute and mark up each module. I drummed this up pretty quickly:

```csharp
using System;
using System.Linq;
using System.Reflection;
using Autofac;
using Autofac.Core;

[AttributeUsage(AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
public sealed class ModuleOrderAttribute : Attribute
{
    public int Order { get; set; }
}

[ModuleOrder()]
public class FirstModule : Autofac.Module
{
}

[ModuleOrder(Order = 200)]
public class SecondModule : Autofac.Module
{
}

public class ThirdModule : Autofac.Module
{
}

public static class Extensions
{
    public static void RegisterModulesWithOrder(this ContainerBuilder builder, params Assembly[] assemblies)
    {
        var modules = assemblies
            .SelectMany(a => a.GetTypes())
            .Where(t => t.IsClass && !t.IsAbstract && t.GetInterfaces().Contains(typeof(IModule)))
            .OrderBy(t => t.GetCustomAttribute<ModuleOrderAttribute>()?.Order ?? 1000);

        foreach(var module in modules)
        {
            builder.RegisterModule((IModule)Activator.CreateInstance(module));
        }
    }
}
```

Using it like this, it registers the modules in the appropriate order:

```csharp
var builder = new ContainerBuilder();
builder.RegisterModulesWithOrder(Assembly.GetExecutingAssembly());
```

That would put the whole thing under your control and wouldn't require any breaking API changes in Autofac.

**Comment by generik0** [comment]
Hi @tillig I see your point. Where people have made there own implementation of IModule they would have an issue.
The attribute idea is interesting, but not POCO.
I have extended IModule + Module and used/modified the registrar code in our own base library.
Thanks for your time :-)
