### ISSUE TITLE
How do I get current scope in .net core console application

### ISSUE THREAD

**Issue by ericwp** [autofac/Autofac#955]
I found HttpContext.RequestServices in ASP.NET Core could get current lifetimescope. It works well for me.
But I don't know how to get current child scope from root container in console application, could you give some help?
Thank you!
The code example like this:

    public static class AutofacContainerWrapper
    {
        private static IContainer _container;
        public static void SetContainer(IContainer container)
        {
           // root container
            _container = container;
        }
        public static ILifetimeScope CurrentContainer()
        {
            //Handle console application request 
            if (!_container.ComponentRegistry
                .IsRegistered(new TypedService(typeof(IHttpContextAccessor))))
            {
                //I don't know how to get current child scope from root container.
            }
            // Handle http request
            var accessor = _container.Resolve<IHttpContextAccessor>();
            return accessor.HttpContext.RequestServices.GetService<ILifetimeScope>();
        }
    }

**Comment by tillig** [comment]
Console applications don't inherently have dependency injection support. If you are creating your own console app then it's up to you to [implement your own custom per-request semantics](https://autofac.readthedocs.io/en/latest/faq/per-request-scope.html#implementing-custom-per-request-semantics). How you manage those scopes, create/destroy/access them, is entirely up to your app.

If you are self-hosting ASP.NET Core trying to get a request lifetime scope at the app level... that doesn't actually make much sense. The ASP.NET app has multiple requests processing simultaneously, so you'd need to get a reference to the actual request, which would get you the `HttpContext`, which would get you back to `RequestServices`. Hopefully this isn't what you're asking.

If you need more guidance on how to manually implement per-request or per-unit-of-work dependency injection scopes in a console app, I'd recommend looking [on StackOverflow](https://stackoverflow.com) and/or asking there. We can provide the DI library and the mechanism for managing scopes but how that works into your custom app will be totally custom and outside the scope of what we can provide.

**Comment by ericwp** [comment]
@tillig Thank you for your feedback
