### ISSUE TITLE
Dependency issue between Autofac and Autofac.Extras.DynamicProxy

### ISSUE THREAD

**Issue by adamxi** [autofac/Autofac#968]
Hej,
I'm using Autofac 4.9.1 along with Autofac.Extras.DynamicProxy 4.5.0.
When i on my ContainerBuilder use ".EnableInterfaceInterceptors()" which is part of Autofac.Extras.DynamicProxy, i get the exception:

_Could not load file or assembly 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)_

I can resolve the issue by downgrading Autofac to version 4.0.1.0 but it's not really a great fix.

**Comment by tillig** [comment]
Add a binding redirect. [This is an FAQ in our documentation.](https://autofac.readthedocs.io/en/latest/faq/binding-redirect.html)
