### ISSUE TITLE
Handle dispose/cleanup of autofac in asp.net application

### ISSUE THREAD

**Issue by StefanHaug** [autofac/Autofac#973]
Occationally there seems to be a race condition when an asp.net application gets restarted and one of my workers are triggering.

As a result I get ObjectDisposedException when using the container or lifetimescope.

My worker respects the CancellationToken and shuts down the 3rd party service (which uses the autofac container), but it may be up to a second late.

I expect that autofac has already cleaned up and been disposed by this time so this results in a ObjectDisposedException.

Is there some way to control the cleanup procedure so that I can make it run later?

**Comment by tillig** [comment]
This is a great question to [ask on StackOverflow](https://stackoverflow.com) and tag it `autofac` as well as `asp.net` and other relevant tags (as noted in the issue template). This is largely an ASP.NET question, and while you're using Autofac, the larger question is more about how to hook in and control the operations during ASP.NET shutdown.

If you end up asking the question there, be sure to include more information, like what sort of ASP.NET app it is (web forms, MVC, Web API, combination), how you have things generally set up, how you kick off these workers, and so on. You can put a link here if you like to help future folks follow up, but any additional answers should happen there.
