### ISSUE TITLE
PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies) doesn't work

### ISSUE THREAD

**Issue by yilianhuaixiao** [autofac/Autofac#974]
I let the whole service layer support propertiesAutowired using the following code:

```
public class RentApplicationModule : Autofac.Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
            .Where(t => t.Name.EndsWith("Service") && !t.Name.StartsWith("I"))
            .AsImplementedInterfaces()
           .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies) ; 
        }
    }
```

I  have a UserService Class  with a public property: IRoleService RoleService.
And I  have a RoleService Class  with a public property: IUserService UserService.

When visiting the service, still reporting the circular dependency  error.

Is  this  a bug or  I  do a wrong work?

**Comment by tillig** [comment]
[From the documentation on property/property circular dependencies](https://autofac.readthedocs.io/en/latest/advanced/circular-dependencies.html):

> **Neither type can be registered as `InstancePerDependency`.** If either type is set to factory scope you won’t get the results you’re looking for (where the two types refer to each other). You can scope them however you like - `SingleInstance`, `InstancePerLifetimeScope`, or any other scope - just not factory.

The default (if you don't specify otherwise) is instance per dependency. Fix the lifetime scopes and you should be okay.

**Comment by yilianhuaixiao** [comment]
thanks a lot .  problem solved
