### ISSUE TITLE
Having Trouble Resolving ServiceCollection registrations once passed to AutoFac Container

### ISSUE THREAD

**Issue by iby-dev** [autofac/Autofac#975]
I am not sure if this is a bug or a label but i have documented my issue here at [StackOverflow](https://stackoverflow.com/questions/55501684/unable-to-resolve-servicecollection-registrations-passed-to-autofac-container)

I would love it if someone from this community could take a look and let me what i am doing wrong or not.

Cheers.

**Comment by tillig** [comment]
The two project owners here already monitor StackOverflow. If you find a bug or something, definitely open an issue, include a repro, and let us know; otherwise, no need to double-post.

**Comment by iby-dev** [comment]
Thanks - will wait for the project owners to take a look and see if there is an obvious issue with what I am doing. Might keep stripping code till it works.
