### ISSUE TITLE
In aspnetcore 2.2 ,Attribute injection does not work

### ISSUE THREAD

**Issue by daoqiang** [autofac/Autofac#982]
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            //services.Replace(ServiceDescriptor.Transient<IControllerActivator, ServiceBasedControllerActivator>());
            var mvcBuild=services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2).AddControllersAsServices().AddControllersAsServices();
            var builder = new ContainerBuilder();
           // Assembly[] assemblies = Directory.GetFiles(AppDomain.CurrentDomain.BaseDirectory, "*.dll").Select(Assembly.LoadFrom).ToArray();
            builder.RegisterType<M1>().As<IM1>().InstancePerLifetimeScope();
            builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly())
                .Where(t => t.IsSubclassOf(typeof(ValuesController)))
                .PropertiesAutowired();
            builder.Populate(services);
            var container = builder.Build();
            return new AutofacServiceProvider(container);
        }

 public class M1:IM1
    {

        public string Eat()
        {
            return  "eart";
        }
    }

 public class ValuesController : Controller
    {
        public IM1 M1 { get; set; }
        // GET api/values
        [HttpGet]
        [Route("api/get")]
        public ActionResult<IEnumerable<string>> Get()
        {
            M1.Eat();
            return new string[] { "value1", "value2" };
        }
    }

**Comment by tillig** [comment]
Looks like you registered controllers that are subclasses of the ValuesController but you didn't actually register the ValuesController type itself for property injection. [See this StackOverflow answer for an example.](https://stackoverflow.com/a/53982996/8116)

**Comment by alexmg** [comment]
@daoqiang You need to make the `builder.Populate(services)` call before registering the controllers with `RegisterAssemblyTypes`. When you use `AddControllersAsServices` the services are added to the `IServiceCollection` and calling `Populate` converts those into Autofac registrations. By default Autofac will use the last registration added as the default and in this case it is the one that ASP.NET Core added to the `IServiceCollection` which does not have a concept of `PropertiesAutowired`.

**Comment by daoqiang** [comment]
it is good ,thank you
