### ISSUE TITLE
The entry and the type to be injected are not in the same assembly, where property injection is invalid

### ISSUE THREAD

**Issue by MR-Small-Grit** [autofac/Autofac#984]
[Common.zip](https://github.com/autofac/Autofac/files/3107754/Common.zip)

**Comment by daoqiang** [comment]
After testing, it was found that the problem had nothing to do with assemblies and namespaces. I'm not sure what the mechanism is.

**Comment by alistairjevans** [comment]
In ASP.NET Core, by default Controllers aren't resolved from Autofac, only the parameters are. So property injection won't work on Controllers out-of-the-box.  See our documentation on this: https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services.

Basically, once I changed:
```
  var mvcBuild = services.AddMvc();
```
to 
```
   var mvcBuild = services.AddMvc().AddControllersAsServices()
````
your properties started injecting.

I'd consider just using constructor injection for your controllers though and then you don't need ``AddControllersAsServices``.
