### ISSUE TITLE
Please update Autofac.Configuration NuGet package

### ISSUE THREAD

**Issue by lukos** [autofac/Autofac#989]
The issue mentioned here: https://github.com/autofac/Autofac/issues/782 still occurs if you install Autofac.Configuration (@4.1.0) Nuget package because it's dependency is >= Autofac 4.0.1, which is before the fix was made.

My understanding is that NuGet will resolve the lowest version that meets the requirement (and certainly not the latest) so installing just the config package causes the duplicate attribute bug and since the dependency on Autofac is not pulled in as a nuget reference, I can't simply manually update Autofac.

Please can you update the config package with a dependency on a newer version of Autofac.

The workaround is to install the full Autofac package, which isn't the end of the world but this is a confusing error, especially when the reference to autofac is indirect.

**Comment by tillig** [comment]
Issue moved to [autofac/Autofac.Configuration #27](https://github.com/autofac/Autofac.Configuration/issues/27) via [**ZenHub**](https://www.zenhub.com/)
