### ISSUE TITLE
AutoFac container configuration (without ConfigureContainer) fails as of ASP.NET Core 3.0 Preview5

### ISSUE THREAD

**Issue by cqinwn** [autofac/Autofac#990]
NotSupportedException: ConfigureServices returning an System.IServiceProvider isn't supported.
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)

NotSupportedException: ConfigureServices returning an System.IServiceProvider isn't supported.
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

What's the new preferred way to register AutoFac?

**Comment by ysmoradi** [comment]
I've the same issue )-:

**Comment by tillig** [comment]
See autofac/Autofac.Extensions.DependencyInjection#36

**Comment by MonkSoul** [comment]
I've got it done. https://www.cnblogs.com/baiqian/p/10964972.html

It's very simple.
